#
# Modifications for the nfsmount program.  We use some C files that are
# automatically generated by rpcgen.
#

RPCSRC = /a/unfsd/rpcsrc
RPCGEN = ${RPCSRC}/rpcgen/rpcgen

GLIBS	= /sprite/src/lib/sunrpc/sun3.md/libsunrpc_g.a -lc_g
LIBS	= -lsunrpc

#include <$(SYSMAKEFILE)>

mount.h mount_clnt.c mount_xdr.c : mount.x
	$(RPCGEN) mount.x
	rm mount_svc.c

nfs_prot.h nfs_prot_clnt.c nfs_prot_xdr.c : nfs_prot.x
	${RPCGEN} nfs_prot.x
	rm nfs_prot_svc.c

