# DO NOT DELETE THIS LINE -- make depend depends on it.

sun3.md/migcmd.o: migcmd.c
sun3.md/migcmd.o: /sprite/lib/include/sprite.h
sun3.md/migcmd.o: /sprite/lib/include/cfuncproto.h
sun3.md/migcmd.o: /sprite/lib/include/sysStats.h
sun3.md/migcmd.o: /sprite/lib/include/stdio.h
sun3.md/migcmd.o: /sprite/lib/include/stdlib.h
sun3.md/migcmd.o: /sprite/lib/include/option.h
sun3.md/migcmd.o: /sprite/lib/include/proc.h
sun3.md/migcmd.o: /sprite/lib/include/spriteTime.h
sun3.md/migcmd.o: /sprite/lib/include/kernel/sigTypes.h
sun3.md/migcmd.o: /sprite/lib/include/sun3.md/kernel/machTypes.h
sun3.md/migcmd.o: /sprite/lib/include/sun3.md/kernel/devAddrs.h
sun3.md/migcmd.o: /sprite/lib/include/sun3.md/kernel/machConst.h
sun3.md/migcmd.o: /sprite/lib/include/sun3.md/kernel/vmSunConst.h
sun3.md/migcmd.o: /sprite/lib/include/fmt.h
sun3.md/migcmd.o: /sprite/lib/include/sig.h
sun3.md/migcmd.o: /sprite/lib/include/kernel/procTypes.h
sun3.md/migcmd.o: /sprite/lib/include/sync.h
sun3.md/migcmd.o: /sprite/lib/include/kernel/syncLock.h
sun3.md/migcmd.o: /sprite/lib/include/list.h
sun3.md/migcmd.o: /sprite/lib/include/kernel/timer.h
sun3.md/migcmd.o: /sprite/lib/include/sun3.md/kernel/timerTick.h
sun3.md/migcmd.o: /sprite/lib/include/sun3.md/kernel/timerMach.h
sun3.md/migcmd.o: /sprite/lib/include/vmTypes.h
sun3.md/migcmd.o: /sprite/lib/include/kernel/sysSysCall.h
sun3.md/migcmd.o: /sprite/lib/include/kernel/trace.h
sun3.md/migcmd.o: /sprite/lib/include/kernel/procMigrate.h
sun3.md/migcmd.o: /sprite/lib/include/kernel/sys.h
sun3.md/migcmd.o: /sprite/lib/include/sys.h
sun3.md/migcmd.o: /sprite/lib/include/status.h
sun3.md/migcmd.o: /sprite/lib/include/kernel/netTypes.h
sun3.md/migcmd.o: /sprite/lib/include/netEther.h
sun3.md/migcmd.o: /sprite/lib/include/machparam.h
sun3.md/migcmd.o: /sprite/lib/include/sun3.md/machine/limits.h
sun3.md/migcmd.o: /sprite/lib/include/net.h
sun3.md/migcmd.o: /sprite/lib/include/netInet.h
sun3.md/migcmd.o: /sprite/lib/include/netUltra.h
sun3.md/migcmd.o: /sprite/lib/include/netFDDI.h
sun3.md/migcmd.o: /sprite/lib/include/kernel/syncTypes.h
sun3.md/migcmd.o: /sprite/lib/include/kernel/fs.h
sun3.md/migcmd.o: /sprite/lib/include/fs.h
sun3.md/migcmd.o: /sprite/lib/include/host.h
sun3.md/migcmd.o: /sprite/lib/include/sys/types.h
sun3.md/migcmd.o: /sprite/lib/include/netinet/in.h
sun3.md/migcmd.o: /sprite/lib/include/sys/stat.h syscalls.h
sun3.md/syscalls.o: syscalls.c
sun3.md/syscalls.o: syscalls.h
