#
#   Makefile for dvips
#

# for SYSV (and friends which use <string.h> instead of <strings.h>
# define the c-compiler flag
# SYS = -DSYSV

# where the installed binary goes
# BINDIR = /usr/bin
BINDIR = /usr/local/bin

# where the TFM files go
# TFMDIR = /usr/lib/tex/fonts/tfm
TFMDIR = /home/fonts
# the default path to search for TFM files 
# (this usually is identical to TeX's defaultfontpath, which omits `.')
# (private fonts are given an explicit directory, which overrides the path)
# TFMPATH = /LocalLibrary/Fonts/TeXFonts/tfm:$(TFMDIR)
TFMPATH = $(TFMDIR)

# where the PK files go
# PKDIR = /usr/lib/tex/fonts/pk
PKDIR = /home/fonts
# the default path to search for PK files (usually omits `.')
# PKPATH = /LocalLibrary/Fonts/TeXFonts/pk:$(PKDIR)
PKPATH = $(PKDIR)

# where the VF files go
# VFDIR = /usr/lib/tex/fonts/vf
VFDIR = /home/fonts/vf
# the default path to search for VF files (usually omits `.')
# VFPATH = /LocalLibrary/Fonts/TeXFonts/vf:$(VFDIR)
VFPATH = $(VFDIR)

# where the config files go
# CONFIGDIR = /usr/lib/tex/ps
CONFIGDIR = /home/lib/ps

# the default path to search for config files
# CONFIGPATH = .:$(CONFIGDIR)
CONFIGPATH = .:$(CONFIGDIR)

# where the header PS files go
# HEADERDIR = /usr/lib/tex/ps
HEADERDIR = /home/lib/ps

# the default path to search for header files
# HEADERPATH = .:$(HEADERDIR)
HEADERPATH = .:$(HEADERDIR)

# where epsf.tex and rotate.tex go (usually the TeX macros directory)
# TEXMACRODIR = /usr/lib/tex/inputs
TEXMACRODIR = /home/tex/local/lib

# the default path to search for epsf and psfiles
# (usually the same as TeX's defaultinputpath)
# FIGPATH = .:..:/usr/lib/tex/inputs
FIGPATH = .:..:/home/tex/local/lib:/home/tex/dist/lib

# where the manual page goes
# MANDIR = /usr/local/text/man/man1
MANDIR = /usr/man/man1

# add -DDEBUG to turn on debugging capability
# add -DTPIC for tpic support
# if the default resolution is not 300 dpi,
# add -DEFRES=400 or whatever is required
DEFS= -DTPIC -DDEBUG

# either use
OPT = -g
# or
#OPT = -s

# libraries to include
FLIBS= -lm

PATHS = -DTFMPATH=\"$(TFMPATH)\" \
	-DPKPATH=\"$(PKPATH)\" \
	-DVFPATH=\"$(VFPATH)\" \
	-DHEADERPATH=\"$(HEADERPATH)\" \
	-DCONFIGPATH=\"$(CONFIGPATH)\" \
	-DFIGPATH=\"$(FIGPATH)\"

CFLAGS = $(DEFS) $(PATHS) $(OPT) $(SYS)

SRC = dospecial.c dviinput.c fontdef.c loadfont.c dvips.c tfmload.c \
	download.c prescan.c scanpage.c skippage.c output.c scalewidth.c \
	dosection.c dopage.c resident.c search.c unpack.c drawPS.c \
	header.c makefont.c repack.c virtualfont.c

OBJ = dospecial.o dviinput.o fontdef.o loadfont.o dvips.o tfmload.o \
	download.o prescan.o scanpage.o skippage.o output.o scalewidth.o \
	dosection.o dopage.o resident.o search.o unpack.o drawPS.o \
	header.o makefont.o repack.o virtualfont.o

# files required to make a distribution
CONFIGFILES = config.ps psfonts.map
HEADERFILES = tex.lpro texc.script texps.lpro special.lpro
FILES = $(CONFIGFILES) $(HEADERFILES) $(SRC) \
	Makefile INSTALLATION README \
	MakeTeXPK ../afm/Makefile epsf.tex rotate.tex dvips.1 \
	paths.h debug.h structures.h squeeze.c afm2tfm.c afm2tfm.1

all : afm2tfm dvips tex.pro texps.pro texc.pro

dvips : $(OBJ)
	$(CC) $(CFLAGS) $(OBJ) $(LIBS) $(FLIBS) -o dvips

afm2tfm: afm2tfm.c
	$(CC) $(CFLAGS) -o afm2tfm afm2tfm.c $(LIBS) $(FLIBS)

$(OBJ) : structures.h debug.h Makefile
resident.o dvips.o loadfont.o tfmload.o : paths.h

squeeze : squeeze.o
	$(CC) $(CFLAGS) squeeze.o -o squeeze

tex.pro : tex.lpro squeeze
	./squeeze <tex.lpro > tex.pro

texc.pro: texc.lpro squeeze
	./squeeze <texc.lpro >texc.pro

texc.lpro: texc.script tex.lpro
	./texc.script tex.lpro texc.lpro

texps.pro : texps.lpro squeeze
	./squeeze <texps.lpro >texps.pro

special.pro : special.lpro squeeze
	./squeeze <special.lpro >special.pro

install : afm2tfm dvips MakeTeXPK \
	tex.pro texc.pro texps.pro special.pro \
	config.ps psfonts.map epsf.tex rotate.tex \
	dvips.1 afm2tfm.1
	- mkdir $(BINDIR)
	- mkdir $(HEADERDIR)
	- mkdir $(CONFIGDIR)
	- mkdir $(MANDIR)
	- mkdir $(TEXMACRODIR)
	install -c -m 755 afm2tfm $(BINDIR)/afm2tfm
	install -c -m 755 dvips $(BINDIR)/dvips
	install -c -m 755 MakeTeXPK $(BINDIR)/MakeTeXPK
	install -c -m 644 tex.pro $(HEADERDIR)
	install -c -m 644 texc.pro $(HEADERDIR)
	install -c -m 644 texps.pro $(HEADERDIR)
	install -c -m 644 special.pro $(HEADERDIR)
	install -c -m 644 config.ps $(CONFIGDIR)
	install -c -m 644 psfonts.map $(CONFIGDIR)
	install -c -m 644 epsf.tex $(TEXMACRODIR)
	install -c -m 644 rotate.tex $(TEXMACRODIR)
	-install -c -m 644 dvips.1 $(MANDIR)
	-install -c -m 644 afm2tfm.1 $(MANDIR)

veryclean :
	rm -f *.o dvips squeeze afm2tfm texc.lpro *.pro

clean :
	rm -f *.o squeeze afm2tfm

lint :
	lint $(DEFS) $(PATHS) $(SRC)
	lint $(DEFS) squeeze.c
	lint $(DEFS) afm2tfm.c

shar :
	shar $(FILES) > dvips.shar

dist :
	tar cf - $(FILES) | compress > dvips.tar.Z
