#define decw$c_num_glyphs 	        54
#define decw$c_select_cursor             0
#define decw$c_leftselect_cursor         0
#define decw$c_help_select_cursor        2
#define decw$c_wait_cursor               4
#define decw$c_inactive_cursor           6
#define decw$c_resize_cursor             8
#define decw$c_vpane_cursor             10
#define decw$c_hpane_cursor             12
#define decw$c_text_insertion_cursor    14
#define decw$c_text_insertion_bl_cursor 16
#define decw$c_cross_hair_cursor        18
#define decw$c_draw_cursor	        20
#define decw$c_pencil_cursor	        22
#define decw$c_rpencil_cursor	        22
#define decw$c_center_cursor	        24
#define decw$c_rightselect_cursor       26
#define decw$c_wselect_cursor	        28
#define decw$c_eselect_cursor	        30
#define decw$c_x_cursor		        32
#define decw$c_circle_cursor	        34
#define decw$c_mouse_cursor	        36
#define decw$c_lpencil_cursor	        38
#define decw$c_leftgrab_cursor	        40
#define decw$c_grabhand_cursor	        42
#define decw$c_rightgrab_cursor	        44
#define decw$c_leftpointing_cursor      46
#define decw$c_uppointing_cursor        48
#define decw$c_rightpointing_cursor     50
#define decw$c_check_cursor             52
