# DO NOT DELETE THIS LINE -- make depend depends on it.

sun4.md/fddicmd.o: fddicmd.c
sun4.md/fddicmd.o: /sprite/lib/include/sprite.h
sun4.md/fddicmd.o: /sprite/lib/include/cfuncproto.h
sun4.md/fddicmd.o: /sprite/lib/include/option.h
sun4.md/fddicmd.o: /sprite/lib/include/stdio.h
sun4.md/fddicmd.o: /sprite/lib/include/sys/file.h
sun4.md/fddicmd.o: /sprite/lib/include/fs.h
sun4.md/fddicmd.o: /sprite/lib/include/spriteTime.h
sun4.md/fddicmd.o: /sprite/lib/include/kernel/procTypes.h
sun4.md/fddicmd.o: /sprite/lib/include/proc.h
sun4.md/fddicmd.o: /sprite/lib/include/kernel/sigTypes.h
sun4.md/fddicmd.o: /sprite/lib/include/sun4.md/kernel/machTypes.h
sun4.md/fddicmd.o: /sprite/lib/include/sun4.md/kernel/devAddrs.h
sun4.md/fddicmd.o: /sprite/lib/include/sun4.md/kernel/machConst.h
sun4.md/fddicmd.o: /sprite/lib/include/sun4.md/kernel/vmSunConst.h
sun4.md/fddicmd.o: /sprite/lib/include/kernel/sysSysCall.h
sun4.md/fddicmd.o: /sprite/lib/include/kernel/sys.h
sun4.md/fddicmd.o: /sprite/lib/include/sys.h
sun4.md/fddicmd.o: /sprite/lib/include/status.h
sun4.md/fddicmd.o: /sprite/lib/include/fmt.h
sun4.md/fddicmd.o: /sprite/lib/include/sig.h
sun4.md/fddicmd.o: /sprite/lib/include/vmTypes.h
sun4.md/fddicmd.o: /sprite/lib/include/sync.h
sun4.md/fddicmd.o: /sprite/lib/include/kernel/syncLock.h
sun4.md/fddicmd.o: /sprite/lib/include/list.h
sun4.md/fddicmd.o: /sprite/lib/include/kernel/timer.h
sun4.md/fddicmd.o: /sprite/lib/include/sun4.md/kernel/timerTick.h
sun4.md/fddicmd.o: /sprite/lib/include/sun4.md/kernel/timerMach.h
sun4.md/fddicmd.o: /sprite/src/kernel/voelker/net/netTypes.h
sun4.md/fddicmd.o: /sprite/lib/include/netEther.h
sun4.md/fddicmd.o: /sprite/lib/include/machparam.h
sun4.md/fddicmd.o: /sprite/lib/include/sun4.md/machine/limits.h
sun4.md/fddicmd.o: /sprite/lib/include/net.h
sun4.md/fddicmd.o: /sprite/lib/include/netInet.h
sun4.md/fddicmd.o: /sprite/lib/include/netUltra.h
sun4.md/fddicmd.o: /sprite/lib/include/netFDDI.h
sun4.md/fddicmd.o: /sprite/lib/include/kernel/syncTypes.h
sun4.md/fddicmd.o: /sprite/lib/include/kernel/fs.h
sun4.md/fddicmd.o: /sprite/src/lib/include/dev/fddi.h
sun4.md/fddicmd.o: /sprite/lib/include/time.h
