# DO NOT DELETE THIS LINE -- make depend depends on it.

sun3.md/fstrash.o: fstrash.c
sun3.md/fstrash.o: /sprite/lib/include/sprite.h
sun3.md/fstrash.o: /sprite/lib/include/cfuncproto.h
sun3.md/fstrash.o: /sprite/lib/include/option.h
sun3.md/fstrash.o: /sprite/lib/include/disk.h
sun3.md/fstrash.o: /sprite/lib/include/sys/file.h
sun3.md/fstrash.o: /sprite/lib/include/kernel/fs.h
sun3.md/fstrash.o: /sprite/lib/include/kernel/dev.h
sun3.md/fstrash.o: /sprite/lib/include/kernel/fsdm.h
sun3.md/fstrash.o: /sprite/lib/include/kernel/ofs.h
sun3.md/fstrash.o: /sprite/lib/include/kernel/devDiskLabel.h
sun3.md/fstrash.o: /sprite/lib/include/kernel/lfsDesc.h
sun3.md/fstrash.o: /sprite/lib/include/kernel/lfsDescMap.h
sun3.md/fstrash.o: /sprite/lib/include/kernel/lfsFileLayout.h
sun3.md/fstrash.o: /sprite/lib/include/kernel/lfsSegLayout.h
sun3.md/fstrash.o: /sprite/lib/include/kernel/lfsStableMem.h
sun3.md/fstrash.o: /sprite/lib/include/kernel/lfsSuperBlock.h
sun3.md/fstrash.o: /sprite/lib/include/kernel/lfsUsageArray.h
sun3.md/fstrash.o: /sprite/lib/include/stdio.h
sun3.md/fstrash.o: /sprite/lib/include/stdlib.h
sun3.md/fstrash.o: /sprite/lib/include/string.h
sun3.md/fsSetFD.o: fsSetFD.c
sun3.md/fsSetFD.o: /sprite/lib/include/sprite.h
sun3.md/fsSetFD.o: /sprite/lib/include/cfuncproto.h
sun3.md/fsSetFD.o: /sprite/lib/include/option.h
sun3.md/fsSetFD.o: /sprite/lib/include/disk.h
sun3.md/fsSetFD.o: /sprite/lib/include/sys/file.h
sun3.md/fsSetFD.o: /sprite/lib/include/kernel/fs.h
sun3.md/fsSetFD.o: /sprite/lib/include/kernel/dev.h
sun3.md/fsSetFD.o: /sprite/lib/include/kernel/fsdm.h
sun3.md/fsSetFD.o: /sprite/lib/include/kernel/ofs.h
sun3.md/fsSetFD.o: /sprite/lib/include/kernel/devDiskLabel.h
sun3.md/fsSetFD.o: /sprite/lib/include/kernel/lfsDesc.h
sun3.md/fsSetFD.o: /sprite/lib/include/kernel/lfsDescMap.h
sun3.md/fsSetFD.o: /sprite/lib/include/kernel/lfsFileLayout.h
sun3.md/fsSetFD.o: /sprite/lib/include/kernel/lfsSegLayout.h
sun3.md/fsSetFD.o: /sprite/lib/include/kernel/lfsStableMem.h
sun3.md/fsSetFD.o: /sprite/lib/include/kernel/lfsSuperBlock.h
sun3.md/fsSetFD.o: /sprite/lib/include/kernel/lfsUsageArray.h
sun3.md/fsSetFD.o: /sprite/lib/include/stdio.h
sun3.md/fsSetFD.o: /sprite/lib/include/stdlib.h
sun3.md/fsSetFD.o: /sprite/lib/include/string.h
