# DO NOT DELETE THIS LINE -- make depend depends on it.

symm.md/Mig_GetPdevName.o: Mig_GetPdevName.c
symm.md/Mig_GetPdevName.o: /sprite/lib/include/fs.h
symm.md/Mig_GetPdevName.o: /sprite/lib/include/spriteTime.h
symm.md/Mig_GetPdevName.o: /sprite/lib/include/sprite.h
symm.md/Mig_GetPdevName.o: /sprite/lib/include/cfuncproto.h
symm.md/Mig_GetPdevName.o: /sprite/lib/include/proc.h
symm.md/Mig_GetPdevName.o: /sprite/lib/include/sig.h
symm.md/Mig_GetPdevName.o: /sprite/lib/include/symm.md/kernel/mach.h
symm.md/Mig_GetPdevName.o: /sprite/lib/include/symm.md/kernel/machConst.h
symm.md/Mig_GetPdevName.o: /sprite/lib/include/symm.md/kernel/vmSymConst.h
symm.md/Mig_GetPdevName.o: /sprite/lib/include/symm.md/kernel/vmSymPTE.h
symm.md/Mig_GetPdevName.o: /sprite/lib/include/symm.md/kernel/machTrap.h
symm.md/Mig_GetPdevName.o: /sprite/lib/include/symm.md/kernel/machFpu.h
symm.md/Mig_GetPdevName.o: /sprite/lib/include/sys/types.h
symm.md/Mig_GetPdevName.o: /sprite/lib/include/fmt.h
symm.md/Mig_GetPdevName.o: /sprite/lib/include/vm.h
symm.md/Mig_GetPdevName.o: /sprite/lib/include/vmStat.h
symm.md/Mig_GetPdevName.o: /sprite/lib/include/symm.md/kernel/vmMachStat.h
symm.md/Mig_GetPdevName.o: /sprite/lib/include/stdio.h
symm.md/Mig_GetPdevName.o: /sprite/lib/include/varargs.h
symm.md/Mig_GetPdevName.o: /sprite/lib/include/mig.h
symm.md/global.o: global.c
symm.md/global.o: /sprite/lib/include/sprite.h
symm.md/global.o: /sprite/lib/include/cfuncproto.h
symm.md/global.o: /sprite/lib/include/string.h
symm.md/global.o: /sprite/lib/include/list.h
symm.md/global.o: /sprite/lib/include/errno.h
symm.md/global.o: /sprite/lib/include/status.h
symm.md/global.o: /sprite/lib/include/syslog.h
symm.md/global.o: /sprite/lib/include/bstring.h
symm.md/global.o: /sprite/lib/include/fs.h
symm.md/global.o: /sprite/lib/include/spriteTime.h
symm.md/global.o: /sprite/lib/include/proc.h
symm.md/global.o: /sprite/lib/include/sig.h
symm.md/global.o: /sprite/lib/include/symm.md/kernel/mach.h
symm.md/global.o: /sprite/lib/include/symm.md/kernel/machConst.h
symm.md/global.o: /sprite/lib/include/symm.md/kernel/vmSymConst.h
symm.md/global.o: /sprite/lib/include/symm.md/kernel/vmSymPTE.h
symm.md/global.o: /sprite/lib/include/symm.md/kernel/machTrap.h
symm.md/global.o: /sprite/lib/include/symm.md/kernel/machFpu.h
symm.md/global.o: /sprite/lib/include/sys/types.h
symm.md/global.o: /sprite/lib/include/fmt.h
symm.md/global.o: /sprite/lib/include/vm.h
symm.md/global.o: /sprite/lib/include/vmStat.h
symm.md/global.o: /sprite/lib/include/symm.md/kernel/vmMachStat.h
symm.md/global.o: /sprite/lib/include/kernel/fs.h
symm.md/global.o: /sprite/lib/include/kernel/sys.h
symm.md/global.o: /sprite/lib/include/kernel/user/sys.h
symm.md/global.o: /sprite/lib/include/kernel/sync.h
symm.md/global.o: /sprite/lib/include/kernel/proc.h
symm.md/global.o: /sprite/lib/include/kernel/syncLock.h
symm.md/global.o: /sprite/lib/include/kernel/user/sync.h
symm.md/global.o: /sprite/lib/include/kernel/timer.h
symm.md/global.o: /sprite/lib/include/symm.md/kernel/timerTick.h
symm.md/global.o: /sprite/lib/include/symm.md/kernel/timerMach.h
symm.md/global.o: /sprite/lib/include/kernel/sig.h
symm.md/global.o: /sprite/lib/include/sys/time.h
symm.md/global.o: /sprite/lib/include/unistd.h
symm.md/global.o: /sprite/lib/include/stdlib.h
symm.md/global.o: /sprite/lib/include/stdio.h
symm.md/global.o: /sprite/lib/include/varargs.h
symm.md/global.o: /sprite/lib/include/sys/dir.h
symm.md/global.o: /sprite/lib/include/sys/file.h
symm.md/global.o: /sprite/lib/include/sys/stat.h
symm.md/global.o: /sprite/lib/include/host.h
symm.md/global.o: /sprite/lib/include/netinet/in.h
symm.md/global.o: /sprite/lib/include/symm.md/machparam.h
symm.md/global.o: /sprite/lib/include/symm.md/limits.h
symm.md/global.o: /sprite/lib/include/signal.h
symm.md/global.o: /sprite/lib/include/pdev.h
symm.md/global.o: /sprite/lib/include/dev/pdev.h
symm.md/global.o: /sprite/lib/include/kernel/net.h
symm.md/global.o: /sprite/lib/include/netEther.h
symm.md/global.o: /sprite/lib/include/kernel/netRoute.h
symm.md/global.o: /sprite/lib/include/netInet.h
symm.md/global.o: /sprite/lib/include/kernel/user/net.h
symm.md/global.o: /sprite/lib/include/kernel/user/netEther.h
symm.md/global.o: /sprite/lib/include/kernel/user/netInet.h
symm.md/global.o: /sprite/lib/include/kernel/user/netUltra.h
symm.md/global.o: /sprite/lib/include/kernel/user/sprite.h
symm.md/global.o: /sprite/lib/include/mig.h migd.h migPdev.h
symm.md/main.o: main.c
symm.md/main.o: /sprite/lib/include/sprite.h
symm.md/main.o: /sprite/lib/include/cfuncproto.h
symm.md/main.o: /sprite/lib/include/stdio.h
symm.md/main.o: /sprite/lib/include/varargs.h
symm.md/main.o: /sprite/lib/include/stdlib.h
symm.md/main.o: /sprite/lib/include/string.h
symm.md/main.o: /sprite/lib/include/errno.h
symm.md/main.o: /sprite/lib/include/signal.h
symm.md/main.o: /sprite/lib/include/fs.h
symm.md/main.o: /sprite/lib/include/spriteTime.h
symm.md/main.o: /sprite/lib/include/proc.h
symm.md/main.o: /sprite/lib/include/sig.h
symm.md/main.o: /sprite/lib/include/symm.md/kernel/mach.h
symm.md/main.o: /sprite/lib/include/symm.md/kernel/machConst.h
symm.md/main.o: /sprite/lib/include/symm.md/kernel/vmSymConst.h
symm.md/main.o: /sprite/lib/include/symm.md/kernel/vmSymPTE.h
symm.md/main.o: /sprite/lib/include/symm.md/kernel/machTrap.h
symm.md/main.o: /sprite/lib/include/symm.md/kernel/machFpu.h
symm.md/main.o: /sprite/lib/include/sys/types.h
symm.md/main.o: /sprite/lib/include/fmt.h /sprite/lib/include/vm.h
symm.md/main.o: /sprite/lib/include/vmStat.h
symm.md/main.o: /sprite/lib/include/symm.md/kernel/vmMachStat.h
symm.md/main.o: /sprite/lib/include/option.h
symm.md/main.o: /sprite/lib/include/syslog.h
symm.md/main.o: /sprite/lib/include/status.h
symm.md/main.o: /sprite/lib/include/sysStats.h
symm.md/main.o: /sprite/lib/include/sys/file.h
symm.md/main.o: /sprite/lib/include/host.h
symm.md/main.o: /sprite/lib/include/netinet/in.h
symm.md/main.o: /sprite/lib/include/symm.md/machparam.h
symm.md/main.o: /sprite/lib/include/symm.md/limits.h migd.h
symm.md/main.o: /sprite/lib/include/mig.h
symm.md/main.o: /sprite/lib/include/list.h
symm.md/main.o: /sprite/lib/include/pdev.h
symm.md/main.o: /sprite/lib/include/dev/pdev.h
symm.md/main.o: /sprite/lib/include/kernel/fs.h
symm.md/main.o: /sprite/lib/include/kernel/sys.h
symm.md/main.o: /sprite/lib/include/kernel/user/sys.h
symm.md/main.o: /sprite/lib/include/kernel/sync.h
symm.md/main.o: /sprite/lib/include/kernel/proc.h
symm.md/main.o: /sprite/lib/include/kernel/syncLock.h
symm.md/main.o: /sprite/lib/include/kernel/user/sync.h
symm.md/main.o: /sprite/lib/include/kernel/timer.h
symm.md/main.o: /sprite/lib/include/symm.md/kernel/timerTick.h
symm.md/main.o: /sprite/lib/include/symm.md/kernel/timerMach.h
symm.md/main.o: /sprite/lib/include/kernel/sig.h migPdev.h global.h
symm.md/migPdev.o: migPdev.c
symm.md/migPdev.o: /sprite/lib/include/sprite.h
symm.md/migPdev.o: /sprite/lib/include/cfuncproto.h
symm.md/migPdev.o: /sprite/lib/include/string.h
symm.md/migPdev.o: /sprite/lib/include/errno.h
symm.md/migPdev.o: /sprite/lib/include/status.h
symm.md/migPdev.o: /sprite/lib/include/syslog.h
symm.md/migPdev.o: /sprite/lib/include/bstring.h
symm.md/migPdev.o: /sprite/lib/include/fs.h
symm.md/migPdev.o: /sprite/lib/include/spriteTime.h
symm.md/migPdev.o: /sprite/lib/include/proc.h
symm.md/migPdev.o: /sprite/lib/include/sig.h
symm.md/migPdev.o: /sprite/lib/include/symm.md/kernel/mach.h
symm.md/migPdev.o: /sprite/lib/include/symm.md/kernel/machConst.h
symm.md/migPdev.o: /sprite/lib/include/symm.md/kernel/vmSymConst.h
symm.md/migPdev.o: /sprite/lib/include/symm.md/kernel/vmSymPTE.h
symm.md/migPdev.o: /sprite/lib/include/symm.md/kernel/machTrap.h
symm.md/migPdev.o: /sprite/lib/include/symm.md/kernel/machFpu.h
symm.md/migPdev.o: /sprite/lib/include/sys/types.h
symm.md/migPdev.o: /sprite/lib/include/fmt.h
symm.md/migPdev.o: /sprite/lib/include/vm.h
symm.md/migPdev.o: /sprite/lib/include/vmStat.h
symm.md/migPdev.o: /sprite/lib/include/symm.md/kernel/vmMachStat.h
symm.md/migPdev.o: /sprite/lib/include/kernel/fs.h
symm.md/migPdev.o: /sprite/lib/include/kernel/sys.h
symm.md/migPdev.o: /sprite/lib/include/kernel/user/sys.h
symm.md/migPdev.o: /sprite/lib/include/kernel/sync.h
symm.md/migPdev.o: /sprite/lib/include/list.h
symm.md/migPdev.o: /sprite/lib/include/kernel/proc.h
symm.md/migPdev.o: /sprite/lib/include/kernel/syncLock.h
symm.md/migPdev.o: /sprite/lib/include/kernel/user/sync.h
symm.md/migPdev.o: /sprite/lib/include/kernel/timer.h
symm.md/migPdev.o: /sprite/lib/include/symm.md/kernel/timerTick.h
symm.md/migPdev.o: /sprite/lib/include/symm.md/kernel/timerMach.h
symm.md/migPdev.o: /sprite/lib/include/kernel/sig.h
symm.md/migPdev.o: /sprite/lib/include/unistd.h
symm.md/migPdev.o: /sprite/lib/include/stdlib.h
symm.md/migPdev.o: /sprite/lib/include/stdio.h
symm.md/migPdev.o: /sprite/lib/include/varargs.h
symm.md/migPdev.o: /sprite/lib/include/sys/dir.h
symm.md/migPdev.o: /sprite/lib/include/sys/stat.h
symm.md/migPdev.o: /sprite/lib/include/host.h
symm.md/migPdev.o: /sprite/lib/include/netinet/in.h
symm.md/migPdev.o: /sprite/lib/include/symm.md/machparam.h
symm.md/migPdev.o: /sprite/lib/include/symm.md/limits.h
symm.md/migPdev.o: /sprite/lib/include/pdev.h
symm.md/migPdev.o: /sprite/lib/include/dev/pdev.h migd.h
symm.md/migPdev.o: /sprite/lib/include/mig.h migPdev.h global.h
symm.md/migd.o: migd.c
symm.md/migd.o: /sprite/lib/include/sprite.h
symm.md/migd.o: /sprite/lib/include/cfuncproto.h
symm.md/migd.o: /sprite/lib/include/stdio.h
symm.md/migd.o: /sprite/lib/include/varargs.h
symm.md/migd.o: /sprite/lib/include/stdlib.h
symm.md/migd.o: /sprite/lib/include/string.h
symm.md/migd.o: /sprite/lib/include/errno.h
symm.md/migd.o: /sprite/lib/include/signal.h
symm.md/migd.o: /sprite/lib/include/setjmp.h
symm.md/migd.o: /sprite/lib/include/fs.h
symm.md/migd.o: /sprite/lib/include/spriteTime.h
symm.md/migd.o: /sprite/lib/include/proc.h
symm.md/migd.o: /sprite/lib/include/sig.h
symm.md/migd.o: /sprite/lib/include/symm.md/kernel/mach.h
symm.md/migd.o: /sprite/lib/include/symm.md/kernel/machConst.h
symm.md/migd.o: /sprite/lib/include/symm.md/kernel/vmSymConst.h
symm.md/migd.o: /sprite/lib/include/symm.md/kernel/vmSymPTE.h
symm.md/migd.o: /sprite/lib/include/symm.md/kernel/machTrap.h
symm.md/migd.o: /sprite/lib/include/symm.md/kernel/machFpu.h
symm.md/migd.o: /sprite/lib/include/sys/types.h
symm.md/migd.o: /sprite/lib/include/fmt.h /sprite/lib/include/vm.h
symm.md/migd.o: /sprite/lib/include/vmStat.h
symm.md/migd.o: /sprite/lib/include/symm.md/kernel/vmMachStat.h
symm.md/migd.o: /sprite/lib/include/option.h
symm.md/migd.o: /sprite/lib/include/syslog.h
symm.md/migd.o: /sprite/lib/include/status.h
symm.md/migd.o: /sprite/lib/include/sysStats.h
symm.md/migd.o: /sprite/lib/include/host.h
symm.md/migd.o: /sprite/lib/include/netinet/in.h
symm.md/migd.o: /sprite/lib/include/symm.md/machparam.h
symm.md/migd.o: /sprite/lib/include/symm.md/limits.h
symm.md/migd.o: /sprite/lib/include/sys/stat.h
symm.md/migd.o: /sprite/lib/include/sys/file.h
symm.md/migd.o: /sprite/lib/include/sys/signal.h
symm.md/migd.o: /sprite/lib/include/sys/wait.h
symm.md/migd.o: /sprite/lib/include/sys/time.h
symm.md/migd.o: /sprite/lib/include/sys/resource.h
symm.md/migd.o: /sprite/lib/include/kernel/sched.h
symm.md/migd.o: /sprite/lib/include/kernel/timer.h
symm.md/migd.o: /sprite/lib/include/list.h
symm.md/migd.o: /sprite/lib/include/symm.md/kernel/timerTick.h
symm.md/migd.o: /sprite/lib/include/symm.md/kernel/timerMach.h
symm.md/migd.o: /sprite/lib/include/kernel/syncLock.h
symm.md/migd.o: /sprite/lib/include/kernel/user/sync.h
symm.md/migd.o: /sprite/lib/include/kernel/proc.h
symm.md/migd.o: /sprite/lib/include/kernel/sync.h
symm.md/migd.o: /sprite/lib/include/kernel/sys.h
symm.md/migd.o: /sprite/lib/include/kernel/user/sys.h
symm.md/migd.o: /sprite/lib/include/kernel/sig.h
symm.md/migd.o: /sprite/lib/include/kernel/procMigrate.h
symm.md/migd.o: /sprite/lib/include/kernel/trace.h
symm.md/migd.o: /sprite/lib/include/kernel/net.h
symm.md/migd.o: /sprite/lib/include/netEther.h
symm.md/migd.o: /sprite/lib/include/kernel/netRoute.h
symm.md/migd.o: /sprite/lib/include/netInet.h
symm.md/migd.o: /sprite/lib/include/kernel/user/net.h
symm.md/migd.o: /sprite/lib/include/kernel/user/netEther.h
symm.md/migd.o: /sprite/lib/include/kernel/user/netInet.h
symm.md/migd.o: /sprite/lib/include/kernel/user/netUltra.h
symm.md/migd.o: /sprite/lib/include/kernel/user/sprite.h
symm.md/migd.o: /sprite/lib/include/bit.h /sprite/lib/include/pwd.h
symm.md/migd.o: migd.h /sprite/lib/include/mig.h
symm.md/migd.o: /sprite/lib/include/pdev.h
symm.md/migd.o: /sprite/lib/include/dev/pdev.h
symm.md/migd.o: /sprite/lib/include/kernel/fs.h migPdev.h global.h
symm.md/util.o: util.c
symm.md/util.o: /sprite/lib/include/syslog.h
symm.md/util.o: /sprite/lib/include/stdlib.h
symm.md/util.o: /sprite/lib/include/stdio.h
symm.md/util.o: /sprite/lib/include/sprite.h
symm.md/util.o: /sprite/lib/include/cfuncproto.h
symm.md/util.o: /sprite/lib/include/varargs.h
symm.md/util.o: /sprite/lib/include/errno.h migd.h
symm.md/util.o: /sprite/lib/include/fs.h
symm.md/util.o: /sprite/lib/include/spriteTime.h
symm.md/util.o: /sprite/lib/include/proc.h
symm.md/util.o: /sprite/lib/include/sig.h
symm.md/util.o: /sprite/lib/include/symm.md/kernel/mach.h
symm.md/util.o: /sprite/lib/include/symm.md/kernel/machConst.h
symm.md/util.o: /sprite/lib/include/symm.md/kernel/vmSymConst.h
symm.md/util.o: /sprite/lib/include/symm.md/kernel/vmSymPTE.h
symm.md/util.o: /sprite/lib/include/symm.md/kernel/machTrap.h
symm.md/util.o: /sprite/lib/include/symm.md/kernel/machFpu.h
symm.md/util.o: /sprite/lib/include/sys/types.h
symm.md/util.o: /sprite/lib/include/fmt.h /sprite/lib/include/vm.h
symm.md/util.o: /sprite/lib/include/vmStat.h
symm.md/util.o: /sprite/lib/include/symm.md/kernel/vmMachStat.h
symm.md/util.o: /sprite/lib/include/mig.h
symm.md/util.o: /sprite/lib/include/list.h
symm.md/util.o: /sprite/lib/include/pdev.h
symm.md/util.o: /sprite/lib/include/dev/pdev.h
symm.md/util.o: /sprite/lib/include/kernel/fs.h
symm.md/util.o: /sprite/lib/include/kernel/sys.h
symm.md/util.o: /sprite/lib/include/kernel/user/sys.h
symm.md/util.o: /sprite/lib/include/status.h
symm.md/util.o: /sprite/lib/include/kernel/sync.h
symm.md/util.o: /sprite/lib/include/kernel/proc.h
symm.md/util.o: /sprite/lib/include/kernel/syncLock.h
symm.md/util.o: /sprite/lib/include/kernel/user/sync.h
symm.md/util.o: /sprite/lib/include/kernel/timer.h
symm.md/util.o: /sprite/lib/include/symm.md/kernel/timerTick.h
symm.md/util.o: /sprite/lib/include/symm.md/kernel/timerMach.h
symm.md/util.o: /sprite/lib/include/kernel/sig.h
