# DO NOT DELETE THIS LINE -- make depend depends on it.

ds3100.md/mt.o: mt.c
ds3100.md/mt.o: /sprite/lib/include/sprite.h
ds3100.md/mt.o: /sprite/lib/include/cfuncproto.h
ds3100.md/mt.o: /sprite/lib/include/status.h
ds3100.md/mt.o: /sprite/lib/include/time.h
ds3100.md/mt.o: /sprite/lib/include/sys/file.h
ds3100.md/mt.o: /sprite/lib/include/fs.h
ds3100.md/mt.o: /sprite/lib/include/spriteTime.h
ds3100.md/mt.o: /sprite/lib/include/kernel/procTypes.h
ds3100.md/mt.o: /sprite/lib/include/proc.h
ds3100.md/mt.o: /sprite/lib/include/kernel/sigTypes.h
ds3100.md/mt.o: /sprite/lib/include/ds3100.md/kernel/machTypes.h
ds3100.md/mt.o: /sprite/lib/include/ds3100.md/kernel/machConst.h
ds3100.md/mt.o: /sprite/lib/include/ds3100.md/kernel/vmPmaxConst.h
ds3100.md/mt.o: /sprite/lib/include/fmt.h /sprite/lib/include/sig.h
ds3100.md/mt.o: /sprite/lib/include/vmTypes.h
ds3100.md/mt.o: /sprite/lib/include/sync.h
ds3100.md/mt.o: /sprite/lib/include/kernel/syncLock.h
ds3100.md/mt.o: /sprite/lib/include/list.h
ds3100.md/mt.o: /sprite/lib/include/kernel/timer.h
ds3100.md/mt.o: /sprite/lib/include/ds3100.md/kernel/timerTick.h
ds3100.md/mt.o: /sprite/lib/include/ds3100.md/kernel/timerMach.h
ds3100.md/mt.o: /sprite/lib/include/dev/tape.h
ds3100.md/mt.o: /sprite/lib/include/sys/types.h
ds3100.md/mt.o: /sprite/lib/include/stdio.h
ds3100.md/mt.o: /sprite/lib/include/option.h
ds3100.md/mt.o: /sprite/lib/include/errno.h mtio.h
ds3100.md/mt.o: /sprite/lib/include/ds3100.md/limits.h
ds3100.md/Ioc_TapeCommand.o: Ioc_TapeCommand.c
ds3100.md/Ioc_TapeCommand.o: /sprite/lib/include/sprite.h
ds3100.md/Ioc_TapeCommand.o: /sprite/lib/include/cfuncproto.h
ds3100.md/Ioc_TapeCommand.o: /sprite/lib/include/fs.h
ds3100.md/Ioc_TapeCommand.o: /sprite/lib/include/spriteTime.h
ds3100.md/Ioc_TapeCommand.o: /sprite/lib/include/kernel/procTypes.h
ds3100.md/Ioc_TapeCommand.o: /sprite/lib/include/proc.h
ds3100.md/Ioc_TapeCommand.o: /sprite/lib/include/kernel/sigTypes.h
ds3100.md/Ioc_TapeCommand.o: /sprite/lib/include/ds3100.md/kernel/machTypes.h
ds3100.md/Ioc_TapeCommand.o: /sprite/lib/include/ds3100.md/kernel/machConst.h
ds3100.md/Ioc_TapeCommand.o: /sprite/lib/include/ds3100.md/kernel/vmPmaxConst.h
ds3100.md/Ioc_TapeCommand.o: /sprite/lib/include/fmt.h
ds3100.md/Ioc_TapeCommand.o: /sprite/lib/include/sig.h
ds3100.md/Ioc_TapeCommand.o: /sprite/lib/include/vmTypes.h
ds3100.md/Ioc_TapeCommand.o: /sprite/lib/include/sync.h
ds3100.md/Ioc_TapeCommand.o: /sprite/lib/include/kernel/syncLock.h
ds3100.md/Ioc_TapeCommand.o: /sprite/lib/include/list.h
ds3100.md/Ioc_TapeCommand.o: /sprite/lib/include/kernel/timer.h
ds3100.md/Ioc_TapeCommand.o: /sprite/lib/include/ds3100.md/kernel/timerTick.h
ds3100.md/Ioc_TapeCommand.o: /sprite/lib/include/ds3100.md/kernel/timerMach.h
ds3100.md/Ioc_TapeCommand.o: /sprite/lib/include/dev/tape.h
ds3100.md/Ioc_TapeCommand.o: /sprite/lib/include/sys/types.h
