# DO NOT DELETE THIS LINE -- make depend depends on it.

sun4.md/rlogind.o: rlogind.c
sun4.md/rlogind.o: /sprite/lib/include/sys/types.h
sun4.md/rlogind.o: /sprite/lib/include/sys/stat.h
sun4.md/rlogind.o: /sprite/lib/include/cfuncproto.h
sun4.md/rlogind.o: /sprite/lib/include/sys/socket.h
sun4.md/rlogind.o: /sprite/lib/include/sys/wait.h
sun4.md/rlogind.o: /sprite/lib/include/sun4.md/machine/machparam.h
sun4.md/rlogind.o: /sprite/lib/include/sun4.md/limits.h
sun4.md/rlogind.o: /sprite/lib/include/sys/file.h
sun4.md/rlogind.o: /sprite/lib/include/netinet/in.h
sun4.md/rlogind.o: /sprite/lib/include/dev/tty.h
sun4.md/rlogind.o: /sprite/lib/include/sys/ioctl.h
sun4.md/rlogind.o: /sprite/lib/include/sys/ttychars.h
sun4.md/rlogind.o: /sprite/lib/include/sys/ttydev.h
sun4.md/rlogind.o: /sprite/lib/include/sys/fb.h
sun4.md/rlogind.o: /sprite/lib/include/errno.h
sun4.md/rlogind.o: /sprite/lib/include/fs.h
sun4.md/rlogind.o: /sprite/lib/include/spriteTime.h
sun4.md/rlogind.o: /sprite/lib/include/sprite.h
sun4.md/rlogind.o: /sprite/lib/include/kernel/procTypes.h
sun4.md/rlogind.o: /sprite/lib/include/proc.h
sun4.md/rlogind.o: /sprite/lib/include/kernel/sigTypes.h
sun4.md/rlogind.o: /sprite/lib/include/sun4.md/kernel/machTypes.h
sun4.md/rlogind.o: /sprite/lib/include/sun4.md/kernel/devAddrs.h
sun4.md/rlogind.o: /sprite/lib/include/sun4.md/kernel/machConst.h
sun4.md/rlogind.o: /sprite/lib/include/sun4.md/kernel/vmSunConst.h
sun4.md/rlogind.o: /sprite/lib/include/kernel/sysSysCall.h
sun4.md/rlogind.o: /sprite/lib/include/kernel/sys.h
sun4.md/rlogind.o: /sprite/lib/include/sys.h
sun4.md/rlogind.o: /sprite/lib/include/status.h
sun4.md/rlogind.o: /sprite/lib/include/fmt.h
sun4.md/rlogind.o: /sprite/lib/include/sig.h
sun4.md/rlogind.o: /sprite/lib/include/vmTypes.h
sun4.md/rlogind.o: /sprite/lib/include/sync.h
sun4.md/rlogind.o: /sprite/lib/include/kernel/syncLock.h
sun4.md/rlogind.o: /sprite/lib/include/list.h
sun4.md/rlogind.o: /sprite/lib/include/kernel/timer.h
sun4.md/rlogind.o: /sprite/lib/include/sun4.md/kernel/timerTick.h
sun4.md/rlogind.o: /sprite/lib/include/sun4.md/kernel/timerMach.h
sun4.md/rlogind.o: /sprite/lib/include/pwd.h
sun4.md/rlogind.o: /sprite/lib/include/signal.h
sun4.md/rlogind.o: /sprite/lib/include/machSignal.h
sun4.md/rlogind.o: /sprite/lib/include/sgtty.h
sun4.md/rlogind.o: /sprite/lib/include/stdio.h
sun4.md/rlogind.o: /sprite/lib/include/netdb.h
sun4.md/rlogind.o: /sprite/lib/include/syslog.h
sun4.md/rlogind.o: /sprite/lib/include/string.h
sun4.md/rlogind.o: /sprite/lib/include/td.h
sun4.md/rlogind.o: /sprite/lib/include/rloginPseudoDev.h
sun4.md/rlogind.o: /sprite/lib/include/ulog.h
