' $Header: /sprite/src/cmds/sync/RCS/sync.man,v 1.1 90/04/27 14:53:23 ouster Exp $ SPRITE (Berkeley)
.so \*(]ltmac.sprite
.HS SYNC cmds
.BS
.SH NAME
sync \- force the file system's cache to the disk or the file server.
.SH SYNOPSIS
\fBsync\fR
.BE

.SH INTRODUCTION
.LP
This command forces the file system's cache to the disk or the file server.
.SH KEYWORDS
sync, write-back, cache, file system
