# DO NOT DELETE THIS LINE -- make depend depends on it.

sun4.md/mt.o: mt.c
sun4.md/mt.o: /sprite/lib/include/sprite.h
sun4.md/mt.o: /sprite/lib/include/cfuncproto.h
sun4.md/mt.o: /sprite/lib/include/status.h
sun4.md/mt.o: /sprite/lib/include/time.h
sun4.md/mt.o: /sprite/lib/include/sys/file.h
sun4.md/mt.o: /sprite/lib/include/fs.h
sun4.md/mt.o: /sprite/lib/include/spriteTime.h
sun4.md/mt.o: /sprite/lib/include/kernel/procTypes.h
sun4.md/mt.o: /sprite/lib/include/proc.h
sun4.md/mt.o: /sprite/lib/include/kernel/sigTypes.h
sun4.md/mt.o: /sprite/lib/include/sun4.md/kernel/machTypes.h
sun4.md/mt.o: /sprite/lib/include/sun4.md/kernel/devAddrs.h
sun4.md/mt.o: /sprite/lib/include/sun4.md/kernel/machConst.h
sun4.md/mt.o: /sprite/lib/include/sun4.md/kernel/vmSunConst.h
sun4.md/mt.o: /sprite/lib/include/kernel/sysSysCall.h
sun4.md/mt.o: /sprite/lib/include/kernel/sys.h
sun4.md/mt.o: /sprite/lib/include/sys.h /sprite/lib/include/fmt.h
sun4.md/mt.o: /sprite/lib/include/sig.h
sun4.md/mt.o: /sprite/lib/include/vmTypes.h
sun4.md/mt.o: /sprite/lib/include/sync.h
sun4.md/mt.o: /sprite/lib/include/kernel/syncLock.h
sun4.md/mt.o: /sprite/lib/include/list.h
sun4.md/mt.o: /sprite/lib/include/kernel/timer.h
sun4.md/mt.o: /sprite/lib/include/sun4.md/kernel/timerTick.h
sun4.md/mt.o: /sprite/lib/include/sun4.md/kernel/timerMach.h
sun4.md/mt.o: /sprite/lib/include/dev/tape.h
sun4.md/mt.o: /sprite/lib/include/sys/types.h
sun4.md/mt.o: /sprite/lib/include/stdio.h
sun4.md/mt.o: /sprite/lib/include/option.h
sun4.md/mt.o: /sprite/lib/include/errno.h mtio.h
sun4.md/mt.o: /sprite/lib/include/sun4.md/limits.h
sun4.md/Ioc_TapeCommand.o: Ioc_TapeCommand.c
sun4.md/Ioc_TapeCommand.o: /sprite/lib/include/sprite.h
sun4.md/Ioc_TapeCommand.o: /sprite/lib/include/cfuncproto.h
sun4.md/Ioc_TapeCommand.o: /sprite/lib/include/fs.h
sun4.md/Ioc_TapeCommand.o: /sprite/lib/include/spriteTime.h
sun4.md/Ioc_TapeCommand.o: /sprite/lib/include/kernel/procTypes.h
sun4.md/Ioc_TapeCommand.o: /sprite/lib/include/proc.h
sun4.md/Ioc_TapeCommand.o: /sprite/lib/include/kernel/sigTypes.h
sun4.md/Ioc_TapeCommand.o: /sprite/lib/include/sun4.md/kernel/machTypes.h
sun4.md/Ioc_TapeCommand.o: /sprite/lib/include/sun4.md/kernel/devAddrs.h
sun4.md/Ioc_TapeCommand.o: /sprite/lib/include/sun4.md/kernel/machConst.h
sun4.md/Ioc_TapeCommand.o: /sprite/lib/include/sun4.md/kernel/vmSunConst.h
sun4.md/Ioc_TapeCommand.o: /sprite/lib/include/kernel/sysSysCall.h
sun4.md/Ioc_TapeCommand.o: /sprite/lib/include/kernel/sys.h
sun4.md/Ioc_TapeCommand.o: /sprite/lib/include/sys.h
sun4.md/Ioc_TapeCommand.o: /sprite/lib/include/status.h
sun4.md/Ioc_TapeCommand.o: /sprite/lib/include/fmt.h
sun4.md/Ioc_TapeCommand.o: /sprite/lib/include/sig.h
sun4.md/Ioc_TapeCommand.o: /sprite/lib/include/vmTypes.h
sun4.md/Ioc_TapeCommand.o: /sprite/lib/include/sync.h
sun4.md/Ioc_TapeCommand.o: /sprite/lib/include/kernel/syncLock.h
sun4.md/Ioc_TapeCommand.o: /sprite/lib/include/list.h
sun4.md/Ioc_TapeCommand.o: /sprite/lib/include/kernel/timer.h
sun4.md/Ioc_TapeCommand.o: /sprite/lib/include/sun4.md/kernel/timerTick.h
sun4.md/Ioc_TapeCommand.o: /sprite/lib/include/sun4.md/kernel/timerMach.h
sun4.md/Ioc_TapeCommand.o: /sprite/lib/include/dev/tape.h
sun4.md/Ioc_TapeCommand.o: /sprite/lib/include/sys/types.h
