# DO NOT DELETE THIS LINE -- make depend depends on it.

ds3100.md/sysstat.o: sysstat.c
ds3100.md/sysstat.o: /sprite/lib/include/sprite.h
ds3100.md/sysstat.o: /sprite/lib/include/cfuncproto.h
ds3100.md/sysstat.o: /sprite/lib/include/spriteTime.h
ds3100.md/sysstat.o: /sprite/lib/include/fs.h
ds3100.md/sysstat.o: /sprite/lib/include/kernel/procTypes.h
ds3100.md/sysstat.o: /sprite/lib/include/sysStats.h
ds3100.md/sysstat.o: /sprite/lib/include/status.h
ds3100.md/sysstat.o: /sprite/lib/include/stdio.h
ds3100.md/sysstat.o: /sprite/lib/include/stdlib.h
ds3100.md/sysstat.o: /sprite/lib/include/option.h
ds3100.md/sysstat.o: /sprite/lib/include/host.h
ds3100.md/sysstat.o: /sprite/lib/include/sys/types.h
ds3100.md/sysstat.o: /sprite/lib/include/netinet/in.h
ds3100.md/sysstat.o: /sprite/lib/include/ds3100.md/machparam.h
ds3100.md/sysstat.o: /sprite/lib/include/machine/limits.h
ds3100.md/sysstat.o: /sprite/lib/include/sys/stat.h
ds3100.md/sysstat.o: /sprite/lib/include/net.h
ds3100.md/sysstat.o: /sprite/lib/include/machparam.h
ds3100.md/sysstat.o: /sprite/lib/include/netEther.h
ds3100.md/sysstat.o: /sprite/lib/include/netInet.h
ds3100.md/sysstat.o: /sprite/lib/include/netUltra.h
ds3100.md/sysstat.o: /sprite/lib/include/netFDDI.h
ds3100.md/sysstat.o: /sprite/lib/include/kernel/sysSysCall.h
ds3100.md/sysstat.o: /sprite/lib/include/kernel/trace.h
ds3100.md/sysstat.o: /sprite/lib/include/kernel/sync.h
ds3100.md/sysstat.o: /sprite/lib/include/list.h
ds3100.md/sysstat.o: /sprite/lib/include/kernel/syncTypes.h
ds3100.md/sysstat.o: /sprite/lib/include/ds3100.md/kernel/mach.h
ds3100.md/sysstat.o: /sprite/lib/include/kernel/proc.h
ds3100.md/sysstat.o: /sprite/lib/include/sys/ipc.h
ds3100.md/sysstat.o: /sprite/lib/include/sys/sem.h
ds3100.md/sysstat.o: /sprite/lib/include/kernel/sched.h
ds3100.md/sysstat.o: /sprite/lib/include/kernel/timer.h
ds3100.md/sysstat.o: /sprite/lib/include/ds3100.md/kernel/timerTick.h
ds3100.md/sysstat.o: /sprite/lib/include/ds3100.md/kernel/timerMach.h
ds3100.md/sysstat.o: /sprite/lib/include/kernel/syncLock.h
ds3100.md/sysstat.o: /sprite/lib/include/sync.h syscalls.h
ds3100.md/syscalls.o: syscalls.c
ds3100.md/syscalls.o: syscalls.h
