#
# This file is automatically included by Pmake while it is processing
# Makefile.  Makefile is automatically generated by mkmf, and this file
# provides additional local personalization
#
# By defining MEM_TRACE we turn on extra caller-PC tracing.
#

XCFLAGS += -DMEM_TRACE

#include	<$(SYSMAKEFILE)>
