#
# This file is automatically included by Pmake while it is processing
# Makefile.  Makefile is automatically generated by mkmf, and this file
# provides additional local personalization
#
# By defining MEM_TRACE we turn on extra caller-PC tracing.
#

NAME = mem
XCFLAGS += -DMEM_TRACE
#if empty(TM:Mds3100) && empty(TM:Mcleands3100)
XCFLAGS += -Wall
#endif


#include	<$(SYSMAKEFILE)>
