# DO NOT DELETE THIS LINE -- make depend depends on it.

ds3100.md/rlogind.o: rlogind.c
ds3100.md/rlogind.o: /sprite/lib/include/sys/types.h
ds3100.md/rlogind.o: /sprite/lib/include/sys/stat.h
ds3100.md/rlogind.o: /sprite/lib/include/cfuncproto.h
ds3100.md/rlogind.o: /sprite/lib/include/sys/socket.h
ds3100.md/rlogind.o: /sprite/lib/include/sys/wait.h
ds3100.md/rlogind.o: /sprite/lib/include/machine/machparam.h
ds3100.md/rlogind.o: /sprite/lib/include/machine/limits.h
ds3100.md/rlogind.o: /sprite/lib/include/sys/file.h
ds3100.md/rlogind.o: /sprite/lib/include/netinet/in.h
ds3100.md/rlogind.o: /sprite/lib/include/dev/tty.h
ds3100.md/rlogind.o: /sprite/lib/include/sys/ioctl.h
ds3100.md/rlogind.o: /sprite/lib/include/sys/ttychars.h
ds3100.md/rlogind.o: /sprite/lib/include/sys/ttydev.h
ds3100.md/rlogind.o: /sprite/lib/include/sys/fb.h
ds3100.md/rlogind.o: /sprite/lib/include/errno.h
ds3100.md/rlogind.o: /sprite/lib/include/fs.h
ds3100.md/rlogind.o: /sprite/lib/include/spriteTime.h
ds3100.md/rlogind.o: /sprite/lib/include/sprite.h
ds3100.md/rlogind.o: /sprite/lib/include/kernel/procTypes.h
ds3100.md/rlogind.o: /sprite/lib/include/proc.h
ds3100.md/rlogind.o: /sprite/lib/include/kernel/sigTypes.h
ds3100.md/rlogind.o: /sprite/lib/include/ds3100.md/kernel/machTypes.h
ds3100.md/rlogind.o: /sprite/lib/include/ds3100.md/kernel/machConst.h
ds3100.md/rlogind.o: /sprite/lib/include/ds3100.md/kernel/vmPmaxConst.h
ds3100.md/rlogind.o: /sprite/lib/include/fmt.h
ds3100.md/rlogind.o: /sprite/lib/include/sig.h
ds3100.md/rlogind.o: /sprite/lib/include/vmTypes.h
ds3100.md/rlogind.o: /sprite/lib/include/sync.h
ds3100.md/rlogind.o: /sprite/lib/include/kernel/syncLock.h
ds3100.md/rlogind.o: /sprite/lib/include/list.h
ds3100.md/rlogind.o: /sprite/lib/include/kernel/timer.h
ds3100.md/rlogind.o: /sprite/lib/include/ds3100.md/kernel/timerTick.h
ds3100.md/rlogind.o: /sprite/lib/include/ds3100.md/kernel/timerMach.h
ds3100.md/rlogind.o: /sprite/lib/include/pwd.h
ds3100.md/rlogind.o: /sprite/lib/include/signal.h
ds3100.md/rlogind.o: /sprite/lib/include/machSignal.h
ds3100.md/rlogind.o: /sprite/lib/include/sgtty.h
ds3100.md/rlogind.o: /sprite/lib/include/stdio.h
ds3100.md/rlogind.o: /sprite/lib/include/netdb.h
ds3100.md/rlogind.o: /sprite/lib/include/syslog.h
ds3100.md/rlogind.o: /sprite/lib/include/string.h
ds3100.md/rlogind.o: /sprite/lib/include/td.h
ds3100.md/rlogind.o: /sprite/lib/include/rloginPseudoDev.h
ds3100.md/rlogind.o: /sprite/lib/include/ulog.h
