# DO NOT DELETE THIS LINE -- make depend depends on it.

sun3.md/mktty.o: mktty.c
sun3.md/mktty.o: /sprite/lib/include/sprite.h
sun3.md/mktty.o: /sprite/lib/include/cfuncproto.h
sun3.md/mktty.o: /sprite/lib/include/bstring.h
sun3.md/mktty.o: /sprite/lib/include/errno.h
sun3.md/mktty.o: /sprite/lib/include/fcntl.h
sun3.md/mktty.o: /sprite/lib/include/fs.h
sun3.md/mktty.o: /sprite/lib/include/spriteTime.h
sun3.md/mktty.o: /sprite/lib/include/kernel/procTypes.h
sun3.md/mktty.o: /sprite/lib/include/proc.h
sun3.md/mktty.o: /sprite/lib/include/kernel/sigTypes.h
sun3.md/mktty.o: /sprite/lib/include/sun3.md/kernel/machTypes.h
sun3.md/mktty.o: /sprite/lib/include/sun3.md/kernel/devAddrs.h
sun3.md/mktty.o: /sprite/lib/include/sun3.md/kernel/machConst.h
sun3.md/mktty.o: /sprite/lib/include/sun3.md/kernel/vmSunConst.h
sun3.md/mktty.o: /sprite/lib/include/fmt.h
sun3.md/mktty.o: /sprite/lib/include/sig.h
sun3.md/mktty.o: /sprite/lib/include/vmTypes.h
sun3.md/mktty.o: /sprite/lib/include/sync.h
sun3.md/mktty.o: /sprite/lib/include/kernel/syncLock.h
sun3.md/mktty.o: /sprite/lib/include/list.h
sun3.md/mktty.o: /sprite/lib/include/kernel/timer.h
sun3.md/mktty.o: /sprite/lib/include/sun3.md/kernel/timerTick.h
sun3.md/mktty.o: /sprite/lib/include/sun3.md/kernel/timerMach.h
sun3.md/mktty.o: /sprite/lib/include/netdb.h
sun3.md/mktty.o: /sprite/lib/include/pdev.h
sun3.md/mktty.o: /sprite/lib/include/dev/pdev.h
sun3.md/mktty.o: /sprite/lib/include/sgtty.h
sun3.md/mktty.o: /sprite/lib/include/sys/ioctl.h
sun3.md/mktty.o: /sprite/lib/include/stdio.h
sun3.md/mktty.o: /sprite/lib/include/stdlib.h
sun3.md/mktty.o: /sprite/lib/include/string.h
sun3.md/mktty.o: /sprite/lib/include/sys/file.h
sun3.md/mktty.o: /sprite/lib/include/sys/types.h
sun3.md/mktty.o: /sprite/lib/include/sys/socket.h
sun3.md/mktty.o: /sprite/lib/include/netinet/in.h
sun3.md/mktty.o: /sprite/lib/include/sun3.md/machparam.h
sun3.md/mktty.o: /sprite/lib/include/sun3.md/limits.h
sun3.md/mktty.o: /sprite/lib/include/td.h
sun3.md/pdev.o: pdev.c
sun3.md/pdev.o: /sprite/lib/include/stdio.h
sun3.md/pdev.o: /sprite/lib/include/cfuncproto.h
sun3.md/pdev.o: /sprite/lib/include/sprite.h
sun3.md/pdev.o: /sprite/lib/include/ctype.h
sun3.md/pdev.o: /sprite/lib/include/errno.h
sun3.md/pdev.o: /sprite/lib/include/pdev.h /sprite/lib/include/fs.h
sun3.md/pdev.o: /sprite/lib/include/spriteTime.h
sun3.md/pdev.o: /sprite/lib/include/kernel/procTypes.h
sun3.md/pdev.o: /sprite/lib/include/proc.h
sun3.md/pdev.o: /sprite/lib/include/kernel/sigTypes.h
sun3.md/pdev.o: /sprite/lib/include/sun3.md/kernel/machTypes.h
sun3.md/pdev.o: /sprite/lib/include/sun3.md/kernel/devAddrs.h
sun3.md/pdev.o: /sprite/lib/include/sun3.md/kernel/machConst.h
sun3.md/pdev.o: /sprite/lib/include/sun3.md/kernel/vmSunConst.h
sun3.md/pdev.o: /sprite/lib/include/fmt.h /sprite/lib/include/sig.h
sun3.md/pdev.o: /sprite/lib/include/vmTypes.h
sun3.md/pdev.o: /sprite/lib/include/sync.h
sun3.md/pdev.o: /sprite/lib/include/kernel/syncLock.h
sun3.md/pdev.o: /sprite/lib/include/list.h
sun3.md/pdev.o: /sprite/lib/include/kernel/timer.h
sun3.md/pdev.o: /sprite/lib/include/sun3.md/kernel/timerTick.h
sun3.md/pdev.o: /sprite/lib/include/sun3.md/kernel/timerMach.h
sun3.md/pdev.o: /sprite/lib/include/dev/pdev.h
sun3.md/pdev.o: /sprite/lib/include/status.h
sun3.md/pdev.o: /sprite/lib/include/stdlib.h
sun3.md/pdev.o: /sprite/lib/include/string.h
sun3.md/pdev.o: /sprite/lib/include/sys/file.h
