# DO NOT DELETE THIS LINE -- make depend depends on it.

sun3.md/rpcstat.o: rpcstat.c
sun3.md/rpcstat.o: /sprite/lib/include/sprite.h
sun3.md/rpcstat.o: /sprite/lib/include/cfuncproto.h
sun3.md/rpcstat.o: /sprite/lib/include/stdio.h
sun3.md/rpcstat.o: /sprite/lib/include/sysStats.h
sun3.md/rpcstat.o: /sprite/lib/include/option.h
sun3.md/rpcstat.o: /sprite/lib/include/kernel/sched.h
sun3.md/rpcstat.o: /sprite/lib/include/kernel/timer.h
sun3.md/rpcstat.o: /sprite/lib/include/list.h
sun3.md/rpcstat.o: /sprite/lib/include/spriteTime.h
sun3.md/rpcstat.o: /sprite/lib/include/sun3.md/kernel/timerTick.h
sun3.md/rpcstat.o: /sprite/lib/include/sun3.md/kernel/timerMach.h
sun3.md/rpcstat.o: /sprite/lib/include/kernel/syncLock.h
sun3.md/rpcstat.o: /sprite/lib/include/sync.h
sun3.md/rpcstat.o: /sprite/lib/include/kernel/proc.h
sun3.md/rpcstat.o: /sprite/lib/include/kernel/procTypes.h
sun3.md/rpcstat.o: /sprite/lib/include/proc.h
sun3.md/rpcstat.o: /sprite/lib/include/kernel/sigTypes.h
sun3.md/rpcstat.o: /sprite/lib/include/sun3.md/kernel/machTypes.h
sun3.md/rpcstat.o: /sprite/lib/include/sun3.md/kernel/devAddrs.h
sun3.md/rpcstat.o: /sprite/lib/include/sun3.md/kernel/machConst.h
sun3.md/rpcstat.o: /sprite/lib/include/sun3.md/kernel/vmSunConst.h
sun3.md/rpcstat.o: /sprite/lib/include/fmt.h
sun3.md/rpcstat.o: /sprite/lib/include/sig.h
sun3.md/rpcstat.o: /sprite/lib/include/vmTypes.h
sun3.md/rpcstat.o: /sprite/lib/include/kernel/sig.h
sun3.md/rpcstat.o: /sprite/lib/include/kernel/rpc.h
sun3.md/rpcstat.o: /sprite/lib/include/status.h
sun3.md/rpcstat.o: /sprite/lib/include/kernel/net.h
sun3.md/rpcstat.o: /sprite/lib/include/net.h
sun3.md/rpcstat.o: /sprite/lib/include/machparam.h
sun3.md/rpcstat.o: /sprite/lib/include/sun3.md/limits.h
sun3.md/rpcstat.o: /sprite/lib/include/netEther.h
sun3.md/rpcstat.o: /sprite/lib/include/netInet.h
sun3.md/rpcstat.o: /sprite/lib/include/netUltra.h
sun3.md/rpcstat.o: /sprite/lib/include/netFDDI.h
sun3.md/rpcstat.o: /sprite/lib/include/kernel/syncTypes.h
sun3.md/rpcstat.o: /sprite/lib/include/kernel/netTypes.h
sun3.md/rpcstat.o: /sprite/lib/include/kernel/fs.h
sun3.md/rpcstat.o: /sprite/lib/include/kernel/sys.h
sun3.md/rpcstat.o: /sprite/lib/include/sys.h
sun3.md/rpcstat.o: /sprite/lib/include/fs.h
sun3.md/rpcstat.o: /sprite/lib/include/kernel/netRoute.h
sun3.md/rpcstat.o: /sprite/lib/include/kernel/rpcTypes.h
sun3.md/rpcstat.o: /sprite/lib/include/kernel/rpcCall.h
sun3.md/rpcstat.o: /sprite/lib/include/kernel/procMigrate.h
sun3.md/rpcstat.o: /sprite/lib/include/kernel/trace.h
sun3.md/rpcstat.o: /sprite/lib/include/sun3.md/kernel/mach.h
sun3.md/rpcstat.o: /sprite/lib/include/kernel/sysSysCallParam.h
sun3.md/rpcstat.o: /sprite/lib/include/kernel/sync.h
sun3.md/rpcstat.o: /sprite/lib/include/sys/types.h
sun3.md/rpcstat.o: /sprite/lib/include/sys/ipc.h
sun3.md/rpcstat.o: /sprite/lib/include/sys/sem.h
sun3.md/rpcstat.o: /sprite/lib/include/vmStat.h
sun3.md/rpcstat.o: /sprite/lib/include/sun3.md/kernel/vmMachStat.h
sun3.md/rpcstat.o: /sprite/lib/include/host.h
sun3.md/rpcstat.o: /sprite/lib/include/netinet/in.h
sun3.md/rpcstat.o: /sprite/lib/include/sys/stat.h
sun3.md/rpcstat.o: /sprite/lib/include/kernel/rpcClient.h
sun3.md/rpcstat.o: /sprite/lib/include/kernel/rpcPacket.h
sun3.md/rpcstat.o: /sprite/lib/include/kernel/rpcCltStat.h
sun3.md/rpcstat.o: /sprite/lib/include/user/rpc.h
sun3.md/rpcstat.o: /sprite/lib/include/kernel/rpcHistogram.h
sun3.md/rpcstat.o: /sprite/lib/include/kernel/rpcServer.h
sun3.md/rpcstat.o: /sprite/lib/include/kernel/rpcSrvStat.h
sun3.md/rpcstat.o: /sprite/lib/include/kernel/rpcTrace.h
