# DO NOT DELETE THIS LINE -- make depend depends on it.

sun3.md/ftpd.o: ftpd.c
sun3.md/ftpd.o: /sprite/lib/include/sys/param.h
sun3.md/ftpd.o: /sprite/lib/include/sys/types.h
sun3.md/ftpd.o: /sprite/lib/include/signal.h
sun3.md/ftpd.o: /sprite/lib/include/sun3.md/machparam.h
sun3.md/ftpd.o: /sprite/lib/include/sys/stat.h
sun3.md/ftpd.o: /sprite/lib/include/cfuncproto.h
sun3.md/ftpd.o: /sprite/lib/include/sys/ioctl.h
sun3.md/ftpd.o: /sprite/lib/include/sys/ttychars.h
sun3.md/ftpd.o: /sprite/lib/include/sys/ttydev.h
sun3.md/ftpd.o: /sprite/lib/include/sys/fb.h
sun3.md/ftpd.o: /sprite/lib/include/sys/socket.h
sun3.md/ftpd.o: /sprite/lib/include/sys/file.h
sun3.md/ftpd.o: /sprite/lib/include/sys/wait.h
sun3.md/ftpd.o: /sprite/lib/include/sun3.md/machine/machparam.h
sun3.md/ftpd.o: /sprite/lib/include/sun3.md/limits.h
sun3.md/ftpd.o: /sprite/lib/include/netinet/in.h
sun3.md/ftpd.o: /sprite/lib/include/arpa/ftp.h
sun3.md/ftpd.o: /sprite/lib/include/arpa/inet.h
sun3.md/ftpd.o: /sprite/lib/include/arpa/telnet.h
sun3.md/ftpd.o: /sprite/lib/include/stdio.h
sun3.md/ftpd.o: /sprite/lib/include/pwd.h
sun3.md/ftpd.o: /sprite/lib/include/sun3.md/setjmp.h
sun3.md/ftpd.o: /sprite/lib/include/netdb.h
sun3.md/ftpd.o: /sprite/lib/include/errno.h
sun3.md/ftpd.o: /sprite/lib/include/strings.h
sun3.md/ftpd.o: /sprite/lib/include/syslog.h
sun3.md/ftpd.o: /sprite/lib/include/sun3.md/varargs.h
sun3.md/ftpd.o: /sprite/lib/include/utmp.h
sun3.md/vers.o: vers.c
sun3.md/glob.o: glob.c
sun3.md/glob.o: /sprite/lib/include/sys/param.h
sun3.md/glob.o: /sprite/lib/include/sys/types.h
sun3.md/glob.o: /sprite/lib/include/signal.h
sun3.md/glob.o: /sprite/lib/include/sun3.md/machparam.h
sun3.md/glob.o: /sprite/lib/include/sys/stat.h
sun3.md/glob.o: /sprite/lib/include/cfuncproto.h
sun3.md/glob.o: /sprite/lib/include/sys/dir.h
sun3.md/glob.o: /sprite/lib/include/stdio.h
sun3.md/glob.o: /sprite/lib/include/errno.h
sun3.md/glob.o: /sprite/lib/include/pwd.h
