# DO NOT DELETE THIS LINE -- make depend depends on it.

sun4.md/nice.o: nice.c
sun4.md/nice.o: /sprite/lib/include/stdio.h
sun4.md/nice.o: /sprite/lib/include/cfuncproto.h
sun4.md/nice.o: /sprite/lib/include/sys/time.h
sun4.md/nice.o: /sprite/lib/include/sys/resource.h
sun4.md/nice.o: /sprite/lib/include/proc.h
sun4.md/nice.o: /sprite/lib/include/sprite.h
sun4.md/nice.o: /sprite/lib/include/spriteTime.h
sun4.md/nice.o: /sprite/lib/include/kernel/sigTypes.h
sun4.md/nice.o: /sprite/lib/include/sun4.md/kernel/machTypes.h
sun4.md/nice.o: /sprite/lib/include/sun4.md/kernel/devAddrs.h
sun4.md/nice.o: /sprite/lib/include/sun4.md/kernel/machConst.h
sun4.md/nice.o: /sprite/lib/include/sun4.md/kernel/vmSunConst.h
sun4.md/nice.o: /sprite/lib/include/kernel/sysSysCall.h
sun4.md/nice.o: /sprite/lib/include/kernel/sys.h
sun4.md/nice.o: /sprite/lib/include/status.h
sun4.md/nice.o: /sprite/lib/include/kernel/timer.h
sun4.md/nice.o: /sprite/lib/include/list.h
sun4.md/nice.o: /sprite/lib/include/sun4.md/kernel/timerTick.h
sun4.md/nice.o: /sprite/lib/include/sun4.md/kernel/timerMach.h
sun4.md/nice.o: /sprite/lib/include/kernel/syncLock.h
sun4.md/nice.o: /sprite/lib/include/kernel/user/sync.h
sun4.md/nice.o: /sprite/lib/include/fmt.h
sun4.md/nice.o: /sprite/lib/include/kernel/sig.h
sun4.md/nice.o: /sprite/lib/include/kernel/rpc.h
sun4.md/nice.o: /sprite/lib/include/kernel/net.h
sun4.md/nice.o: /sprite/lib/include/kernel/syncTypes.h
sun4.md/nice.o: /sprite/lib/include/kernel/sync.h
sun4.md/nice.o: /sprite/lib/include/sun4.md/kernel/mach.h
sun4.md/nice.o: /sprite/lib/include/kernel/procMigrate.h
sun4.md/nice.o: /sprite/lib/include/kernel/proc.h
sun4.md/nice.o: /sprite/lib/include/kernel/procTypes.h
sun4.md/nice.o: /sprite/lib/include/kernel/trace.h
sun4.md/nice.o: /sprite/lib/include/kernel/netTypes.h
sun4.md/nice.o: /sprite/lib/include/netEther.h
sun4.md/nice.o: /sprite/lib/include/sun4.md/machparam.h
sun4.md/nice.o: /sprite/lib/include/sun4.md/limits.h
sun4.md/nice.o: /sprite/lib/include/kernel/fs.h
sun4.md/nice.o: /sprite/lib/include/sys/types.h
sun4.md/nice.o: /sprite/lib/include/sys/ipc.h
sun4.md/nice.o: /sprite/lib/include/sys/sem.h
sun4.md/nice.o: /sprite/lib/include/netInet.h
sun4.md/nice.o: /sprite/lib/include/netUltra.h
sun4.md/nice.o: /sprite/lib/include/kernel/netRoute.h
sun4.md/nice.o: /sprite/lib/include/kernel/rpcTypes.h
sun4.md/nice.o: /sprite/lib/include/kernel/rpcCall.h
sun4.md/nice.o: /sprite/lib/include/vmTypes.h
