# DO NOT DELETE THIS LINE -- make depend depends on it.

sun3.md/dev.o: sun3.md/dev.c
sun3.md/dev.o: /sprite/lib/include/sprite.h
sun3.md/dev.o: /sprite/lib/include/cfuncproto.h devInt.h
sun3.md/dev.o: vmSunConst.h
sun3.md/devConfig.o: sun3.md/devConfig.c
sun3.md/devConfig.o: /sprite/lib/include/sprite.h
sun3.md/devConfig.o: /sprite/lib/include/cfuncproto.h boot.h
sun3.md/devConfig.o: devInt.h devTypesInt.h fs.h
sun3.md/devConfig.o: /sprite/lib/include/kernel/sys.h
sun3.md/devConfig.o: /sprite/lib/include/kernel/user/sys.h
sun3.md/devConfig.o: /sprite/lib/include/status.h
sun3.md/devConfig.o: /sprite/lib/include/kernel/timer.h
sun3.md/devConfig.o: /sprite/lib/include/list.h
sun3.md/devConfig.o: /sprite/lib/include/spriteTime.h
sun3.md/devConfig.o: /sprite/lib/include/sun3.md/kernel/timerTick.h
sun3.md/devConfig.o: /sprite/lib/include/sun3.md/kernel/timerMach.h
sun3.md/devConfig.o: /sprite/lib/include/kernel/syncLock.h
sun3.md/devConfig.o: /sprite/lib/include/kernel/user/sync.h
sun3.md/devConfig.o: /sprite/lib/include/kernel/sync.h
sun3.md/devConfig.o: /sprite/lib/include/kernel/syncTypes.h
sun3.md/devConfig.o: /sprite/lib/include/kernel/procTypes.h
sun3.md/devConfig.o: /sprite/lib/include/kernel/proc.h
sun3.md/devConfig.o: /sprite/lib/include/kernel/sig.h
sun3.md/devConfig.o: /sprite/lib/include/kernel/sigTypes.h
sun3.md/devConfig.o: /sprite/lib/include/sun3.md/kernel/machTypes.h
sun3.md/devConfig.o: /sprite/lib/include/sun3.md/kernel/devAddrs.h
sun3.md/devConfig.o: /sprite/lib/include/sun3.md/kernel/machConst.h
sun3.md/devConfig.o: /sprite/lib/include/sun3.md/kernel/vmSunConst.h
sun3.md/devConfig.o: /sprite/lib/include/fmt.h
sun3.md/devConfig.o: /sprite/lib/include/kernel/rpc.h
sun3.md/devConfig.o: /sprite/lib/include/kernel/net.h
sun3.md/devConfig.o: /sprite/lib/include/kernel/user/net.h
sun3.md/devConfig.o: /sprite/lib/include/sun3.md/machparam.h
sun3.md/devConfig.o: /sprite/lib/include/sun3.md/limits.h
sun3.md/devConfig.o: /sprite/lib/include/kernel/user/netEther.h
sun3.md/devConfig.o: /sprite/lib/include/kernel/user/netInet.h
sun3.md/devConfig.o: /sprite/lib/include/kernel/user/netUltra.h
sun3.md/devConfig.o: /sprite/lib/include/kernel/user/sprite.h
sun3.md/devConfig.o: /sprite/lib/include/kernel/netTypes.h
sun3.md/devConfig.o: /sprite/lib/include/netEther.h
sun3.md/devConfig.o: /sprite/lib/include/kernel/netRoute.h
sun3.md/devConfig.o: /sprite/lib/include/netInet.h
sun3.md/devConfig.o: /sprite/lib/include/kernel/rpcCall.h
sun3.md/devConfig.o: /sprite/lib/include/kernel/procMigrate.h
sun3.md/devConfig.o: /sprite/lib/include/kernel/trace.h
sun3.md/devConfig.o: /sprite/lib/include/sun3.md/kernel/mach.h
sun3.md/devConfig.o: scsiHBA.h scsi0.h
sun3.md/devFsOpTable.o: sun3.md/devFsOpTable.c
sun3.md/devFsOpTable.o: /sprite/lib/include/sprite.h
sun3.md/devFsOpTable.o: /sprite/lib/include/cfuncproto.h dev.h
sun3.md/devFsOpTable.o: /sprite/lib/include/status.h
sun3.md/devFsOpTable.o: /sprite/lib/include/kernel/devSyslog.h
sun3.md/devFsOpTable.o: /sprite/lib/include/kernel/user/fs.h
sun3.md/devFsOpTable.o: /sprite/lib/include/kernel/user/spriteTime.h
sun3.md/devFsOpTable.o: /sprite/lib/include/kernel/user/kernel/procTypes.h
sun3.md/devFsOpTable.o: /sprite/lib/include/kernel/user/kernel/proc.h
sun3.md/devFsOpTable.o: /sprite/lib/include/kernel/procTypes.h
sun3.md/devFsOpTable.o: /sprite/lib/include/kernel/proc.h
sun3.md/devFsOpTable.o: /sprite/lib/include/kernel/sync.h
sun3.md/devFsOpTable.o: /sprite/lib/include/list.h
sun3.md/devFsOpTable.o: /sprite/lib/include/kernel/syncTypes.h
sun3.md/devFsOpTable.o: /sprite/lib/include/kernel/syncLock.h
sun3.md/devFsOpTable.o: /sprite/lib/include/kernel/user/sync.h
sun3.md/devFsOpTable.o: /sprite/lib/include/sun3.md/kernel/machTypes.h
sun3.md/devFsOpTable.o: /sprite/lib/include/sun3.md/kernel/devAddrs.h
sun3.md/devFsOpTable.o: /sprite/lib/include/sun3.md/kernel/machConst.h
sun3.md/devFsOpTable.o: /sprite/lib/include/sun3.md/kernel/vmSunConst.h
sun3.md/devFsOpTable.o: /sprite/lib/include/fmt.h
sun3.md/devFsOpTable.o: /sprite/lib/include/sun3.md/kernel/mach.h
sun3.md/devFsOpTable.o: /sprite/lib/include/kernel/timer.h
sun3.md/devFsOpTable.o: /sprite/lib/include/spriteTime.h
sun3.md/devFsOpTable.o: /sprite/lib/include/sun3.md/kernel/timerTick.h
sun3.md/devFsOpTable.o: /sprite/lib/include/sun3.md/kernel/timerMach.h
sun3.md/devFsOpTable.o: /sprite/lib/include/kernel/sig.h
sun3.md/devFsOpTable.o: /sprite/lib/include/kernel/sigTypes.h
sun3.md/devFsOpTable.o: /sprite/lib/include/kernel/rpc.h
sun3.md/devFsOpTable.o: /sprite/lib/include/kernel/net.h
sun3.md/devFsOpTable.o: /sprite/lib/include/kernel/user/net.h
sun3.md/devFsOpTable.o: /sprite/lib/include/sun3.md/machparam.h
sun3.md/devFsOpTable.o: /sprite/lib/include/sun3.md/limits.h
sun3.md/devFsOpTable.o: /sprite/lib/include/kernel/user/netEther.h
sun3.md/devFsOpTable.o: /sprite/lib/include/kernel/user/netInet.h
sun3.md/devFsOpTable.o: /sprite/lib/include/kernel/user/netUltra.h
sun3.md/devFsOpTable.o: /sprite/lib/include/kernel/user/sprite.h
sun3.md/devFsOpTable.o: /sprite/lib/include/kernel/netTypes.h
sun3.md/devFsOpTable.o: /sprite/lib/include/netEther.h
sun3.md/devFsOpTable.o: /sprite/lib/include/kernel/netRoute.h
sun3.md/devFsOpTable.o: /sprite/lib/include/netInet.h
sun3.md/devFsOpTable.o: /sprite/lib/include/kernel/sys.h
sun3.md/devFsOpTable.o: /sprite/lib/include/kernel/user/sys.h
sun3.md/devFsOpTable.o: /sprite/lib/include/kernel/rpcCall.h
sun3.md/devFsOpTable.o: /sprite/lib/include/kernel/procMigrate.h
sun3.md/devFsOpTable.o: /sprite/lib/include/kernel/trace.h
sun3.md/devFsOpTable.o: /sprite/lib/include/kernel/user/kernel/sync.h
sun3.md/devFsOpTable.o: /sprite/lib/include/kernel/fs.h
sun3.md/devFsOpTable.o: /sprite/lib/include/sysStats.h devInt.h
sun3.md/devFsOpTable.o: rawBlockDev.h devFsOpTable.h user/fs.h
sun3.md/devFsOpTable.o: devBlockDevice.h devTypesInt.h
sun3.md/devFsOpTable.o: devSCSIDisk.h
sun3.md/devSCSI0.o: sun3.md/devSCSI0.c
sun3.md/devSCSI0.o: /sprite/lib/include/sprite.h
sun3.md/devSCSI0.o: /sprite/lib/include/cfuncproto.h mach.h
sun3.md/devSCSI0.o: /sprite/lib/include/sun3.md/kernel/devAddrs.h
sun3.md/devSCSI0.o: /sprite/lib/include/sun3.md/kernel/machTypes.h
sun3.md/devSCSI0.o: /sprite/lib/include/sun3.md/kernel/machConst.h
sun3.md/devSCSI0.o: /sprite/lib/include/sun3.md/kernel/vmSunConst.h
sun3.md/devSCSI0.o: /sprite/lib/include/fmt.h ../sync.h
sun3.md/devSCSI0.o: /sprite/lib/include/list.h
sun3.md/devSCSI0.o: /sprite/lib/include/kernel/syncTypes.h
sun3.md/devSCSI0.o: /sprite/lib/include/kernel/sync.h
sun3.md/devSCSI0.o: /sprite/lib/include/sun3.md/kernel/mach.h
sun3.md/devSCSI0.o: /sprite/lib/include/kernel/proc.h
sun3.md/devSCSI0.o: /sprite/lib/include/kernel/procTypes.h
sun3.md/devSCSI0.o: /sprite/lib/include/kernel/syncLock.h
sun3.md/devSCSI0.o: /sprite/lib/include/kernel/user/sync.h
sun3.md/devSCSI0.o: /sprite/lib/include/kernel/timer.h
sun3.md/devSCSI0.o: /sprite/lib/include/spriteTime.h
sun3.md/devSCSI0.o: /sprite/lib/include/sun3.md/kernel/timerTick.h
sun3.md/devSCSI0.o: /sprite/lib/include/sun3.md/kernel/timerMach.h
sun3.md/devSCSI0.o: /sprite/lib/include/kernel/sigTypes.h
sun3.md/devSCSI0.o: /sprite/lib/include/kernel/sig.h
sun3.md/devSCSI0.o: /sprite/lib/include/kernel/rpc.h
sun3.md/devSCSI0.o: /sprite/lib/include/kernel/net.h
sun3.md/devSCSI0.o: /sprite/lib/include/kernel/user/net.h
sun3.md/devSCSI0.o: /sprite/lib/include/sun3.md/machparam.h
sun3.md/devSCSI0.o: /sprite/lib/include/sun3.md/limits.h
sun3.md/devSCSI0.o: /sprite/lib/include/kernel/user/netEther.h
sun3.md/devSCSI0.o: /sprite/lib/include/kernel/user/netInet.h
sun3.md/devSCSI0.o: /sprite/lib/include/kernel/user/netUltra.h
sun3.md/devSCSI0.o: /sprite/lib/include/kernel/user/sprite.h
sun3.md/devSCSI0.o: /sprite/lib/include/kernel/netTypes.h
sun3.md/devSCSI0.o: /sprite/lib/include/netEther.h
sun3.md/devSCSI0.o: /sprite/lib/include/kernel/netRoute.h
sun3.md/devSCSI0.o: /sprite/lib/include/netInet.h
sun3.md/devSCSI0.o: /sprite/lib/include/kernel/sys.h
sun3.md/devSCSI0.o: /sprite/lib/include/kernel/user/sys.h
sun3.md/devSCSI0.o: /sprite/lib/include/status.h
sun3.md/devSCSI0.o: /sprite/lib/include/kernel/rpcCall.h
sun3.md/devSCSI0.o: /sprite/lib/include/kernel/procMigrate.h
sun3.md/devSCSI0.o: /sprite/lib/include/kernel/trace.h scsi0.h
sun3.md/devSCSI0.o: dev.h /sprite/lib/include/kernel/devSyslog.h
sun3.md/devSCSI0.o: /sprite/lib/include/kernel/user/fs.h
sun3.md/devSCSI0.o: /sprite/lib/include/kernel/user/spriteTime.h
sun3.md/devSCSI0.o: /sprite/lib/include/kernel/user/kernel/procTypes.h
sun3.md/devSCSI0.o: /sprite/lib/include/kernel/user/kernel/proc.h
sun3.md/devSCSI0.o: /sprite/lib/include/kernel/user/kernel/sync.h
sun3.md/devSCSI0.o: /sprite/lib/include/kernel/fs.h
sun3.md/devSCSI0.o: /sprite/lib/include/sysStats.h devInt.h scsi.h
sun3.md/devSCSI0.o: scsiHBA.h scsiDevice.h devMultibus.h
sun3.md/devSCSI0.o: /sprite/lib/include/stdlib.h boot.h machMon.h
sun3.md/devSCSI3.o: sun3.md/devSCSI3.c
sun3.md/devSCSI3.o: /sprite/lib/include/sprite.h
sun3.md/devSCSI3.o: /sprite/lib/include/cfuncproto.h ../sync.h
sun3.md/devSCSI3.o: /sprite/lib/include/list.h
sun3.md/devSCSI3.o: /sprite/lib/include/kernel/syncTypes.h
sun3.md/devSCSI3.o: /sprite/lib/include/kernel/sync.h
sun3.md/devSCSI3.o: /sprite/lib/include/sun3.md/kernel/mach.h
sun3.md/devSCSI3.o: /sprite/lib/include/sun3.md/kernel/devAddrs.h
sun3.md/devSCSI3.o: /sprite/lib/include/sun3.md/kernel/machTypes.h
sun3.md/devSCSI3.o: /sprite/lib/include/sun3.md/kernel/machConst.h
sun3.md/devSCSI3.o: /sprite/lib/include/sun3.md/kernel/vmSunConst.h
sun3.md/devSCSI3.o: /sprite/lib/include/fmt.h
sun3.md/devSCSI3.o: /sprite/lib/include/kernel/proc.h
sun3.md/devSCSI3.o: /sprite/lib/include/kernel/procTypes.h
sun3.md/devSCSI3.o: /sprite/lib/include/kernel/syncLock.h
sun3.md/devSCSI3.o: /sprite/lib/include/kernel/user/sync.h
sun3.md/devSCSI3.o: /sprite/lib/include/kernel/timer.h
sun3.md/devSCSI3.o: /sprite/lib/include/spriteTime.h
sun3.md/devSCSI3.o: /sprite/lib/include/sun3.md/kernel/timerTick.h
sun3.md/devSCSI3.o: /sprite/lib/include/sun3.md/kernel/timerMach.h
sun3.md/devSCSI3.o: /sprite/lib/include/kernel/sigTypes.h
sun3.md/devSCSI3.o: /sprite/lib/include/kernel/sig.h
sun3.md/devSCSI3.o: /sprite/lib/include/kernel/rpc.h
sun3.md/devSCSI3.o: /sprite/lib/include/kernel/net.h
sun3.md/devSCSI3.o: /sprite/lib/include/kernel/user/net.h
sun3.md/devSCSI3.o: /sprite/lib/include/sun3.md/machparam.h
sun3.md/devSCSI3.o: /sprite/lib/include/sun3.md/limits.h
sun3.md/devSCSI3.o: /sprite/lib/include/kernel/user/netEther.h
sun3.md/devSCSI3.o: /sprite/lib/include/kernel/user/netInet.h
sun3.md/devSCSI3.o: /sprite/lib/include/kernel/user/netUltra.h
sun3.md/devSCSI3.o: /sprite/lib/include/kernel/user/sprite.h
sun3.md/devSCSI3.o: /sprite/lib/include/kernel/netTypes.h
sun3.md/devSCSI3.o: /sprite/lib/include/netEther.h
sun3.md/devSCSI3.o: /sprite/lib/include/kernel/netRoute.h
sun3.md/devSCSI3.o: /sprite/lib/include/netInet.h
sun3.md/devSCSI3.o: /sprite/lib/include/kernel/sys.h
sun3.md/devSCSI3.o: /sprite/lib/include/kernel/user/sys.h
sun3.md/devSCSI3.o: /sprite/lib/include/status.h
sun3.md/devSCSI3.o: /sprite/lib/include/kernel/rpcCall.h
sun3.md/devSCSI3.o: /sprite/lib/include/kernel/procMigrate.h
sun3.md/devSCSI3.o: /sprite/lib/include/kernel/trace.h scsi3.h
sun3.md/devSCSI3.o: mach.h dev.h
sun3.md/devSCSI3.o: /sprite/lib/include/kernel/devSyslog.h
sun3.md/devSCSI3.o: /sprite/lib/include/kernel/user/fs.h
sun3.md/devSCSI3.o: /sprite/lib/include/kernel/user/spriteTime.h
sun3.md/devSCSI3.o: /sprite/lib/include/kernel/user/kernel/procTypes.h
sun3.md/devSCSI3.o: /sprite/lib/include/kernel/user/kernel/proc.h
sun3.md/devSCSI3.o: /sprite/lib/include/kernel/user/kernel/sync.h
sun3.md/devSCSI3.o: /sprite/lib/include/kernel/fs.h
sun3.md/devSCSI3.o: /sprite/lib/include/sysStats.h devInt.h
sun3.md/devSCSI3.o: scsiHBA.h scsiDevice.h
sun3.md/devSCSI3.o: /sprite/lib/include/stdlib.h boot.h dbg.h
sun3.md/byte.o: byte.c
sun3.md/devBlockDevice.o: devBlockDevice.c
sun3.md/devBlockDevice.o: /sprite/lib/include/sprite.h
sun3.md/devBlockDevice.o: /sprite/lib/include/cfuncproto.h
sun3.md/devBlockDevice.o: user/fs.h devBlockDevice.h devFsOpTable.h
sun3.md/devBlockDevice.o: sync.h /sprite/lib/include/list.h boot.h
sun3.md/devBlockDevice.o: /sprite/lib/include/kernel/sys.h
sun3.md/devBlockDevice.o: /sprite/lib/include/kernel/user/sys.h
sun3.md/devBlockDevice.o: /sprite/lib/include/status.h
sun3.md/devBlockDevice.o: /sprite/lib/include/kernel/timer.h
sun3.md/devBlockDevice.o: /sprite/lib/include/spriteTime.h
sun3.md/devBlockDevice.o: /sprite/lib/include/sun3.md/kernel/timerTick.h
sun3.md/devBlockDevice.o: /sprite/lib/include/sun3.md/kernel/timerMach.h
sun3.md/devBlockDevice.o: /sprite/lib/include/kernel/syncLock.h
sun3.md/devBlockDevice.o: /sprite/lib/include/kernel/user/sync.h
sun3.md/devBlockDevice.o: /sprite/lib/include/kernel/proc.h
sun3.md/devBlockDevice.o: /sprite/lib/include/kernel/procTypes.h
sun3.md/devBlockDevice.o: /sprite/lib/include/kernel/sync.h
sun3.md/devBlockDevice.o: /sprite/lib/include/kernel/syncTypes.h
sun3.md/devBlockDevice.o: /sprite/lib/include/sun3.md/kernel/machTypes.h
sun3.md/devBlockDevice.o: /sprite/lib/include/sun3.md/kernel/devAddrs.h
sun3.md/devBlockDevice.o: /sprite/lib/include/sun3.md/kernel/machConst.h
sun3.md/devBlockDevice.o: /sprite/lib/include/sun3.md/kernel/vmSunConst.h
sun3.md/devBlockDevice.o: /sprite/lib/include/fmt.h
sun3.md/devBlockDevice.o: /sprite/lib/include/sun3.md/kernel/mach.h
sun3.md/devBlockDevice.o: /sprite/lib/include/kernel/sigTypes.h
sun3.md/devBlockDevice.o: /sprite/lib/include/kernel/sig.h
sun3.md/devBlockDevice.o: /sprite/lib/include/kernel/rpc.h
sun3.md/devBlockDevice.o: /sprite/lib/include/kernel/net.h
sun3.md/devBlockDevice.o: /sprite/lib/include/kernel/user/net.h
sun3.md/devBlockDevice.o: /sprite/lib/include/sun3.md/machparam.h
sun3.md/devBlockDevice.o: /sprite/lib/include/sun3.md/limits.h
sun3.md/devBlockDevice.o: /sprite/lib/include/kernel/user/netEther.h
sun3.md/devBlockDevice.o: /sprite/lib/include/kernel/user/netInet.h
sun3.md/devBlockDevice.o: /sprite/lib/include/kernel/user/netUltra.h
sun3.md/devBlockDevice.o: /sprite/lib/include/kernel/user/sprite.h
sun3.md/devBlockDevice.o: /sprite/lib/include/kernel/netTypes.h
sun3.md/devBlockDevice.o: /sprite/lib/include/netEther.h
sun3.md/devBlockDevice.o: /sprite/lib/include/kernel/netRoute.h
sun3.md/devBlockDevice.o: /sprite/lib/include/netInet.h
sun3.md/devBlockDevice.o: /sprite/lib/include/kernel/rpcCall.h
sun3.md/devBlockDevice.o: /sprite/lib/include/kernel/procMigrate.h
sun3.md/devBlockDevice.o: /sprite/lib/include/kernel/trace.h
sun3.md/devBlockDevice.o: machMon.h
sun3.md/devRawBlockDev.o: devRawBlockDev.c
sun3.md/devRawBlockDev.o: /sprite/lib/include/sprite.h
sun3.md/devRawBlockDev.o: /sprite/lib/include/cfuncproto.h
sun3.md/devRawBlockDev.o: /sprite/lib/include/status.h
sun3.md/devRawBlockDev.o: rawBlockDev.h devBlockDevice.h user/fs.h
sun3.md/devRawBlockDev.o: dev.h
sun3.md/devRawBlockDev.o: /sprite/lib/include/kernel/devSyslog.h
sun3.md/devRawBlockDev.o: /sprite/lib/include/kernel/user/fs.h
sun3.md/devRawBlockDev.o: /sprite/lib/include/kernel/user/spriteTime.h
sun3.md/devRawBlockDev.o: /sprite/lib/include/kernel/user/kernel/procTypes.h
sun3.md/devRawBlockDev.o: /sprite/lib/include/kernel/user/kernel/proc.h
sun3.md/devRawBlockDev.o: /sprite/lib/include/kernel/procTypes.h
sun3.md/devRawBlockDev.o: /sprite/lib/include/kernel/proc.h
sun3.md/devRawBlockDev.o: /sprite/lib/include/kernel/sync.h
sun3.md/devRawBlockDev.o: /sprite/lib/include/list.h
sun3.md/devRawBlockDev.o: /sprite/lib/include/kernel/syncTypes.h
sun3.md/devRawBlockDev.o: /sprite/lib/include/kernel/syncLock.h
sun3.md/devRawBlockDev.o: /sprite/lib/include/kernel/user/sync.h
sun3.md/devRawBlockDev.o: /sprite/lib/include/sun3.md/kernel/machTypes.h
sun3.md/devRawBlockDev.o: /sprite/lib/include/sun3.md/kernel/devAddrs.h
sun3.md/devRawBlockDev.o: /sprite/lib/include/sun3.md/kernel/machConst.h
sun3.md/devRawBlockDev.o: /sprite/lib/include/sun3.md/kernel/vmSunConst.h
sun3.md/devRawBlockDev.o: /sprite/lib/include/fmt.h
sun3.md/devRawBlockDev.o: /sprite/lib/include/sun3.md/kernel/mach.h
sun3.md/devRawBlockDev.o: /sprite/lib/include/kernel/timer.h
sun3.md/devRawBlockDev.o: /sprite/lib/include/spriteTime.h
sun3.md/devRawBlockDev.o: /sprite/lib/include/sun3.md/kernel/timerTick.h
sun3.md/devRawBlockDev.o: /sprite/lib/include/sun3.md/kernel/timerMach.h
sun3.md/devRawBlockDev.o: /sprite/lib/include/kernel/sig.h
sun3.md/devRawBlockDev.o: /sprite/lib/include/kernel/sigTypes.h
sun3.md/devRawBlockDev.o: /sprite/lib/include/kernel/rpc.h
sun3.md/devRawBlockDev.o: /sprite/lib/include/kernel/net.h
sun3.md/devRawBlockDev.o: /sprite/lib/include/kernel/user/net.h
sun3.md/devRawBlockDev.o: /sprite/lib/include/sun3.md/machparam.h
sun3.md/devRawBlockDev.o: /sprite/lib/include/sun3.md/limits.h
sun3.md/devRawBlockDev.o: /sprite/lib/include/kernel/user/netEther.h
sun3.md/devRawBlockDev.o: /sprite/lib/include/kernel/user/netInet.h
sun3.md/devRawBlockDev.o: /sprite/lib/include/kernel/user/netUltra.h
sun3.md/devRawBlockDev.o: /sprite/lib/include/kernel/user/sprite.h
sun3.md/devRawBlockDev.o: /sprite/lib/include/kernel/netTypes.h
sun3.md/devRawBlockDev.o: /sprite/lib/include/netEther.h
sun3.md/devRawBlockDev.o: /sprite/lib/include/kernel/netRoute.h
sun3.md/devRawBlockDev.o: /sprite/lib/include/netInet.h
sun3.md/devRawBlockDev.o: /sprite/lib/include/kernel/sys.h
sun3.md/devRawBlockDev.o: /sprite/lib/include/kernel/user/sys.h
sun3.md/devRawBlockDev.o: /sprite/lib/include/kernel/rpcCall.h
sun3.md/devRawBlockDev.o: /sprite/lib/include/kernel/procMigrate.h
sun3.md/devRawBlockDev.o: /sprite/lib/include/kernel/trace.h
sun3.md/devRawBlockDev.o: /sprite/lib/include/kernel/user/kernel/sync.h
sun3.md/devRawBlockDev.o: /sprite/lib/include/kernel/fs.h
sun3.md/devRawBlockDev.o: /sprite/lib/include/sysStats.h devInt.h
sun3.md/devRawBlockDev.o: fs.h
sun3.md/devSCSI.o: devSCSI.c
sun3.md/devSCSI.o: /sprite/lib/include/sprite.h
sun3.md/devSCSI.o: /sprite/lib/include/cfuncproto.h mach.h
sun3.md/devSCSI.o: /sprite/lib/include/sun3.md/kernel/devAddrs.h
sun3.md/devSCSI.o: /sprite/lib/include/sun3.md/kernel/machTypes.h
sun3.md/devSCSI.o: /sprite/lib/include/sun3.md/kernel/machConst.h
sun3.md/devSCSI.o: /sprite/lib/include/sun3.md/kernel/vmSunConst.h
sun3.md/devSCSI.o: /sprite/lib/include/fmt.h dev.h
sun3.md/devSCSI.o: /sprite/lib/include/status.h
sun3.md/devSCSI.o: /sprite/lib/include/kernel/devSyslog.h
sun3.md/devSCSI.o: /sprite/lib/include/kernel/user/fs.h
sun3.md/devSCSI.o: /sprite/lib/include/kernel/user/spriteTime.h
sun3.md/devSCSI.o: /sprite/lib/include/kernel/user/kernel/procTypes.h
sun3.md/devSCSI.o: /sprite/lib/include/kernel/user/kernel/proc.h
sun3.md/devSCSI.o: /sprite/lib/include/kernel/procTypes.h
sun3.md/devSCSI.o: /sprite/lib/include/kernel/proc.h
sun3.md/devSCSI.o: /sprite/lib/include/kernel/sync.h
sun3.md/devSCSI.o: /sprite/lib/include/list.h
sun3.md/devSCSI.o: /sprite/lib/include/kernel/syncTypes.h
sun3.md/devSCSI.o: /sprite/lib/include/kernel/syncLock.h
sun3.md/devSCSI.o: /sprite/lib/include/kernel/user/sync.h
sun3.md/devSCSI.o: /sprite/lib/include/sun3.md/kernel/mach.h
sun3.md/devSCSI.o: /sprite/lib/include/kernel/timer.h
sun3.md/devSCSI.o: /sprite/lib/include/spriteTime.h
sun3.md/devSCSI.o: /sprite/lib/include/sun3.md/kernel/timerTick.h
sun3.md/devSCSI.o: /sprite/lib/include/sun3.md/kernel/timerMach.h
sun3.md/devSCSI.o: /sprite/lib/include/kernel/sig.h
sun3.md/devSCSI.o: /sprite/lib/include/kernel/sigTypes.h
sun3.md/devSCSI.o: /sprite/lib/include/kernel/rpc.h
sun3.md/devSCSI.o: /sprite/lib/include/kernel/net.h
sun3.md/devSCSI.o: /sprite/lib/include/kernel/user/net.h
sun3.md/devSCSI.o: /sprite/lib/include/sun3.md/machparam.h
sun3.md/devSCSI.o: /sprite/lib/include/sun3.md/limits.h
sun3.md/devSCSI.o: /sprite/lib/include/kernel/user/netEther.h
sun3.md/devSCSI.o: /sprite/lib/include/kernel/user/netInet.h
sun3.md/devSCSI.o: /sprite/lib/include/kernel/user/netUltra.h
sun3.md/devSCSI.o: /sprite/lib/include/kernel/user/sprite.h
sun3.md/devSCSI.o: /sprite/lib/include/kernel/netTypes.h
sun3.md/devSCSI.o: /sprite/lib/include/netEther.h
sun3.md/devSCSI.o: /sprite/lib/include/kernel/netRoute.h
sun3.md/devSCSI.o: /sprite/lib/include/netInet.h
sun3.md/devSCSI.o: /sprite/lib/include/kernel/sys.h
sun3.md/devSCSI.o: /sprite/lib/include/kernel/user/sys.h
sun3.md/devSCSI.o: /sprite/lib/include/kernel/rpcCall.h
sun3.md/devSCSI.o: /sprite/lib/include/kernel/procMigrate.h
sun3.md/devSCSI.o: /sprite/lib/include/kernel/trace.h
sun3.md/devSCSI.o: /sprite/lib/include/kernel/user/kernel/sync.h
sun3.md/devSCSI.o: /sprite/lib/include/kernel/fs.h
sun3.md/devSCSI.o: /sprite/lib/include/sysStats.h devInt.h scsi.h
sun3.md/devSCSI.o: scsiDevice.h dbg.h vm.h
sun3.md/devSCSI.o: /sprite/lib/include/vmStat.h
sun3.md/devSCSI.o: /sprite/lib/include/sun3.md/kernel/vmMachStat.h
sun3.md/devSCSI.o: sys.h sync.h boot.h fs.h
sun3.md/devSCSI.o: /sprite/lib/include/stdlib.h sched.h
sun3.md/devSCSIDisk.o: devSCSIDisk.c
sun3.md/devSCSIDisk.o: /sprite/lib/include/sprite.h
sun3.md/devSCSIDisk.o: /sprite/lib/include/cfuncproto.h fs.h
sun3.md/devSCSIDisk.o: /sprite/lib/include/kernel/sys.h
sun3.md/devSCSIDisk.o: /sprite/lib/include/kernel/user/sys.h
sun3.md/devSCSIDisk.o: /sprite/lib/include/status.h
sun3.md/devSCSIDisk.o: /sprite/lib/include/kernel/timer.h
sun3.md/devSCSIDisk.o: /sprite/lib/include/list.h
sun3.md/devSCSIDisk.o: /sprite/lib/include/spriteTime.h
sun3.md/devSCSIDisk.o: /sprite/lib/include/sun3.md/kernel/timerTick.h
sun3.md/devSCSIDisk.o: /sprite/lib/include/sun3.md/kernel/timerMach.h
sun3.md/devSCSIDisk.o: /sprite/lib/include/kernel/syncLock.h
sun3.md/devSCSIDisk.o: /sprite/lib/include/kernel/user/sync.h
sun3.md/devSCSIDisk.o: /sprite/lib/include/kernel/sync.h
sun3.md/devSCSIDisk.o: /sprite/lib/include/kernel/syncTypes.h
sun3.md/devSCSIDisk.o: /sprite/lib/include/kernel/procTypes.h
sun3.md/devSCSIDisk.o: /sprite/lib/include/kernel/proc.h
sun3.md/devSCSIDisk.o: /sprite/lib/include/kernel/sig.h
sun3.md/devSCSIDisk.o: /sprite/lib/include/kernel/sigTypes.h
sun3.md/devSCSIDisk.o: /sprite/lib/include/sun3.md/kernel/machTypes.h
sun3.md/devSCSIDisk.o: /sprite/lib/include/sun3.md/kernel/devAddrs.h
sun3.md/devSCSIDisk.o: /sprite/lib/include/sun3.md/kernel/machConst.h
sun3.md/devSCSIDisk.o: /sprite/lib/include/sun3.md/kernel/vmSunConst.h
sun3.md/devSCSIDisk.o: /sprite/lib/include/fmt.h
sun3.md/devSCSIDisk.o: /sprite/lib/include/kernel/rpc.h
sun3.md/devSCSIDisk.o: /sprite/lib/include/kernel/net.h
sun3.md/devSCSIDisk.o: /sprite/lib/include/kernel/user/net.h
sun3.md/devSCSIDisk.o: /sprite/lib/include/sun3.md/machparam.h
sun3.md/devSCSIDisk.o: /sprite/lib/include/sun3.md/limits.h
sun3.md/devSCSIDisk.o: /sprite/lib/include/kernel/user/netEther.h
sun3.md/devSCSIDisk.o: /sprite/lib/include/kernel/user/netInet.h
sun3.md/devSCSIDisk.o: /sprite/lib/include/kernel/user/netUltra.h
sun3.md/devSCSIDisk.o: /sprite/lib/include/kernel/user/sprite.h
sun3.md/devSCSIDisk.o: /sprite/lib/include/kernel/netTypes.h
sun3.md/devSCSIDisk.o: /sprite/lib/include/netEther.h
sun3.md/devSCSIDisk.o: /sprite/lib/include/kernel/netRoute.h
sun3.md/devSCSIDisk.o: /sprite/lib/include/netInet.h
sun3.md/devSCSIDisk.o: /sprite/lib/include/kernel/rpcCall.h
sun3.md/devSCSIDisk.o: /sprite/lib/include/kernel/procMigrate.h
sun3.md/devSCSIDisk.o: /sprite/lib/include/kernel/trace.h
sun3.md/devSCSIDisk.o: /sprite/lib/include/sun3.md/kernel/mach.h
sun3.md/devSCSIDisk.o: dev.h /sprite/lib/include/kernel/devSyslog.h
sun3.md/devSCSIDisk.o: /sprite/lib/include/kernel/user/fs.h
sun3.md/devSCSIDisk.o: /sprite/lib/include/kernel/user/spriteTime.h
sun3.md/devSCSIDisk.o: /sprite/lib/include/kernel/user/kernel/procTypes.h
sun3.md/devSCSIDisk.o: /sprite/lib/include/kernel/user/kernel/proc.h
sun3.md/devSCSIDisk.o: /sprite/lib/include/kernel/user/kernel/sync.h
sun3.md/devSCSIDisk.o: /sprite/lib/include/kernel/fs.h
sun3.md/devSCSIDisk.o: /sprite/lib/include/sysStats.h devInt.h
sun3.md/devSCSIDisk.o: scsi.h scsiDevice.h devDiskLabel.h
sun3.md/devSCSIDisk.o: devDiskStats.h user/sysStats.h user/fs.h
sun3.md/devSCSIDisk.o: devBlockDevice.h
sun3.md/devSCSIDisk.o: /sprite/lib/include/stdlib.h
sun3.md/devSCSIDisk.o: /sprite/lib/include/dev/scsi.h boot.h dbg.h
sun3.md/devScsiDevice.o: devScsiDevice.c
sun3.md/devScsiDevice.o: /sprite/lib/include/sprite.h
sun3.md/devScsiDevice.o: /sprite/lib/include/cfuncproto.h
sun3.md/devScsiDevice.o: scsiDevice.h scsiHBA.h
sun3.md/devScsiDevice.o: /sprite/lib/include/dev/scsi.h scsi.h
sun3.md/devScsiDevice.o: devQueue.h /sprite/lib/include/list.h
sun3.md/devScsiDevice.o: boot.h user/fs.h sync.h
sun3.md/devScsiDevice.o: /sprite/lib/include/kernel/sys.h
sun3.md/devScsiDevice.o: /sprite/lib/include/kernel/user/sys.h
sun3.md/devScsiDevice.o: /sprite/lib/include/status.h
sun3.md/devScsiDevice.o: /sprite/lib/include/kernel/timer.h
sun3.md/devScsiDevice.o: /sprite/lib/include/spriteTime.h
sun3.md/devScsiDevice.o: /sprite/lib/include/sun3.md/kernel/timerTick.h
sun3.md/devScsiDevice.o: /sprite/lib/include/sun3.md/kernel/timerMach.h
sun3.md/devScsiDevice.o: /sprite/lib/include/kernel/syncLock.h
sun3.md/devScsiDevice.o: /sprite/lib/include/kernel/user/sync.h
sun3.md/devScsiDevice.o: /sprite/lib/include/kernel/proc.h
sun3.md/devScsiDevice.o: /sprite/lib/include/kernel/procTypes.h
sun3.md/devScsiDevice.o: /sprite/lib/include/kernel/sync.h
sun3.md/devScsiDevice.o: /sprite/lib/include/kernel/syncTypes.h
sun3.md/devScsiDevice.o: /sprite/lib/include/sun3.md/kernel/machTypes.h
sun3.md/devScsiDevice.o: /sprite/lib/include/sun3.md/kernel/devAddrs.h
sun3.md/devScsiDevice.o: /sprite/lib/include/sun3.md/kernel/machConst.h
sun3.md/devScsiDevice.o: /sprite/lib/include/sun3.md/kernel/vmSunConst.h
sun3.md/devScsiDevice.o: /sprite/lib/include/fmt.h
sun3.md/devScsiDevice.o: /sprite/lib/include/sun3.md/kernel/mach.h
sun3.md/devScsiDevice.o: /sprite/lib/include/kernel/sigTypes.h
sun3.md/devScsiDevice.o: /sprite/lib/include/kernel/sig.h
sun3.md/devScsiDevice.o: /sprite/lib/include/kernel/rpc.h
sun3.md/devScsiDevice.o: /sprite/lib/include/kernel/net.h
sun3.md/devScsiDevice.o: /sprite/lib/include/kernel/user/net.h
sun3.md/devScsiDevice.o: /sprite/lib/include/sun3.md/machparam.h
sun3.md/devScsiDevice.o: /sprite/lib/include/sun3.md/limits.h
sun3.md/devScsiDevice.o: /sprite/lib/include/kernel/user/netEther.h
sun3.md/devScsiDevice.o: /sprite/lib/include/kernel/user/netInet.h
sun3.md/devScsiDevice.o: /sprite/lib/include/kernel/user/netUltra.h
sun3.md/devScsiDevice.o: /sprite/lib/include/kernel/user/sprite.h
sun3.md/devScsiDevice.o: /sprite/lib/include/kernel/netTypes.h
sun3.md/devScsiDevice.o: /sprite/lib/include/netEther.h
sun3.md/devScsiDevice.o: /sprite/lib/include/kernel/netRoute.h
sun3.md/devScsiDevice.o: /sprite/lib/include/netInet.h
sun3.md/devScsiDevice.o: /sprite/lib/include/kernel/rpcCall.h
sun3.md/devScsiDevice.o: /sprite/lib/include/kernel/procMigrate.h
sun3.md/devScsiDevice.o: /sprite/lib/include/kernel/trace.h
sun3.md/devScsiDevice.o: /sprite/lib/include/stdlib.h
sun3.md/fileLoad.o: fileLoad.c
sun3.md/fileLoad.o: /sprite/lib/include/sprite.h
sun3.md/fileLoad.o: /sprite/lib/include/cfuncproto.h fs.h
sun3.md/fileLoad.o: /sprite/lib/include/kernel/sys.h
sun3.md/fileLoad.o: /sprite/lib/include/kernel/user/sys.h
sun3.md/fileLoad.o: /sprite/lib/include/status.h
sun3.md/fileLoad.o: /sprite/lib/include/kernel/timer.h
sun3.md/fileLoad.o: /sprite/lib/include/list.h
sun3.md/fileLoad.o: /sprite/lib/include/spriteTime.h
sun3.md/fileLoad.o: /sprite/lib/include/sun3.md/kernel/timerTick.h
sun3.md/fileLoad.o: /sprite/lib/include/sun3.md/kernel/timerMach.h
sun3.md/fileLoad.o: /sprite/lib/include/kernel/syncLock.h
sun3.md/fileLoad.o: /sprite/lib/include/kernel/user/sync.h
sun3.md/fileLoad.o: /sprite/lib/include/kernel/sync.h
sun3.md/fileLoad.o: /sprite/lib/include/kernel/syncTypes.h
sun3.md/fileLoad.o: /sprite/lib/include/kernel/procTypes.h
sun3.md/fileLoad.o: /sprite/lib/include/kernel/proc.h
sun3.md/fileLoad.o: /sprite/lib/include/kernel/sig.h
sun3.md/fileLoad.o: /sprite/lib/include/kernel/sigTypes.h
sun3.md/fileLoad.o: /sprite/lib/include/sun3.md/kernel/machTypes.h
sun3.md/fileLoad.o: /sprite/lib/include/sun3.md/kernel/devAddrs.h
sun3.md/fileLoad.o: /sprite/lib/include/sun3.md/kernel/machConst.h
sun3.md/fileLoad.o: /sprite/lib/include/sun3.md/kernel/vmSunConst.h
sun3.md/fileLoad.o: /sprite/lib/include/fmt.h
sun3.md/fileLoad.o: /sprite/lib/include/kernel/rpc.h
sun3.md/fileLoad.o: /sprite/lib/include/kernel/net.h
sun3.md/fileLoad.o: /sprite/lib/include/kernel/user/net.h
sun3.md/fileLoad.o: /sprite/lib/include/sun3.md/machparam.h
sun3.md/fileLoad.o: /sprite/lib/include/sun3.md/limits.h
sun3.md/fileLoad.o: /sprite/lib/include/kernel/user/netEther.h
sun3.md/fileLoad.o: /sprite/lib/include/kernel/user/netInet.h
sun3.md/fileLoad.o: /sprite/lib/include/kernel/user/netUltra.h
sun3.md/fileLoad.o: /sprite/lib/include/kernel/user/sprite.h
sun3.md/fileLoad.o: /sprite/lib/include/kernel/netTypes.h
sun3.md/fileLoad.o: /sprite/lib/include/netEther.h
sun3.md/fileLoad.o: /sprite/lib/include/kernel/netRoute.h
sun3.md/fileLoad.o: /sprite/lib/include/netInet.h
sun3.md/fileLoad.o: /sprite/lib/include/kernel/rpcCall.h
sun3.md/fileLoad.o: /sprite/lib/include/kernel/procMigrate.h
sun3.md/fileLoad.o: /sprite/lib/include/kernel/trace.h
sun3.md/fileLoad.o: /sprite/lib/include/sun3.md/kernel/mach.h
sun3.md/fileLoad.o: procAOUT.h machMon.h boot.h
sun3.md/fs.o: fs.c
sun3.md/fs.o: /sprite/lib/include/sprite.h
sun3.md/fs.o: /sprite/lib/include/cfuncproto.h fsBoot.h fs.h
sun3.md/fs.o: /sprite/lib/include/kernel/sys.h
sun3.md/fs.o: /sprite/lib/include/kernel/user/sys.h
sun3.md/fs.o: /sprite/lib/include/status.h
sun3.md/fs.o: /sprite/lib/include/kernel/timer.h
sun3.md/fs.o: /sprite/lib/include/list.h
sun3.md/fs.o: /sprite/lib/include/spriteTime.h
sun3.md/fs.o: /sprite/lib/include/sun3.md/kernel/timerTick.h
sun3.md/fs.o: /sprite/lib/include/sun3.md/kernel/timerMach.h
sun3.md/fs.o: /sprite/lib/include/kernel/syncLock.h
sun3.md/fs.o: /sprite/lib/include/kernel/user/sync.h
sun3.md/fs.o: /sprite/lib/include/kernel/sync.h
sun3.md/fs.o: /sprite/lib/include/kernel/syncTypes.h
sun3.md/fs.o: /sprite/lib/include/kernel/procTypes.h
sun3.md/fs.o: /sprite/lib/include/kernel/proc.h
sun3.md/fs.o: /sprite/lib/include/kernel/sig.h
sun3.md/fs.o: /sprite/lib/include/kernel/sigTypes.h
sun3.md/fs.o: /sprite/lib/include/sun3.md/kernel/machTypes.h
sun3.md/fs.o: /sprite/lib/include/sun3.md/kernel/devAddrs.h
sun3.md/fs.o: /sprite/lib/include/sun3.md/kernel/machConst.h
sun3.md/fs.o: /sprite/lib/include/sun3.md/kernel/vmSunConst.h
sun3.md/fs.o: /sprite/lib/include/fmt.h
sun3.md/fs.o: /sprite/lib/include/kernel/rpc.h
sun3.md/fs.o: /sprite/lib/include/kernel/net.h
sun3.md/fs.o: /sprite/lib/include/kernel/user/net.h
sun3.md/fs.o: /sprite/lib/include/sun3.md/machparam.h
sun3.md/fs.o: /sprite/lib/include/sun3.md/limits.h
sun3.md/fs.o: /sprite/lib/include/kernel/user/netEther.h
sun3.md/fs.o: /sprite/lib/include/kernel/user/netInet.h
sun3.md/fs.o: /sprite/lib/include/kernel/user/netUltra.h
sun3.md/fs.o: /sprite/lib/include/kernel/user/sprite.h
sun3.md/fs.o: /sprite/lib/include/kernel/netTypes.h
sun3.md/fs.o: /sprite/lib/include/netEther.h
sun3.md/fs.o: /sprite/lib/include/kernel/netRoute.h
sun3.md/fs.o: /sprite/lib/include/netInet.h
sun3.md/fs.o: /sprite/lib/include/kernel/rpcCall.h
sun3.md/fs.o: /sprite/lib/include/kernel/procMigrate.h
sun3.md/fs.o: /sprite/lib/include/kernel/trace.h
sun3.md/fs.o: /sprite/lib/include/sun3.md/kernel/mach.h fsInt.h
sun3.md/fs.o: fsLocalDomain.h fsIndex.h fsFile.h fsDevice.h boot.h
sun3.md/fs.o: machMon.h
sun3.md/fsDisk.o: fsDisk.c
sun3.md/fsDisk.o: /sprite/lib/include/sprite.h
sun3.md/fsDisk.o: /sprite/lib/include/cfuncproto.h fsBoot.h fs.h
sun3.md/fsDisk.o: /sprite/lib/include/kernel/sys.h
sun3.md/fsDisk.o: /sprite/lib/include/kernel/user/sys.h
sun3.md/fsDisk.o: /sprite/lib/include/status.h
sun3.md/fsDisk.o: /sprite/lib/include/kernel/timer.h
sun3.md/fsDisk.o: /sprite/lib/include/list.h
sun3.md/fsDisk.o: /sprite/lib/include/spriteTime.h
sun3.md/fsDisk.o: /sprite/lib/include/sun3.md/kernel/timerTick.h
sun3.md/fsDisk.o: /sprite/lib/include/sun3.md/kernel/timerMach.h
sun3.md/fsDisk.o: /sprite/lib/include/kernel/syncLock.h
sun3.md/fsDisk.o: /sprite/lib/include/kernel/user/sync.h
sun3.md/fsDisk.o: /sprite/lib/include/kernel/sync.h
sun3.md/fsDisk.o: /sprite/lib/include/kernel/syncTypes.h
sun3.md/fsDisk.o: /sprite/lib/include/kernel/procTypes.h
sun3.md/fsDisk.o: /sprite/lib/include/kernel/proc.h
sun3.md/fsDisk.o: /sprite/lib/include/kernel/sig.h
sun3.md/fsDisk.o: /sprite/lib/include/kernel/sigTypes.h
sun3.md/fsDisk.o: /sprite/lib/include/sun3.md/kernel/machTypes.h
sun3.md/fsDisk.o: /sprite/lib/include/sun3.md/kernel/devAddrs.h
sun3.md/fsDisk.o: /sprite/lib/include/sun3.md/kernel/machConst.h
sun3.md/fsDisk.o: /sprite/lib/include/sun3.md/kernel/vmSunConst.h
sun3.md/fsDisk.o: /sprite/lib/include/fmt.h
sun3.md/fsDisk.o: /sprite/lib/include/kernel/rpc.h
sun3.md/fsDisk.o: /sprite/lib/include/kernel/net.h
sun3.md/fsDisk.o: /sprite/lib/include/kernel/user/net.h
sun3.md/fsDisk.o: /sprite/lib/include/sun3.md/machparam.h
sun3.md/fsDisk.o: /sprite/lib/include/sun3.md/limits.h
sun3.md/fsDisk.o: /sprite/lib/include/kernel/user/netEther.h
sun3.md/fsDisk.o: /sprite/lib/include/kernel/user/netInet.h
sun3.md/fsDisk.o: /sprite/lib/include/kernel/user/netUltra.h
sun3.md/fsDisk.o: /sprite/lib/include/kernel/user/sprite.h
sun3.md/fsDisk.o: /sprite/lib/include/kernel/netTypes.h
sun3.md/fsDisk.o: /sprite/lib/include/netEther.h
sun3.md/fsDisk.o: /sprite/lib/include/kernel/netRoute.h
sun3.md/fsDisk.o: /sprite/lib/include/netInet.h
sun3.md/fsDisk.o: /sprite/lib/include/kernel/rpcCall.h
sun3.md/fsDisk.o: /sprite/lib/include/kernel/procMigrate.h
sun3.md/fsDisk.o: /sprite/lib/include/kernel/trace.h
sun3.md/fsDisk.o: /sprite/lib/include/sun3.md/kernel/mach.h fsInt.h
sun3.md/fsDisk.o: fsLocalDomain.h fsIndex.h fsFile.h fsDevice.h
sun3.md/fsDisk.o: boot.h devDiskLabel.h dev.h
sun3.md/fsDisk.o: /sprite/lib/include/kernel/devSyslog.h
sun3.md/fsDisk.o: /sprite/lib/include/kernel/user/fs.h
sun3.md/fsDisk.o: /sprite/lib/include/kernel/user/spriteTime.h
sun3.md/fsDisk.o: /sprite/lib/include/kernel/user/kernel/procTypes.h
sun3.md/fsDisk.o: /sprite/lib/include/kernel/user/kernel/proc.h
sun3.md/fsDisk.o: /sprite/lib/include/kernel/user/kernel/sync.h
sun3.md/fsDisk.o: /sprite/lib/include/kernel/fs.h
sun3.md/fsDisk.o: /sprite/lib/include/sysStats.h sync.h machMon.h
sun3.md/fsIndex.o: fsIndex.c
sun3.md/fsIndex.o: /sprite/lib/include/sprite.h
sun3.md/fsIndex.o: /sprite/lib/include/cfuncproto.h fsBoot.h fs.h
sun3.md/fsIndex.o: /sprite/lib/include/kernel/sys.h
sun3.md/fsIndex.o: /sprite/lib/include/kernel/user/sys.h
sun3.md/fsIndex.o: /sprite/lib/include/status.h
sun3.md/fsIndex.o: /sprite/lib/include/kernel/timer.h
sun3.md/fsIndex.o: /sprite/lib/include/list.h
sun3.md/fsIndex.o: /sprite/lib/include/spriteTime.h
sun3.md/fsIndex.o: /sprite/lib/include/sun3.md/kernel/timerTick.h
sun3.md/fsIndex.o: /sprite/lib/include/sun3.md/kernel/timerMach.h
sun3.md/fsIndex.o: /sprite/lib/include/kernel/syncLock.h
sun3.md/fsIndex.o: /sprite/lib/include/kernel/user/sync.h
sun3.md/fsIndex.o: /sprite/lib/include/kernel/sync.h
sun3.md/fsIndex.o: /sprite/lib/include/kernel/syncTypes.h
sun3.md/fsIndex.o: /sprite/lib/include/kernel/procTypes.h
sun3.md/fsIndex.o: /sprite/lib/include/kernel/proc.h
sun3.md/fsIndex.o: /sprite/lib/include/kernel/sig.h
sun3.md/fsIndex.o: /sprite/lib/include/kernel/sigTypes.h
sun3.md/fsIndex.o: /sprite/lib/include/sun3.md/kernel/machTypes.h
sun3.md/fsIndex.o: /sprite/lib/include/sun3.md/kernel/devAddrs.h
sun3.md/fsIndex.o: /sprite/lib/include/sun3.md/kernel/machConst.h
sun3.md/fsIndex.o: /sprite/lib/include/sun3.md/kernel/vmSunConst.h
sun3.md/fsIndex.o: /sprite/lib/include/fmt.h
sun3.md/fsIndex.o: /sprite/lib/include/kernel/rpc.h
sun3.md/fsIndex.o: /sprite/lib/include/kernel/net.h
sun3.md/fsIndex.o: /sprite/lib/include/kernel/user/net.h
sun3.md/fsIndex.o: /sprite/lib/include/sun3.md/machparam.h
sun3.md/fsIndex.o: /sprite/lib/include/sun3.md/limits.h
sun3.md/fsIndex.o: /sprite/lib/include/kernel/user/netEther.h
sun3.md/fsIndex.o: /sprite/lib/include/kernel/user/netInet.h
sun3.md/fsIndex.o: /sprite/lib/include/kernel/user/netUltra.h
sun3.md/fsIndex.o: /sprite/lib/include/kernel/user/sprite.h
sun3.md/fsIndex.o: /sprite/lib/include/kernel/netTypes.h
sun3.md/fsIndex.o: /sprite/lib/include/netEther.h
sun3.md/fsIndex.o: /sprite/lib/include/kernel/netRoute.h
sun3.md/fsIndex.o: /sprite/lib/include/netInet.h
sun3.md/fsIndex.o: /sprite/lib/include/kernel/rpcCall.h
sun3.md/fsIndex.o: /sprite/lib/include/kernel/procMigrate.h
sun3.md/fsIndex.o: /sprite/lib/include/kernel/trace.h
sun3.md/fsIndex.o: /sprite/lib/include/sun3.md/kernel/mach.h
sun3.md/fsIndex.o: fsInt.h fsLocalDomain.h fsIndex.h fsFile.h
sun3.md/fsIndex.o: fsDevice.h boot.h byte.h
sun3.md/machStubs.o: machStubs.c
sun3.md/machStubs.o: /sprite/lib/include/sprite.h
sun3.md/machStubs.o: /sprite/lib/include/cfuncproto.h
sun3.md/main.o: main.c
sun3.md/main.o: /sprite/lib/include/sprite.h
sun3.md/main.o: /sprite/lib/include/cfuncproto.h machMon.h fs.h
sun3.md/main.o: /sprite/lib/include/kernel/sys.h
sun3.md/main.o: /sprite/lib/include/kernel/user/sys.h
sun3.md/main.o: /sprite/lib/include/status.h
sun3.md/main.o: /sprite/lib/include/kernel/timer.h
sun3.md/main.o: /sprite/lib/include/list.h
sun3.md/main.o: /sprite/lib/include/spriteTime.h
sun3.md/main.o: /sprite/lib/include/sun3.md/kernel/timerTick.h
sun3.md/main.o: /sprite/lib/include/sun3.md/kernel/timerMach.h
sun3.md/main.o: /sprite/lib/include/kernel/syncLock.h
sun3.md/main.o: /sprite/lib/include/kernel/user/sync.h
sun3.md/main.o: /sprite/lib/include/kernel/sync.h
sun3.md/main.o: /sprite/lib/include/kernel/syncTypes.h
sun3.md/main.o: /sprite/lib/include/kernel/procTypes.h
sun3.md/main.o: /sprite/lib/include/kernel/proc.h
sun3.md/main.o: /sprite/lib/include/kernel/sig.h
sun3.md/main.o: /sprite/lib/include/kernel/sigTypes.h
sun3.md/main.o: /sprite/lib/include/sun3.md/kernel/machTypes.h
sun3.md/main.o: /sprite/lib/include/sun3.md/kernel/devAddrs.h
sun3.md/main.o: /sprite/lib/include/sun3.md/kernel/machConst.h
sun3.md/main.o: /sprite/lib/include/sun3.md/kernel/vmSunConst.h
sun3.md/main.o: /sprite/lib/include/fmt.h
sun3.md/main.o: /sprite/lib/include/kernel/rpc.h
sun3.md/main.o: /sprite/lib/include/kernel/net.h
sun3.md/main.o: /sprite/lib/include/kernel/user/net.h
sun3.md/main.o: /sprite/lib/include/sun3.md/machparam.h
sun3.md/main.o: /sprite/lib/include/sun3.md/limits.h
sun3.md/main.o: /sprite/lib/include/kernel/user/netEther.h
sun3.md/main.o: /sprite/lib/include/kernel/user/netInet.h
sun3.md/main.o: /sprite/lib/include/kernel/user/netUltra.h
sun3.md/main.o: /sprite/lib/include/kernel/user/sprite.h
sun3.md/main.o: /sprite/lib/include/kernel/netTypes.h
sun3.md/main.o: /sprite/lib/include/netEther.h
sun3.md/main.o: /sprite/lib/include/kernel/netRoute.h
sun3.md/main.o: /sprite/lib/include/netInet.h
sun3.md/main.o: /sprite/lib/include/kernel/rpcCall.h
sun3.md/main.o: /sprite/lib/include/kernel/procMigrate.h
sun3.md/main.o: /sprite/lib/include/kernel/trace.h
sun3.md/main.o: /sprite/lib/include/sun3.md/kernel/mach.h fsInt.h
sun3.md/main.o: fsLocalDomain.h boot.h
sun3.md/mem.o: mem.c
sun3.md/mem.o: /sprite/lib/include/sprite.h
sun3.md/mem.o: /sprite/lib/include/cfuncproto.h
sun3.md/stubs.o: stubs.c
sun3.md/stubs.o: /sprite/lib/include/sprite.h
sun3.md/stubs.o: /sprite/lib/include/cfuncproto.h machMon.h
sun3.md/vm.o: vm.c
sun3.md/vm.o: /sprite/lib/include/sprite.h
sun3.md/vm.o: /sprite/lib/include/cfuncproto.h vmSunConst.h
sun3.md/vm.o: vmMachInt.h vm.h /sprite/lib/include/list.h
sun3.md/vm.o: /sprite/lib/include/vmStat.h
sun3.md/vm.o: /sprite/lib/include/sun3.md/kernel/vmMachStat.h
sun3.md/vm.o: /sprite/lib/include/kernel/fs.h
sun3.md/vm.o: /sprite/lib/include/kernel/sys.h
sun3.md/vm.o: /sprite/lib/include/kernel/user/sys.h
sun3.md/vm.o: /sprite/lib/include/status.h
sun3.md/vm.o: /sprite/lib/include/kernel/timer.h
sun3.md/vm.o: /sprite/lib/include/spriteTime.h
sun3.md/vm.o: /sprite/lib/include/sun3.md/kernel/timerTick.h
sun3.md/vm.o: /sprite/lib/include/sun3.md/kernel/timerMach.h
sun3.md/vm.o: /sprite/lib/include/kernel/syncLock.h
sun3.md/vm.o: /sprite/lib/include/kernel/user/sync.h
sun3.md/vm.o: /sprite/lib/include/kernel/sync.h
sun3.md/vm.o: /sprite/lib/include/kernel/syncTypes.h
sun3.md/vm.o: /sprite/lib/include/kernel/procTypes.h
sun3.md/vm.o: /sprite/lib/include/kernel/proc.h
sun3.md/vm.o: /sprite/lib/include/kernel/sig.h
sun3.md/vm.o: /sprite/lib/include/kernel/sigTypes.h
sun3.md/vm.o: /sprite/lib/include/sun3.md/kernel/machTypes.h
sun3.md/vm.o: /sprite/lib/include/sun3.md/kernel/devAddrs.h
sun3.md/vm.o: /sprite/lib/include/sun3.md/kernel/machConst.h
sun3.md/vm.o: /sprite/lib/include/sun3.md/kernel/vmSunConst.h
sun3.md/vm.o: /sprite/lib/include/fmt.h
sun3.md/vm.o: /sprite/lib/include/kernel/rpc.h
sun3.md/vm.o: /sprite/lib/include/kernel/net.h
sun3.md/vm.o: /sprite/lib/include/kernel/user/net.h
sun3.md/vm.o: /sprite/lib/include/sun3.md/machparam.h
sun3.md/vm.o: /sprite/lib/include/sun3.md/limits.h
sun3.md/vm.o: /sprite/lib/include/kernel/user/netEther.h
sun3.md/vm.o: /sprite/lib/include/kernel/user/netInet.h
sun3.md/vm.o: /sprite/lib/include/kernel/user/netUltra.h
sun3.md/vm.o: /sprite/lib/include/kernel/user/sprite.h
sun3.md/vm.o: /sprite/lib/include/kernel/netTypes.h
sun3.md/vm.o: /sprite/lib/include/netEther.h
sun3.md/vm.o: /sprite/lib/include/kernel/netRoute.h
sun3.md/vm.o: /sprite/lib/include/netInet.h
sun3.md/vm.o: /sprite/lib/include/kernel/rpcCall.h
sun3.md/vm.o: /sprite/lib/include/kernel/procMigrate.h
sun3.md/vm.o: /sprite/lib/include/kernel/trace.h
sun3.md/vm.o: /sprite/lib/include/sun3.md/kernel/mach.h mach.h
sun3.md/start.o: sun3.md/start.s
sun3.md/start.o: machConst.h
sun3.md/start.o: /sprite/lib/include/sun3.md/kernel/vmSunConst.h
sun3.md/vmSunAsm.o: sun3.md/vmSunAsm.s
sun3.md/vmSunAsm.o: vmSunConst.h machAsmDefs.h machConst.h
sun3.md/vmSunAsm.o: /sprite/lib/include/sun3.md/kernel/vmSunConst.h
