# DO NOT DELETE THIS LINE -- make depend depends on it.

sun3.md/ultracmd.o: ultracmd.c
sun3.md/ultracmd.o: /sprite/lib/include/sprite.h
sun3.md/ultracmd.o: /sprite/lib/include/cfuncproto.h
sun3.md/ultracmd.o: /sprite/lib/include/option.h
sun3.md/ultracmd.o: /sprite/lib/include/stdio.h
sun3.md/ultracmd.o: /sprite/lib/include/sys/file.h
sun3.md/ultracmd.o: /sprite/lib/include/fs.h
sun3.md/ultracmd.o: /sprite/lib/include/spriteTime.h
sun3.md/ultracmd.o: /sprite/lib/include/kernel/procTypes.h
sun3.md/ultracmd.o: /sprite/lib/include/proc.h
sun3.md/ultracmd.o: /sprite/lib/include/kernel/sigTypes.h
sun3.md/ultracmd.o: /sprite/lib/include/sun3.md/kernel/machTypes.h
sun3.md/ultracmd.o: /sprite/lib/include/sig.h
sun3.md/ultracmd.o: /sprite/lib/include/vmTypes.h
sun3.md/ultracmd.o: /sprite/lib/include/sync.h
sun3.md/ultracmd.o: /sprite/lib/include/kernel/syncLock.h
sun3.md/ultracmd.o: /sprite/lib/include/list.h
sun3.md/ultracmd.o: /sprite/lib/include/kernel/timer.h
sun3.md/ultracmd.o: /sprite/lib/include/sun3.md/kernel/timerTick.h
sun3.md/ultracmd.o: /sprite/lib/include/sun3.md/kernel/timerMach.h
sun3.md/ultracmd.o: /sprite/lib/include/net.h
sun3.md/ultracmd.o: /sprite/lib/include/machparam.h
sun3.md/ultracmd.o: /sprite/lib/include/sun3.md/machine/limits.h
sun3.md/ultracmd.o: /sprite/lib/include/netEther.h
sun3.md/ultracmd.o: /sprite/lib/include/netInet.h
sun3.md/ultracmd.o: /sprite/lib/include/netUltra.h
sun3.md/ultracmd.o: /sprite/lib/include/netFDDI.h
sun3.md/ultracmd.o: /sprite/src/lib/include/dev/ultra.h
sun3.md/ultracmd.o: /sprite/lib/include/status.h
sun3.md/ultracmd.o: /sprite/lib/include/fmt.h
