# DO NOT DELETE THIS LINE -- make depend depends on it.

ds3100.md/main.o: main.c
ds3100.md/main.o: /sprite/lib/include/sprite.h
ds3100.md/main.o: /sprite/lib/include/cfuncproto.h
ds3100.md/main.o: /sprite/lib/include/stdio.h
ds3100.md/main.o: /sprite/lib/include/stdlib.h
ds3100.md/main.o: /sprite/lib/include/string.h
ds3100.md/main.o: /sprite/lib/include/errno.h
ds3100.md/main.o: /sprite/lib/include/signal.h
ds3100.md/main.o: /sprite/lib/include/machSignal.h
ds3100.md/main.o: /sprite/lib/include/fs.h
ds3100.md/main.o: /sprite/lib/include/spriteTime.h
ds3100.md/main.o: /sprite/lib/include/kernel/procTypes.h
ds3100.md/main.o: /sprite/lib/include/proc.h
ds3100.md/main.o: /sprite/lib/include/kernel/sigTypes.h
ds3100.md/main.o: /sprite/lib/include/ds3100.md/kernel/machTypes.h
ds3100.md/main.o: /sprite/lib/include/ds3100.md/kernel/machConst.h
ds3100.md/main.o: /sprite/lib/include/ds3100.md/kernel/vmPmaxConst.h
ds3100.md/main.o: /sprite/lib/include/fmt.h /sprite/lib/include/sig.h
ds3100.md/main.o: /sprite/lib/include/vmTypes.h
ds3100.md/main.o: /sprite/lib/include/sync.h
ds3100.md/main.o: /sprite/lib/include/kernel/syncLock.h
ds3100.md/main.o: /sprite/lib/include/list.h
ds3100.md/main.o: /sprite/lib/include/kernel/timer.h
ds3100.md/main.o: /sprite/lib/include/ds3100.md/kernel/timerTick.h
ds3100.md/main.o: /sprite/lib/include/ds3100.md/kernel/timerMach.h
ds3100.md/main.o: /sprite/lib/include/option.h
ds3100.md/main.o: /sprite/lib/include/syslog.h
ds3100.md/main.o: /sprite/lib/include/status.h
ds3100.md/main.o: /sprite/lib/include/sysStats.h
ds3100.md/main.o: /sprite/lib/include/sys/file.h
ds3100.md/main.o: /sprite/lib/include/host.h
ds3100.md/main.o: /sprite/lib/include/sys/types.h
ds3100.md/main.o: /sprite/lib/include/netinet/in.h
ds3100.md/main.o: /sprite/lib/include/ds3100.md/machparam.h
ds3100.md/main.o: /sprite/lib/include/machine/limits.h
ds3100.md/main.o: /sprite/lib/include/sys/stat.h
ds3100.md/main.o: /sprite/lib/include/net.h
ds3100.md/main.o: /sprite/lib/include/machparam.h
ds3100.md/main.o: /sprite/lib/include/netEther.h
ds3100.md/main.o: /sprite/lib/include/netInet.h
ds3100.md/main.o: /sprite/lib/include/netUltra.h
ds3100.md/main.o: /sprite/lib/include/netFDDI.h migd.h
ds3100.md/main.o: /sprite/lib/include/mig.h
ds3100.md/main.o: /sprite/lib/include/pdev.h migPdev.h global.h
ds3100.md/migd.o: migd.c
ds3100.md/migd.o: /sprite/lib/include/sprite.h
ds3100.md/migd.o: /sprite/lib/include/cfuncproto.h
ds3100.md/migd.o: /sprite/lib/include/stdio.h
ds3100.md/migd.o: /sprite/lib/include/stdlib.h
ds3100.md/migd.o: /sprite/lib/include/string.h
ds3100.md/migd.o: /sprite/lib/include/errno.h
ds3100.md/migd.o: /sprite/lib/include/signal.h
ds3100.md/migd.o: /sprite/lib/include/machSignal.h
ds3100.md/migd.o: /sprite/lib/include/ds3100.md/setjmp.h
ds3100.md/migd.o: /sprite/lib/include/fs.h
ds3100.md/migd.o: /sprite/lib/include/spriteTime.h
ds3100.md/migd.o: /sprite/lib/include/kernel/procTypes.h
ds3100.md/migd.o: /sprite/lib/include/proc.h
ds3100.md/migd.o: /sprite/lib/include/kernel/sigTypes.h
ds3100.md/migd.o: /sprite/lib/include/ds3100.md/kernel/machTypes.h
ds3100.md/migd.o: /sprite/lib/include/ds3100.md/kernel/machConst.h
ds3100.md/migd.o: /sprite/lib/include/ds3100.md/kernel/vmPmaxConst.h
ds3100.md/migd.o: /sprite/lib/include/fmt.h /sprite/lib/include/sig.h
ds3100.md/migd.o: /sprite/lib/include/vmTypes.h
ds3100.md/migd.o: /sprite/lib/include/sync.h
ds3100.md/migd.o: /sprite/lib/include/kernel/syncLock.h
ds3100.md/migd.o: /sprite/lib/include/list.h
ds3100.md/migd.o: /sprite/lib/include/kernel/timer.h
ds3100.md/migd.o: /sprite/lib/include/ds3100.md/kernel/timerTick.h
ds3100.md/migd.o: /sprite/lib/include/ds3100.md/kernel/timerMach.h
ds3100.md/migd.o: /sprite/lib/include/option.h
ds3100.md/migd.o: /sprite/lib/include/syslog.h
ds3100.md/migd.o: /sprite/lib/include/status.h
ds3100.md/migd.o: /sprite/lib/include/sysStats.h
ds3100.md/migd.o: /sprite/lib/include/host.h
ds3100.md/migd.o: /sprite/lib/include/sys/types.h
ds3100.md/migd.o: /sprite/lib/include/netinet/in.h
ds3100.md/migd.o: /sprite/lib/include/ds3100.md/machparam.h
ds3100.md/migd.o: /sprite/lib/include/machine/limits.h
ds3100.md/migd.o: /sprite/lib/include/sys/stat.h
ds3100.md/migd.o: /sprite/lib/include/net.h
ds3100.md/migd.o: /sprite/lib/include/machparam.h
ds3100.md/migd.o: /sprite/lib/include/netEther.h
ds3100.md/migd.o: /sprite/lib/include/netInet.h
ds3100.md/migd.o: /sprite/lib/include/netUltra.h
ds3100.md/migd.o: /sprite/lib/include/netFDDI.h
ds3100.md/migd.o: /sprite/lib/include/sys/file.h
ds3100.md/migd.o: /sprite/lib/include/sys/signal.h
ds3100.md/migd.o: /sprite/lib/include/sys/wait.h
ds3100.md/migd.o: /sprite/lib/include/machine/machparam.h
ds3100.md/migd.o: /sprite/lib/include/sys/time.h
ds3100.md/migd.o: /sprite/lib/include/time.h
ds3100.md/migd.o: /sprite/lib/include/sys/resource.h
ds3100.md/migd.o: /sprite/lib/include/kernel/sched.h
ds3100.md/migd.o: /sprite/lib/include/kernel/proc.h
ds3100.md/migd.o: /sprite/lib/include/kernel/sig.h
ds3100.md/migd.o: /sprite/lib/include/kernel/rpc.h
ds3100.md/migd.o: /sprite/lib/include/kernel/net.h
ds3100.md/migd.o: /sprite/lib/include/kernel/syncTypes.h
ds3100.md/migd.o: /sprite/lib/include/kernel/netTypes.h
ds3100.md/migd.o: /sprite/lib/include/kernel/fs.h
ds3100.md/migd.o: /sprite/lib/include/kernel/sys.h
ds3100.md/migd.o: /sprite/lib/include/sys.h
ds3100.md/migd.o: /sprite/lib/include/kernel/netRoute.h
ds3100.md/migd.o: /sprite/lib/include/kernel/rpcTypes.h
ds3100.md/migd.o: /sprite/lib/include/kernel/rpcCall.h
ds3100.md/migd.o: /sprite/lib/include/kernel/procMigrate.h
ds3100.md/migd.o: /sprite/lib/include/kernel/trace.h
ds3100.md/migd.o: /sprite/lib/include/ds3100.md/kernel/mach.h
ds3100.md/migd.o: /sprite/lib/include/kernel/sysSysCallParam.h
ds3100.md/migd.o: /sprite/lib/include/kernel/sync.h
ds3100.md/migd.o: /sprite/lib/include/sys/ipc.h
ds3100.md/migd.o: /sprite/lib/include/sys/sem.h
ds3100.md/migd.o: /sprite/lib/include/bit.h
ds3100.md/migd.o: /sprite/lib/include/bstring.h
ds3100.md/migd.o: /sprite/lib/include/pwd.h migd.h
ds3100.md/migd.o: /sprite/lib/include/mig.h
ds3100.md/migd.o: /sprite/lib/include/pdev.h migPdev.h global.h
ds3100.md/util.o: util.c
ds3100.md/util.o: /sprite/lib/include/syslog.h
ds3100.md/util.o: /sprite/lib/include/stdlib.h
ds3100.md/util.o: /sprite/lib/include/cfuncproto.h
ds3100.md/util.o: /sprite/lib/include/stdio.h
ds3100.md/util.o: /sprite/lib/include/errno.h migd.h
ds3100.md/util.o: /sprite/lib/include/sprite.h
ds3100.md/util.o: /sprite/lib/include/fs.h
ds3100.md/util.o: /sprite/lib/include/spriteTime.h
ds3100.md/util.o: /sprite/lib/include/kernel/procTypes.h
ds3100.md/util.o: /sprite/lib/include/proc.h
ds3100.md/util.o: /sprite/lib/include/kernel/sigTypes.h
ds3100.md/util.o: /sprite/lib/include/ds3100.md/kernel/machTypes.h
ds3100.md/util.o: /sprite/lib/include/ds3100.md/kernel/machConst.h
ds3100.md/util.o: /sprite/lib/include/ds3100.md/kernel/vmPmaxConst.h
ds3100.md/util.o: /sprite/lib/include/fmt.h /sprite/lib/include/sig.h
ds3100.md/util.o: /sprite/lib/include/vmTypes.h
ds3100.md/util.o: /sprite/lib/include/sync.h
ds3100.md/util.o: /sprite/lib/include/kernel/syncLock.h
ds3100.md/util.o: /sprite/lib/include/list.h
ds3100.md/util.o: /sprite/lib/include/kernel/timer.h
ds3100.md/util.o: /sprite/lib/include/ds3100.md/kernel/timerTick.h
ds3100.md/util.o: /sprite/lib/include/ds3100.md/kernel/timerMach.h
ds3100.md/util.o: /sprite/lib/include/mig.h
ds3100.md/util.o: /sprite/lib/include/pdev.h
ds3100.md/migPdev.o: migPdev.c
ds3100.md/migPdev.o: /sprite/lib/include/sprite.h
ds3100.md/migPdev.o: /sprite/lib/include/cfuncproto.h
ds3100.md/migPdev.o: /sprite/lib/include/string.h
ds3100.md/migPdev.o: /sprite/lib/include/errno.h
ds3100.md/migPdev.o: /sprite/lib/include/status.h
ds3100.md/migPdev.o: /sprite/lib/include/syslog.h
ds3100.md/migPdev.o: /sprite/lib/include/bstring.h
ds3100.md/migPdev.o: /sprite/lib/include/fs.h
ds3100.md/migPdev.o: /sprite/lib/include/spriteTime.h
ds3100.md/migPdev.o: /sprite/lib/include/kernel/procTypes.h
ds3100.md/migPdev.o: /sprite/lib/include/proc.h
ds3100.md/migPdev.o: /sprite/lib/include/kernel/sigTypes.h
ds3100.md/migPdev.o: /sprite/lib/include/ds3100.md/kernel/machTypes.h
ds3100.md/migPdev.o: /sprite/lib/include/ds3100.md/kernel/machConst.h
ds3100.md/migPdev.o: /sprite/lib/include/ds3100.md/kernel/vmPmaxConst.h
ds3100.md/migPdev.o: /sprite/lib/include/fmt.h
ds3100.md/migPdev.o: /sprite/lib/include/sig.h
ds3100.md/migPdev.o: /sprite/lib/include/vmTypes.h
ds3100.md/migPdev.o: /sprite/lib/include/sync.h
ds3100.md/migPdev.o: /sprite/lib/include/kernel/syncLock.h
ds3100.md/migPdev.o: /sprite/lib/include/list.h
ds3100.md/migPdev.o: /sprite/lib/include/kernel/timer.h
ds3100.md/migPdev.o: /sprite/lib/include/ds3100.md/kernel/timerTick.h
ds3100.md/migPdev.o: /sprite/lib/include/ds3100.md/kernel/timerMach.h
ds3100.md/migPdev.o: /sprite/lib/include/kernel/fs.h
ds3100.md/migPdev.o: /sprite/lib/include/kernel/sys.h
ds3100.md/migPdev.o: /sprite/lib/include/sys.h
ds3100.md/migPdev.o: /sprite/lib/include/kernel/syncTypes.h
ds3100.md/migPdev.o: /sprite/lib/include/sys/types.h
ds3100.md/migPdev.o: /sprite/lib/include/unistd.h
ds3100.md/migPdev.o: /sprite/lib/include/stdlib.h
ds3100.md/migPdev.o: /sprite/lib/include/stdio.h
ds3100.md/migPdev.o: /sprite/lib/include/sys/dir.h
ds3100.md/migPdev.o: /sprite/lib/include/sys/stat.h
ds3100.md/migPdev.o: /sprite/lib/include/host.h
ds3100.md/migPdev.o: /sprite/lib/include/netinet/in.h
ds3100.md/migPdev.o: /sprite/lib/include/ds3100.md/machparam.h
ds3100.md/migPdev.o: /sprite/lib/include/machine/limits.h
ds3100.md/migPdev.o: /sprite/lib/include/net.h
ds3100.md/migPdev.o: /sprite/lib/include/machparam.h
ds3100.md/migPdev.o: /sprite/lib/include/netEther.h
ds3100.md/migPdev.o: /sprite/lib/include/netInet.h
ds3100.md/migPdev.o: /sprite/lib/include/netUltra.h
ds3100.md/migPdev.o: /sprite/lib/include/netFDDI.h
ds3100.md/migPdev.o: /sprite/lib/include/pdev.h migd.h
ds3100.md/migPdev.o: /sprite/lib/include/mig.h migPdev.h global.h
ds3100.md/Mig_GetPdevName.o: Mig_GetPdevName.c
ds3100.md/Mig_GetPdevName.o: /sprite/lib/include/fs.h
ds3100.md/Mig_GetPdevName.o: /sprite/lib/include/spriteTime.h
ds3100.md/Mig_GetPdevName.o: /sprite/lib/include/kernel/procTypes.h
ds3100.md/Mig_GetPdevName.o: /sprite/lib/include/proc.h
ds3100.md/Mig_GetPdevName.o: /sprite/lib/include/sprite.h
ds3100.md/Mig_GetPdevName.o: /sprite/lib/include/cfuncproto.h
ds3100.md/Mig_GetPdevName.o: /sprite/lib/include/kernel/sigTypes.h
ds3100.md/Mig_GetPdevName.o: /sprite/lib/include/ds3100.md/kernel/machTypes.h
ds3100.md/Mig_GetPdevName.o: /sprite/lib/include/ds3100.md/kernel/machConst.h
ds3100.md/Mig_GetPdevName.o: /sprite/lib/include/ds3100.md/kernel/vmPmaxConst.h
ds3100.md/Mig_GetPdevName.o: /sprite/lib/include/fmt.h
ds3100.md/Mig_GetPdevName.o: /sprite/lib/include/sig.h
ds3100.md/Mig_GetPdevName.o: /sprite/lib/include/vmTypes.h
ds3100.md/Mig_GetPdevName.o: /sprite/lib/include/sync.h
ds3100.md/Mig_GetPdevName.o: /sprite/lib/include/kernel/syncLock.h
ds3100.md/Mig_GetPdevName.o: /sprite/lib/include/list.h
ds3100.md/Mig_GetPdevName.o: /sprite/lib/include/kernel/timer.h
ds3100.md/Mig_GetPdevName.o: /sprite/lib/include/ds3100.md/kernel/timerTick.h
ds3100.md/Mig_GetPdevName.o: /sprite/lib/include/ds3100.md/kernel/timerMach.h
ds3100.md/Mig_GetPdevName.o: /sprite/lib/include/stdio.h
ds3100.md/Mig_GetPdevName.o: /sprite/lib/include/mig.h
ds3100.md/global.o: global.c
ds3100.md/global.o: /sprite/lib/include/sprite.h
ds3100.md/global.o: /sprite/lib/include/cfuncproto.h
ds3100.md/global.o: /sprite/lib/include/string.h
ds3100.md/global.o: /sprite/lib/include/list.h
ds3100.md/global.o: /sprite/lib/include/errno.h
ds3100.md/global.o: /sprite/lib/include/status.h
ds3100.md/global.o: /sprite/lib/include/syslog.h
ds3100.md/global.o: /sprite/lib/include/bstring.h
ds3100.md/global.o: /sprite/lib/include/fs.h
ds3100.md/global.o: /sprite/lib/include/spriteTime.h
ds3100.md/global.o: /sprite/lib/include/kernel/procTypes.h
ds3100.md/global.o: /sprite/lib/include/proc.h
ds3100.md/global.o: /sprite/lib/include/kernel/sigTypes.h
ds3100.md/global.o: /sprite/lib/include/ds3100.md/kernel/machTypes.h
ds3100.md/global.o: /sprite/lib/include/ds3100.md/kernel/machConst.h
ds3100.md/global.o: /sprite/lib/include/ds3100.md/kernel/vmPmaxConst.h
ds3100.md/global.o: /sprite/lib/include/fmt.h
ds3100.md/global.o: /sprite/lib/include/sig.h
ds3100.md/global.o: /sprite/lib/include/vmTypes.h
ds3100.md/global.o: /sprite/lib/include/sync.h
ds3100.md/global.o: /sprite/lib/include/kernel/syncLock.h
ds3100.md/global.o: /sprite/lib/include/kernel/timer.h
ds3100.md/global.o: /sprite/lib/include/ds3100.md/kernel/timerTick.h
ds3100.md/global.o: /sprite/lib/include/ds3100.md/kernel/timerMach.h
ds3100.md/global.o: /sprite/lib/include/kernel/fs.h
ds3100.md/global.o: /sprite/lib/include/kernel/sys.h
ds3100.md/global.o: /sprite/lib/include/sys.h
ds3100.md/global.o: /sprite/lib/include/kernel/syncTypes.h
ds3100.md/global.o: /sprite/lib/include/sys/types.h
ds3100.md/global.o: /sprite/lib/include/sys/time.h
ds3100.md/global.o: /sprite/lib/include/time.h
ds3100.md/global.o: /sprite/lib/include/unistd.h
ds3100.md/global.o: /sprite/lib/include/stdlib.h
ds3100.md/global.o: /sprite/lib/include/stdio.h
ds3100.md/global.o: /sprite/lib/include/sys/dir.h
ds3100.md/global.o: /sprite/lib/include/sys/file.h
ds3100.md/global.o: /sprite/lib/include/sys/stat.h
ds3100.md/global.o: /sprite/lib/include/host.h
ds3100.md/global.o: /sprite/lib/include/netinet/in.h
ds3100.md/global.o: /sprite/lib/include/ds3100.md/machparam.h
ds3100.md/global.o: /sprite/lib/include/machine/limits.h
ds3100.md/global.o: /sprite/lib/include/net.h
ds3100.md/global.o: /sprite/lib/include/machparam.h
ds3100.md/global.o: /sprite/lib/include/netEther.h
ds3100.md/global.o: /sprite/lib/include/netInet.h
ds3100.md/global.o: /sprite/lib/include/netUltra.h
ds3100.md/global.o: /sprite/lib/include/netFDDI.h
ds3100.md/global.o: /sprite/lib/include/signal.h
ds3100.md/global.o: /sprite/lib/include/machSignal.h
ds3100.md/global.o: /sprite/lib/include/pdev.h
ds3100.md/global.o: /sprite/lib/include/kernel/net.h
ds3100.md/global.o: /sprite/lib/include/kernel/netTypes.h
ds3100.md/global.o: /sprite/lib/include/kernel/netRoute.h
ds3100.md/global.o: /sprite/lib/include/mig.h migd.h migPdev.h
