if (!defined &LOCORE) {
    eval 'sub AUDIO_DEFAULT_RING_SIZE {16384;}';
    eval 'sub AUDIO_DEFAULT_RING_MASK {0x003fff;}';
    eval 'sub AUDIO_MIN_RING_SIZE {1024;}';
    eval 'sub AUDIO_MAX_RING_SIZE {1048576;}';
    if (0) {
    }
}
sub AUDIO_INTERRUPT_NONE {0;}
sub AUDIO_INTERRUPT_WAKEUP_READ {0x01;}
sub AUDIO_INTERRUPT_WAKEUP_WRITE {0x02;}
sub AUDIO_INTERRUPT_STOP_READ {0x04;}
sub AUDIO_INTERRUPT_STOP_WRITE {0x08;}
sub AUDIO_INTERRUPT_UNEXPECTED {0x10;}
1;
