#
# This file is automatically included by Pmake while it is processing
# Makefile.  Makefile is automatically generated by mkmf, and this file
# provides additional local personalization, namely to insist on not
# using a profiled version of procFork.o, even when creating a profiled
# kernel.
#

POBJS		= $(OBJS:S/.o$/.po/g:S/procFork.po/procFork.o/g)

#include	<$(SYSMAKEFILE)>
