# DO NOT DELETE THIS LINE -- make depend depends on it.

ds3100.md/ultracmd.o: ultracmd.c
ds3100.md/ultracmd.o: /sprite/lib/include/sprite.h
ds3100.md/ultracmd.o: /sprite/lib/include/cfuncproto.h
ds3100.md/ultracmd.o: /sprite/lib/include/option.h
ds3100.md/ultracmd.o: /sprite/lib/include/stdio.h
ds3100.md/ultracmd.o: /sprite/lib/include/sys/file.h
ds3100.md/ultracmd.o: /sprite/lib/include/fs.h
ds3100.md/ultracmd.o: /sprite/lib/include/spriteTime.h
ds3100.md/ultracmd.o: /sprite/lib/include/kernel/procTypes.h
ds3100.md/ultracmd.o: /sprite/lib/include/proc.h
ds3100.md/ultracmd.o: /sprite/lib/include/kernel/sigTypes.h
ds3100.md/ultracmd.o: /sprite/lib/include/ds3100.md/kernel/machTypes.h
ds3100.md/ultracmd.o: /sprite/lib/include/ds3100.md/kernel/machConst.h
ds3100.md/ultracmd.o: /sprite/lib/include/ds3100.md/kernel/vmPmaxConst.h
ds3100.md/ultracmd.o: /sprite/lib/include/fmt.h
ds3100.md/ultracmd.o: /sprite/lib/include/sig.h
ds3100.md/ultracmd.o: /sprite/lib/include/vmTypes.h
ds3100.md/ultracmd.o: /sprite/lib/include/sync.h
ds3100.md/ultracmd.o: /sprite/lib/include/kernel/syncLock.h
ds3100.md/ultracmd.o: /sprite/lib/include/list.h
ds3100.md/ultracmd.o: /sprite/lib/include/kernel/timer.h
ds3100.md/ultracmd.o: /sprite/lib/include/ds3100.md/kernel/timerTick.h
ds3100.md/ultracmd.o: /sprite/lib/include/ds3100.md/kernel/timerMach.h
ds3100.md/ultracmd.o: /sprite/lib/include/net.h
ds3100.md/ultracmd.o: /sprite/lib/include/machparam.h
ds3100.md/ultracmd.o: /sprite/lib/include/netEther.h
ds3100.md/ultracmd.o: /sprite/lib/include/netInet.h
ds3100.md/ultracmd.o: /sprite/lib/include/netUltra.h
ds3100.md/ultracmd.o: /sprite/lib/include/netFDDI.h
ds3100.md/ultracmd.o: /sprite/src/lib/include/dev/ultra.h
ds3100.md/ultracmd.o: /sprite/lib/include/status.h
