dir /sprite/src/kernel/Installed/1.099/mach
dir /sprite/src/kernel/Installed/1.099/dbg
dir /sprite/src/kernel/Installed/1.099/dev
dir /sprite/src/kernel/Installed/1.099/fs
dir /sprite/src/kernel/Installed/1.099/fscache
dir /sprite/src/kernel/Installed/1.099/fsconsist 
dir /sprite/src/kernel/Installed/1.099/fsdm 
dir /sprite/src/kernel/Installed/1.099/fsio 
dir /sprite/src/kernel/Installed/1.099/fslcl
dir /sprite/src/kernel/Installed/1.099/fspdev 
dir /sprite/src/kernel/Installed/1.099/fsprefix 
dir /sprite/src/kernel/Installed/1.099/fsrmt
dir /sprite/src/kernel/Installed/1.099/fsutil
dir /sprite/src/kernel/Installed/1.099/lfs
dir /sprite/src/kernel/Installed/1.099/main
dir /sprite/src/kernel/Installed/1.099/mem
dir /sprite/src/kernel/Installed/1.099/net
dir /sprite/src/kernel/Installed/1.099/ofs
dir /sprite/src/kernel/Installed/1.099/proc
dir /sprite/src/kernel/Installed/1.099/prof
dir /sprite/src/kernel/Installed/1.099/recov
dir /sprite/src/kernel/Installed/1.099/rpc
dir /sprite/src/kernel/Installed/1.099/sched
dir /sprite/src/kernel/Installed/1.099/sig
dir /sprite/src/kernel/Installed/1.099/sync
dir /sprite/src/kernel/Installed/1.099/sys
dir /sprite/src/kernel/Installed/1.099/timer
dir /sprite/src/kernel/Installed/1.099/utils
dir /sprite/src/kernel/Installed/1.099/vm
