dir /sprite/src/kernel/mach
dir /sprite/src/kernel/dbg
dir /sprite/src/kernel/dev
dir /sprite/src/kernel/fs
dir /sprite/src/kernel/fscache
dir /sprite/src/kernel/fsconsist 
dir /sprite/src/kernel/fsdm 
dir /sprite/src/kernel/fsio 
dir /sprite/src/kernel/fslcl
dir /sprite/src/kernel/fspdev 
dir /sprite/src/kernel/fsprefix 
dir /sprite/src/kernel/fsrmt
dir /sprite/src/kernel/fsutil
dir /sprite/src/kernel/lfs
dir /sprite/src/kernel/main
dir /sprite/src/kernel/mem
dir /sprite/src/kernel/net
dir /sprite/src/kernel/ofs
dir /sprite/src/kernel/proc
dir /sprite/src/kernel/prof
dir /sprite/src/kernel/recov
dir /sprite/src/kernel/rpc
dir /sprite/src/kernel/sched
dir /sprite/src/kernel/sig
dir /sprite/src/kernel/sync
dir /sprite/src/kernel/sys
dir /sprite/src/kernel/timer
dir /sprite/src/kernel/utils
dir /sprite/src/kernel/vm
