# DO NOT DELETE THIS LINE -- make depend depends on it.

ds3100.md/ftpd.o: ftpd.c
ds3100.md/ftpd.o: /sprite/lib/include/sys/param.h
ds3100.md/ftpd.o: /sprite/lib/include/sys/types.h
ds3100.md/ftpd.o: /sprite/lib/include/signal.h
ds3100.md/ftpd.o: /sprite/lib/include/ds3100.md/machparam.h
ds3100.md/ftpd.o: /sprite/lib/include/sys/stat.h
ds3100.md/ftpd.o: /sprite/lib/include/cfuncproto.h
ds3100.md/ftpd.o: /sprite/lib/include/sys/ioctl.h
ds3100.md/ftpd.o: /sprite/lib/include/sys/ttychars.h
ds3100.md/ftpd.o: /sprite/lib/include/sys/ttydev.h
ds3100.md/ftpd.o: /sprite/lib/include/sys/fb.h
ds3100.md/ftpd.o: /sprite/lib/include/sys/socket.h
ds3100.md/ftpd.o: /sprite/lib/include/sys/file.h
ds3100.md/ftpd.o: /sprite/lib/include/sys/wait.h
ds3100.md/ftpd.o: /sprite/lib/include/machine/machparam.h
ds3100.md/ftpd.o: /sprite/lib/include/netinet/in.h
ds3100.md/ftpd.o: /sprite/lib/include/arpa/ftp.h
ds3100.md/ftpd.o: /sprite/lib/include/arpa/inet.h
ds3100.md/ftpd.o: /sprite/lib/include/arpa/telnet.h
ds3100.md/ftpd.o: /sprite/lib/include/stdio.h
ds3100.md/ftpd.o: /sprite/lib/include/pwd.h
ds3100.md/ftpd.o: /sprite/lib/include/ds3100.md/setjmp.h
ds3100.md/ftpd.o: /sprite/lib/include/netdb.h
ds3100.md/ftpd.o: /sprite/lib/include/errno.h
ds3100.md/ftpd.o: /sprite/lib/include/strings.h
ds3100.md/ftpd.o: /sprite/lib/include/syslog.h
ds3100.md/ftpd.o: /sprite/lib/include/ds3100.md/varargs.h
ds3100.md/ftpd.o: /sprite/lib/include/utmp.h
ds3100.md/vers.o: vers.c
ds3100.md/glob.o: glob.c
ds3100.md/glob.o: /sprite/lib/include/sys/param.h
ds3100.md/glob.o: /sprite/lib/include/sys/types.h
ds3100.md/glob.o: /sprite/lib/include/signal.h
ds3100.md/glob.o: /sprite/lib/include/ds3100.md/machparam.h
ds3100.md/glob.o: /sprite/lib/include/sys/stat.h
ds3100.md/glob.o: /sprite/lib/include/cfuncproto.h
ds3100.md/glob.o: /sprite/lib/include/sys/dir.h
ds3100.md/glob.o: /sprite/lib/include/stdio.h
ds3100.md/glob.o: /sprite/lib/include/errno.h
ds3100.md/glob.o: /sprite/lib/include/pwd.h
