# DO NOT DELETE THIS LINE -- make depend depends on it.

ds3100.md/whence.o: whence.c
ds3100.md/whence.o: /sprite/lib/include/stdio.h
ds3100.md/whence.o: /sprite/lib/include/cfuncproto.h
ds3100.md/whence.o: /sprite/lib/include/ctype.h
ds3100.md/whence.o: /sprite/lib/include/sys/param.h
ds3100.md/whence.o: /sprite/lib/include/sys/types.h
ds3100.md/whence.o: /sprite/lib/include/sys/signal.h
ds3100.md/whence.o: /sprite/lib/include/ds3100.md/machparam.h
ds3100.md/whence.o: /sprite/lib/include/ds3100.md/limits.h
ds3100.md/whence.o: /sprite/lib/include/sys/stat.h
ds3100.md/whence.o: /sprite/lib/include/strings.h
ds3100.md/wishCmd.o: wishCmd.c
ds3100.md/wishCmd.o: /sprite/lib/include/sys/types.h
ds3100.md/wishCmd.o: /sprite/lib/include/sys/stat.h
ds3100.md/wishCmd.o: /sprite/lib/include/sx.h
ds3100.md/wishCmd.o: /sprite/lib/include/X11/Xlib.h
ds3100.md/wishCmd.o: /sprite/lib/include/X11/X.h
ds3100.md/wishCmd.o: /sprite/lib/include/util.h monitorClient.h
ds3100.md/wishCmd.o: wishInt.h /sprite/lib/include/sys/param.h
ds3100.md/wishCmd.o: /sprite/lib/include/sys/signal.h
ds3100.md/wishCmd.o: /sprite/lib/include/ds3100.md/machparam.h
ds3100.md/wishCmd.o: /sprite/lib/include/ds3100.md/limits.h
ds3100.md/wishCmd.o: /sprite/lib/include/X11/Xutil.h
ds3100.md/wishCmd.o: /sprite/lib/include/cmd.h
ds3100.md/wishCmd.o: /sprite/lib/include/stdio.h
ds3100.md/wishCmd.o: /sprite/lib/include/cfuncproto.h
ds3100.md/wishCmd.o: /sprite/lib/include/mx.h
ds3100.md/wishCmd.o: /sprite/lib/include/tcl.h
ds3100.md/wishDisplay.o: wishDisplay.c
ds3100.md/wishDisplay.o: /sprite/lib/include/sys/types.h
ds3100.md/wishDisplay.o: /sprite/lib/include/sys/stat.h
ds3100.md/wishDisplay.o: /sprite/lib/include/time.h
ds3100.md/wishDisplay.o: /sprite/lib/include/cfuncproto.h
ds3100.md/wishDisplay.o: /sprite/lib/include/sys/dir.h
ds3100.md/wishDisplay.o: /sprite/lib/include/string.h
ds3100.md/wishDisplay.o: /sprite/lib/include/sx.h
ds3100.md/wishDisplay.o: /sprite/lib/include/X11/Xlib.h
ds3100.md/wishDisplay.o: /sprite/lib/include/X11/X.h
ds3100.md/wishDisplay.o: /sprite/lib/include/util.h monitorClient.h
ds3100.md/wishDisplay.o: wishInt.h /sprite/lib/include/sys/param.h
ds3100.md/wishDisplay.o: /sprite/lib/include/sys/signal.h
ds3100.md/wishDisplay.o: /sprite/lib/include/ds3100.md/machparam.h
ds3100.md/wishDisplay.o: /sprite/lib/include/ds3100.md/limits.h
ds3100.md/wishDisplay.o: /sprite/lib/include/X11/Xutil.h
ds3100.md/wishDisplay.o: /sprite/lib/include/cmd.h
ds3100.md/wishDisplay.o: /sprite/lib/include/stdio.h
ds3100.md/wishDisplay.o: /sprite/lib/include/mx.h
ds3100.md/wishDisplay.o: /sprite/lib/include/tcl.h flat.cursor
ds3100.md/wishDisplay.o: wait.cursor
ds3100.md/wishGarbage.o: wishGarbage.c
ds3100.md/wishGarbage.o: /sprite/lib/include/X11/Xlib.h
ds3100.md/wishGarbage.o: /sprite/lib/include/sys/types.h
ds3100.md/wishGarbage.o: /sprite/lib/include/X11/X.h wishInt.h
ds3100.md/wishGarbage.o: /sprite/lib/include/sys/param.h
ds3100.md/wishGarbage.o: /sprite/lib/include/sys/signal.h
ds3100.md/wishGarbage.o: /sprite/lib/include/ds3100.md/machparam.h
ds3100.md/wishGarbage.o: /sprite/lib/include/ds3100.md/limits.h
ds3100.md/wishGarbage.o: /sprite/lib/include/X11/Xutil.h
ds3100.md/wishGarbage.o: /sprite/lib/include/cmd.h
ds3100.md/wishGarbage.o: /sprite/lib/include/stdio.h
ds3100.md/wishGarbage.o: /sprite/lib/include/cfuncproto.h
ds3100.md/wishGarbage.o: /sprite/lib/include/mx.h
ds3100.md/wishGarbage.o: /sprite/lib/include/tcl.h
ds3100.md/wishGather.o: wishGather.c
ds3100.md/wishGather.o: /sprite/lib/include/sys/types.h
ds3100.md/wishGather.o: /sprite/lib/include/sys/stat.h
ds3100.md/wishGather.o: /sprite/lib/include/sys/dir.h
ds3100.md/wishGather.o: /sprite/lib/include/errno.h
ds3100.md/wishGather.o: /sprite/lib/include/sx.h
ds3100.md/wishGather.o: /sprite/lib/include/X11/Xlib.h
ds3100.md/wishGather.o: /sprite/lib/include/X11/X.h
ds3100.md/wishGather.o: /sprite/lib/include/string.h
ds3100.md/wishGather.o: /sprite/lib/include/cfuncproto.h
ds3100.md/wishGather.o: /sprite/lib/include/util.h wishInt.h
ds3100.md/wishGather.o: /sprite/lib/include/sys/param.h
ds3100.md/wishGather.o: /sprite/lib/include/sys/signal.h
ds3100.md/wishGather.o: /sprite/lib/include/ds3100.md/machparam.h
ds3100.md/wishGather.o: /sprite/lib/include/ds3100.md/limits.h
ds3100.md/wishGather.o: /sprite/lib/include/X11/Xutil.h
ds3100.md/wishGather.o: /sprite/lib/include/cmd.h
ds3100.md/wishGather.o: /sprite/lib/include/stdio.h
ds3100.md/wishGather.o: /sprite/lib/include/mx.h
ds3100.md/wishGather.o: /sprite/lib/include/tcl.h
ds3100.md/wishHandlers.o: wishHandlers.c
ds3100.md/wishHandlers.o: /sprite/lib/include/sys/types.h
ds3100.md/wishHandlers.o: /sprite/lib/include/sys/stat.h
ds3100.md/wishHandlers.o: /sprite/lib/include/string.h
ds3100.md/wishHandlers.o: /sprite/lib/include/cfuncproto.h
ds3100.md/wishHandlers.o: /sprite/lib/include/util.h monitorClient.h
ds3100.md/wishHandlers.o: wishInt.h /sprite/lib/include/sys/param.h
ds3100.md/wishHandlers.o: /sprite/lib/include/sys/signal.h
ds3100.md/wishHandlers.o: /sprite/lib/include/ds3100.md/machparam.h
ds3100.md/wishHandlers.o: /sprite/lib/include/ds3100.md/limits.h
ds3100.md/wishHandlers.o: /sprite/lib/include/X11/Xutil.h
ds3100.md/wishHandlers.o: /sprite/lib/include/cmd.h
ds3100.md/wishHandlers.o: /sprite/lib/include/stdio.h
ds3100.md/wishHandlers.o: /sprite/lib/include/mx.h
ds3100.md/wishHandlers.o: /sprite/lib/include/tcl.h
ds3100.md/wishMain.o: wishMain.c
ds3100.md/wishMain.o: /sprite/lib/include/X11/Xlib.h
ds3100.md/wishMain.o: /sprite/lib/include/sys/types.h
ds3100.md/wishMain.o: /sprite/lib/include/X11/X.h
ds3100.md/wishMain.o: /sprite/lib/include/X11/Xutil.h
ds3100.md/wishMain.o: /sprite/lib/include/sys/time.h
ds3100.md/wishMain.o: /sprite/lib/include/string.h
ds3100.md/wishMain.o: /sprite/lib/include/cfuncproto.h
ds3100.md/wishMain.o: /sprite/lib/include/fs.h
ds3100.md/wishMain.o: /sprite/lib/include/spriteTime.h
ds3100.md/wishMain.o: /sprite/lib/include/sprite.h
ds3100.md/wishMain.o: /sprite/lib/include/kernel/procTypes.h
ds3100.md/wishMain.o: /sprite/lib/include/kernel/proc.h
ds3100.md/wishMain.o: /sprite/lib/include/kernel/sync.h
ds3100.md/wishMain.o: /sprite/lib/include/list.h
ds3100.md/wishMain.o: /sprite/lib/include/kernel/syncTypes.h
ds3100.md/wishMain.o: /sprite/lib/include/kernel/syncLock.h
ds3100.md/wishMain.o: /sprite/lib/include/kernel/user/sync.h
ds3100.md/wishMain.o: /sprite/lib/include/ds3100.md/kernel/machTypes.h
ds3100.md/wishMain.o: /sprite/lib/include/ds3100.md/kernel/machConst.h
ds3100.md/wishMain.o: /sprite/lib/include/ds3100.md/kernel/vmPmaxConst.h
ds3100.md/wishMain.o: /sprite/lib/include/fmt.h
ds3100.md/wishMain.o: /sprite/lib/include/ds3100.md/kernel/mach.h
ds3100.md/wishMain.o: /sprite/lib/include/sys/ipc.h
ds3100.md/wishMain.o: /sprite/lib/include/sys/sem.h
ds3100.md/wishMain.o: /sprite/lib/include/kernel/timer.h
ds3100.md/wishMain.o: /sprite/lib/include/ds3100.md/kernel/timerTick.h
ds3100.md/wishMain.o: /sprite/lib/include/ds3100.md/kernel/timerMach.h
ds3100.md/wishMain.o: /sprite/lib/include/kernel/sig.h
ds3100.md/wishMain.o: /sprite/lib/include/kernel/sigTypes.h
ds3100.md/wishMain.o: /sprite/lib/include/kernel/rpc.h
ds3100.md/wishMain.o: /sprite/lib/include/status.h
ds3100.md/wishMain.o: /sprite/lib/include/kernel/net.h
ds3100.md/wishMain.o: /sprite/lib/include/kernel/netTypes.h
ds3100.md/wishMain.o: /sprite/lib/include/netEther.h
ds3100.md/wishMain.o: /sprite/lib/include/ds3100.md/machparam.h
ds3100.md/wishMain.o: /sprite/lib/include/ds3100.md/limits.h
ds3100.md/wishMain.o: /sprite/lib/include/kernel/fs.h
ds3100.md/wishMain.o: /sprite/lib/include/kernel/sys.h
ds3100.md/wishMain.o: /sprite/lib/include/netInet.h
ds3100.md/wishMain.o: /sprite/lib/include/netUltra.h
ds3100.md/wishMain.o: /sprite/lib/include/kernel/netRoute.h
ds3100.md/wishMain.o: /sprite/lib/include/kernel/rpcCall.h
ds3100.md/wishMain.o: /sprite/lib/include/kernel/procMigrate.h
ds3100.md/wishMain.o: /sprite/lib/include/kernel/trace.h
ds3100.md/wishMain.o: /sprite/lib/include/sx.h
ds3100.md/wishMain.o: /sprite/lib/include/util.h monitorClient.h
ds3100.md/wishMain.o: wishInt.h /sprite/lib/include/sys/param.h
ds3100.md/wishMain.o: /sprite/lib/include/sys/signal.h
ds3100.md/wishMain.o: /sprite/lib/include/cmd.h
ds3100.md/wishMain.o: /sprite/lib/include/stdio.h
ds3100.md/wishMain.o: /sprite/lib/include/mx.h
ds3100.md/wishMain.o: /sprite/lib/include/tcl.h
ds3100.md/wishMain.o: /sprite/lib/include/signal.h
ds3100.md/wishScroll.o: wishScroll.c
ds3100.md/wishScroll.o: /sprite/lib/include/string.h
ds3100.md/wishScroll.o: /sprite/lib/include/cfuncproto.h
ds3100.md/wishScroll.o: /sprite/lib/include/sx.h
ds3100.md/wishScroll.o: /sprite/lib/include/X11/Xlib.h
ds3100.md/wishScroll.o: /sprite/lib/include/sys/types.h
ds3100.md/wishScroll.o: /sprite/lib/include/X11/X.h wishInt.h
ds3100.md/wishScroll.o: /sprite/lib/include/sys/param.h
ds3100.md/wishScroll.o: /sprite/lib/include/sys/signal.h
ds3100.md/wishScroll.o: /sprite/lib/include/ds3100.md/machparam.h
ds3100.md/wishScroll.o: /sprite/lib/include/ds3100.md/limits.h
ds3100.md/wishScroll.o: /sprite/lib/include/X11/Xutil.h
ds3100.md/wishScroll.o: /sprite/lib/include/cmd.h
ds3100.md/wishScroll.o: /sprite/lib/include/stdio.h
ds3100.md/wishScroll.o: /sprite/lib/include/mx.h
ds3100.md/wishScroll.o: /sprite/lib/include/tcl.h
ds3100.md/wishSelect.o: wishSelect.c
ds3100.md/wishSelect.o: /sprite/lib/include/sx.h
ds3100.md/wishSelect.o: /sprite/lib/include/X11/Xlib.h
ds3100.md/wishSelect.o: /sprite/lib/include/sys/types.h
ds3100.md/wishSelect.o: /sprite/lib/include/X11/X.h
ds3100.md/wishSelect.o: /sprite/lib/include/string.h
ds3100.md/wishSelect.o: /sprite/lib/include/cfuncproto.h wishInt.h
ds3100.md/wishSelect.o: /sprite/lib/include/sys/param.h
ds3100.md/wishSelect.o: /sprite/lib/include/sys/signal.h
ds3100.md/wishSelect.o: /sprite/lib/include/ds3100.md/machparam.h
ds3100.md/wishSelect.o: /sprite/lib/include/ds3100.md/limits.h
ds3100.md/wishSelect.o: /sprite/lib/include/X11/Xutil.h
ds3100.md/wishSelect.o: /sprite/lib/include/cmd.h
ds3100.md/wishSelect.o: /sprite/lib/include/stdio.h
ds3100.md/wishSelect.o: /sprite/lib/include/mx.h
ds3100.md/wishSelect.o: /sprite/lib/include/tcl.h
ds3100.md/wishUtils.o: wishUtils.c
ds3100.md/wishUtils.o: /sprite/lib/include/string.h
ds3100.md/wishUtils.o: /sprite/lib/include/cfuncproto.h
ds3100.md/wishUtils.o: /sprite/lib/include/sx.h
ds3100.md/wishUtils.o: /sprite/lib/include/X11/Xlib.h
ds3100.md/wishUtils.o: /sprite/lib/include/sys/types.h
ds3100.md/wishUtils.o: /sprite/lib/include/X11/X.h
ds3100.md/wishUtils.o: /sprite/lib/include/util.h wishInt.h
ds3100.md/wishUtils.o: /sprite/lib/include/sys/param.h
ds3100.md/wishUtils.o: /sprite/lib/include/sys/signal.h
ds3100.md/wishUtils.o: /sprite/lib/include/ds3100.md/machparam.h
ds3100.md/wishUtils.o: /sprite/lib/include/ds3100.md/limits.h
ds3100.md/wishUtils.o: /sprite/lib/include/X11/Xutil.h
ds3100.md/wishUtils.o: /sprite/lib/include/cmd.h
ds3100.md/wishUtils.o: /sprite/lib/include/stdio.h
ds3100.md/wishUtils.o: /sprite/lib/include/mx.h
ds3100.md/wishUtils.o: /sprite/lib/include/tcl.h
