#
# This file is automatically included by Pmake while it is processing
# Makefile.  Makefile is automatically generated by mkmf, and this file
# provides additional local personalization
#

#include	<$(SYSMAKEFILE)>

CTAGS = true	# i.e. just return success, don't do anything

tags:: $(ALLCSRCS) $(HDRS)
	/sprite/cmds/ctags -f tags.here $(CTFLAGS) $(ALLCSRCS) $(HDRS)
	/sprite/src/kernel/fs/fstags
