# DO NOT DELETE THIS LINE -- make depend depends on it.

ds3100.md/portmap.o: portmap.c
ds3100.md/portmap.o: /sprite/lib/include/rpc/rpc.h
ds3100.md/portmap.o: /sprite/lib/include/rpc/types.h
ds3100.md/portmap.o: /sprite/lib/include/sys/types.h
ds3100.md/portmap.o: /sprite/lib/include/netinet/in.h
ds3100.md/portmap.o: /sprite/lib/include/ds3100.md/machparam.h
ds3100.md/portmap.o: /sprite/lib/include/machine/limits.h
ds3100.md/portmap.o: /sprite/lib/include/rpc/xdr.h
ds3100.md/portmap.o: /sprite/lib/include/rpc/auth.h
ds3100.md/portmap.o: /sprite/lib/include/rpc/clnt.h
ds3100.md/portmap.o: /sprite/lib/include/rpc/rpc_msg.h
ds3100.md/portmap.o: /sprite/lib/include/rpc/auth_unix.h
ds3100.md/portmap.o: /sprite/lib/include/rpc/svc.h
ds3100.md/portmap.o: /sprite/lib/include/rpc/svc_auth.h
ds3100.md/portmap.o: /sprite/lib/include/rpc/netdb.h
ds3100.md/portmap.o: /sprite/lib/include/rpc/pmap_prot.h
ds3100.md/portmap.o: /sprite/lib/include/stdio.h
ds3100.md/portmap.o: /sprite/lib/include/cfuncproto.h
ds3100.md/portmap.o: /sprite/lib/include/netdb.h
ds3100.md/portmap.o: /sprite/lib/include/sys/socket.h
ds3100.md/portmap.o: /sprite/lib/include/sys/time.h
ds3100.md/portmap.o: /sprite/lib/include/time.h
ds3100.md/portmap.o: /sprite/lib/include/sys/ioctl.h
ds3100.md/portmap.o: /sprite/lib/include/sys/ttychars.h
ds3100.md/portmap.o: /sprite/lib/include/sys/ttydev.h
ds3100.md/portmap.o: /sprite/lib/include/sys/fb.h
ds3100.md/portmap.o: /sprite/lib/include/sys/wait.h
ds3100.md/portmap.o: /sprite/lib/include/machine/machparam.h
