# DO NOT DELETE THIS LINE -- make depend depends on it.

sun4.md/acosh.po sun4.md/acosh.go sun4.md/acosh.o: acosh.c
sun4.md/asincos.po sun4.md/asincos.go sun4.md/asincos.o: asincos.c
sun4.md/asinh.po sun4.md/asinh.go sun4.md/asinh.o: asinh.c
sun4.md/atan.po sun4.md/atan.go sun4.md/atan.o: atan.c
sun4.md/atanh.po sun4.md/atanh.go sun4.md/atanh.o: atanh.c
sun4.md/cosh.po sun4.md/cosh.go sun4.md/cosh.o: cosh.c
sun4.md/erf.po sun4.md/erf.go sun4.md/erf.o: erf.c
sun4.md/exp.po sun4.md/exp.go sun4.md/exp.o: exp.c
sun4.md/exp__E.po sun4.md/exp__E.go sun4.md/exp__E.o: exp__E.c
sun4.md/expm1.po sun4.md/expm1.go sun4.md/expm1.o: expm1.c
sun4.md/fabs.po sun4.md/fabs.go sun4.md/fabs.o: fabs.c
sun4.md/floor.po sun4.md/floor.go sun4.md/floor.o: floor.c
sun4.md/j0.po sun4.md/j0.go sun4.md/j0.o: j0.c
sun4.md/j0.po sun4.md/j0.go sun4.md/j0.o: math.h
sun4.md/j1.po sun4.md/j1.go sun4.md/j1.o: j1.c
sun4.md/j1.po sun4.md/j1.go sun4.md/j1.o: math.h
sun4.md/jn.po sun4.md/jn.go sun4.md/jn.o: jn.c
sun4.md/jn.po sun4.md/jn.go sun4.md/jn.o: math.h
sun4.md/lgamma.po sun4.md/lgamma.go sun4.md/lgamma.o: lgamma.c
sun4.md/lgamma.po sun4.md/lgamma.go sun4.md/lgamma.o: math.h
sun4.md/log.po sun4.md/log.go sun4.md/log.o: log.c
sun4.md/log10.po sun4.md/log10.go sun4.md/log10.o: log10.c
sun4.md/log1p.po sun4.md/log1p.go sun4.md/log1p.o: log1p.c
sun4.md/log__L.po sun4.md/log__L.go sun4.md/log__L.o: log__L.c
sun4.md/pow.po sun4.md/pow.go sun4.md/pow.o: pow.c
sun4.md/sinh.po sun4.md/sinh.go sun4.md/sinh.o: sinh.c
sun4.md/tanh.po sun4.md/tanh.go sun4.md/tanh.o: tanh.c
sun4.md/atan2.po sun4.md/atan2.go sun4.md/atan2.o: atan2.c
sun4.md/cabs.po sun4.md/cabs.go sun4.md/cabs.o: cabs.c
sun4.md/cbrt.po sun4.md/cbrt.go sun4.md/cbrt.o: cbrt.c
sun4.md/sincos.po sun4.md/sincos.go sun4.md/sincos.o: sincos.c
sun4.md/sincos.po sun4.md/sincos.go sun4.md/sincos.o: trig.h
sun4.md/support.po sun4.md/support.go sun4.md/support.o: support.c
sun4.md/tan.po sun4.md/tan.go sun4.md/tan.o: tan.c
sun4.md/tan.po sun4.md/tan.go sun4.md/tan.o: trig.h
sun4.md/fmod.po sun4.md/fmod.go sun4.md/fmod.o: fmod.c
