# DO NOT DELETE THIS LINE -- make depend depends on it.

sun3.md/ccMachStat.o: sun3.md/ccMachStat.c
sun3.md/ccMachStat.o: /sprite/lib/include/sprite.h
sun3.md/ccMachStat.o: /sprite/lib/include/status.h
sun3.md/ccMachStat.o: /sprite/lib/include/fs.h
sun3.md/ccMachStat.o: /sprite/lib/include/fsCmd.h
sun3.md/ccMachStat.o: /sprite/lib/include/sysStats.h
sun3.md/ccMachStat.o: /sprite/lib/include/proc.h
sun3.md/ccMachStat.o: /sprite/lib/include/vm.h
sun3.md/ccMachStat.o: /sprite/lib/include/kernel/sched.h
sun3.md/ccMachStat.o: /sprite/lib/include/kernel/fsStat.h
sun3.md/ccMachStat.o: /sprite/lib/include/kernel/vm.h
sun3.md/ccMachStat.o: /sprite/lib/include/stdio.h ccMachStat.h
sun3.md/printStats.o: sun3.md/printStats.c
sun3.md/printStats.o: /sprite/lib/include/sprite.h
sun3.md/printStats.o: /sprite/lib/include/status.h
sun3.md/printStats.o: /sprite/lib/include/sys/ioctl.h
sun3.md/printStats.o: /sprite/lib/include/sys/file.h
sun3.md/printStats.o: /sprite/lib/include/stdio.h
sun3.md/printStats.o: /sprite/lib/include/proc.h
sun3.md/printStats.o: /sprite/lib/include/vm.h
sun3.md/printStats.o: /sprite/lib/include/sysStats.h
sun3.md/printStats.o: /sprite/lib/include/kernel/fs.h
sun3.md/printStats.o: /sprite/lib/include/kernel/fsStat.h
sun3.md/printStats.o: /sprite/lib/include/kernel/sched.h
sun3.md/printStats.o: /sprite/lib/include/kernel/vm.h
sun3.md/client.o: client.c
sun3.md/client.o: /sprite/lib/include/sprite.h
sun3.md/client.o: /sprite/lib/include/status.h
sun3.md/client.o: /sprite/lib/include/sys/ioctl.h
sun3.md/client.o: /sprite/lib/include/sys/file.h
sun3.md/client.o: /sprite/lib/include/stdio.h
sun3.md/server.o: server.c
sun3.md/server.o: /sprite/lib/include/sprite.h
sun3.md/server.o: /sprite/lib/include/status.h
sun3.md/server.o: /sprite/lib/include/fs.h
sun3.md/server.o: /sprite/lib/include/dev/pdev.h
sun3.md/server.o: /sprite/lib/include/proc.h
sun3.md/server.o: /sprite/lib/include/kernel/fs.h
sun3.md/server.o: /sprite/lib/include/sys/file.h
sun3.md/server.o: /sprite/lib/include/stdio.h
sun3.md/server.o: /sprite/lib/include/bit.h
sun3.md/server.o: /sprite/lib/include/cfuncproto.h
sun3.md/server.o: /sprite/lib/include/bstring.h
sun3.md/server.o: /sprite/lib/include/sys.h
sun3.md/proc.o: proc.c
sun3.md/proc.o: /sprite/lib/include/proc.h
sun3.md/proc.o: /sprite/lib/include/stdio.h
sun3.md/bench.o: bench.c
sun3.md/bench.o: /sprite/lib/include/sprite.h
sun3.md/bench.o: /sprite/lib/include/status.h
sun3.md/bench.o: /sprite/lib/include/sys/ioctl.h
sun3.md/bench.o: /sprite/lib/include/sys/file.h
sun3.md/bench.o: /sprite/lib/include/fs.h
sun3.md/bench.o: /sprite/lib/include/fsCmd.h
sun3.md/bench.o: /sprite/lib/include/sysStats.h
sun3.md/bench.o: /sprite/lib/include/proc.h
sun3.md/bench.o: /sprite/lib/include/vm.h
sun3.md/bench.o: /sprite/lib/include/kernel/sched.h
sun3.md/bench.o: /sprite/lib/include/kernel/fsStat.h
sun3.md/bench.o: /sprite/lib/include/kernel/vm.h
sun3.md/bench.o: /sprite/lib/include/kernel/net.h
sun3.md/bench.o: /sprite/lib/include/option.h
sun3.md/bench.o: /sprite/lib/include/sig.h
sun3.md/bench.o: /sprite/lib/include/signal.h
sun3.md/bench.o: /sprite/lib/include/stdio.h
