# DO NOT DELETE THIS LINE -- make depend depends on it.

sun3.md/acosh.po sun3.md/acosh.go sun3.md/acosh.o: acosh.c
sun3.md/asincos.po sun3.md/asincos.go sun3.md/asincos.o: asincos.c
sun3.md/asinh.po sun3.md/asinh.go sun3.md/asinh.o: asinh.c
sun3.md/atan.po sun3.md/atan.go sun3.md/atan.o: atan.c
sun3.md/atanh.po sun3.md/atanh.go sun3.md/atanh.o: atanh.c
sun3.md/cosh.po sun3.md/cosh.go sun3.md/cosh.o: cosh.c
sun3.md/erf.po sun3.md/erf.go sun3.md/erf.o: erf.c
sun3.md/exp.po sun3.md/exp.go sun3.md/exp.o: exp.c
sun3.md/exp__E.po sun3.md/exp__E.go sun3.md/exp__E.o: exp__E.c
sun3.md/expm1.po sun3.md/expm1.go sun3.md/expm1.o: expm1.c
sun3.md/fabs.po sun3.md/fabs.go sun3.md/fabs.o: fabs.c
sun3.md/floor.po sun3.md/floor.go sun3.md/floor.o: floor.c
sun3.md/j0.po sun3.md/j0.go sun3.md/j0.o: j0.c
sun3.md/j0.po sun3.md/j0.go sun3.md/j0.o: math.h
sun3.md/j1.po sun3.md/j1.go sun3.md/j1.o: j1.c
sun3.md/j1.po sun3.md/j1.go sun3.md/j1.o: math.h
sun3.md/jn.po sun3.md/jn.go sun3.md/jn.o: jn.c
sun3.md/jn.po sun3.md/jn.go sun3.md/jn.o: math.h
sun3.md/lgamma.po sun3.md/lgamma.go sun3.md/lgamma.o: lgamma.c
sun3.md/lgamma.po sun3.md/lgamma.go sun3.md/lgamma.o: math.h
sun3.md/log.po sun3.md/log.go sun3.md/log.o: log.c
sun3.md/log10.po sun3.md/log10.go sun3.md/log10.o: log10.c
sun3.md/log1p.po sun3.md/log1p.go sun3.md/log1p.o: log1p.c
sun3.md/log__L.po sun3.md/log__L.go sun3.md/log__L.o: log__L.c
sun3.md/pow.po sun3.md/pow.go sun3.md/pow.o: pow.c
sun3.md/sinh.po sun3.md/sinh.go sun3.md/sinh.o: sinh.c
sun3.md/tanh.po sun3.md/tanh.go sun3.md/tanh.o: tanh.c
sun3.md/atan2.po sun3.md/atan2.go sun3.md/atan2.o: atan2.c
sun3.md/cabs.po sun3.md/cabs.go sun3.md/cabs.o: cabs.c
sun3.md/cbrt.po sun3.md/cbrt.go sun3.md/cbrt.o: cbrt.c
sun3.md/sincos.po sun3.md/sincos.go sun3.md/sincos.o: sincos.c
sun3.md/sincos.po sun3.md/sincos.go sun3.md/sincos.o: trig.h
sun3.md/support.po sun3.md/support.go sun3.md/support.o: support.c
sun3.md/tan.po sun3.md/tan.go sun3.md/tan.o: tan.c
sun3.md/tan.po sun3.md/tan.go sun3.md/tan.o: trig.h
sun3.md/fmod.po sun3.md/fmod.go sun3.md/fmod.o: fmod.c
