# DO NOT DELETE THIS LINE -- make depend depends on it.

sun3.md/login.o: login.c
sun3.md/login.o: /sprite/lib/include/errno.h
sun3.md/login.o: /sprite/lib/include/fs.h
sun3.md/login.o: /sprite/lib/include/spriteTime.h
sun3.md/login.o: /sprite/lib/include/sprite.h
sun3.md/login.o: /sprite/lib/include/cfuncproto.h
sun3.md/login.o: /sprite/lib/include/kernel/procTypes.h
sun3.md/login.o: /sprite/lib/include/proc.h
sun3.md/login.o: /sprite/lib/include/kernel/sigTypes.h
sun3.md/login.o: /sprite/lib/include/sun3.md/kernel/machTypes.h
sun3.md/login.o: /sprite/lib/include/sun3.md/kernel/devAddrs.h
sun3.md/login.o: /sprite/lib/include/sun3.md/kernel/machConst.h
sun3.md/login.o: /sprite/lib/include/sun3.md/kernel/vmSunConst.h
sun3.md/login.o: /sprite/lib/include/fmt.h
sun3.md/login.o: /sprite/lib/include/sig.h
sun3.md/login.o: /sprite/lib/include/vmTypes.h
sun3.md/login.o: /sprite/lib/include/sync.h
sun3.md/login.o: /sprite/lib/include/kernel/syncLock.h
sun3.md/login.o: /sprite/lib/include/list.h
sun3.md/login.o: /sprite/lib/include/kernel/timer.h
sun3.md/login.o: /sprite/lib/include/sun3.md/kernel/timerTick.h
sun3.md/login.o: /sprite/lib/include/sun3.md/kernel/timerMach.h
sun3.md/login.o: /sprite/lib/include/option.h
sun3.md/login.o: /sprite/lib/include/pwd.h
sun3.md/login.o: /sprite/lib/include/sgtty.h
sun3.md/login.o: /sprite/lib/include/sys/ioctl.h
sun3.md/login.o: /sprite/lib/include/sys/ttychars.h
sun3.md/login.o: /sprite/lib/include/sys/ttydev.h
sun3.md/login.o: /sprite/lib/include/sys/fb.h
sun3.md/login.o: /sprite/lib/include/signal.h
sun3.md/login.o: /sprite/lib/include/machSignal.h
sun3.md/login.o: /sprite/lib/include/stdio.h
sun3.md/login.o: /sprite/lib/include/stdlib.h
sun3.md/login.o: /sprite/lib/include/string.h
sun3.md/login.o: /sprite/lib/include/sysStats.h
sun3.md/login.o: /sprite/lib/include/sys/types.h
sun3.md/login.o: /sprite/lib/include/sys/file.h
sun3.md/login.o: /sprite/lib/include/sys/param.h
sun3.md/login.o: /sprite/lib/include/sun3.md/machparam.h
sun3.md/login.o: /sprite/lib/include/sun3.md/limits.h
sun3.md/login.o: /sprite/lib/include/sys/stat.h
sun3.md/login.o: /sprite/lib/include/sys/wait.h
sun3.md/login.o: /sprite/lib/include/sun3.md/machine/machparam.h
sun3.md/login.o: /sprite/lib/include/sys/time.h
sun3.md/login.o: /sprite/lib/include/time.h
sun3.md/login.o: /sprite/lib/include/ulog.h
sun3.md/login.o: /sprite/lib/include/host.h
sun3.md/login.o: /sprite/lib/include/netinet/in.h
sun3.md/login.o: /sprite/lib/include/net.h
sun3.md/login.o: /sprite/lib/include/machparam.h
sun3.md/login.o: /sprite/lib/include/netEther.h
sun3.md/login.o: /sprite/lib/include/netInet.h
sun3.md/login.o: /sprite/lib/include/netUltra.h
sun3.md/login.o: /sprite/lib/include/netFDDI.h
sun3.md/login.o: /sprite/lib/include/syslog.h
