# DO NOT DELETE THIS LINE -- make depend depends on it.

sun3.md/Net_AddrNetMask.po sun3.md/Net_AddrNetMask.go sun3.md/Net_AddrNetMask.o: Net_AddrNetMask.c
sun3.md/Net_AddrNetMask.po sun3.md/Net_AddrNetMask.go sun3.md/Net_AddrNetMask.o: /sprite/lib/include/sprite.h
sun3.md/Net_AddrNetMask.po sun3.md/Net_AddrNetMask.go sun3.md/Net_AddrNetMask.o: /sprite/lib/include/cfuncproto.h /sprite/lib/include/net.h
sun3.md/Net_AddrNetMask.po sun3.md/Net_AddrNetMask.go sun3.md/Net_AddrNetMask.o: /sprite/lib/include/sun3.md/machparam.h
sun3.md/Net_AddrNetMask.po sun3.md/Net_AddrNetMask.go sun3.md/Net_AddrNetMask.o: /sprite/lib/include/sun3.md/limits.h
sun3.md/Net_AddrNetMask.po sun3.md/Net_AddrNetMask.go sun3.md/Net_AddrNetMask.o: /sprite/lib/include/netEther.h /sprite/lib/include/netInet.h
sun3.md/Net_AddrNetMask.po sun3.md/Net_AddrNetMask.go sun3.md/Net_AddrNetMask.o: /sprite/lib/include/netUltra.h
sun3.md/Net_AddrNetNum.po sun3.md/Net_AddrNetNum.go sun3.md/Net_AddrNetNum.o: Net_AddrNetNum.c
sun3.md/Net_AddrNetNum.po sun3.md/Net_AddrNetNum.go sun3.md/Net_AddrNetNum.o: /sprite/lib/include/sprite.h /sprite/lib/include/cfuncproto.h
sun3.md/Net_AddrNetNum.po sun3.md/Net_AddrNetNum.go sun3.md/Net_AddrNetNum.o: /sprite/lib/include/net.h
sun3.md/Net_AddrNetNum.po sun3.md/Net_AddrNetNum.go sun3.md/Net_AddrNetNum.o: /sprite/lib/include/sun3.md/machparam.h
sun3.md/Net_AddrNetNum.po sun3.md/Net_AddrNetNum.go sun3.md/Net_AddrNetNum.o: /sprite/lib/include/sun3.md/limits.h
sun3.md/Net_AddrNetNum.po sun3.md/Net_AddrNetNum.go sun3.md/Net_AddrNetNum.o: /sprite/lib/include/netEther.h /sprite/lib/include/netInet.h
sun3.md/Net_AddrNetNum.po sun3.md/Net_AddrNetNum.go sun3.md/Net_AddrNetNum.o: /sprite/lib/include/netUltra.h
sun3.md/Net_AddrToString.po sun3.md/Net_AddrToString.go sun3.md/Net_AddrToString.o: Net_AddrToString.c
sun3.md/Net_AddrToString.po sun3.md/Net_AddrToString.go sun3.md/Net_AddrToString.o: /sprite/lib/include/sprite.h
sun3.md/Net_AddrToString.po sun3.md/Net_AddrToString.go sun3.md/Net_AddrToString.o: /sprite/lib/include/cfuncproto.h
sun3.md/Net_AddrToString.po sun3.md/Net_AddrToString.go sun3.md/Net_AddrToString.o: /sprite/lib/include/stdio.h /sprite/lib/include/net.h
sun3.md/Net_AddrToString.po sun3.md/Net_AddrToString.go sun3.md/Net_AddrToString.o: /sprite/lib/include/sun3.md/machparam.h
sun3.md/Net_AddrToString.po sun3.md/Net_AddrToString.go sun3.md/Net_AddrToString.o: /sprite/lib/include/sun3.md/limits.h
sun3.md/Net_AddrToString.po sun3.md/Net_AddrToString.go sun3.md/Net_AddrToString.o: /sprite/lib/include/netEther.h
sun3.md/Net_AddrToString.po sun3.md/Net_AddrToString.go sun3.md/Net_AddrToString.o: /sprite/lib/include/netInet.h
sun3.md/Net_AddrToString.po sun3.md/Net_AddrToString.go sun3.md/Net_AddrToString.o: /sprite/lib/include/netUltra.h
sun3.md/Net_EtherAddrToString.po sun3.md/Net_EtherAddrToString.go sun3.md/Net_EtherAddrToString.o: Net_EtherAddrToString.c
sun3.md/Net_EtherAddrToString.po sun3.md/Net_EtherAddrToString.go sun3.md/Net_EtherAddrToString.o: /sprite/lib/include/sprite.h
sun3.md/Net_EtherAddrToString.po sun3.md/Net_EtherAddrToString.go sun3.md/Net_EtherAddrToString.o: /sprite/lib/include/cfuncproto.h
sun3.md/Net_EtherAddrToString.po sun3.md/Net_EtherAddrToString.go sun3.md/Net_EtherAddrToString.o: /sprite/lib/include/stdio.h /sprite/lib/include/net.h
sun3.md/Net_EtherAddrToString.po sun3.md/Net_EtherAddrToString.go sun3.md/Net_EtherAddrToString.o: /sprite/lib/include/sun3.md/machparam.h
sun3.md/Net_EtherAddrToString.po sun3.md/Net_EtherAddrToString.go sun3.md/Net_EtherAddrToString.o: /sprite/lib/include/sun3.md/limits.h
sun3.md/Net_EtherAddrToString.po sun3.md/Net_EtherAddrToString.go sun3.md/Net_EtherAddrToString.o: /sprite/lib/include/netEther.h
sun3.md/Net_EtherAddrToString.po sun3.md/Net_EtherAddrToString.go sun3.md/Net_EtherAddrToString.o: /sprite/lib/include/netInet.h
sun3.md/Net_EtherAddrToString.po sun3.md/Net_EtherAddrToString.go sun3.md/Net_EtherAddrToString.o: /sprite/lib/include/netUltra.h
sun3.md/Net_HostToNetInt.po sun3.md/Net_HostToNetInt.go sun3.md/Net_HostToNetInt.o: Net_HostToNetInt.c
sun3.md/Net_HostToNetInt.po sun3.md/Net_HostToNetInt.go sun3.md/Net_HostToNetInt.o: /sprite/lib/include/sun3.md/machparam.h
sun3.md/Net_HostToNetInt.po sun3.md/Net_HostToNetInt.go sun3.md/Net_HostToNetInt.o: /sprite/lib/include/sun3.md/limits.h
sun3.md/Net_HostToNetShort.po sun3.md/Net_HostToNetShort.go sun3.md/Net_HostToNetShort.o: Net_HostToNetShort.c
sun3.md/Net_HostToNetShort.po sun3.md/Net_HostToNetShort.go sun3.md/Net_HostToNetShort.o: /sprite/lib/include/sun3.md/machparam.h
sun3.md/Net_HostToNetShort.po sun3.md/Net_HostToNetShort.go sun3.md/Net_HostToNetShort.o: /sprite/lib/include/sun3.md/limits.h
sun3.md/Net_InetAddrHostNum.po sun3.md/Net_InetAddrHostNum.go sun3.md/Net_InetAddrHostNum.o: Net_InetAddrHostNum.c
sun3.md/Net_InetAddrHostNum.po sun3.md/Net_InetAddrHostNum.go sun3.md/Net_InetAddrHostNum.o: /sprite/lib/include/sprite.h
sun3.md/Net_InetAddrHostNum.po sun3.md/Net_InetAddrHostNum.go sun3.md/Net_InetAddrHostNum.o: /sprite/lib/include/cfuncproto.h
sun3.md/Net_InetAddrHostNum.po sun3.md/Net_InetAddrHostNum.go sun3.md/Net_InetAddrHostNum.o: /sprite/lib/include/net.h
sun3.md/Net_InetAddrHostNum.po sun3.md/Net_InetAddrHostNum.go sun3.md/Net_InetAddrHostNum.o: /sprite/lib/include/sun3.md/machparam.h
sun3.md/Net_InetAddrHostNum.po sun3.md/Net_InetAddrHostNum.go sun3.md/Net_InetAddrHostNum.o: /sprite/lib/include/sun3.md/limits.h
sun3.md/Net_InetAddrHostNum.po sun3.md/Net_InetAddrHostNum.go sun3.md/Net_InetAddrHostNum.o: /sprite/lib/include/netEther.h
sun3.md/Net_InetAddrHostNum.po sun3.md/Net_InetAddrHostNum.go sun3.md/Net_InetAddrHostNum.o: /sprite/lib/include/netInet.h
sun3.md/Net_InetAddrHostNum.po sun3.md/Net_InetAddrHostNum.go sun3.md/Net_InetAddrHostNum.o: /sprite/lib/include/netUltra.h
sun3.md/Net_InetAddrToString.po sun3.md/Net_InetAddrToString.go sun3.md/Net_InetAddrToString.o: Net_InetAddrToString.c
sun3.md/Net_InetAddrToString.po sun3.md/Net_InetAddrToString.go sun3.md/Net_InetAddrToString.o: /sprite/lib/include/sprite.h
sun3.md/Net_InetAddrToString.po sun3.md/Net_InetAddrToString.go sun3.md/Net_InetAddrToString.o: /sprite/lib/include/cfuncproto.h
sun3.md/Net_InetAddrToString.po sun3.md/Net_InetAddrToString.go sun3.md/Net_InetAddrToString.o: /sprite/lib/include/net.h
sun3.md/Net_InetAddrToString.po sun3.md/Net_InetAddrToString.go sun3.md/Net_InetAddrToString.o: /sprite/lib/include/sun3.md/machparam.h
sun3.md/Net_InetAddrToString.po sun3.md/Net_InetAddrToString.go sun3.md/Net_InetAddrToString.o: /sprite/lib/include/sun3.md/limits.h
sun3.md/Net_InetAddrToString.po sun3.md/Net_InetAddrToString.go sun3.md/Net_InetAddrToString.o: /sprite/lib/include/netEther.h
sun3.md/Net_InetAddrToString.po sun3.md/Net_InetAddrToString.go sun3.md/Net_InetAddrToString.o: /sprite/lib/include/netInet.h
sun3.md/Net_InetAddrToString.po sun3.md/Net_InetAddrToString.go sun3.md/Net_InetAddrToString.o: /sprite/lib/include/netUltra.h
sun3.md/Net_InetAddrToString.po sun3.md/Net_InetAddrToString.go sun3.md/Net_InetAddrToString.o: /sprite/lib/include/stdio.h
sun3.md/Net_InetChecksum.po sun3.md/Net_InetChecksum.go sun3.md/Net_InetChecksum.o: Net_InetChecksum.c
sun3.md/Net_InetChecksum.po sun3.md/Net_InetChecksum.go sun3.md/Net_InetChecksum.o: /sprite/lib/include/sprite.h
sun3.md/Net_InetChecksum.po sun3.md/Net_InetChecksum.go sun3.md/Net_InetChecksum.o: /sprite/lib/include/cfuncproto.h /sprite/lib/include/net.h
sun3.md/Net_InetChecksum.po sun3.md/Net_InetChecksum.go sun3.md/Net_InetChecksum.o: /sprite/lib/include/sun3.md/machparam.h
sun3.md/Net_InetChecksum.po sun3.md/Net_InetChecksum.go sun3.md/Net_InetChecksum.o: /sprite/lib/include/sun3.md/limits.h
sun3.md/Net_InetChecksum.po sun3.md/Net_InetChecksum.go sun3.md/Net_InetChecksum.o: /sprite/lib/include/netEther.h
sun3.md/Net_InetChecksum.po sun3.md/Net_InetChecksum.go sun3.md/Net_InetChecksum.o: /sprite/lib/include/netInet.h
sun3.md/Net_InetChecksum.po sun3.md/Net_InetChecksum.go sun3.md/Net_InetChecksum.o: /sprite/lib/include/netUltra.h
sun3.md/Net_InetHdrChecksum.po sun3.md/Net_InetHdrChecksum.go sun3.md/Net_InetHdrChecksum.o: Net_InetHdrChecksum.c
sun3.md/Net_InetHdrChecksum.po sun3.md/Net_InetHdrChecksum.go sun3.md/Net_InetHdrChecksum.o: /sprite/lib/include/sprite.h
sun3.md/Net_InetHdrChecksum.po sun3.md/Net_InetHdrChecksum.go sun3.md/Net_InetHdrChecksum.o: /sprite/lib/include/cfuncproto.h
sun3.md/Net_InetHdrChecksum.po sun3.md/Net_InetHdrChecksum.go sun3.md/Net_InetHdrChecksum.o: /sprite/lib/include/net.h
sun3.md/Net_InetHdrChecksum.po sun3.md/Net_InetHdrChecksum.go sun3.md/Net_InetHdrChecksum.o: /sprite/lib/include/sun3.md/machparam.h
sun3.md/Net_InetHdrChecksum.po sun3.md/Net_InetHdrChecksum.go sun3.md/Net_InetHdrChecksum.o: /sprite/lib/include/sun3.md/limits.h
sun3.md/Net_InetHdrChecksum.po sun3.md/Net_InetHdrChecksum.go sun3.md/Net_InetHdrChecksum.o: /sprite/lib/include/netEther.h
sun3.md/Net_InetHdrChecksum.po sun3.md/Net_InetHdrChecksum.go sun3.md/Net_InetHdrChecksum.o: /sprite/lib/include/netInet.h
sun3.md/Net_InetHdrChecksum.po sun3.md/Net_InetHdrChecksum.go sun3.md/Net_InetHdrChecksum.o: /sprite/lib/include/netUltra.h
sun3.md/Net_MakeInetAddr.po sun3.md/Net_MakeInetAddr.go sun3.md/Net_MakeInetAddr.o: Net_MakeInetAddr.c
sun3.md/Net_MakeInetAddr.po sun3.md/Net_MakeInetAddr.go sun3.md/Net_MakeInetAddr.o: /sprite/lib/include/sprite.h
sun3.md/Net_MakeInetAddr.po sun3.md/Net_MakeInetAddr.go sun3.md/Net_MakeInetAddr.o: /sprite/lib/include/cfuncproto.h /sprite/lib/include/net.h
sun3.md/Net_MakeInetAddr.po sun3.md/Net_MakeInetAddr.go sun3.md/Net_MakeInetAddr.o: /sprite/lib/include/sun3.md/machparam.h
sun3.md/Net_MakeInetAddr.po sun3.md/Net_MakeInetAddr.go sun3.md/Net_MakeInetAddr.o: /sprite/lib/include/sun3.md/limits.h
sun3.md/Net_MakeInetAddr.po sun3.md/Net_MakeInetAddr.go sun3.md/Net_MakeInetAddr.o: /sprite/lib/include/netEther.h
sun3.md/Net_MakeInetAddr.po sun3.md/Net_MakeInetAddr.go sun3.md/Net_MakeInetAddr.o: /sprite/lib/include/netInet.h
sun3.md/Net_MakeInetAddr.po sun3.md/Net_MakeInetAddr.go sun3.md/Net_MakeInetAddr.o: /sprite/lib/include/netUltra.h
sun3.md/Net_NetToHostInt.po sun3.md/Net_NetToHostInt.go sun3.md/Net_NetToHostInt.o: Net_NetToHostInt.c
sun3.md/Net_NetToHostInt.po sun3.md/Net_NetToHostInt.go sun3.md/Net_NetToHostInt.o: /sprite/lib/include/sun3.md/machparam.h
sun3.md/Net_NetToHostInt.po sun3.md/Net_NetToHostInt.go sun3.md/Net_NetToHostInt.o: /sprite/lib/include/sun3.md/limits.h
sun3.md/Net_NetToHostShort.po sun3.md/Net_NetToHostShort.go sun3.md/Net_NetToHostShort.o: Net_NetToHostShort.c
sun3.md/Net_NetToHostShort.po sun3.md/Net_NetToHostShort.go sun3.md/Net_NetToHostShort.o: /sprite/lib/include/sun3.md/machparam.h
sun3.md/Net_NetToHostShort.po sun3.md/Net_NetToHostShort.go sun3.md/Net_NetToHostShort.o: /sprite/lib/include/sun3.md/limits.h
sun3.md/Net_StringToAddr.po sun3.md/Net_StringToAddr.go sun3.md/Net_StringToAddr.o: Net_StringToAddr.c
sun3.md/Net_StringToAddr.po sun3.md/Net_StringToAddr.go sun3.md/Net_StringToAddr.o: /sprite/lib/include/sprite.h
sun3.md/Net_StringToAddr.po sun3.md/Net_StringToAddr.go sun3.md/Net_StringToAddr.o: /sprite/lib/include/cfuncproto.h /sprite/lib/include/net.h
sun3.md/Net_StringToAddr.po sun3.md/Net_StringToAddr.go sun3.md/Net_StringToAddr.o: /sprite/lib/include/sun3.md/machparam.h
sun3.md/Net_StringToAddr.po sun3.md/Net_StringToAddr.go sun3.md/Net_StringToAddr.o: /sprite/lib/include/sun3.md/limits.h
sun3.md/Net_StringToAddr.po sun3.md/Net_StringToAddr.go sun3.md/Net_StringToAddr.o: /sprite/lib/include/netEther.h
sun3.md/Net_StringToAddr.po sun3.md/Net_StringToAddr.go sun3.md/Net_StringToAddr.o: /sprite/lib/include/netInet.h
sun3.md/Net_StringToAddr.po sun3.md/Net_StringToAddr.go sun3.md/Net_StringToAddr.o: /sprite/lib/include/netUltra.h
sun3.md/Net_StringToEtherAddr.po sun3.md/Net_StringToEtherAddr.go sun3.md/Net_StringToEtherAddr.o: Net_StringToEtherAddr.c
sun3.md/Net_StringToEtherAddr.po sun3.md/Net_StringToEtherAddr.go sun3.md/Net_StringToEtherAddr.o: /sprite/lib/include/sprite.h
sun3.md/Net_StringToEtherAddr.po sun3.md/Net_StringToEtherAddr.go sun3.md/Net_StringToEtherAddr.o: /sprite/lib/include/cfuncproto.h
sun3.md/Net_StringToEtherAddr.po sun3.md/Net_StringToEtherAddr.go sun3.md/Net_StringToEtherAddr.o: /sprite/lib/include/net.h
sun3.md/Net_StringToEtherAddr.po sun3.md/Net_StringToEtherAddr.go sun3.md/Net_StringToEtherAddr.o: /sprite/lib/include/sun3.md/machparam.h
sun3.md/Net_StringToEtherAddr.po sun3.md/Net_StringToEtherAddr.go sun3.md/Net_StringToEtherAddr.o: /sprite/lib/include/sun3.md/limits.h
sun3.md/Net_StringToEtherAddr.po sun3.md/Net_StringToEtherAddr.go sun3.md/Net_StringToEtherAddr.o: /sprite/lib/include/netEther.h
sun3.md/Net_StringToEtherAddr.po sun3.md/Net_StringToEtherAddr.go sun3.md/Net_StringToEtherAddr.o: /sprite/lib/include/netInet.h
sun3.md/Net_StringToEtherAddr.po sun3.md/Net_StringToEtherAddr.go sun3.md/Net_StringToEtherAddr.o: /sprite/lib/include/netUltra.h
sun3.md/Net_StringToInetAddr.po sun3.md/Net_StringToInetAddr.go sun3.md/Net_StringToInetAddr.o: Net_StringToInetAddr.c
sun3.md/Net_StringToInetAddr.po sun3.md/Net_StringToInetAddr.go sun3.md/Net_StringToInetAddr.o: /sprite/lib/include/sprite.h
sun3.md/Net_StringToInetAddr.po sun3.md/Net_StringToInetAddr.go sun3.md/Net_StringToInetAddr.o: /sprite/lib/include/cfuncproto.h
sun3.md/Net_StringToInetAddr.po sun3.md/Net_StringToInetAddr.go sun3.md/Net_StringToInetAddr.o: /sprite/lib/include/net.h
sun3.md/Net_StringToInetAddr.po sun3.md/Net_StringToInetAddr.go sun3.md/Net_StringToInetAddr.o: /sprite/lib/include/sun3.md/machparam.h
sun3.md/Net_StringToInetAddr.po sun3.md/Net_StringToInetAddr.go sun3.md/Net_StringToInetAddr.o: /sprite/lib/include/sun3.md/limits.h
sun3.md/Net_StringToInetAddr.po sun3.md/Net_StringToInetAddr.go sun3.md/Net_StringToInetAddr.o: /sprite/lib/include/netEther.h
sun3.md/Net_StringToInetAddr.po sun3.md/Net_StringToInetAddr.go sun3.md/Net_StringToInetAddr.o: /sprite/lib/include/netInet.h
sun3.md/Net_StringToInetAddr.po sun3.md/Net_StringToInetAddr.go sun3.md/Net_StringToInetAddr.o: /sprite/lib/include/netUltra.h
sun3.md/Net_StringToNetNum.po sun3.md/Net_StringToNetNum.go sun3.md/Net_StringToNetNum.o: Net_StringToNetNum.c
sun3.md/Net_StringToNetNum.po sun3.md/Net_StringToNetNum.go sun3.md/Net_StringToNetNum.o: /sprite/lib/include/sprite.h
sun3.md/Net_StringToNetNum.po sun3.md/Net_StringToNetNum.go sun3.md/Net_StringToNetNum.o: /sprite/lib/include/cfuncproto.h
sun3.md/Net_StringToNetNum.po sun3.md/Net_StringToNetNum.go sun3.md/Net_StringToNetNum.o: /sprite/lib/include/net.h
sun3.md/Net_StringToNetNum.po sun3.md/Net_StringToNetNum.go sun3.md/Net_StringToNetNum.o: /sprite/lib/include/sun3.md/machparam.h
sun3.md/Net_StringToNetNum.po sun3.md/Net_StringToNetNum.go sun3.md/Net_StringToNetNum.o: /sprite/lib/include/sun3.md/limits.h
sun3.md/Net_StringToNetNum.po sun3.md/Net_StringToNetNum.go sun3.md/Net_StringToNetNum.o: /sprite/lib/include/netEther.h
sun3.md/Net_StringToNetNum.po sun3.md/Net_StringToNetNum.go sun3.md/Net_StringToNetNum.o: /sprite/lib/include/netInet.h
sun3.md/Net_StringToNetNum.po sun3.md/Net_StringToNetNum.go sun3.md/Net_StringToNetNum.o: /sprite/lib/include/netUltra.h
sun3.md/Net_StringToNetNum.po sun3.md/Net_StringToNetNum.go sun3.md/Net_StringToNetNum.o: /sprite/lib/include/ctype.h
