# DO NOT DELETE THIS LINE -- make depend depends on it.

sun4.md/common.o: common.c
sun4.md/common.o: lp.h /sprite/lib/include/stdio.h
sun4.md/common.o: /sprite/lib/include/cfuncproto.h
sun4.md/common.o: /sprite/lib/include/sys/param.h
sun4.md/common.o: /sprite/lib/include/sys/types.h
sun4.md/common.o: /sprite/lib/include/sys/signal.h
sun4.md/common.o: /sprite/lib/include/sun4.md/machparam.h
sun4.md/common.o: /sprite/lib/include/sun4.md/limits.h
sun4.md/common.o: /sprite/lib/include/sys/file.h
sun4.md/common.o: /sprite/lib/include/sys/dir.h
sun4.md/common.o: /sprite/lib/include/sys/stat.h
sun4.md/common.o: /sprite/lib/include/sys/socket.h
sun4.md/common.o: /sprite/lib/include/netinet/in.h
sun4.md/common.o: /sprite/lib/include/netdb.h
sun4.md/common.o: /sprite/lib/include/pwd.h
sun4.md/common.o: /sprite/lib/include/syslog.h
sun4.md/common.o: /sprite/lib/include/signal.h
sun4.md/common.o: /sprite/lib/include/sys/wait.h
sun4.md/common.o: /sprite/lib/include/sgtty.h
sun4.md/common.o: /sprite/lib/include/sys/ioctl.h
sun4.md/common.o: /sprite/lib/include/sys/ttychars.h
sun4.md/common.o: /sprite/lib/include/sys/ttydev.h
sun4.md/common.o: /sprite/lib/include/sys/fb.h
sun4.md/common.o: /sprite/lib/include/ctype.h
sun4.md/common.o: /sprite/lib/include/errno.h lp.local.h
sun4.md/common.o: /sprite/lib/include/sun4.md/a.out.h
sun4.md/common.o: /sprite/lib/include/sun4.md/sys/exec.h
sun4.md/common.o: /sprite/lib/include/sun4.md/kernel/procMach.h
sun4.md/common.o: /sprite/lib/include/sprite.h
sun4.md/common.o: /sprite/lib/include/ar.h
sun4.md/lpdchar.o: lpdchar.c
sun4.md/lpdchar.o: lp.local.h /sprite/lib/include/sun4.md/a.out.h
sun4.md/lpdchar.o: /sprite/lib/include/sun4.md/sys/exec.h
sun4.md/lpdchar.o: /sprite/lib/include/sun4.md/kernel/procMach.h
sun4.md/lpdchar.o: /sprite/lib/include/sprite.h
sun4.md/lpdchar.o: /sprite/lib/include/cfuncproto.h
sun4.md/lpdchar.o: /sprite/lib/include/ar.h
sun4.md/lpdchar.o: /sprite/lib/include/sys/param.h
sun4.md/lpdchar.o: /sprite/lib/include/sys/types.h
sun4.md/lpdchar.o: /sprite/lib/include/sys/signal.h
sun4.md/lpdchar.o: /sprite/lib/include/sun4.md/machparam.h
sun4.md/lpdchar.o: /sprite/lib/include/sun4.md/limits.h
sun4.md/wait.o: wait.c
sun4.md/wait.o: /sprite/lib/include/sprite.h
sun4.md/wait.o: /sprite/lib/include/cfuncproto.h
sun4.md/wait.o: /sprite/lib/include/proc.h
sun4.md/wait.o: /sprite/lib/include/spriteTime.h
sun4.md/wait.o: /sprite/lib/include/kernel/sigTypes.h
sun4.md/wait.o: /sprite/lib/include/sun4.md/kernel/machTypes.h
sun4.md/wait.o: /sprite/lib/include/sun4.md/kernel/devAddrs.h
sun4.md/wait.o: /sprite/lib/include/sun4.md/kernel/machConst.h
sun4.md/wait.o: /sprite/lib/include/sun4.md/kernel/vmSunConst.h
sun4.md/wait.o: /sprite/lib/include/kernel/sysSysCall.h
sun4.md/wait.o: /sprite/lib/include/kernel/sys.h
sun4.md/wait.o: /sprite/lib/include/status.h
sun4.md/wait.o: /sprite/lib/include/fmt.h
sun4.md/wait.o: /sprite/lib/include/kernel/sig.h
sun4.md/wait.o: /sprite/lib/include/kernel/rpc.h
sun4.md/wait.o: /sprite/lib/include/kernel/net.h
sun4.md/wait.o: /sprite/lib/include/kernel/syncTypes.h
sun4.md/wait.o: /sprite/lib/include/kernel/sync.h
sun4.md/wait.o: /sprite/lib/include/list.h
sun4.md/wait.o: /sprite/lib/include/sun4.md/kernel/mach.h
sun4.md/wait.o: /sprite/lib/include/setjmp.h
sun4.md/wait.o: /sprite/lib/include/kernel/procMigrate.h
sun4.md/wait.o: /sprite/lib/include/kernel/proc.h
sun4.md/wait.o: /sprite/lib/include/kernel/procTypes.h
sun4.md/wait.o: /sprite/lib/include/kernel/syncLock.h
sun4.md/wait.o: /sprite/lib/include/kernel/timer.h
sun4.md/wait.o: /sprite/lib/include/sun4.md/kernel/timerTick.h
sun4.md/wait.o: /sprite/lib/include/sun4.md/kernel/timerMach.h
sun4.md/wait.o: /sprite/lib/include/kernel/sysSysCallParam.h
sun4.md/wait.o: /sprite/lib/include/kernel/trace.h
sun4.md/wait.o: /sprite/lib/include/kernel/netTypes.h
sun4.md/wait.o: /sprite/lib/include/netEther.h
sun4.md/wait.o: /sprite/lib/include/sun4.md/machparam.h
sun4.md/wait.o: /sprite/lib/include/sun4.md/limits.h
sun4.md/wait.o: /sprite/lib/include/kernel/fs.h
sun4.md/wait.o: /sprite/lib/include/sys/types.h
sun4.md/wait.o: /sprite/lib/include/sys/ipc.h
sun4.md/wait.o: /sprite/lib/include/sys/sem.h
sun4.md/wait.o: /sprite/lib/include/netInet.h
sun4.md/wait.o: /sprite/lib/include/netUltra.h
sun4.md/wait.o: /sprite/lib/include/kernel/netRoute.h
sun4.md/wait.o: /sprite/lib/include/kernel/rpcTypes.h
sun4.md/wait.o: /sprite/lib/include/kernel/rpcCall.h
sun4.md/wait.o: /sprite/lib/include/vmTypes.h compatInt.h
sun4.md/wait.o: /sprite/lib/include/sys/wait.h
sun4.md/wait.o: /sprite/lib/include/sys/time.h
sun4.md/wait.o: /sprite/lib/include/sys/resource.h
sun4.md/printcap.o: printcap.c
sun4.md/printcap.o: lp.h /sprite/lib/include/stdio.h
sun4.md/printcap.o: /sprite/lib/include/cfuncproto.h
sun4.md/printcap.o: /sprite/lib/include/sys/param.h
sun4.md/printcap.o: /sprite/lib/include/sys/types.h
sun4.md/printcap.o: /sprite/lib/include/sys/signal.h
sun4.md/printcap.o: /sprite/lib/include/sun4.md/machparam.h
sun4.md/printcap.o: /sprite/lib/include/sun4.md/limits.h
sun4.md/printcap.o: /sprite/lib/include/sys/file.h
sun4.md/printcap.o: /sprite/lib/include/sys/dir.h
sun4.md/printcap.o: /sprite/lib/include/sys/stat.h
sun4.md/printcap.o: /sprite/lib/include/sys/socket.h
sun4.md/printcap.o: /sprite/lib/include/netinet/in.h
sun4.md/printcap.o: /sprite/lib/include/netdb.h
sun4.md/printcap.o: /sprite/lib/include/pwd.h
sun4.md/printcap.o: /sprite/lib/include/syslog.h
sun4.md/printcap.o: /sprite/lib/include/signal.h
sun4.md/printcap.o: /sprite/lib/include/sys/wait.h
sun4.md/printcap.o: /sprite/lib/include/sgtty.h
sun4.md/printcap.o: /sprite/lib/include/sys/ioctl.h
sun4.md/printcap.o: /sprite/lib/include/sys/ttychars.h
sun4.md/printcap.o: /sprite/lib/include/sys/ttydev.h
sun4.md/printcap.o: /sprite/lib/include/sys/fb.h
sun4.md/printcap.o: /sprite/lib/include/ctype.h
sun4.md/printcap.o: /sprite/lib/include/errno.h lp.local.h
sun4.md/printcap.o: /sprite/lib/include/sun4.md/a.out.h
sun4.md/printcap.o: /sprite/lib/include/sun4.md/sys/exec.h
sun4.md/printcap.o: /sprite/lib/include/sun4.md/kernel/procMach.h
sun4.md/printcap.o: /sprite/lib/include/sprite.h
sun4.md/printcap.o: /sprite/lib/include/ar.h
sun4.md/startdaemon.o: startdaemon.c
sun4.md/startdaemon.o: /sprite/lib/include/stdio.h
sun4.md/startdaemon.o: /sprite/lib/include/cfuncproto.h
sun4.md/startdaemon.o: /sprite/lib/include/sys/types.h
sun4.md/startdaemon.o: /sprite/lib/include/sys/socket.h lp.local.h
sun4.md/startdaemon.o: /sprite/lib/include/sun4.md/a.out.h
sun4.md/startdaemon.o: /sprite/lib/include/sun4.md/sys/exec.h
sun4.md/startdaemon.o: /sprite/lib/include/sun4.md/kernel/procMach.h
sun4.md/startdaemon.o: /sprite/lib/include/sprite.h
sun4.md/startdaemon.o: /sprite/lib/include/ar.h
sun4.md/startdaemon.o: /sprite/lib/include/sys/param.h
sun4.md/startdaemon.o: /sprite/lib/include/sys/signal.h
sun4.md/startdaemon.o: /sprite/lib/include/sun4.md/machparam.h
sun4.md/startdaemon.o: /sprite/lib/include/sun4.md/limits.h
sun4.md/displayq.o: displayq.c
sun4.md/displayq.o: lp.h /sprite/lib/include/stdio.h
sun4.md/displayq.o: /sprite/lib/include/cfuncproto.h
sun4.md/displayq.o: /sprite/lib/include/sys/param.h
sun4.md/displayq.o: /sprite/lib/include/sys/types.h
sun4.md/displayq.o: /sprite/lib/include/sys/signal.h
sun4.md/displayq.o: /sprite/lib/include/sun4.md/machparam.h
sun4.md/displayq.o: /sprite/lib/include/sun4.md/limits.h
sun4.md/displayq.o: /sprite/lib/include/sys/file.h
sun4.md/displayq.o: /sprite/lib/include/sys/dir.h
sun4.md/displayq.o: /sprite/lib/include/sys/stat.h
sun4.md/displayq.o: /sprite/lib/include/sys/socket.h
sun4.md/displayq.o: /sprite/lib/include/netinet/in.h
sun4.md/displayq.o: /sprite/lib/include/netdb.h
sun4.md/displayq.o: /sprite/lib/include/pwd.h
sun4.md/displayq.o: /sprite/lib/include/syslog.h
sun4.md/displayq.o: /sprite/lib/include/signal.h
sun4.md/displayq.o: /sprite/lib/include/sys/wait.h
sun4.md/displayq.o: /sprite/lib/include/sgtty.h
sun4.md/displayq.o: /sprite/lib/include/sys/ioctl.h
sun4.md/displayq.o: /sprite/lib/include/sys/ttychars.h
sun4.md/displayq.o: /sprite/lib/include/sys/ttydev.h
sun4.md/displayq.o: /sprite/lib/include/sys/fb.h
sun4.md/displayq.o: /sprite/lib/include/ctype.h
sun4.md/displayq.o: /sprite/lib/include/errno.h lp.local.h
sun4.md/displayq.o: /sprite/lib/include/sun4.md/a.out.h
sun4.md/displayq.o: /sprite/lib/include/sun4.md/sys/exec.h
sun4.md/displayq.o: /sprite/lib/include/sun4.md/kernel/procMach.h
sun4.md/displayq.o: /sprite/lib/include/sprite.h
sun4.md/displayq.o: /sprite/lib/include/ar.h
sun4.md/lpd.o: lpd.c
sun4.md/lpd.o: lp.h /sprite/lib/include/stdio.h
sun4.md/lpd.o: /sprite/lib/include/cfuncproto.h
sun4.md/lpd.o: /sprite/lib/include/sys/param.h
sun4.md/lpd.o: /sprite/lib/include/sys/types.h
sun4.md/lpd.o: /sprite/lib/include/sys/signal.h
sun4.md/lpd.o: /sprite/lib/include/sun4.md/machparam.h
sun4.md/lpd.o: /sprite/lib/include/sun4.md/limits.h
sun4.md/lpd.o: /sprite/lib/include/sys/file.h
sun4.md/lpd.o: /sprite/lib/include/sys/dir.h
sun4.md/lpd.o: /sprite/lib/include/sys/stat.h
sun4.md/lpd.o: /sprite/lib/include/sys/socket.h
sun4.md/lpd.o: /sprite/lib/include/netinet/in.h
sun4.md/lpd.o: /sprite/lib/include/netdb.h
sun4.md/lpd.o: /sprite/lib/include/pwd.h
sun4.md/lpd.o: /sprite/lib/include/syslog.h
sun4.md/lpd.o: /sprite/lib/include/signal.h
sun4.md/lpd.o: /sprite/lib/include/sys/wait.h
sun4.md/lpd.o: /sprite/lib/include/sgtty.h
sun4.md/lpd.o: /sprite/lib/include/sys/ioctl.h
sun4.md/lpd.o: /sprite/lib/include/sys/ttychars.h
sun4.md/lpd.o: /sprite/lib/include/sys/ttydev.h
sun4.md/lpd.o: /sprite/lib/include/sys/fb.h
sun4.md/lpd.o: /sprite/lib/include/ctype.h
sun4.md/lpd.o: /sprite/lib/include/errno.h lp.local.h
sun4.md/lpd.o: /sprite/lib/include/sun4.md/a.out.h
sun4.md/lpd.o: /sprite/lib/include/sun4.md/sys/exec.h
sun4.md/lpd.o: /sprite/lib/include/sun4.md/kernel/procMach.h
sun4.md/lpd.o: /sprite/lib/include/sprite.h
sun4.md/lpd.o: /sprite/lib/include/ar.h /sprite/lib/include/fs.h
sun4.md/lpd.o: /sprite/lib/include/spriteTime.h
sun4.md/lpd.o: /sprite/lib/include/kernel/procTypes.h
sun4.md/lpd.o: /sprite/lib/include/kernel/proc.h
sun4.md/lpd.o: /sprite/lib/include/kernel/sync.h
sun4.md/lpd.o: /sprite/lib/include/list.h
sun4.md/lpd.o: /sprite/lib/include/kernel/syncTypes.h
sun4.md/lpd.o: /sprite/lib/include/kernel/syncLock.h
sun4.md/lpd.o: /sprite/lib/include/sun4.md/kernel/machTypes.h
sun4.md/lpd.o: /sprite/lib/include/sun4.md/kernel/devAddrs.h
sun4.md/lpd.o: /sprite/lib/include/sun4.md/kernel/machConst.h
sun4.md/lpd.o: /sprite/lib/include/sun4.md/kernel/vmSunConst.h
sun4.md/lpd.o: /sprite/lib/include/kernel/sysSysCall.h
sun4.md/lpd.o: /sprite/lib/include/kernel/sys.h
sun4.md/lpd.o: /sprite/lib/include/status.h
sun4.md/lpd.o: /sprite/lib/include/fmt.h
sun4.md/lpd.o: /sprite/lib/include/kernel/sigTypes.h
sun4.md/lpd.o: /sprite/lib/include/kernel/sig.h
sun4.md/lpd.o: /sprite/lib/include/kernel/rpc.h
sun4.md/lpd.o: /sprite/lib/include/kernel/net.h
sun4.md/lpd.o: /sprite/lib/include/kernel/netTypes.h
sun4.md/lpd.o: /sprite/lib/include/netEther.h
sun4.md/lpd.o: /sprite/lib/include/kernel/fs.h
sun4.md/lpd.o: /sprite/lib/include/netInet.h
sun4.md/lpd.o: /sprite/lib/include/netUltra.h
sun4.md/lpd.o: /sprite/lib/include/kernel/netRoute.h
sun4.md/lpd.o: /sprite/lib/include/kernel/rpcTypes.h
sun4.md/lpd.o: /sprite/lib/include/kernel/rpcCall.h
sun4.md/lpd.o: /sprite/lib/include/kernel/procMigrate.h
sun4.md/lpd.o: /sprite/lib/include/kernel/trace.h
sun4.md/lpd.o: /sprite/lib/include/sun4.md/kernel/mach.h
sun4.md/lpd.o: /sprite/lib/include/setjmp.h
sun4.md/lpd.o: /sprite/lib/include/sys/ipc.h
sun4.md/lpd.o: /sprite/lib/include/sys/sem.h
sun4.md/lpd.o: /sprite/lib/include/kernel/timer.h
sun4.md/lpd.o: /sprite/lib/include/sun4.md/kernel/timerTick.h
sun4.md/lpd.o: /sprite/lib/include/sun4.md/kernel/timerMach.h
sun4.md/lpd.o: /sprite/lib/include/kernel/sysSysCallParam.h
sun4.md/lpd.o: /sprite/lib/include/pdev.h
sun4.md/lpd.o: /sprite/lib/include/dev/pdev.h
sun4.md/lpd.o: /sprite/lib/include/proc.h
sun4.md/lpd.o: /sprite/lib/include/vmTypes.h
sun4.md/printjob.o: printjob.c
sun4.md/printjob.o: lp.h /sprite/lib/include/stdio.h
sun4.md/printjob.o: /sprite/lib/include/cfuncproto.h
sun4.md/printjob.o: /sprite/lib/include/sys/param.h
sun4.md/printjob.o: /sprite/lib/include/sys/types.h
sun4.md/printjob.o: /sprite/lib/include/sys/signal.h
sun4.md/printjob.o: /sprite/lib/include/sun4.md/machparam.h
sun4.md/printjob.o: /sprite/lib/include/sun4.md/limits.h
sun4.md/printjob.o: /sprite/lib/include/sys/file.h
sun4.md/printjob.o: /sprite/lib/include/sys/dir.h
sun4.md/printjob.o: /sprite/lib/include/sys/stat.h
sun4.md/printjob.o: /sprite/lib/include/sys/socket.h
sun4.md/printjob.o: /sprite/lib/include/netinet/in.h
sun4.md/printjob.o: /sprite/lib/include/netdb.h
sun4.md/printjob.o: /sprite/lib/include/pwd.h
sun4.md/printjob.o: /sprite/lib/include/syslog.h
sun4.md/printjob.o: /sprite/lib/include/signal.h
sun4.md/printjob.o: /sprite/lib/include/sys/wait.h
sun4.md/printjob.o: /sprite/lib/include/sgtty.h
sun4.md/printjob.o: /sprite/lib/include/sys/ioctl.h
sun4.md/printjob.o: /sprite/lib/include/sys/ttychars.h
sun4.md/printjob.o: /sprite/lib/include/sys/ttydev.h
sun4.md/printjob.o: /sprite/lib/include/sys/fb.h
sun4.md/printjob.o: /sprite/lib/include/ctype.h
sun4.md/printjob.o: /sprite/lib/include/errno.h lp.local.h
sun4.md/printjob.o: /sprite/lib/include/sun4.md/a.out.h
sun4.md/printjob.o: /sprite/lib/include/sun4.md/sys/exec.h
sun4.md/printjob.o: /sprite/lib/include/sun4.md/kernel/procMach.h
sun4.md/printjob.o: /sprite/lib/include/sprite.h
sun4.md/printjob.o: /sprite/lib/include/ar.h
sun4.md/printjob.o: /sprite/lib/include/proc.h
sun4.md/printjob.o: /sprite/lib/include/spriteTime.h
sun4.md/printjob.o: /sprite/lib/include/kernel/sigTypes.h
sun4.md/printjob.o: /sprite/lib/include/sun4.md/kernel/machTypes.h
sun4.md/printjob.o: /sprite/lib/include/sun4.md/kernel/devAddrs.h
sun4.md/printjob.o: /sprite/lib/include/sun4.md/kernel/machConst.h
sun4.md/printjob.o: /sprite/lib/include/sun4.md/kernel/vmSunConst.h
sun4.md/printjob.o: /sprite/lib/include/kernel/sysSysCall.h
sun4.md/printjob.o: /sprite/lib/include/kernel/sys.h
sun4.md/printjob.o: /sprite/lib/include/status.h
sun4.md/printjob.o: /sprite/lib/include/fmt.h
sun4.md/printjob.o: /sprite/lib/include/kernel/sig.h
sun4.md/printjob.o: /sprite/lib/include/kernel/rpc.h
sun4.md/printjob.o: /sprite/lib/include/kernel/net.h
sun4.md/printjob.o: /sprite/lib/include/kernel/syncTypes.h
sun4.md/printjob.o: /sprite/lib/include/kernel/sync.h
sun4.md/printjob.o: /sprite/lib/include/list.h
sun4.md/printjob.o: /sprite/lib/include/sun4.md/kernel/mach.h
sun4.md/printjob.o: /sprite/lib/include/setjmp.h
sun4.md/printjob.o: /sprite/lib/include/kernel/procMigrate.h
sun4.md/printjob.o: /sprite/lib/include/kernel/proc.h
sun4.md/printjob.o: /sprite/lib/include/kernel/procTypes.h
sun4.md/printjob.o: /sprite/lib/include/kernel/syncLock.h
sun4.md/printjob.o: /sprite/lib/include/kernel/timer.h
sun4.md/printjob.o: /sprite/lib/include/sun4.md/kernel/timerTick.h
sun4.md/printjob.o: /sprite/lib/include/sun4.md/kernel/timerMach.h
sun4.md/printjob.o: /sprite/lib/include/kernel/sysSysCallParam.h
sun4.md/printjob.o: /sprite/lib/include/kernel/trace.h
sun4.md/printjob.o: /sprite/lib/include/kernel/netTypes.h
sun4.md/printjob.o: /sprite/lib/include/netEther.h
sun4.md/printjob.o: /sprite/lib/include/kernel/fs.h
sun4.md/printjob.o: /sprite/lib/include/sys/ipc.h
sun4.md/printjob.o: /sprite/lib/include/sys/sem.h
sun4.md/printjob.o: /sprite/lib/include/netInet.h
sun4.md/printjob.o: /sprite/lib/include/netUltra.h
sun4.md/printjob.o: /sprite/lib/include/kernel/netRoute.h
sun4.md/printjob.o: /sprite/lib/include/kernel/rpcTypes.h
sun4.md/printjob.o: /sprite/lib/include/kernel/rpcCall.h
sun4.md/printjob.o: /sprite/lib/include/vmTypes.h
sun4.md/printjob.o: /sprite/lib/include/fs.h
sun4.md/recvjob.o: recvjob.c
sun4.md/recvjob.o: lp.h /sprite/lib/include/stdio.h
sun4.md/recvjob.o: /sprite/lib/include/cfuncproto.h
sun4.md/recvjob.o: /sprite/lib/include/sys/param.h
sun4.md/recvjob.o: /sprite/lib/include/sys/types.h
sun4.md/recvjob.o: /sprite/lib/include/sys/signal.h
sun4.md/recvjob.o: /sprite/lib/include/sun4.md/machparam.h
sun4.md/recvjob.o: /sprite/lib/include/sun4.md/limits.h
sun4.md/recvjob.o: /sprite/lib/include/sys/file.h
sun4.md/recvjob.o: /sprite/lib/include/sys/dir.h
sun4.md/recvjob.o: /sprite/lib/include/sys/stat.h
sun4.md/recvjob.o: /sprite/lib/include/sys/socket.h
sun4.md/recvjob.o: /sprite/lib/include/netinet/in.h
sun4.md/recvjob.o: /sprite/lib/include/netdb.h
sun4.md/recvjob.o: /sprite/lib/include/pwd.h
sun4.md/recvjob.o: /sprite/lib/include/syslog.h
sun4.md/recvjob.o: /sprite/lib/include/signal.h
sun4.md/recvjob.o: /sprite/lib/include/sys/wait.h
sun4.md/recvjob.o: /sprite/lib/include/sgtty.h
sun4.md/recvjob.o: /sprite/lib/include/sys/ioctl.h
sun4.md/recvjob.o: /sprite/lib/include/sys/ttychars.h
sun4.md/recvjob.o: /sprite/lib/include/sys/ttydev.h
sun4.md/recvjob.o: /sprite/lib/include/sys/fb.h
sun4.md/recvjob.o: /sprite/lib/include/ctype.h
sun4.md/recvjob.o: /sprite/lib/include/errno.h lp.local.h
sun4.md/recvjob.o: /sprite/lib/include/sun4.md/a.out.h
sun4.md/recvjob.o: /sprite/lib/include/sun4.md/sys/exec.h
sun4.md/recvjob.o: /sprite/lib/include/sun4.md/kernel/procMach.h
sun4.md/recvjob.o: /sprite/lib/include/sprite.h
sun4.md/recvjob.o: /sprite/lib/include/ar.h
sun4.md/rmjob.o: rmjob.c
sun4.md/rmjob.o: lp.h /sprite/lib/include/stdio.h
sun4.md/rmjob.o: /sprite/lib/include/cfuncproto.h
sun4.md/rmjob.o: /sprite/lib/include/sys/param.h
sun4.md/rmjob.o: /sprite/lib/include/sys/types.h
sun4.md/rmjob.o: /sprite/lib/include/sys/signal.h
sun4.md/rmjob.o: /sprite/lib/include/sun4.md/machparam.h
sun4.md/rmjob.o: /sprite/lib/include/sun4.md/limits.h
sun4.md/rmjob.o: /sprite/lib/include/sys/file.h
sun4.md/rmjob.o: /sprite/lib/include/sys/dir.h
sun4.md/rmjob.o: /sprite/lib/include/sys/stat.h
sun4.md/rmjob.o: /sprite/lib/include/sys/socket.h
sun4.md/rmjob.o: /sprite/lib/include/netinet/in.h
sun4.md/rmjob.o: /sprite/lib/include/netdb.h
sun4.md/rmjob.o: /sprite/lib/include/pwd.h
sun4.md/rmjob.o: /sprite/lib/include/syslog.h
sun4.md/rmjob.o: /sprite/lib/include/signal.h
sun4.md/rmjob.o: /sprite/lib/include/sys/wait.h
sun4.md/rmjob.o: /sprite/lib/include/sgtty.h
sun4.md/rmjob.o: /sprite/lib/include/sys/ioctl.h
sun4.md/rmjob.o: /sprite/lib/include/sys/ttychars.h
sun4.md/rmjob.o: /sprite/lib/include/sys/ttydev.h
sun4.md/rmjob.o: /sprite/lib/include/sys/fb.h
sun4.md/rmjob.o: /sprite/lib/include/ctype.h
sun4.md/rmjob.o: /sprite/lib/include/errno.h lp.local.h
sun4.md/rmjob.o: /sprite/lib/include/sun4.md/a.out.h
sun4.md/rmjob.o: /sprite/lib/include/sun4.md/sys/exec.h
sun4.md/rmjob.o: /sprite/lib/include/sun4.md/kernel/procMach.h
sun4.md/rmjob.o: /sprite/lib/include/sprite.h
sun4.md/rmjob.o: /sprite/lib/include/ar.h
