# DO NOT DELETE THIS LINE -- make depend depends on it.

spur.md/printMachDepStats.o: spur.md/printMachDepStats.c
spur.md/client.o: client.c
spur.md/client.o: /sprite/lib/include/sprite.h
spur.md/client.o: /sprite/lib/include/status.h
spur.md/client.o: /sprite/lib/include/stdio.h
spur.md/client.o: /sprite/lib/include/fs.h
spur.md/client.o: /sprite/lib/include/spriteTime.h
spur.md/client.o: /sprite/lib/include/proc.h
spur.md/client.o: /sprite/lib/include/sys/file.h
spur.md/client.o: /sprite/lib/include/dev/pdev.h
spur.md/client.o: /sprite/lib/include/kernel/fs.h pdevInt.h
spur.md/pdevtest.o: pdevtest.c
spur.md/pdevtest.o: /sprite/lib/include/sprite.h
spur.md/pdevtest.o: /sprite/lib/include/status.h
spur.md/pdevtest.o: /sprite/lib/include/stdio.h
spur.md/pdevtest.o: /sprite/lib/include/fs.h
spur.md/pdevtest.o: /sprite/lib/include/spriteTime.h
spur.md/pdevtest.o: /sprite/lib/include/proc.h
spur.md/pdevtest.o: /sprite/lib/include/fsCmd.h
spur.md/pdevtest.o: /sprite/lib/include/sysStats.h
spur.md/pdevtest.o: /sprite/lib/include/rpc.h
spur.md/pdevtest.o: /sprite/lib/include/vm.h
spur.md/pdevtest.o: /sprite/lib/include/spur.md/vmMach.h
spur.md/pdevtest.o: /sprite/lib/include/vmStat.h
spur.md/pdevtest.o: /sprite/lib/include/kernel/sched.h
spur.md/pdevtest.o: /sprite/lib/include/kernel/timer.h
spur.md/pdevtest.o: /sprite/lib/include/kernel/proc.h
spur.md/pdevtest.o: /sprite/lib/include/spur.md/kernel/mach.h
spur.md/pdevtest.o: /sprite/lib/include/kernel/sync.h
spur.md/pdevtest.o: /sprite/lib/include/kernel/fsStat.h
spur.md/pdevtest.o: /sprite/lib/include/kernel/vm.h
spur.md/pdevtest.o: /sprite/lib/include/list.h
spur.md/pdevtest.o: /sprite/lib/include/spur.md/kernel/vmMach.h
spur.md/pdevtest.o: /sprite/lib/include/kernel/fs.h
spur.md/pdevtest.o: /sprite/lib/include/option.h pdevInt.h
spur.md/printStats.o: printStats.c
spur.md/printStats.o: /sprite/lib/include/sprite.h
spur.md/printStats.o: /sprite/lib/include/status.h
spur.md/printStats.o: /sprite/lib/include/stdio.h
spur.md/printStats.o: /sprite/lib/include/proc.h
spur.md/printStats.o: /sprite/lib/include/vm.h
spur.md/printStats.o: /sprite/lib/include/spur.md/vmMach.h
spur.md/printStats.o: /sprite/lib/include/vmStat.h
spur.md/printStats.o: /sprite/lib/include/kernel/fs.h
spur.md/printStats.o: /sprite/lib/include/kernel/fsStat.h
spur.md/printStats.o: /sprite/lib/include/kernel/sched.h
spur.md/printStats.o: /sprite/lib/include/kernel/timer.h
spur.md/printStats.o: /sprite/lib/include/kernel/proc.h
spur.md/printStats.o: /sprite/lib/include/spur.md/kernel/mach.h
spur.md/printStats.o: /sprite/lib/include/kernel/sync.h
spur.md/printStats.o: /sprite/lib/include/kernel/vm.h
spur.md/printStats.o: /sprite/lib/include/list.h
spur.md/printStats.o: /sprite/lib/include/spur.md/kernel/vmMach.h
spur.md/server.o: server.c
spur.md/server.o: /sprite/lib/include/sprite.h
spur.md/server.o: /sprite/lib/include/status.h
spur.md/server.o: /sprite/lib/include/sys/file.h
spur.md/server.o: /sprite/lib/include/errno.h
spur.md/server.o: /sprite/lib/include/fs.h
spur.md/server.o: /sprite/lib/include/spriteTime.h
spur.md/server.o: /sprite/lib/include/proc.h
spur.md/server.o: /sprite/lib/include/dev/pdev.h
spur.md/server.o: /sprite/lib/include/kernel/fs.h
spur.md/server.o: /sprite/lib/include/stdio.h
spur.md/server.o: /sprite/lib/include/time.h
spur.md/server.o: /sprite/lib/include/sys.h
spur.md/server.o: /sprite/lib/include/bit.h pdevInt.h
