# DO NOT DELETE THIS LINE -- make depend depends on it.

sym.md/fsmakedev.o: fsmakedev.c
sym.md/fsmakedev.o: /sprite/lib/include/sprite.h
sym.md/fsmakedev.o: /sprite/lib/include/option.h
sym.md/fsmakedev.o: /sprite/lib/include/fs.h
sym.md/fsmakedev.o: /sprite/lib/include/spriteTime.h
sym.md/fsmakedev.o: /sprite/lib/include/proc.h
sym.md/fsmakedev.o: /sprite/lib/include/sig.h
sym.md/fsmakedev.o: /sprite/lib/include/sym.md/kernel/mach.h
sym.md/fsmakedev.o: /sprite/lib/include/sym.md/kernel/machConst.h
sym.md/fsmakedev.o: /sprite/lib/include/sym.md/kernel/vmSymConst.h
sym.md/fsmakedev.o: /sprite/lib/include/sym.md/kernel/vmSymPTE.h
sym.md/fsmakedev.o: /sprite/lib/include/sym.md/kernel/machTrap.h
sym.md/fsmakedev.o: /sprite/lib/include/sym.md/kernel/machFpu.h
sym.md/fsmakedev.o: /sprite/lib/include/sys/types.h
sym.md/fsmakedev.o: /sprite/lib/include/fmt.h
sym.md/fsmakedev.o: /sprite/lib/include/vm.h
sym.md/fsmakedev.o: /sprite/lib/include/sym.md/vmMach.h
sym.md/fsmakedev.o: /sprite/lib/include/vmStat.h
sym.md/fsmakedev.o: /sprite/lib/include/sym.md/kernel/vmMachStat.h
sym.md/fsmakedev.o: /sprite/lib/include/kernel/fs.h
sym.md/fsmakedev.o: /sprite/lib/include/kernel/sys.h
sym.md/fsmakedev.o: /sprite/lib/include/kernel/user/sys.h
sym.md/fsmakedev.o: /sprite/lib/include/status.h
sym.md/fsmakedev.o: /sprite/lib/include/kernel/sync.h
sym.md/fsmakedev.o: /sprite/lib/include/list.h
sym.md/fsmakedev.o: /sprite/lib/include/kernel/proc.h
sym.md/fsmakedev.o: /sprite/lib/include/kernel/syncLock.h
sym.md/fsmakedev.o: /sprite/lib/include/kernel/user/sync.h
sym.md/fsmakedev.o: /sprite/lib/include/kernel/timer.h
sym.md/fsmakedev.o: /sprite/lib/include/sym.md/kernel/timerTick.h
sym.md/fsmakedev.o: /sprite/lib/include/sym.md/kernel/timerMach.h
sym.md/fsmakedev.o: /sprite/lib/include/kernel/sig.h
sym.md/fsmakedev.o: /sprite/lib/include/stdio.h
