# DO NOT DELETE THIS LINE -- make depend depends on it.

sun4.md/kgcore.o: kgcore.c
sun4.md/kgcore.o: /sprite/lib/include/errno.h
sun4.md/kgcore.o: /sprite/lib/include/host.h
sun4.md/kgcore.o: /sprite/lib/include/sys/types.h
sun4.md/kgcore.o: /sprite/lib/include/netinet/in.h
sun4.md/kgcore.o: /sprite/lib/include/sun4.md/machparam.h
sun4.md/kgcore.o: /sprite/lib/include/sun4.md/limits.h
sun4.md/kgcore.o: /sprite/lib/include/net.h
sun4.md/kgcore.o: /sprite/lib/include/netEther.h
sun4.md/kgcore.o: /sprite/lib/include/netInet.h
sun4.md/kgcore.o: /sprite/lib/include/option.h
sun4.md/kgcore.o: /sprite/lib/include/stdio.h
sun4.md/kgcore.o: /sprite/lib/include/string.h
sun4.md/kgcore.o: /sprite/lib/include/sys/file.h
sun4.md/kgcore.o: /sprite/lib/include/sun4.md/kernel/dbg.h
sun4.md/kgcore.o: /sprite/lib/include/sprite.h
sun4.md/kgcore.o: /sprite/lib/include/kernel/sun4.md/mach.h
sun4.md/kgcore.o: /sprite/lib/include/sun4.md/kernel/devAddrs.h
sun4.md/kgcore.o: /sprite/lib/include/sun4.md/kernel/machConst.h
sun4.md/kgcore.o: /sprite/lib/include/sun4.md/kernel/vmSunConst.h
sun4.md/kgcore.o: /sprite/lib/include/kernel/sysSysCall.h
sun4.md/kgcore.o: /sprite/lib/include/kernel/sys.h
sun4.md/kgcore.o: /sprite/lib/include/kernel/user/sys.h
sun4.md/kgcore.o: /sprite/lib/include/status.h
sun4.md/kgcore.o: /sprite/lib/include/fmt.h
sun4.md/kgcore.o: /sprite/lib/include/sun4.md/kernel/machSig.h
sun4.md/kgcore.o: /sprite/lib/include/kernel/sig.h
sun4.md/kgcore.o: /sprite/lib/include/sun4.md/kernel/mach.h
sun4.md/kgcore.o: /sprite/lib/include/stdlib.h
sun4.md/kgcore.o: /sprite/lib/include/signal.h
sun4.md/kgcore.o: /sprite/lib/include/sys/socket.h
sun4.md/kgcore.o: /sprite/lib/include/sys/time.h
sun4.md/kgcore.o: /sprite/lib/include/netdb.h
sun4.md/kgcore.o: /sprite/lib/include/sgtty.h
sun4.md/kgcore.o: /sprite/lib/include/sys/ioctl.h
sun4.md/kgcore.o: /sprite/lib/include/sys/ttychars.h
sun4.md/kgcore.o: /sprite/lib/include/sys/ttydev.h
