# DO NOT DELETE THIS LINE -- make depend depends on it.

ds3100.md/fstrash.o: fstrash.c
ds3100.md/fstrash.o: /sprite/lib/include/sprite.h
ds3100.md/fstrash.o: /sprite/lib/include/cfuncproto.h
ds3100.md/fstrash.o: /sprite/lib/include/option.h
ds3100.md/fstrash.o: /sprite/lib/include/disk.h
ds3100.md/fstrash.o: /sprite/lib/include/sys/file.h
ds3100.md/fstrash.o: /sprite/lib/include/kernel/fs.h
ds3100.md/fstrash.o: /sprite/lib/include/kernel/dev.h
ds3100.md/fstrash.o: /sprite/lib/include/kernel/fsdm.h
ds3100.md/fstrash.o: /sprite/lib/include/kernel/ofs.h
ds3100.md/fstrash.o: /sprite/lib/include/kernel/devDiskLabel.h
ds3100.md/fstrash.o: /sprite/lib/include/kernel/lfsDesc.h
ds3100.md/fstrash.o: /sprite/lib/include/kernel/lfsDescMap.h
ds3100.md/fstrash.o: /sprite/lib/include/kernel/lfsFileLayout.h
ds3100.md/fstrash.o: /sprite/lib/include/kernel/lfsSegLayout.h
ds3100.md/fstrash.o: /sprite/lib/include/kernel/lfsStableMem.h
ds3100.md/fstrash.o: /sprite/lib/include/kernel/lfsSuperBlock.h
ds3100.md/fstrash.o: /sprite/lib/include/kernel/lfsUsageArray.h
ds3100.md/fstrash.o: /sprite/lib/include/stdio.h
ds3100.md/fstrash.o: /sprite/lib/include/stdlib.h
ds3100.md/fstrash.o: /sprite/lib/include/string.h
ds3100.md/fsSetFD.o: fsSetFD.c
ds3100.md/fsSetFD.o: /sprite/lib/include/sprite.h
ds3100.md/fsSetFD.o: /sprite/lib/include/cfuncproto.h
ds3100.md/fsSetFD.o: /sprite/lib/include/option.h
ds3100.md/fsSetFD.o: /sprite/lib/include/disk.h
ds3100.md/fsSetFD.o: /sprite/lib/include/sys/file.h
ds3100.md/fsSetFD.o: /sprite/lib/include/kernel/fs.h
ds3100.md/fsSetFD.o: /sprite/lib/include/kernel/dev.h
ds3100.md/fsSetFD.o: /sprite/lib/include/kernel/fsdm.h
ds3100.md/fsSetFD.o: /sprite/lib/include/kernel/ofs.h
ds3100.md/fsSetFD.o: /sprite/lib/include/kernel/devDiskLabel.h
ds3100.md/fsSetFD.o: /sprite/lib/include/kernel/lfsDesc.h
ds3100.md/fsSetFD.o: /sprite/lib/include/kernel/lfsDescMap.h
ds3100.md/fsSetFD.o: /sprite/lib/include/kernel/lfsFileLayout.h
ds3100.md/fsSetFD.o: /sprite/lib/include/kernel/lfsSegLayout.h
ds3100.md/fsSetFD.o: /sprite/lib/include/kernel/lfsStableMem.h
ds3100.md/fsSetFD.o: /sprite/lib/include/kernel/lfsSuperBlock.h
ds3100.md/fsSetFD.o: /sprite/lib/include/kernel/lfsUsageArray.h
ds3100.md/fsSetFD.o: /sprite/lib/include/stdio.h
ds3100.md/fsSetFD.o: /sprite/lib/include/stdlib.h
ds3100.md/fsSetFD.o: /sprite/lib/include/string.h
