# DO NOT DELETE THIS LINE -- make depend depends on it.

ds3100.md/Host_ByID.o: Host_ByID.c
ds3100.md/Host_ByID.o: /sprite/lib/include/stdio.h
ds3100.md/Host_ByID.o: /sprite/lib/include/cfuncproto.h
ds3100.md/Host_ByID.o: /sprite/lib/include/host.h
ds3100.md/Host_ByID.o: /sprite/lib/include/sys/types.h
ds3100.md/Host_ByID.o: /sprite/lib/include/netinet/in.h
ds3100.md/Host_ByID.o: /sprite/lib/include/ds3100.md/machparam.h
ds3100.md/Host_ByID.o: /sprite/lib/include/machine/limits.h
ds3100.md/Host_ByID.o: /sprite/lib/include/sys/stat.h
ds3100.md/Host_ByID.o: /sprite/lib/include/net.h
ds3100.md/Host_ByID.o: /sprite/lib/include/machparam.h
ds3100.md/Host_ByID.o: /sprite/lib/include/netEther.h
ds3100.md/Host_ByID.o: /sprite/lib/include/netInet.h
ds3100.md/Host_ByID.o: /sprite/lib/include/netUltra.h
ds3100.md/Host_ByID.o: /sprite/lib/include/netFDDI.h
ds3100.md/Host_ByID.o: /sprite/lib/include/sprite.h hostInt.h
ds3100.md/Host_ByName.o: Host_ByName.c
ds3100.md/Host_ByName.o: /sprite/lib/include/stdio.h
ds3100.md/Host_ByName.o: /sprite/lib/include/cfuncproto.h
ds3100.md/Host_ByName.o: /sprite/lib/include/host.h
ds3100.md/Host_ByName.o: /sprite/lib/include/sys/types.h
ds3100.md/Host_ByName.o: /sprite/lib/include/netinet/in.h
ds3100.md/Host_ByName.o: /sprite/lib/include/ds3100.md/machparam.h
ds3100.md/Host_ByName.o: /sprite/lib/include/machine/limits.h
ds3100.md/Host_ByName.o: /sprite/lib/include/sys/stat.h
ds3100.md/Host_ByName.o: /sprite/lib/include/net.h
ds3100.md/Host_ByName.o: /sprite/lib/include/machparam.h
ds3100.md/Host_ByName.o: /sprite/lib/include/netEther.h
ds3100.md/Host_ByName.o: /sprite/lib/include/netInet.h
ds3100.md/Host_ByName.o: /sprite/lib/include/netUltra.h
ds3100.md/Host_ByName.o: /sprite/lib/include/netFDDI.h
ds3100.md/Host_ByName.o: /sprite/lib/include/sprite.h hostInt.h
ds3100.md/Host_ByName.o: /sprite/lib/include/string.h
ds3100.md/Host_End.o: Host_End.c
ds3100.md/Host_End.o: /sprite/lib/include/stdio.h
ds3100.md/Host_End.o: /sprite/lib/include/cfuncproto.h
ds3100.md/Host_End.o: /sprite/lib/include/host.h
ds3100.md/Host_End.o: /sprite/lib/include/sys/types.h
ds3100.md/Host_End.o: /sprite/lib/include/netinet/in.h
ds3100.md/Host_End.o: /sprite/lib/include/ds3100.md/machparam.h
ds3100.md/Host_End.o: /sprite/lib/include/machine/limits.h
ds3100.md/Host_End.o: /sprite/lib/include/sys/stat.h
ds3100.md/Host_End.o: /sprite/lib/include/net.h
ds3100.md/Host_End.o: /sprite/lib/include/machparam.h
ds3100.md/Host_End.o: /sprite/lib/include/netEther.h
ds3100.md/Host_End.o: /sprite/lib/include/netInet.h
ds3100.md/Host_End.o: /sprite/lib/include/netUltra.h
ds3100.md/Host_End.o: /sprite/lib/include/netFDDI.h
ds3100.md/Host_End.o: /sprite/lib/include/sprite.h hostInt.h
ds3100.md/disklabel.o: disklabel.c
ds3100.md/disklabel.o: fsmake.h /sprite/lib/include/sprite.h
ds3100.md/disklabel.o: /sprite/lib/include/stdio.h
ds3100.md/disklabel.o: /sprite/lib/include/cfuncproto.h
ds3100.md/disklabel.o: /sprite/lib/include/stdlib.h
ds3100.md/disklabel.o: /sprite/lib/include/unistd.h
ds3100.md/disklabel.o: /sprite/lib/include/sys/types.h
ds3100.md/disklabel.o: /sprite/lib/include/string.h
ds3100.md/disklabel.o: /sprite/lib/include/bstring.h
ds3100.md/disklabel.o: /sprite/lib/include/sys/file.h
ds3100.md/disklabel.o: /sprite/lib/include/sys/dir.h
ds3100.md/disklabel.o: /sprite/lib/include/option.h
ds3100.md/disklabel.o: /sprite/lib/include/disk.h
ds3100.md/disklabel.o: /sprite/lib/include/kernel/fs.h
ds3100.md/disklabel.o: /sprite/lib/include/kernel/sys.h
ds3100.md/disklabel.o: /sprite/lib/include/sys.h
ds3100.md/disklabel.o: /sprite/lib/include/status.h
ds3100.md/disklabel.o: /sprite/lib/include/spriteTime.h
ds3100.md/disklabel.o: /sprite/lib/include/kernel/syncTypes.h
ds3100.md/disklabel.o: /sprite/lib/include/sync.h
ds3100.md/disklabel.o: /sprite/lib/include/kernel/procTypes.h
ds3100.md/disklabel.o: /sprite/lib/include/proc.h
ds3100.md/disklabel.o: /sprite/lib/include/kernel/sigTypes.h
ds3100.md/disklabel.o: /sprite/lib/include/ds3100.md/kernel/machTypes.h
ds3100.md/disklabel.o: /sprite/lib/include/ds3100.md/kernel/machConst.h
ds3100.md/disklabel.o: /sprite/lib/include/ds3100.md/kernel/vmPmaxConst.h
ds3100.md/disklabel.o: /sprite/lib/include/fmt.h
ds3100.md/disklabel.o: /sprite/lib/include/sig.h
ds3100.md/disklabel.o: /sprite/lib/include/vmTypes.h
ds3100.md/disklabel.o: /sprite/lib/include/kernel/syncLock.h
ds3100.md/disklabel.o: /sprite/lib/include/list.h
ds3100.md/disklabel.o: /sprite/lib/include/kernel/timer.h
ds3100.md/disklabel.o: /sprite/lib/include/ds3100.md/kernel/timerTick.h
ds3100.md/disklabel.o: /sprite/lib/include/ds3100.md/kernel/timerMach.h
ds3100.md/disklabel.o: /sprite/lib/include/fs.h
ds3100.md/disklabel.o: /sprite/lib/include/kernel/dev.h
ds3100.md/disklabel.o: /sprite/lib/include/kernel/devSyslog.h
ds3100.md/disklabel.o: /sprite/lib/include/user/fs.h
ds3100.md/disklabel.o: /sprite/lib/include/sysStats.h
ds3100.md/disklabel.o: /sprite/lib/include/kernel/fsdm.h
ds3100.md/disklabel.o: /sprite/lib/include/kernel/ofs.h
ds3100.md/disklabel.o: /sprite/lib/include/kernel/fslcl.h
ds3100.md/disklabel.o: /sprite/lib/include/kernel/devBlockDevice.h
ds3100.md/disklabel.o: /sprite/lib/include/kernel/devDiskLabel.h
ds3100.md/disklabel.o: /sprite/lib/include/kernel/lfsDesc.h
ds3100.md/disklabel.o: /sprite/lib/include/kernel/lfsDescMap.h
ds3100.md/disklabel.o: /sprite/lib/include/kernel/lfsStableMem.h
ds3100.md/disklabel.o: /sprite/lib/include/kernel/lfsFileLayout.h
ds3100.md/disklabel.o: /sprite/lib/include/kernel/lfsSegLayout.h
ds3100.md/disklabel.o: /sprite/lib/include/kernel/lfsSuperBlock.h
ds3100.md/disklabel.o: /sprite/lib/include/kernel/lfsUsageArray.h
ds3100.md/disklabel.o: /sprite/lib/include/host.h
ds3100.md/disklabel.o: /sprite/lib/include/netinet/in.h
ds3100.md/disklabel.o: /sprite/lib/include/ds3100.md/machparam.h
ds3100.md/disklabel.o: /sprite/lib/include/machine/limits.h
ds3100.md/disklabel.o: /sprite/lib/include/sys/stat.h
ds3100.md/disklabel.o: /sprite/lib/include/net.h
ds3100.md/disklabel.o: /sprite/lib/include/machparam.h
ds3100.md/disklabel.o: /sprite/lib/include/netEther.h
ds3100.md/disklabel.o: /sprite/lib/include/netInet.h
ds3100.md/disklabel.o: /sprite/lib/include/netUltra.h
ds3100.md/disklabel.o: /sprite/lib/include/netFDDI.h
ds3100.md/disklabel.o: /sprite/lib/include/dev/scsi.h
ds3100.md/disklabel.o: /sprite/lib/include/sys/time.h
ds3100.md/disklabel.o: /sprite/lib/include/time.h
ds3100.md/Host_Next.o: Host_Next.c
ds3100.md/Host_Next.o: /sprite/lib/include/stdio.h
ds3100.md/Host_Next.o: /sprite/lib/include/cfuncproto.h
ds3100.md/Host_Next.o: /sprite/lib/include/sprite.h
ds3100.md/Host_Next.o: /sprite/lib/include/ctype.h
ds3100.md/Host_Next.o: /sprite/lib/include/host.h
ds3100.md/Host_Next.o: /sprite/lib/include/sys/types.h
ds3100.md/Host_Next.o: /sprite/lib/include/netinet/in.h
ds3100.md/Host_Next.o: /sprite/lib/include/ds3100.md/machparam.h
ds3100.md/Host_Next.o: /sprite/lib/include/machine/limits.h
ds3100.md/Host_Next.o: /sprite/lib/include/sys/stat.h
ds3100.md/Host_Next.o: /sprite/lib/include/net.h
ds3100.md/Host_Next.o: /sprite/lib/include/machparam.h
ds3100.md/Host_Next.o: /sprite/lib/include/netEther.h
ds3100.md/Host_Next.o: /sprite/lib/include/netInet.h
ds3100.md/Host_Next.o: /sprite/lib/include/netUltra.h
ds3100.md/Host_Next.o: /sprite/lib/include/netFDDI.h hostInt.h
ds3100.md/Host_Next.o: /sprite/lib/include/stdlib.h
ds3100.md/Host_Next.o: /sprite/lib/include/string.h
ds3100.md/Host_Next.o: /sprite/lib/include/arpa/inet.h
ds3100.md/Host_Start.o: Host_Start.c
ds3100.md/Host_Start.o: /sprite/lib/include/stdio.h
ds3100.md/Host_Start.o: /sprite/lib/include/cfuncproto.h
ds3100.md/Host_Start.o: /sprite/lib/include/host.h
ds3100.md/Host_Start.o: /sprite/lib/include/sys/types.h
ds3100.md/Host_Start.o: /sprite/lib/include/netinet/in.h
ds3100.md/Host_Start.o: /sprite/lib/include/ds3100.md/machparam.h
ds3100.md/Host_Start.o: /sprite/lib/include/machine/limits.h
ds3100.md/Host_Start.o: /sprite/lib/include/sys/stat.h
ds3100.md/Host_Start.o: /sprite/lib/include/net.h
ds3100.md/Host_Start.o: /sprite/lib/include/machparam.h
ds3100.md/Host_Start.o: /sprite/lib/include/netEther.h
ds3100.md/Host_Start.o: /sprite/lib/include/netInet.h
ds3100.md/Host_Start.o: /sprite/lib/include/netUltra.h
ds3100.md/Host_Start.o: /sprite/lib/include/netFDDI.h
ds3100.md/Host_Start.o: /sprite/lib/include/sprite.h
ds3100.md/diskHeader.o: diskHeader.c
ds3100.md/diskHeader.o: /sprite/lib/include/disk.h
ds3100.md/diskHeader.o: /sprite/lib/include/sys/file.h
ds3100.md/diskHeader.o: /sprite/lib/include/kernel/fs.h
ds3100.md/diskHeader.o: /sprite/lib/include/kernel/sys.h
ds3100.md/diskHeader.o: /sprite/lib/include/sys.h
ds3100.md/diskHeader.o: /sprite/lib/include/sprite.h
ds3100.md/diskHeader.o: /sprite/lib/include/status.h
ds3100.md/diskHeader.o: /sprite/lib/include/spriteTime.h
ds3100.md/diskHeader.o: /sprite/lib/include/kernel/syncTypes.h
ds3100.md/diskHeader.o: /sprite/lib/include/sync.h
ds3100.md/diskHeader.o: /sprite/lib/include/kernel/procTypes.h
ds3100.md/diskHeader.o: /sprite/lib/include/proc.h
ds3100.md/diskHeader.o: /sprite/lib/include/kernel/sigTypes.h
ds3100.md/diskHeader.o: /sprite/lib/include/ds3100.md/kernel/machTypes.h
ds3100.md/diskHeader.o: /sprite/lib/include/ds3100.md/kernel/machConst.h
ds3100.md/diskHeader.o: /sprite/lib/include/ds3100.md/kernel/vmPmaxConst.h
ds3100.md/diskHeader.o: /sprite/lib/include/fmt.h
ds3100.md/diskHeader.o: /sprite/lib/include/cfuncproto.h
ds3100.md/diskHeader.o: /sprite/lib/include/sig.h
ds3100.md/diskHeader.o: /sprite/lib/include/vmTypes.h
ds3100.md/diskHeader.o: /sprite/lib/include/kernel/syncLock.h
ds3100.md/diskHeader.o: /sprite/lib/include/list.h
ds3100.md/diskHeader.o: /sprite/lib/include/kernel/timer.h
ds3100.md/diskHeader.o: /sprite/lib/include/ds3100.md/kernel/timerTick.h
ds3100.md/diskHeader.o: /sprite/lib/include/ds3100.md/kernel/timerMach.h
ds3100.md/diskHeader.o: /sprite/lib/include/fs.h
ds3100.md/diskHeader.o: /sprite/lib/include/kernel/dev.h
ds3100.md/diskHeader.o: /sprite/lib/include/kernel/devSyslog.h
ds3100.md/diskHeader.o: /sprite/lib/include/user/fs.h
ds3100.md/diskHeader.o: /sprite/lib/include/sysStats.h
ds3100.md/diskHeader.o: /sprite/lib/include/kernel/fsdm.h
ds3100.md/diskHeader.o: /sprite/lib/include/kernel/ofs.h
ds3100.md/diskHeader.o: /sprite/lib/include/kernel/fslcl.h
ds3100.md/diskHeader.o: /sprite/lib/include/kernel/devBlockDevice.h
ds3100.md/diskHeader.o: /sprite/lib/include/kernel/devDiskLabel.h
ds3100.md/diskHeader.o: /sprite/lib/include/kernel/lfsDesc.h
ds3100.md/diskHeader.o: /sprite/lib/include/kernel/lfsDescMap.h
ds3100.md/diskHeader.o: /sprite/lib/include/kernel/lfsStableMem.h
ds3100.md/diskHeader.o: /sprite/lib/include/kernel/lfsFileLayout.h
ds3100.md/diskHeader.o: /sprite/lib/include/kernel/lfsSegLayout.h
ds3100.md/diskHeader.o: /sprite/lib/include/kernel/lfsSuperBlock.h
ds3100.md/diskHeader.o: /sprite/lib/include/kernel/lfsUsageArray.h
ds3100.md/diskHeader.o: /sprite/lib/include/string.h
ds3100.md/diskHeader.o: /sprite/lib/include/stdio.h
ds3100.md/diskHeader.o: /sprite/lib/include/stdlib.h
ds3100.md/diskIO.o: diskIO.c
ds3100.md/diskIO.o: /sprite/lib/include/disk.h
ds3100.md/diskIO.o: /sprite/lib/include/sys/file.h
ds3100.md/diskIO.o: /sprite/lib/include/kernel/fs.h
ds3100.md/diskIO.o: /sprite/lib/include/kernel/sys.h
ds3100.md/diskIO.o: /sprite/lib/include/sys.h
ds3100.md/diskIO.o: /sprite/lib/include/sprite.h
ds3100.md/diskIO.o: /sprite/lib/include/status.h
ds3100.md/diskIO.o: /sprite/lib/include/spriteTime.h
ds3100.md/diskIO.o: /sprite/lib/include/kernel/syncTypes.h
ds3100.md/diskIO.o: /sprite/lib/include/sync.h
ds3100.md/diskIO.o: /sprite/lib/include/kernel/procTypes.h
ds3100.md/diskIO.o: /sprite/lib/include/proc.h
ds3100.md/diskIO.o: /sprite/lib/include/kernel/sigTypes.h
ds3100.md/diskIO.o: /sprite/lib/include/ds3100.md/kernel/machTypes.h
ds3100.md/diskIO.o: /sprite/lib/include/ds3100.md/kernel/machConst.h
ds3100.md/diskIO.o: /sprite/lib/include/ds3100.md/kernel/vmPmaxConst.h
ds3100.md/diskIO.o: /sprite/lib/include/fmt.h
ds3100.md/diskIO.o: /sprite/lib/include/cfuncproto.h
ds3100.md/diskIO.o: /sprite/lib/include/sig.h
ds3100.md/diskIO.o: /sprite/lib/include/vmTypes.h
ds3100.md/diskIO.o: /sprite/lib/include/kernel/syncLock.h
ds3100.md/diskIO.o: /sprite/lib/include/list.h
ds3100.md/diskIO.o: /sprite/lib/include/kernel/timer.h
ds3100.md/diskIO.o: /sprite/lib/include/ds3100.md/kernel/timerTick.h
ds3100.md/diskIO.o: /sprite/lib/include/ds3100.md/kernel/timerMach.h
ds3100.md/diskIO.o: /sprite/lib/include/fs.h
ds3100.md/diskIO.o: /sprite/lib/include/kernel/dev.h
ds3100.md/diskIO.o: /sprite/lib/include/kernel/devSyslog.h
ds3100.md/diskIO.o: /sprite/lib/include/user/fs.h
ds3100.md/diskIO.o: /sprite/lib/include/sysStats.h
ds3100.md/diskIO.o: /sprite/lib/include/kernel/fsdm.h
ds3100.md/diskIO.o: /sprite/lib/include/kernel/ofs.h
ds3100.md/diskIO.o: /sprite/lib/include/kernel/fslcl.h
ds3100.md/diskIO.o: /sprite/lib/include/kernel/devBlockDevice.h
ds3100.md/diskIO.o: /sprite/lib/include/kernel/devDiskLabel.h
ds3100.md/diskIO.o: /sprite/lib/include/kernel/lfsDesc.h
ds3100.md/diskIO.o: /sprite/lib/include/kernel/lfsDescMap.h
ds3100.md/diskIO.o: /sprite/lib/include/kernel/lfsStableMem.h
ds3100.md/diskIO.o: /sprite/lib/include/kernel/lfsFileLayout.h
ds3100.md/diskIO.o: /sprite/lib/include/kernel/lfsSegLayout.h
ds3100.md/diskIO.o: /sprite/lib/include/kernel/lfsSuperBlock.h
ds3100.md/diskIO.o: /sprite/lib/include/kernel/lfsUsageArray.h
ds3100.md/diskIO.o: /sprite/lib/include/stdio.h
ds3100.md/diskIO.o: /sprite/lib/include/errno.h
ds3100.md/diskPrint.o: diskPrint.c
ds3100.md/diskPrint.o: /sprite/lib/include/stdio.h
ds3100.md/diskPrint.o: /sprite/lib/include/cfuncproto.h
ds3100.md/diskPrint.o: /sprite/lib/include/disk.h
ds3100.md/diskPrint.o: /sprite/lib/include/sys/file.h
ds3100.md/diskPrint.o: /sprite/lib/include/kernel/fs.h
ds3100.md/diskPrint.o: /sprite/lib/include/kernel/sys.h
ds3100.md/diskPrint.o: /sprite/lib/include/sys.h
ds3100.md/diskPrint.o: /sprite/lib/include/sprite.h
ds3100.md/diskPrint.o: /sprite/lib/include/status.h
ds3100.md/diskPrint.o: /sprite/lib/include/spriteTime.h
ds3100.md/diskPrint.o: /sprite/lib/include/kernel/syncTypes.h
ds3100.md/diskPrint.o: /sprite/lib/include/sync.h
ds3100.md/diskPrint.o: /sprite/lib/include/kernel/procTypes.h
ds3100.md/diskPrint.o: /sprite/lib/include/proc.h
ds3100.md/diskPrint.o: /sprite/lib/include/kernel/sigTypes.h
ds3100.md/diskPrint.o: /sprite/lib/include/ds3100.md/kernel/machTypes.h
ds3100.md/diskPrint.o: /sprite/lib/include/ds3100.md/kernel/machConst.h
ds3100.md/diskPrint.o: /sprite/lib/include/ds3100.md/kernel/vmPmaxConst.h
ds3100.md/diskPrint.o: /sprite/lib/include/fmt.h
ds3100.md/diskPrint.o: /sprite/lib/include/sig.h
ds3100.md/diskPrint.o: /sprite/lib/include/vmTypes.h
ds3100.md/diskPrint.o: /sprite/lib/include/kernel/syncLock.h
ds3100.md/diskPrint.o: /sprite/lib/include/list.h
ds3100.md/diskPrint.o: /sprite/lib/include/kernel/timer.h
ds3100.md/diskPrint.o: /sprite/lib/include/ds3100.md/kernel/timerTick.h
ds3100.md/diskPrint.o: /sprite/lib/include/ds3100.md/kernel/timerMach.h
ds3100.md/diskPrint.o: /sprite/lib/include/fs.h
ds3100.md/diskPrint.o: /sprite/lib/include/kernel/dev.h
ds3100.md/diskPrint.o: /sprite/lib/include/kernel/devSyslog.h
ds3100.md/diskPrint.o: /sprite/lib/include/user/fs.h
ds3100.md/diskPrint.o: /sprite/lib/include/sysStats.h
ds3100.md/diskPrint.o: /sprite/lib/include/kernel/fsdm.h
ds3100.md/diskPrint.o: /sprite/lib/include/kernel/ofs.h
ds3100.md/diskPrint.o: /sprite/lib/include/kernel/fslcl.h
ds3100.md/diskPrint.o: /sprite/lib/include/kernel/devBlockDevice.h
ds3100.md/diskPrint.o: /sprite/lib/include/kernel/devDiskLabel.h
ds3100.md/diskPrint.o: /sprite/lib/include/kernel/lfsDesc.h
ds3100.md/diskPrint.o: /sprite/lib/include/kernel/lfsDescMap.h
ds3100.md/diskPrint.o: /sprite/lib/include/kernel/lfsStableMem.h
ds3100.md/diskPrint.o: /sprite/lib/include/kernel/lfsFileLayout.h
ds3100.md/diskPrint.o: /sprite/lib/include/kernel/lfsSegLayout.h
ds3100.md/diskPrint.o: /sprite/lib/include/kernel/lfsSuperBlock.h
ds3100.md/diskPrint.o: /sprite/lib/include/kernel/lfsUsageArray.h
ds3100.md/option.o: option.c
ds3100.md/option.o: /sprite/lib/include/option.h
ds3100.md/option.o: /sprite/lib/include/cfuncproto.h
ds3100.md/option.o: /sprite/lib/include/stdio.h
ds3100.md/option.o: /sprite/lib/include/stdlib.h
ds3100.md/option.o: /sprite/lib/include/strings.h
ds3100.md/option.o: /sprite/lib/include/time.h
ds3100.md/fsmake.o: fsmake.c
ds3100.md/fsmake.o: fsmake.h /sprite/lib/include/sprite.h
ds3100.md/fsmake.o: /sprite/lib/include/stdio.h
ds3100.md/fsmake.o: /sprite/lib/include/cfuncproto.h
ds3100.md/fsmake.o: /sprite/lib/include/stdlib.h
ds3100.md/fsmake.o: /sprite/lib/include/unistd.h
ds3100.md/fsmake.o: /sprite/lib/include/sys/types.h
ds3100.md/fsmake.o: /sprite/lib/include/string.h
ds3100.md/fsmake.o: /sprite/lib/include/bstring.h
ds3100.md/fsmake.o: /sprite/lib/include/sys/file.h
ds3100.md/fsmake.o: /sprite/lib/include/sys/dir.h
ds3100.md/fsmake.o: /sprite/lib/include/option.h
ds3100.md/fsmake.o: /sprite/lib/include/disk.h
ds3100.md/fsmake.o: /sprite/lib/include/kernel/fs.h
ds3100.md/fsmake.o: /sprite/lib/include/kernel/sys.h
ds3100.md/fsmake.o: /sprite/lib/include/sys.h
ds3100.md/fsmake.o: /sprite/lib/include/status.h
ds3100.md/fsmake.o: /sprite/lib/include/spriteTime.h
ds3100.md/fsmake.o: /sprite/lib/include/kernel/syncTypes.h
ds3100.md/fsmake.o: /sprite/lib/include/sync.h
ds3100.md/fsmake.o: /sprite/lib/include/kernel/procTypes.h
ds3100.md/fsmake.o: /sprite/lib/include/proc.h
ds3100.md/fsmake.o: /sprite/lib/include/kernel/sigTypes.h
ds3100.md/fsmake.o: /sprite/lib/include/ds3100.md/kernel/machTypes.h
ds3100.md/fsmake.o: /sprite/lib/include/ds3100.md/kernel/machConst.h
ds3100.md/fsmake.o: /sprite/lib/include/ds3100.md/kernel/vmPmaxConst.h
ds3100.md/fsmake.o: /sprite/lib/include/fmt.h
ds3100.md/fsmake.o: /sprite/lib/include/sig.h
ds3100.md/fsmake.o: /sprite/lib/include/vmTypes.h
ds3100.md/fsmake.o: /sprite/lib/include/kernel/syncLock.h
ds3100.md/fsmake.o: /sprite/lib/include/list.h
ds3100.md/fsmake.o: /sprite/lib/include/kernel/timer.h
ds3100.md/fsmake.o: /sprite/lib/include/ds3100.md/kernel/timerTick.h
ds3100.md/fsmake.o: /sprite/lib/include/ds3100.md/kernel/timerMach.h
ds3100.md/fsmake.o: /sprite/lib/include/fs.h
ds3100.md/fsmake.o: /sprite/lib/include/kernel/dev.h
ds3100.md/fsmake.o: /sprite/lib/include/kernel/devSyslog.h
ds3100.md/fsmake.o: /sprite/lib/include/user/fs.h
ds3100.md/fsmake.o: /sprite/lib/include/sysStats.h
ds3100.md/fsmake.o: /sprite/lib/include/kernel/fsdm.h
ds3100.md/fsmake.o: /sprite/lib/include/kernel/ofs.h
ds3100.md/fsmake.o: /sprite/lib/include/kernel/fslcl.h
ds3100.md/fsmake.o: /sprite/lib/include/kernel/devBlockDevice.h
ds3100.md/fsmake.o: /sprite/lib/include/kernel/devDiskLabel.h
ds3100.md/fsmake.o: /sprite/lib/include/kernel/lfsDesc.h
ds3100.md/fsmake.o: /sprite/lib/include/kernel/lfsDescMap.h
ds3100.md/fsmake.o: /sprite/lib/include/kernel/lfsStableMem.h
ds3100.md/fsmake.o: /sprite/lib/include/kernel/lfsFileLayout.h
ds3100.md/fsmake.o: /sprite/lib/include/kernel/lfsSegLayout.h
ds3100.md/fsmake.o: /sprite/lib/include/kernel/lfsSuperBlock.h
ds3100.md/fsmake.o: /sprite/lib/include/kernel/lfsUsageArray.h
ds3100.md/fsmake.o: /sprite/lib/include/host.h
ds3100.md/fsmake.o: /sprite/lib/include/netinet/in.h
ds3100.md/fsmake.o: /sprite/lib/include/ds3100.md/machparam.h
ds3100.md/fsmake.o: /sprite/lib/include/machine/limits.h
ds3100.md/fsmake.o: /sprite/lib/include/sys/stat.h
ds3100.md/fsmake.o: /sprite/lib/include/net.h
ds3100.md/fsmake.o: /sprite/lib/include/machparam.h
ds3100.md/fsmake.o: /sprite/lib/include/netEther.h
ds3100.md/fsmake.o: /sprite/lib/include/netInet.h
ds3100.md/fsmake.o: /sprite/lib/include/netUltra.h
ds3100.md/fsmake.o: /sprite/lib/include/netFDDI.h
ds3100.md/fsmake.o: /sprite/lib/include/dev/scsi.h
ds3100.md/fsmake.o: /sprite/lib/include/sys/time.h
ds3100.md/fsmake.o: /sprite/lib/include/time.h
ds3100.md/fsmake.o: /sprite/lib/include/assert.h
