# DO NOT DELETE THIS LINE -- make depend depends on it.

sun4.md/checkdir.o: checkdir.c
sun4.md/checkdir.o: /sprite/lib/include/option.h
sun4.md/checkdir.o: /sprite/lib/include/cfuncproto.h fscheck.h
sun4.md/checkdir.o: /sprite/lib/include/disk.h
sun4.md/checkdir.o: /sprite/lib/include/sys/types.h
sun4.md/checkdir.o: /sprite/lib/include/sun4.md/varargs.h
sun4.md/checkdir.o: /sprite/lib/include/stdio.h
sun4.md/checkdir.o: /sprite/lib/include/errno.h
sun4.md/checkdir.o: /sprite/lib/include/stdlib.h
sun4.md/checkdir.o: /sprite/lib/include/time.h
sun4.md/checkdir.o: /sprite/lib/include/sys/time.h
sun4.md/checkdir.o: /sprite/lib/include/list.h
sun4.md/checkdir.o: /sprite/lib/include/sprite.h
sun4.md/checkdir.o: /sprite/lib/include/string.h
sun4.md/checkdir.o: /sprite/lib/include/ctype.h
sun4.md/fscheck.o: fscheck.c
sun4.md/fscheck.o: /sprite/lib/include/option.h
sun4.md/fscheck.o: /sprite/lib/include/cfuncproto.h
sun4.md/fscheck.o: /sprite/lib/include/list.h
sun4.md/fscheck.o: /sprite/lib/include/sprite.h fscheck.h
sun4.md/fscheck.o: /sprite/lib/include/disk.h
sun4.md/fscheck.o: /sprite/lib/include/sys/types.h
sun4.md/fscheck.o: /sprite/lib/include/sun4.md/varargs.h
sun4.md/fscheck.o: /sprite/lib/include/stdio.h
sun4.md/fscheck.o: /sprite/lib/include/errno.h
sun4.md/fscheck.o: /sprite/lib/include/stdlib.h
sun4.md/fscheck.o: /sprite/lib/include/time.h
sun4.md/fscheck.o: /sprite/lib/include/sys/time.h
sun4.md/fscheck.o: /sprite/lib/include/string.h
sun4.md/fscheck.o: /sprite/lib/include/host.h
sun4.md/fscheck.o: /sprite/lib/include/netinet/in.h
sun4.md/fscheck.o: /sprite/lib/include/sun4.md/machparam.h
sun4.md/fscheck.o: /sprite/lib/include/sun4.md/limits.h
sun4.md/fscheck.o: /sprite/lib/include/sys/stat.h
sun4.md/fscheck.o: /sprite/lib/include/net.h
sun4.md/fscheck.o: /sprite/lib/include/machparam.h
sun4.md/fscheck.o: /sprite/lib/include/netEther.h
sun4.md/fscheck.o: /sprite/lib/include/netInet.h
sun4.md/fscheck.o: /sprite/lib/include/netUltra.h
sun4.md/fscheck.o: /sprite/lib/include/netFDDI.h
sun4.md/fscheck.o: /sprite/lib/include/sys/file.h
sun4.md/fsUtils.o: fsUtils.c
sun4.md/fsUtils.o: /sprite/lib/include/option.h
sun4.md/fsUtils.o: /sprite/lib/include/cfuncproto.h
sun4.md/fsUtils.o: /sprite/lib/include/list.h
sun4.md/fsUtils.o: /sprite/lib/include/sprite.h fscheck.h
sun4.md/fsUtils.o: /sprite/lib/include/disk.h
sun4.md/fsUtils.o: /sprite/lib/include/sys/types.h
sun4.md/fsUtils.o: /sprite/lib/include/sun4.md/varargs.h
sun4.md/fsUtils.o: /sprite/lib/include/stdio.h
sun4.md/fsUtils.o: /sprite/lib/include/errno.h
sun4.md/fsUtils.o: /sprite/lib/include/stdlib.h
sun4.md/fsUtils.o: /sprite/lib/include/time.h
sun4.md/fsUtils.o: /sprite/lib/include/sys/time.h
sun4.md/fsUtils.o: /sprite/lib/include/string.h
sun4.md/fsUtils.o: /sprite/lib/include/host.h
sun4.md/fsUtils.o: /sprite/lib/include/netinet/in.h
sun4.md/fsUtils.o: /sprite/lib/include/sun4.md/machparam.h
sun4.md/fsUtils.o: /sprite/lib/include/sun4.md/limits.h
sun4.md/fsUtils.o: /sprite/lib/include/sys/stat.h
sun4.md/fsUtils.o: /sprite/lib/include/net.h
sun4.md/fsUtils.o: /sprite/lib/include/machparam.h
sun4.md/fsUtils.o: /sprite/lib/include/netEther.h
sun4.md/fsUtils.o: /sprite/lib/include/netInet.h
sun4.md/fsUtils.o: /sprite/lib/include/netUltra.h
sun4.md/fsUtils.o: /sprite/lib/include/netFDDI.h
sun4.md/fsUtils.o: /sprite/lib/include/sys/file.h
sun4.md/fsUtils.o: /sprite/lib/include/sysStats.h
sun4.md/fsUtils.o: /sprite/lib/include/sys/param.h
sun4.md/fsUtils.o: /sprite/lib/include/signal.h
sun4.md/fsUtils.o: /sprite/lib/include/machSignal.h
