# DO NOT DELETE THIS LINE -- make depend depends on it.

sun3.md/stdlib.o: stdlib.c
sun3.md/stdlib.o: /sprite/lib/include/sprite.h
sun3.md/stdlib.o: /sprite/lib/include/cfuncproto.h
sun3.md/stdlib.o: /sprite/lib/include/proc.h
sun3.md/stdlib.o: /sprite/lib/include/spriteTime.h
sun3.md/stdlib.o: /sprite/lib/include/kernel/sigTypes.h
sun3.md/stdlib.o: /sprite/lib/include/sun3.md/kernel/machTypes.h
sun3.md/stdlib.o: /sprite/lib/include/sun3.md/kernel/devAddrs.h
sun3.md/stdlib.o: /sprite/lib/include/sun3.md/kernel/machConst.h
sun3.md/stdlib.o: /sprite/lib/include/sun3.md/kernel/vmSunConst.h
sun3.md/stdlib.o: /sprite/lib/include/fmt.h
sun3.md/stdlib.o: /sprite/lib/include/sig.h
sun3.md/stdlib.o: /sprite/lib/include/kernel/procTypes.h
sun3.md/stdlib.o: /sprite/lib/include/sync.h
sun3.md/stdlib.o: /sprite/lib/include/kernel/syncLock.h
sun3.md/stdlib.o: /sprite/lib/include/list.h
sun3.md/stdlib.o: /sprite/lib/include/kernel/timer.h
sun3.md/stdlib.o: /sprite/lib/include/sun3.md/kernel/timerTick.h
sun3.md/stdlib.o: /sprite/lib/include/sun3.md/kernel/timerMach.h
sun3.md/stdlib.o: /sprite/lib/include/vmTypes.h
sun3.md/stdlib.o: /sprite/lib/include/stdio.h
sun3.md/stdlib.o: /sprite/lib/include/stdlib.h
sun3.md/stdlib.o: /sprite/lib/include/string.h
sun3.md/stdlib.o: /sprite/lib/include/sys/wait.h
sun3.md/stdlib.o: /sprite/lib/include/sun3.md/machine/machparam.h
sun3.md/stdlib.o: /sprite/lib/include/sun3.md/limits.h
sun3.md/stdlib.o: /sprite/lib/include/signal.h
sun3.md/stdlib.o: /sprite/lib/include/machSignal.h
