#
# Prototype Makefile for machine-dependent directories.
#
# A file of this form resides in each ".md" subdirectory of a
# command.  Its name is typically "md.mk".  During makes in the
# parent directory, this file (or a similar file in a sibling
# subdirectory) is included to define machine-specific things
# such as additional source and object files.
#
# This Makefile is automatically generated.
# DO NOT EDIT IT OR YOU MAY LOSE YOUR CHANGES.
#
# Generated from /sprite/lib/mkmf/Makefile.md
# Tue Jul  2 13:43:51 PDT 1991
#
# For more information, refer to the mkmf manual page.
#
# $Header: /sprite/lib/mkmf/RCS/Makefile.md,v 1.6 90/03/12 23:28:42 jhh Exp $
#
# Allow mkmf

SRCS		= sun3.md/_adddf3.s sun3.md/_divdf3.s sun3.md/_fixdfsi.s sun3.md/_floatsidf.s sun3.md/_muldf3.s sun3.md/_subdf3.s sun3.md/Faintd.s sun3.md/compatMapCode.c sun3.md/modf.s sun3.md/fp_globals.s sun3.md/_cmpdf2.s sun3.md/_negdf2.s sun3.md/compatSig.c sun3.md/bcopy.c sun3.md/_addsf3.s sun3.md/_ashlsi3.s sun3.md/_ashrsi3.s sun3.md/_cmpdi2.s sun3.md/_cmpsf2.s sun3.md/_divsf3.s sun3.md/_divsi3.s sun3.md/_extendsfdf2.s sun3.md/_fixdfdi.s sun3.md/_fixunsdfdi.s sun3.md/_fixunsdfsi.s sun3.md/_floatdidf.s sun3.md/_lshlsi3.s sun3.md/_lshrsi3.s sun3.md/_modsi3.s sun3.md/_mulsf3.s sun3.md/_mulsi3.s sun3.md/_negsf2.s sun3.md/_subsf3.s sun3.md/_truncdfsf2.s sun3.md/_ucmpdi2.s sun3.md/_udivsi3.s sun3.md/_umodsi3.s sun3.md/_umulsi3.s List_Init.c List_Insert.c List_Move.c List_Remove.c MemData.c Time_Add.c Time_Divide.c Time_Multiply.c Time_Subtract.c Time_ToAscii.c Time_ToParts.c bcmp.c bzero.c fmt.c isinf.c sprintf.c status.c strcat.c strchr.c strcmp.c strcpy.c strlen.c strncmp.c strncpy.c strtoul.c timeConstants.c ttyDriver.c frexp.c isascii.c Stdio_Setup.c ctypeBits.c fflush.c fputc.c isspace.c vfprintf.c atof.c atoi.c fgetc.c sscanf.c ungetc.c vfscanf.c Net_AddrToString.c Net_EtherAddrToString.c Net_HostToNetInt.c Net_HostToNetShort.c Net_InetAddrToString.c Net_InetChecksum.c Net_InetHdrChecksum.c Net_NetToHostInt.c Net_NetToHostShort.c fclose.c fgets.c fprintf.c fscanf.c isatty.c isnan.c iszero.c rename.c strcasecmp.c unlink.c errno.c strerror.c Quad_AddUns.c Quad_AddUnsLong.c Quad_CompareUns.c
HDRS		= sun3.md/DEFSInt.h sun3.md/compatSig.h sun3.md/fpcrtInt.h fileInt.h memInt.h
MDPUBHDRS	= 
OBJS		= sun3.md/Faddd.o sun3.md/Fadds.o sun3.md/Faintd.o sun3.md/Fdtos.o sun3.md/Ffloat.o sun3.md/Ffltd.o sun3.md/Fmuld.o sun3.md/Fstod.o sun3.md/List_Init.o sun3.md/List_Insert.o sun3.md/List_Move.o sun3.md/List_Remove.o sun3.md/MemData.o sun3.md/Net_AddrToString.o sun3.md/Net_EtherAddrToString.o sun3.md/Net_HostToNetInt.o sun3.md/Net_HostToNetShort.o sun3.md/Net_InetAddrToString.o sun3.md/Net_InetChecksum.o sun3.md/Net_InetHdrChecksum.o sun3.md/Net_NetToHostInt.o sun3.md/Net_NetToHostShort.o sun3.md/Quad_AddUns.o sun3.md/Quad_AddUnsLong.o sun3.md/Quad_CompareUns.o sun3.md/Stdio_Setup.o sun3.md/Time_Add.o sun3.md/Time_Divide.o sun3.md/Time_Multiply.o sun3.md/Time_Subtract.o sun3.md/Time_ToAscii.o sun3.md/Time_ToParts.o sun3.md/_adddf3.o sun3.md/_addsf3.o sun3.md/_ashlsi3.o sun3.md/_ashrsi3.o sun3.md/_cmpdf2.o sun3.md/_cmpdi2.o sun3.md/_cmpsf2.o sun3.md/_divdf3.o sun3.md/_divsf3.o sun3.md/_divsi3.o sun3.md/_extendsfdf2.o sun3.md/_fixdfdi.o sun3.md/_fixdfsi.o sun3.md/_fixunsdfdi.o sun3.md/_fixunsdfsi.o sun3.md/_floatdidf.o sun3.md/_floatsidf.o sun3.md/_lshlsi3.o sun3.md/_lshrsi3.o sun3.md/_modsi3.o sun3.md/_muldf3.o sun3.md/_mulsf3.o sun3.md/_mulsi3.o sun3.md/_negdf2.o sun3.md/_negsf2.o sun3.md/_subdf3.o sun3.md/_subsf3.o sun3.md/_truncdfsf2.o sun3.md/_ucmpdi2.o sun3.md/_udivsi3.o sun3.md/_umodsi3.o sun3.md/_umulsi3.o sun3.md/atof.o sun3.md/atoi.o sun3.md/bcmp.o sun3.md/bcopy.o sun3.md/bzero.o sun3.md/compatMapCode.o sun3.md/compatSig.o sun3.md/ctypeBits.o sun3.md/errno.o sun3.md/fclose.o sun3.md/fflush.o sun3.md/fgetc.o sun3.md/fgets.o sun3.md/fmt.o sun3.md/fp_globals.o sun3.md/fprintf.o sun3.md/fputc.o sun3.md/frexp.o sun3.md/fscanf.o sun3.md/isascii.o sun3.md/isatty.o sun3.md/isinf.o sun3.md/isnan.o sun3.md/isspace.o sun3.md/iszero.o sun3.md/modf.o sun3.md/rename.o sun3.md/sprintf.o sun3.md/sscanf.o sun3.md/status.o sun3.md/strcasecmp.o sun3.md/strcat.o sun3.md/strchr.o sun3.md/strcmp.o sun3.md/strcpy.o sun3.md/strerror.o sun3.md/strlen.o sun3.md/strncmp.o sun3.md/strncpy.o sun3.md/strtoul.o sun3.md/timeConstants.o sun3.md/ttyDriver.o sun3.md/ungetc.o sun3.md/unlink.o sun3.md/vfprintf.o sun3.md/vfscanf.o
CLEANOBJS	= sun3.md/_adddf3.o sun3.md/_divdf3.o sun3.md/_fixdfsi.o sun3.md/_floatsidf.o sun3.md/_muldf3.o sun3.md/_subdf3.o sun3.md/Faintd.o sun3.md/compatMapCode.o sun3.md/modf.o sun3.md/fp_globals.o sun3.md/_cmpdf2.o sun3.md/_negdf2.o sun3.md/compatSig.o sun3.md/bcopy.o sun3.md/_addsf3.o sun3.md/_ashlsi3.o sun3.md/_ashrsi3.o sun3.md/_cmpdi2.o sun3.md/_cmpsf2.o sun3.md/_divsf3.o sun3.md/_divsi3.o sun3.md/_extendsfdf2.o sun3.md/_fixdfdi.o sun3.md/_fixunsdfdi.o sun3.md/_fixunsdfsi.o sun3.md/_floatdidf.o sun3.md/_lshlsi3.o sun3.md/_lshrsi3.o sun3.md/_modsi3.o sun3.md/_mulsf3.o sun3.md/_mulsi3.o sun3.md/_negsf2.o sun3.md/_subsf3.o sun3.md/_truncdfsf2.o sun3.md/_ucmpdi2.o sun3.md/_udivsi3.o sun3.md/_umodsi3.o sun3.md/_umulsi3.o sun3.md/List_Init.o sun3.md/List_Insert.o sun3.md/List_Move.o sun3.md/List_Remove.o sun3.md/MemData.o sun3.md/Time_Add.o sun3.md/Time_Divide.o sun3.md/Time_Multiply.o sun3.md/Time_Subtract.o sun3.md/Time_ToAscii.o sun3.md/Time_ToParts.o sun3.md/bcmp.o sun3.md/bzero.o sun3.md/fmt.o sun3.md/isinf.o sun3.md/sprintf.o sun3.md/status.o sun3.md/strcat.o sun3.md/strchr.o sun3.md/strcmp.o sun3.md/strcpy.o sun3.md/strlen.o sun3.md/strncmp.o sun3.md/strncpy.o sun3.md/strtoul.o sun3.md/timeConstants.o sun3.md/ttyDriver.o sun3.md/frexp.o sun3.md/isascii.o sun3.md/Stdio_Setup.o sun3.md/ctypeBits.o sun3.md/fflush.o sun3.md/fputc.o sun3.md/isspace.o sun3.md/vfprintf.o sun3.md/atof.o sun3.md/atoi.o sun3.md/fgetc.o sun3.md/sscanf.o sun3.md/ungetc.o sun3.md/vfscanf.o sun3.md/Net_AddrToString.o sun3.md/Net_EtherAddrToString.o sun3.md/Net_HostToNetInt.o sun3.md/Net_HostToNetShort.o sun3.md/Net_InetAddrToString.o sun3.md/Net_InetChecksum.o sun3.md/Net_InetHdrChecksum.o sun3.md/Net_NetToHostInt.o sun3.md/Net_NetToHostShort.o sun3.md/fclose.o sun3.md/fgets.o sun3.md/fprintf.o sun3.md/fscanf.o sun3.md/isatty.o sun3.md/isnan.o sun3.md/iszero.o sun3.md/rename.o sun3.md/strcasecmp.o sun3.md/unlink.o sun3.md/errno.o sun3.md/strerror.o sun3.md/Quad_AddUns.o sun3.md/Quad_AddUnsLong.o sun3.md/Quad_CompareUns.o
INSTFILES	= sun3.md/md.mk sun3.md/dependencies.mk Makefile tags TAGS
SACREDOBJS	= sun3.md/Faddd.o sun3.md/Fadds.o sun3.md/Fdtos.o sun3.md/Ffloat.o sun3.md/Ffltd.o sun3.md/Fmuld.o sun3.md/Fstod.o
