# DO NOT DELETE THIS LINE -- make depend depends on it.

sun2.md/client.o: client.c
sun2.md/client.o: /sprite/lib/include/sprite.h
sun2.md/client.o: /sprite/lib/include/cfuncproto.h
sun2.md/client.o: /sprite/lib/include/status.h
sun2.md/client.o: /sprite/lib/include/stdio.h
sun2.md/client.o: /sprite/lib/include/fs.h
sun2.md/client.o: /sprite/lib/include/spriteTime.h
sun2.md/client.o: /sprite/lib/include/kernel/procTypes.h
sun2.md/client.o: /sprite/lib/include/sys/file.h
sun2.md/client.o: /sprite/lib/include/dev/pdev.h
sun2.md/client.o: /sprite/lib/include/proc.h
sun2.md/client.o: /sprite/lib/include/kernel/fs.h pdevInt.h
sun2.md/pdevtest.o: pdevtest.c
sun2.md/pdevtest.o: /sprite/lib/include/sprite.h
sun2.md/pdevtest.o: /sprite/lib/include/cfuncproto.h
sun2.md/pdevtest.o: /sprite/lib/include/status.h
sun2.md/pdevtest.o: /sprite/lib/include/stdio.h
sun2.md/pdevtest.o: /sprite/lib/include/fs.h
sun2.md/pdevtest.o: /sprite/lib/include/spriteTime.h
sun2.md/pdevtest.o: /sprite/lib/include/kernel/procTypes.h
sun2.md/pdevtest.o: /sprite/lib/include/fsCmd.h
sun2.md/pdevtest.o: /sprite/lib/include/sysStats.h
sun2.md/pdevtest.o: /sprite/lib/include/rpc.h
sun2.md/pdevtest.o: /sprite/lib/include/proc.h
sun2.md/pdevtest.o: /sprite/lib/include/vm.h
sun2.md/pdevtest.o: /sprite/lib/include/kernel/sched.h
sun2.md/pdevtest.o: /sprite/lib/include/kernel/fsStat.h
sun2.md/pdevtest.o: /sprite/lib/include/kernel/vm.h
sun2.md/pdevtest.o: /sprite/lib/include/option.h pdevInt.h
sun2.md/server.o: server.c
sun2.md/server.o: /sprite/lib/include/sprite.h
sun2.md/server.o: /sprite/lib/include/cfuncproto.h
sun2.md/server.o: /sprite/lib/include/status.h
sun2.md/server.o: /sprite/lib/include/sys/file.h
sun2.md/server.o: /sprite/lib/include/errno.h
sun2.md/server.o: /sprite/lib/include/fs.h
sun2.md/server.o: /sprite/lib/include/spriteTime.h
sun2.md/server.o: /sprite/lib/include/kernel/procTypes.h
sun2.md/server.o: /sprite/lib/include/dev/pdev.h
sun2.md/server.o: /sprite/lib/include/proc.h
sun2.md/server.o: /sprite/lib/include/kernel/fs.h
sun2.md/server.o: /sprite/lib/include/stdio.h
sun2.md/server.o: /sprite/lib/include/time.h
sun2.md/server.o: /sprite/lib/include/sys.h
sun2.md/server.o: /sprite/lib/include/bit.h
sun2.md/server.o: /sprite/lib/include/bstring.h pdevInt.h
sun2.md/printStats.o: printStats.c
sun2.md/printStats.o: /sprite/lib/include/sprite.h
sun2.md/printStats.o: /sprite/lib/include/cfuncproto.h
sun2.md/printStats.o: /sprite/lib/include/status.h
sun2.md/printStats.o: /sprite/lib/include/stdio.h
sun2.md/printStats.o: /sprite/lib/include/proc.h
sun2.md/printStats.o: /sprite/lib/include/vm.h
sun2.md/printStats.o: /sprite/lib/include/kernel/fs.h
sun2.md/printStats.o: /sprite/lib/include/kernel/fsStat.h
sun2.md/printStats.o: /sprite/lib/include/kernel/sched.h
sun2.md/printStats.o: /sprite/lib/include/kernel/vm.h
