# DO NOT DELETE THIS LINE -- make depend depends on it.

sun3.md/diskFragIO.o: diskFragIO.c
sun3.md/diskFragIO.o: /sprite/lib/include/disk.h
sun3.md/diskFragIO.o: /sprite/lib/include/sys/file.h
sun3.md/diskFragIO.o: /sprite/lib/include/kernel/fs.h
sun3.md/diskFragIO.o: /sprite/lib/include/kernel/dev.h
sun3.md/diskFragIO.o: /sprite/lib/include/kernel/fsdm.h
sun3.md/diskFragIO.o: /sprite/lib/include/kernel/ofs.h
sun3.md/diskFragIO.o: /sprite/lib/include/kernel/devDiskLabel.h
sun3.md/diskFragIO.o: /sprite/lib/include/kernel/lfsDesc.h
sun3.md/diskFragIO.o: /sprite/lib/include/kernel/lfsDescMap.h
sun3.md/diskFragIO.o: /sprite/lib/include/kernel/lfsFileLayout.h
sun3.md/diskFragIO.o: /sprite/lib/include/kernel/lfsSegLayout.h
sun3.md/diskFragIO.o: /sprite/lib/include/kernel/lfsStableMem.h
sun3.md/diskFragIO.o: /sprite/lib/include/kernel/lfsSuperBlock.h
sun3.md/diskFragIO.o: /sprite/lib/include/kernel/lfsUsageArray.h
sun3.md/diskFragIO.o: /sprite/lib/include/stdio.h
sun3.md/diskFragIO.o: /sprite/lib/include/cfuncproto.h
sun3.md/diskIO.o: diskIO.c
sun3.md/diskIO.o: /sprite/lib/include/disk.h
sun3.md/diskIO.o: /sprite/lib/include/sys/file.h
sun3.md/diskIO.o: /sprite/lib/include/kernel/fs.h
sun3.md/diskIO.o: /sprite/lib/include/kernel/dev.h
sun3.md/diskIO.o: /sprite/lib/include/kernel/fsdm.h
sun3.md/diskIO.o: /sprite/lib/include/kernel/ofs.h
sun3.md/diskIO.o: /sprite/lib/include/kernel/devDiskLabel.h
sun3.md/diskIO.o: /sprite/lib/include/kernel/lfsDesc.h
sun3.md/diskIO.o: /sprite/lib/include/kernel/lfsDescMap.h
sun3.md/diskIO.o: /sprite/lib/include/kernel/lfsFileLayout.h
sun3.md/diskIO.o: /sprite/lib/include/kernel/lfsSegLayout.h
sun3.md/diskIO.o: /sprite/lib/include/kernel/lfsStableMem.h
sun3.md/diskIO.o: /sprite/lib/include/kernel/lfsSuperBlock.h
sun3.md/diskIO.o: /sprite/lib/include/kernel/lfsUsageArray.h
sun3.md/diskIO.o: /sprite/lib/include/stdio.h
sun3.md/diskIO.o: /sprite/lib/include/cfuncproto.h
sun3.md/diskIO.o: /sprite/lib/include/errno.h
sun3.md/diskPrint.o: diskPrint.c
sun3.md/diskPrint.o: /sprite/lib/include/stdio.h
sun3.md/diskPrint.o: /sprite/lib/include/cfuncproto.h
sun3.md/diskPrint.o: /sprite/lib/include/disk.h
sun3.md/diskPrint.o: /sprite/lib/include/sys/file.h
sun3.md/diskPrint.o: /sprite/lib/include/kernel/fs.h
sun3.md/diskPrint.o: /sprite/lib/include/kernel/dev.h
sun3.md/diskPrint.o: /sprite/lib/include/kernel/fsdm.h
sun3.md/diskPrint.o: /sprite/lib/include/kernel/ofs.h
sun3.md/diskPrint.o: /sprite/lib/include/kernel/devDiskLabel.h
sun3.md/diskPrint.o: /sprite/lib/include/kernel/lfsDesc.h
sun3.md/diskPrint.o: /sprite/lib/include/kernel/lfsDescMap.h
sun3.md/diskPrint.o: /sprite/lib/include/kernel/lfsFileLayout.h
sun3.md/diskPrint.o: /sprite/lib/include/kernel/lfsSegLayout.h
sun3.md/diskPrint.o: /sprite/lib/include/kernel/lfsStableMem.h
sun3.md/diskPrint.o: /sprite/lib/include/kernel/lfsSuperBlock.h
sun3.md/diskPrint.o: /sprite/lib/include/kernel/lfsUsageArray.h
sun3.md/option.o: option.c
sun3.md/option.o: /sprite/lib/include/option.h
sun3.md/option.o: /sprite/lib/include/cfuncproto.h
sun3.md/option.o: /sprite/lib/include/stdio.h
sun3.md/option.o: /sprite/lib/include/stdlib.h
sun3.md/option.o: /sprite/lib/include/strings.h
sun3.md/option.o: /sprite/lib/include/time.h
sun3.md/fsmake.o: fsmake.c
sun3.md/fsmake.o: sprite.h /sprite/lib/include/option.h
sun3.md/fsmake.o: /sprite/lib/include/cfuncproto.h
sun3.md/fsmake.o: /sprite/lib/include/disk.h
sun3.md/fsmake.o: /sprite/lib/include/sys/file.h
sun3.md/fsmake.o: /sprite/lib/include/kernel/fs.h
sun3.md/fsmake.o: /sprite/lib/include/kernel/dev.h
sun3.md/fsmake.o: /sprite/lib/include/kernel/fsdm.h
sun3.md/fsmake.o: /sprite/lib/include/kernel/ofs.h
sun3.md/fsmake.o: /sprite/lib/include/kernel/devDiskLabel.h
sun3.md/fsmake.o: /sprite/lib/include/kernel/lfsDesc.h
sun3.md/fsmake.o: /sprite/lib/include/kernel/lfsDescMap.h
sun3.md/fsmake.o: /sprite/lib/include/kernel/lfsFileLayout.h
sun3.md/fsmake.o: /sprite/lib/include/kernel/lfsSegLayout.h
sun3.md/fsmake.o: /sprite/lib/include/kernel/lfsStableMem.h
sun3.md/fsmake.o: /sprite/lib/include/kernel/lfsSuperBlock.h
sun3.md/fsmake.o: /sprite/lib/include/kernel/lfsUsageArray.h
sun3.md/fsmake.o: /sprite/lib/include/stdio.h
sun3.md/fsmake.o: /sprite/lib/include/stdlib.h
sun3.md/fsmake.o: /sprite/lib/include/string.h
sun3.md/fsmake.o: /sprite/lib/include/sys/types.h
sun3.md/fsmake.o: /sprite/lib/include/sys/stat.h
sun3.md/fsmake.o: /sprite/lib/include/sys/dir.h
sun3.md/fsmake.o: /sprite/lib/include/assert.h
sun3.md/fsmake.o: /sprite/lib/include/sys/time.h
sun3.md/fsmake.o: /sprite/lib/include/time.h
