# DO NOT DELETE THIS LINE -- make depend depends on it.

ds3100.md/fsdomain.o: fsdomain.c
ds3100.md/fsdomain.o: /sprite/lib/include/sprite.h
ds3100.md/fsdomain.o: /sprite/lib/include/cfuncproto.h
ds3100.md/fsdomain.o: /sprite/lib/include/sys/file.h
ds3100.md/fsdomain.o: /sprite/lib/include/stdio.h
ds3100.md/fsdomain.o: /sprite/lib/include/errno.h
ds3100.md/fsdomain.o: /sprite/lib/include/disk.h
ds3100.md/fsdomain.o: /sprite/lib/include/kernel/fs.h
ds3100.md/fsdomain.o: /sprite/lib/include/kernel/sys.h
ds3100.md/fsdomain.o: /sprite/lib/include/status.h
ds3100.md/fsdomain.o: /sprite/lib/include/spriteTime.h
ds3100.md/fsdomain.o: /sprite/lib/include/kernel/syncTypes.h
ds3100.md/fsdomain.o: /sprite/lib/include/kernel/sync.h
ds3100.md/fsdomain.o: /sprite/lib/include/list.h
ds3100.md/fsdomain.o: /sprite/lib/include/ds3100.md/kernel/mach.h
ds3100.md/fsdomain.o: /sprite/lib/include/ds3100.md/kernel/machTypes.h
ds3100.md/fsdomain.o: /sprite/lib/include/ds3100.md/kernel/machConst.h
ds3100.md/fsdomain.o: /sprite/lib/include/ds3100.md/kernel/vmPmaxConst.h
ds3100.md/fsdomain.o: /sprite/lib/include/fmt.h
ds3100.md/fsdomain.o: /sprite/lib/include/kernel/proc.h
ds3100.md/fsdomain.o: /sprite/lib/include/kernel/procTypes.h
ds3100.md/fsdomain.o: /sprite/lib/include/kernel/syncLock.h
ds3100.md/fsdomain.o: /sprite/lib/include/kernel/timer.h
ds3100.md/fsdomain.o: /sprite/lib/include/ds3100.md/kernel/timerTick.h
ds3100.md/fsdomain.o: /sprite/lib/include/ds3100.md/kernel/timerMach.h
ds3100.md/fsdomain.o: /sprite/lib/include/kernel/sigTypes.h
ds3100.md/fsdomain.o: /sprite/lib/include/kernel/sig.h
ds3100.md/fsdomain.o: /sprite/lib/include/kernel/rpc.h
ds3100.md/fsdomain.o: /sprite/lib/include/kernel/net.h
ds3100.md/fsdomain.o: /sprite/lib/include/kernel/netTypes.h
ds3100.md/fsdomain.o: /sprite/lib/include/netEther.h
ds3100.md/fsdomain.o: /sprite/lib/include/machparam.h
ds3100.md/fsdomain.o: /sprite/lib/include/machine/limits.h
ds3100.md/fsdomain.o: /sprite/lib/include/netInet.h
ds3100.md/fsdomain.o: /sprite/lib/include/netUltra.h
ds3100.md/fsdomain.o: /sprite/lib/include/kernel/netRoute.h
ds3100.md/fsdomain.o: /sprite/lib/include/kernel/rpcTypes.h
ds3100.md/fsdomain.o: /sprite/lib/include/kernel/rpcCall.h
ds3100.md/fsdomain.o: /sprite/lib/include/kernel/procMigrate.h
ds3100.md/fsdomain.o: /sprite/lib/include/kernel/trace.h
ds3100.md/fsdomain.o: /sprite/lib/include/kernel/sysSysCallParam.h
ds3100.md/fsdomain.o: /sprite/lib/include/sys/types.h
ds3100.md/fsdomain.o: /sprite/lib/include/sys/ipc.h
ds3100.md/fsdomain.o: /sprite/lib/include/sys/sem.h
ds3100.md/fsdomain.o: /sprite/lib/include/kernel/dev.h
ds3100.md/fsdomain.o: /sprite/lib/include/kernel/devSyslog.h
ds3100.md/fsdomain.o: /sprite/lib/include/kernel/user/fs.h
ds3100.md/fsdomain.o: /sprite/lib/include/kernel/user/spriteTime.h
ds3100.md/fsdomain.o: /sprite/lib/include/kernel/user/kernel/procTypes.h
ds3100.md/fsdomain.o: /sprite/lib/include/sysStats.h
ds3100.md/fsdomain.o: /sprite/lib/include/kernel/fsdm.h
ds3100.md/fsdomain.o: /sprite/lib/include/kernel/ofs.h
ds3100.md/fsdomain.o: /sprite/lib/include/kernel/fslcl.h
ds3100.md/fsdomain.o: /sprite/lib/include/kernel/devBlockDevice.h
ds3100.md/fsdomain.o: /sprite/lib/include/kernel/devDiskLabel.h
ds3100.md/fsdomain.o: /sprite/lib/include/kernel/lfsDesc.h
ds3100.md/fsdomain.o: /sprite/lib/include/kernel/lfsDescMap.h
ds3100.md/fsdomain.o: /sprite/lib/include/kernel/lfsStableMem.h
ds3100.md/fsdomain.o: /sprite/lib/include/kernel/lfsFileLayout.h
ds3100.md/fsdomain.o: /sprite/lib/include/kernel/lfsSegLayout.h
ds3100.md/fsdomain.o: /sprite/lib/include/kernel/lfsSuperBlock.h
ds3100.md/fsdomain.o: /sprite/lib/include/kernel/lfsUsageArray.h
ds3100.md/fsdomain.o: /sprite/lib/include/option.h
