# DO NOT DELETE THIS LINE -- make depend depends on it.

sun4.md/mig.o: mig.c
sun4.md/mig.o: /sprite/lib/include/sprite.h
sun4.md/mig.o: /sprite/lib/include/cfuncproto.h
sun4.md/mig.o: /sprite/lib/include/status.h
sun4.md/mig.o: /sprite/lib/include/option.h
sun4.md/mig.o: /sprite/lib/include/proc.h
sun4.md/mig.o: /sprite/lib/include/spriteTime.h
sun4.md/mig.o: /sprite/lib/include/kernel/sigTypes.h
sun4.md/mig.o: /sprite/lib/include/sun4.md/kernel/machTypes.h
sun4.md/mig.o: /sprite/lib/include/sig.h
sun4.md/mig.o: /sprite/lib/include/kernel/procTypes.h
sun4.md/mig.o: /sprite/lib/include/sync.h
sun4.md/mig.o: /sprite/lib/include/kernel/syncLock.h
sun4.md/mig.o: /sprite/lib/include/list.h
sun4.md/mig.o: /sprite/lib/include/kernel/timer.h
sun4.md/mig.o: /sprite/lib/include/sun4.md/kernel/timerTick.h
sun4.md/mig.o: /sprite/lib/include/sun4.md/kernel/timerMach.h
sun4.md/mig.o: /sprite/lib/include/vmTypes.h
sun4.md/mig.o: /sprite/lib/include/stdio.h
sun4.md/mig.o: /sprite/lib/include/stdlib.h
sun4.md/mig.o: /sprite/lib/include/host.h
sun4.md/mig.o: /sprite/lib/include/sys/types.h
sun4.md/mig.o: /sprite/lib/include/netinet/in.h
sun4.md/mig.o: /sprite/lib/include/sun4.md/machparam.h
sun4.md/mig.o: /sprite/lib/include/sun4.md/limits.h
sun4.md/mig.o: /sprite/lib/include/sys/stat.h
sun4.md/mig.o: /sprite/lib/include/net.h
sun4.md/mig.o: /sprite/lib/include/machparam.h
sun4.md/mig.o: /sprite/lib/include/netEther.h
sun4.md/mig.o: /sprite/lib/include/netInet.h
sun4.md/mig.o: /sprite/lib/include/netUltra.h
sun4.md/mig.o: /sprite/lib/include/netFDDI.h
sun4.md/mig.o: /sprite/lib/include/sys/wait.h
sun4.md/mig.o: /sprite/lib/include/sun4.md/machine/machparam.h
sun4.md/mig.o: /sprite/lib/include/signal.h
sun4.md/mig.o: /sprite/lib/include/machSignal.h
sun4.md/mig.o: /sprite/lib/include/string.h
sun4.md/mig.o: /sprite/lib/include/errno.h
sun4.md/mig.o: /sprite/lib/include/mig.h /sprite/lib/include/fs.h
