# DO NOT DELETE THIS LINE -- make depend depends on it.

sun4.md/printStats.o: sun4.md/printStats.c
sun4.md/printStats.o: /sprite/lib/include/sprite.h
sun4.md/printStats.o: /sprite/lib/include/status.h
sun4.md/printStats.o: /sprite/lib/include/sys/ioctl.h
sun4.md/printStats.o: /sprite/lib/include/sys/file.h
sun4.md/printStats.o: /sprite/lib/include/stdio.h
sun4.md/printStats.o: /sprite/lib/include/proc.h
sun4.md/printStats.o: /sprite/lib/include/vm.h
sun4.md/printStats.o: /sprite/lib/include/sysStats.h
sun4.md/printStats.o: /sprite/lib/include/kernel/fs.h
sun4.md/printStats.o: /sprite/lib/include/kernel/fsStat.h
sun4.md/printStats.o: /sprite/lib/include/kernel/sched.h
sun4.md/printStats.o: /sprite/lib/include/kernel/vm.h
sun4.md/printStats.o: /sprite/lib/include/kernel/net.h
sun4.md/client.o: client.c
sun4.md/client.o: /sprite/lib/include/sprite.h
sun4.md/client.o: /sprite/lib/include/status.h
sun4.md/client.o: /sprite/lib/include/sys/ioctl.h
sun4.md/client.o: /sprite/lib/include/sys/file.h
sun4.md/client.o: /sprite/lib/include/stdio.h
sun4.md/server.o: server.c
sun4.md/server.o: /sprite/lib/include/sprite.h
sun4.md/server.o: /sprite/lib/include/status.h
sun4.md/server.o: /sprite/lib/include/fs.h
sun4.md/server.o: /sprite/lib/include/spriteTime.h
sun4.md/server.o: /sprite/lib/include/kernel/procTypes.h
sun4.md/server.o: /sprite/lib/include/proc.h
sun4.md/server.o: /sprite/lib/include/sync.h
sun4.md/server.o: /sprite/lib/include/kernel/syncLock.h
sun4.md/server.o: /sprite/lib/include/list.h
sun4.md/server.o: /sprite/lib/include/kernel/timer.h
sun4.md/server.o: /sprite/lib/include/sun4.md/kernel/timerTick.h
sun4.md/server.o: /sprite/lib/include/sun4.md/kernel/timerMach.h
sun4.md/server.o: /sprite/lib/include/kernel/sigTypes.h
sun4.md/server.o: /sprite/lib/include/sun4.md/kernel/machTypes.h
sun4.md/server.o: /sprite/lib/include/sig.h
sun4.md/server.o: /sprite/lib/include/dev/pdev.h
sun4.md/server.o: /sprite/lib/include/kernel/fs.h
sun4.md/server.o: /sprite/lib/include/sys/file.h
sun4.md/server.o: /sprite/lib/include/stdio.h
sun4.md/server.o: /sprite/lib/include/bit.h
sun4.md/server.o: /sprite/lib/include/cfuncproto.h
sun4.md/server.o: /sprite/lib/include/bstring.h
sun4.md/server.o: /sprite/lib/include/sys.h
sun4.md/proc.o: proc.c
sun4.md/proc.o: /sprite/lib/include/proc.h
sun4.md/proc.o: /sprite/lib/include/stdio.h
sun4.md/bench.o: bench.c
sun4.md/bench.o: /sprite/lib/include/sprite.h
sun4.md/bench.o: /sprite/lib/include/status.h
sun4.md/bench.o: /sprite/lib/include/sys/ioctl.h
sun4.md/bench.o: /sprite/lib/include/sys/file.h
sun4.md/bench.o: /sprite/lib/include/fs.h
sun4.md/bench.o: /sprite/lib/include/spriteTime.h
sun4.md/bench.o: /sprite/lib/include/kernel/procTypes.h
sun4.md/bench.o: /sprite/lib/include/proc.h
sun4.md/bench.o: /sprite/lib/include/sync.h
sun4.md/bench.o: /sprite/lib/include/kernel/syncLock.h
sun4.md/bench.o: /sprite/lib/include/list.h
sun4.md/bench.o: /sprite/lib/include/kernel/timer.h
sun4.md/bench.o: /sprite/lib/include/sun4.md/kernel/timerTick.h
sun4.md/bench.o: /sprite/lib/include/sun4.md/kernel/timerMach.h
sun4.md/bench.o: /sprite/lib/include/kernel/sigTypes.h
sun4.md/bench.o: /sprite/lib/include/sun4.md/kernel/machTypes.h
sun4.md/bench.o: /sprite/lib/include/sig.h
sun4.md/bench.o: /sprite/lib/include/fsCmd.h
sun4.md/bench.o: /sprite/lib/include/sysStats.h
sun4.md/bench.o: /sprite/lib/include/vm.h
sun4.md/bench.o: /sprite/lib/include/kernel/sched.h
sun4.md/bench.o: /sprite/lib/include/kernel/fsStat.h
sun4.md/bench.o: /sprite/lib/include/kernel/vm.h
sun4.md/bench.o: /sprite/lib/include/kernel/net.h
sun4.md/bench.o: /sprite/lib/include/option.h
sun4.md/bench.o: /sprite/lib/include/signal.h
sun4.md/bench.o: /sprite/lib/include/stdio.h
