# DO NOT DELETE THIS LINE -- make depend depends on it.

sun3.md/main.o: main.c
sun3.md/main.o: /sprite/lib/include/sprite.h
sun3.md/main.o: /sprite/lib/include/cfuncproto.h
sun3.md/main.o: /sprite/lib/include/stdio.h
sun3.md/main.o: /sprite/lib/include/stdlib.h
sun3.md/main.o: /sprite/lib/include/string.h
sun3.md/main.o: /sprite/lib/include/errno.h
sun3.md/main.o: /sprite/lib/include/signal.h
sun3.md/main.o: /sprite/lib/include/machSignal.h
sun3.md/main.o: /sprite/lib/include/fs.h
sun3.md/main.o: /sprite/lib/include/spriteTime.h
sun3.md/main.o: /sprite/lib/include/kernel/procTypes.h
sun3.md/main.o: /sprite/lib/include/option.h
sun3.md/main.o: /sprite/lib/include/syslog.h
sun3.md/main.o: /sprite/lib/include/status.h
sun3.md/main.o: /sprite/lib/include/sysStats.h
sun3.md/main.o: /sprite/lib/include/sys/file.h
sun3.md/main.o: /sprite/lib/include/host.h
sun3.md/main.o: /sprite/lib/include/sys/types.h
sun3.md/main.o: /sprite/lib/include/netinet/in.h
sun3.md/main.o: /sprite/lib/include/sun3.md/machparam.h
sun3.md/main.o: /sprite/lib/include/sun3.md/limits.h
sun3.md/main.o: /sprite/lib/include/sys/stat.h
sun3.md/main.o: /sprite/lib/include/net.h
sun3.md/main.o: /sprite/lib/include/machparam.h
sun3.md/main.o: /sprite/lib/include/netEther.h
sun3.md/main.o: /sprite/lib/include/netInet.h
sun3.md/main.o: /sprite/lib/include/netUltra.h
sun3.md/main.o: /sprite/lib/include/netFDDI.h migd.h
sun3.md/main.o: /sprite/lib/include/mig.h
sun3.md/main.o: /sprite/lib/include/list.h
sun3.md/main.o: /sprite/lib/include/pdev.h migPdev.h global.h
sun3.md/migd.o: migd.c
sun3.md/migd.o: /sprite/lib/include/sprite.h
sun3.md/migd.o: /sprite/lib/include/cfuncproto.h
sun3.md/migd.o: /sprite/lib/include/stdio.h
sun3.md/migd.o: /sprite/lib/include/stdlib.h
sun3.md/migd.o: /sprite/lib/include/string.h
sun3.md/migd.o: /sprite/lib/include/errno.h
sun3.md/migd.o: /sprite/lib/include/signal.h
sun3.md/migd.o: /sprite/lib/include/machSignal.h
sun3.md/migd.o: /sprite/lib/include/sun3.md/setjmp.h
sun3.md/migd.o: /sprite/lib/include/fs.h
sun3.md/migd.o: /sprite/lib/include/spriteTime.h
sun3.md/migd.o: /sprite/lib/include/kernel/procTypes.h
sun3.md/migd.o: /sprite/lib/include/option.h
sun3.md/migd.o: /sprite/lib/include/syslog.h
sun3.md/migd.o: /sprite/lib/include/status.h
sun3.md/migd.o: /sprite/lib/include/sysStats.h
sun3.md/migd.o: /sprite/lib/include/host.h
sun3.md/migd.o: /sprite/lib/include/sys/types.h
sun3.md/migd.o: /sprite/lib/include/netinet/in.h
sun3.md/migd.o: /sprite/lib/include/sun3.md/machparam.h
sun3.md/migd.o: /sprite/lib/include/sun3.md/limits.h
sun3.md/migd.o: /sprite/lib/include/sys/stat.h
sun3.md/migd.o: /sprite/lib/include/net.h
sun3.md/migd.o: /sprite/lib/include/machparam.h
sun3.md/migd.o: /sprite/lib/include/netEther.h
sun3.md/migd.o: /sprite/lib/include/netInet.h
sun3.md/migd.o: /sprite/lib/include/netUltra.h
sun3.md/migd.o: /sprite/lib/include/netFDDI.h
sun3.md/migd.o: /sprite/lib/include/sys/file.h
sun3.md/migd.o: /sprite/lib/include/sys/signal.h
sun3.md/migd.o: /sprite/lib/include/sys/wait.h
sun3.md/migd.o: /sprite/lib/include/sun3.md/machine/machparam.h
sun3.md/migd.o: /sprite/lib/include/sys/time.h
sun3.md/migd.o: /sprite/lib/include/time.h
sun3.md/migd.o: /sprite/lib/include/sys/resource.h
sun3.md/migd.o: /sprite/lib/include/kernel/sched.h
sun3.md/migd.o: /sprite/lib/include/kernel/timer.h
sun3.md/migd.o: /sprite/lib/include/list.h
sun3.md/migd.o: /sprite/lib/include/sun3.md/kernel/timerTick.h
sun3.md/migd.o: /sprite/lib/include/sun3.md/kernel/timerMach.h
sun3.md/migd.o: /sprite/lib/include/kernel/syncLock.h
sun3.md/migd.o: /sprite/lib/include/sync.h
sun3.md/migd.o: /sprite/lib/include/kernel/proc.h
sun3.md/migd.o: /sprite/lib/include/kernel/sig.h
sun3.md/migd.o: /sprite/lib/include/kernel/sigTypes.h
sun3.md/migd.o: /sprite/lib/include/sun3.md/kernel/machTypes.h
sun3.md/migd.o: /sprite/lib/include/sig.h
sun3.md/migd.o: /sprite/lib/include/kernel/rpc.h
sun3.md/migd.o: /sprite/lib/include/kernel/net.h
sun3.md/migd.o: /sprite/lib/include/kernel/syncTypes.h
sun3.md/migd.o: /sprite/lib/include/proc.h
sun3.md/migd.o: /sprite/lib/include/vmTypes.h
sun3.md/migd.o: /sprite/lib/include/kernel/netTypes.h
sun3.md/migd.o: /sprite/lib/include/kernel/fs.h
sun3.md/migd.o: /sprite/lib/include/kernel/sys.h
sun3.md/migd.o: /sprite/lib/include/sys.h /sprite/lib/include/fmt.h
sun3.md/migd.o: /sprite/lib/include/kernel/netRoute.h
sun3.md/migd.o: /sprite/lib/include/kernel/rpcTypes.h
sun3.md/migd.o: /sprite/lib/include/kernel/rpcCall.h
sun3.md/migd.o: /sprite/lib/include/kernel/procMigrate.h
sun3.md/migd.o: /sprite/lib/include/kernel/trace.h
sun3.md/migd.o: /sprite/lib/include/sun3.md/kernel/mach.h
sun3.md/migd.o: /sprite/lib/include/sun3.md/kernel/devAddrs.h
sun3.md/migd.o: /sprite/lib/include/kernel/sysSysCallParam.h
sun3.md/migd.o: /sprite/lib/include/kernel/sync.h
sun3.md/migd.o: /sprite/lib/include/sys/ipc.h
sun3.md/migd.o: /sprite/lib/include/sys/sem.h
sun3.md/migd.o: /sprite/lib/include/bit.h
sun3.md/migd.o: /sprite/lib/include/bstring.h
sun3.md/migd.o: /sprite/lib/include/pwd.h migd.h
sun3.md/migd.o: /sprite/lib/include/mig.h
sun3.md/migd.o: /sprite/lib/include/pdev.h migPdev.h global.h
sun3.md/util.o: util.c
sun3.md/util.o: /sprite/lib/include/syslog.h
sun3.md/util.o: /sprite/lib/include/stdlib.h
sun3.md/util.o: /sprite/lib/include/cfuncproto.h
sun3.md/util.o: /sprite/lib/include/stdio.h
sun3.md/util.o: /sprite/lib/include/errno.h migd.h
sun3.md/util.o: /sprite/lib/include/sprite.h
sun3.md/util.o: /sprite/lib/include/fs.h
sun3.md/util.o: /sprite/lib/include/spriteTime.h
sun3.md/util.o: /sprite/lib/include/kernel/procTypes.h
sun3.md/util.o: /sprite/lib/include/mig.h
sun3.md/util.o: /sprite/lib/include/list.h
sun3.md/util.o: /sprite/lib/include/pdev.h
sun3.md/migPdev.o: migPdev.c
sun3.md/migPdev.o: /sprite/lib/include/sprite.h
sun3.md/migPdev.o: /sprite/lib/include/cfuncproto.h
sun3.md/migPdev.o: /sprite/lib/include/string.h
sun3.md/migPdev.o: /sprite/lib/include/errno.h
sun3.md/migPdev.o: /sprite/lib/include/status.h
sun3.md/migPdev.o: /sprite/lib/include/syslog.h
sun3.md/migPdev.o: /sprite/lib/include/bstring.h
sun3.md/migPdev.o: /sprite/lib/include/fs.h
sun3.md/migPdev.o: /sprite/lib/include/spriteTime.h
sun3.md/migPdev.o: /sprite/lib/include/kernel/procTypes.h
sun3.md/migPdev.o: /sprite/lib/include/kernel/fs.h
sun3.md/migPdev.o: /sprite/lib/include/kernel/sys.h
sun3.md/migPdev.o: /sprite/lib/include/sys.h
sun3.md/migPdev.o: /sprite/lib/include/kernel/syncTypes.h
sun3.md/migPdev.o: /sprite/lib/include/sync.h
sun3.md/migPdev.o: /sprite/lib/include/kernel/syncLock.h
sun3.md/migPdev.o: /sprite/lib/include/list.h
sun3.md/migPdev.o: /sprite/lib/include/sun3.md/kernel/machTypes.h
sun3.md/migPdev.o: /sprite/lib/include/proc.h
sun3.md/migPdev.o: /sprite/lib/include/kernel/sigTypes.h
sun3.md/migPdev.o: /sprite/lib/include/sig.h
sun3.md/migPdev.o: /sprite/lib/include/vmTypes.h
sun3.md/migPdev.o: /sprite/lib/include/fmt.h
sun3.md/migPdev.o: /sprite/lib/include/sys/types.h
sun3.md/migPdev.o: /sprite/lib/include/unistd.h
sun3.md/migPdev.o: /sprite/lib/include/stdlib.h
sun3.md/migPdev.o: /sprite/lib/include/stdio.h
sun3.md/migPdev.o: /sprite/lib/include/sys/dir.h
sun3.md/migPdev.o: /sprite/lib/include/sys/stat.h
sun3.md/migPdev.o: /sprite/lib/include/host.h
sun3.md/migPdev.o: /sprite/lib/include/netinet/in.h
sun3.md/migPdev.o: /sprite/lib/include/sun3.md/machparam.h
sun3.md/migPdev.o: /sprite/lib/include/sun3.md/limits.h
sun3.md/migPdev.o: /sprite/lib/include/net.h
sun3.md/migPdev.o: /sprite/lib/include/machparam.h
sun3.md/migPdev.o: /sprite/lib/include/netEther.h
sun3.md/migPdev.o: /sprite/lib/include/netInet.h
sun3.md/migPdev.o: /sprite/lib/include/netUltra.h
sun3.md/migPdev.o: /sprite/lib/include/netFDDI.h
sun3.md/migPdev.o: /sprite/lib/include/pdev.h migd.h
sun3.md/migPdev.o: /sprite/lib/include/mig.h migPdev.h global.h
sun3.md/Mig_GetPdevName.o: Mig_GetPdevName.c
sun3.md/Mig_GetPdevName.o: /sprite/lib/include/fs.h
sun3.md/Mig_GetPdevName.o: /sprite/lib/include/spriteTime.h
sun3.md/Mig_GetPdevName.o: /sprite/lib/include/kernel/procTypes.h
sun3.md/Mig_GetPdevName.o: /sprite/lib/include/stdio.h
sun3.md/Mig_GetPdevName.o: /sprite/lib/include/cfuncproto.h
sun3.md/Mig_GetPdevName.o: /sprite/lib/include/mig.h
sun3.md/global.o: global.c
sun3.md/global.o: /sprite/lib/include/sprite.h
sun3.md/global.o: /sprite/lib/include/cfuncproto.h
sun3.md/global.o: /sprite/lib/include/string.h
sun3.md/global.o: /sprite/lib/include/list.h
sun3.md/global.o: /sprite/lib/include/errno.h
sun3.md/global.o: /sprite/lib/include/status.h
sun3.md/global.o: /sprite/lib/include/syslog.h
sun3.md/global.o: /sprite/lib/include/bstring.h
sun3.md/global.o: /sprite/lib/include/fs.h
sun3.md/global.o: /sprite/lib/include/spriteTime.h
sun3.md/global.o: /sprite/lib/include/kernel/procTypes.h
sun3.md/global.o: /sprite/lib/include/kernel/fs.h
sun3.md/global.o: /sprite/lib/include/kernel/sys.h
sun3.md/global.o: /sprite/lib/include/sys.h
sun3.md/global.o: /sprite/lib/include/kernel/syncTypes.h
sun3.md/global.o: /sprite/lib/include/sync.h
sun3.md/global.o: /sprite/lib/include/kernel/syncLock.h
sun3.md/global.o: /sprite/lib/include/sun3.md/kernel/machTypes.h
sun3.md/global.o: /sprite/lib/include/proc.h
sun3.md/global.o: /sprite/lib/include/kernel/sigTypes.h
sun3.md/global.o: /sprite/lib/include/sig.h
sun3.md/global.o: /sprite/lib/include/vmTypes.h
sun3.md/global.o: /sprite/lib/include/fmt.h
sun3.md/global.o: /sprite/lib/include/sys/types.h
sun3.md/global.o: /sprite/lib/include/sys/time.h
sun3.md/global.o: /sprite/lib/include/time.h
sun3.md/global.o: /sprite/lib/include/unistd.h
sun3.md/global.o: /sprite/lib/include/stdlib.h
sun3.md/global.o: /sprite/lib/include/stdio.h
sun3.md/global.o: /sprite/lib/include/sys/dir.h
sun3.md/global.o: /sprite/lib/include/sys/file.h
sun3.md/global.o: /sprite/lib/include/sys/stat.h
sun3.md/global.o: /sprite/lib/include/host.h
sun3.md/global.o: /sprite/lib/include/netinet/in.h
sun3.md/global.o: /sprite/lib/include/sun3.md/machparam.h
sun3.md/global.o: /sprite/lib/include/sun3.md/limits.h
sun3.md/global.o: /sprite/lib/include/net.h
sun3.md/global.o: /sprite/lib/include/machparam.h
sun3.md/global.o: /sprite/lib/include/netEther.h
sun3.md/global.o: /sprite/lib/include/netInet.h
sun3.md/global.o: /sprite/lib/include/netUltra.h
sun3.md/global.o: /sprite/lib/include/netFDDI.h
sun3.md/global.o: /sprite/lib/include/signal.h
sun3.md/global.o: /sprite/lib/include/machSignal.h
sun3.md/global.o: /sprite/lib/include/pdev.h
sun3.md/global.o: /sprite/lib/include/kernel/net.h
sun3.md/global.o: /sprite/lib/include/kernel/netTypes.h
sun3.md/global.o: /sprite/lib/include/kernel/netRoute.h
sun3.md/global.o: /sprite/lib/include/mig.h migd.h migPdev.h
