# DO NOT DELETE THIS LINE -- make depend depends on it.

sun4.md/whence.o: whence.c
sun4.md/whence.o: /sprite/lib/include/stdio.h
sun4.md/whence.o: /sprite/lib/include/ctype.h
sun4.md/whence.o: /sprite/lib/include/sys/param.h
sun4.md/whence.o: /sprite/lib/include/sys/types.h
sun4.md/whence.o: /sprite/lib/include/sys/signal.h
sun4.md/whence.o: /sprite/lib/include/sun4.md/machparam.h
sun4.md/whence.o: /sprite/lib/include/sun4.md/limits.h
sun4.md/whence.o: /sprite/lib/include/sys/stat.h
sun4.md/whence.o: /sprite/lib/include/strings.h
sun4.md/wishCmd.o: wishCmd.c
sun4.md/wishCmd.o: /sprite/lib/include/sys/types.h
sun4.md/wishCmd.o: /sprite/lib/include/sys/stat.h
sun4.md/wishCmd.o: /sprite/lib/include/sx.h
sun4.md/wishCmd.o: /sprite/lib/include/X11/Xlib.h
sun4.md/wishCmd.o: /sprite/lib/include/X11/X.h
sun4.md/wishCmd.o: /sprite/lib/include/util.h monitorClient.h
sun4.md/wishCmd.o: wishInt.h /sprite/lib/include/sys/param.h
sun4.md/wishCmd.o: /sprite/lib/include/sys/signal.h
sun4.md/wishCmd.o: /sprite/lib/include/sun4.md/machparam.h
sun4.md/wishCmd.o: /sprite/lib/include/sun4.md/limits.h
sun4.md/wishCmd.o: /sprite/lib/include/X11/Xutil.h
sun4.md/wishCmd.o: /sprite/lib/include/cmd.h
sun4.md/wishCmd.o: /sprite/lib/include/stdio.h
sun4.md/wishCmd.o: /sprite/lib/include/mx.h
sun4.md/wishCmd.o: /sprite/lib/include/tcl.h
sun4.md/wishDisplay.o: wishDisplay.c
sun4.md/wishDisplay.o: /sprite/lib/include/sys/types.h
sun4.md/wishDisplay.o: /sprite/lib/include/sys/stat.h
sun4.md/wishDisplay.o: /sprite/lib/include/time.h
sun4.md/wishDisplay.o: /sprite/lib/include/sys/dir.h
sun4.md/wishDisplay.o: /sprite/lib/include/string.h
sun4.md/wishDisplay.o: /sprite/lib/include/sx.h
sun4.md/wishDisplay.o: /sprite/lib/include/X11/Xlib.h
sun4.md/wishDisplay.o: /sprite/lib/include/X11/X.h
sun4.md/wishDisplay.o: /sprite/lib/include/util.h monitorClient.h
sun4.md/wishDisplay.o: wishInt.h /sprite/lib/include/sys/param.h
sun4.md/wishDisplay.o: /sprite/lib/include/sys/signal.h
sun4.md/wishDisplay.o: /sprite/lib/include/sun4.md/machparam.h
sun4.md/wishDisplay.o: /sprite/lib/include/sun4.md/limits.h
sun4.md/wishDisplay.o: /sprite/lib/include/X11/Xutil.h
sun4.md/wishDisplay.o: /sprite/lib/include/cmd.h
sun4.md/wishDisplay.o: /sprite/lib/include/stdio.h
sun4.md/wishDisplay.o: /sprite/lib/include/mx.h
sun4.md/wishDisplay.o: /sprite/lib/include/tcl.h flat.cursor
sun4.md/wishDisplay.o: wait.cursor
sun4.md/wishGarbage.o: wishGarbage.c
sun4.md/wishGarbage.o: /sprite/lib/include/X11/Xlib.h
sun4.md/wishGarbage.o: /sprite/lib/include/sys/types.h
sun4.md/wishGarbage.o: /sprite/lib/include/X11/X.h wishInt.h
sun4.md/wishGarbage.o: /sprite/lib/include/sys/param.h
sun4.md/wishGarbage.o: /sprite/lib/include/sys/signal.h
sun4.md/wishGarbage.o: /sprite/lib/include/sun4.md/machparam.h
sun4.md/wishGarbage.o: /sprite/lib/include/sun4.md/limits.h
sun4.md/wishGarbage.o: /sprite/lib/include/X11/Xutil.h
sun4.md/wishGarbage.o: /sprite/lib/include/cmd.h
sun4.md/wishGarbage.o: /sprite/lib/include/stdio.h
sun4.md/wishGarbage.o: /sprite/lib/include/mx.h
sun4.md/wishGarbage.o: /sprite/lib/include/tcl.h
sun4.md/wishGather.o: wishGather.c
sun4.md/wishGather.o: /sprite/lib/include/sys/types.h
sun4.md/wishGather.o: /sprite/lib/include/sys/stat.h
sun4.md/wishGather.o: /sprite/lib/include/sys/dir.h
sun4.md/wishGather.o: /sprite/lib/include/errno.h
sun4.md/wishGather.o: /sprite/lib/include/sx.h
sun4.md/wishGather.o: /sprite/lib/include/X11/Xlib.h
sun4.md/wishGather.o: /sprite/lib/include/X11/X.h
sun4.md/wishGather.o: /sprite/lib/include/string.h
sun4.md/wishGather.o: /sprite/lib/include/util.h wishInt.h
sun4.md/wishGather.o: /sprite/lib/include/sys/param.h
sun4.md/wishGather.o: /sprite/lib/include/sys/signal.h
sun4.md/wishGather.o: /sprite/lib/include/sun4.md/machparam.h
sun4.md/wishGather.o: /sprite/lib/include/sun4.md/limits.h
sun4.md/wishGather.o: /sprite/lib/include/X11/Xutil.h
sun4.md/wishGather.o: /sprite/lib/include/cmd.h
sun4.md/wishGather.o: /sprite/lib/include/stdio.h
sun4.md/wishGather.o: /sprite/lib/include/mx.h
sun4.md/wishGather.o: /sprite/lib/include/tcl.h
sun4.md/wishHandlers.o: wishHandlers.c
sun4.md/wishHandlers.o: /sprite/lib/include/sys/types.h
sun4.md/wishHandlers.o: /sprite/lib/include/sys/stat.h
sun4.md/wishHandlers.o: /sprite/lib/include/string.h
sun4.md/wishHandlers.o: /sprite/lib/include/util.h monitorClient.h
sun4.md/wishHandlers.o: wishInt.h /sprite/lib/include/sys/param.h
sun4.md/wishHandlers.o: /sprite/lib/include/sys/signal.h
sun4.md/wishHandlers.o: /sprite/lib/include/sun4.md/machparam.h
sun4.md/wishHandlers.o: /sprite/lib/include/sun4.md/limits.h
sun4.md/wishHandlers.o: /sprite/lib/include/X11/Xutil.h
sun4.md/wishHandlers.o: /sprite/lib/include/cmd.h
sun4.md/wishHandlers.o: /sprite/lib/include/stdio.h
sun4.md/wishHandlers.o: /sprite/lib/include/mx.h
sun4.md/wishHandlers.o: /sprite/lib/include/tcl.h
sun4.md/wishMain.o: wishMain.c
sun4.md/wishMain.o: /sprite/lib/include/X11/Xlib.h
sun4.md/wishMain.o: /sprite/lib/include/sys/types.h
sun4.md/wishMain.o: /sprite/lib/include/X11/X.h
sun4.md/wishMain.o: /sprite/lib/include/X11/Xutil.h
sun4.md/wishMain.o: /sprite/lib/include/sys/time.h
sun4.md/wishMain.o: /sprite/lib/include/string.h
sun4.md/wishMain.o: /sprite/lib/include/fs.h
sun4.md/wishMain.o: /sprite/lib/include/spriteTime.h
sun4.md/wishMain.o: /sprite/lib/include/sprite.h
sun4.md/wishMain.o: /sprite/lib/include/proc.h
sun4.md/wishMain.o: /sprite/lib/include/sig.h
sun4.md/wishMain.o: /sprite/lib/include/sun4.md/kernel/mach.h
sun4.md/wishMain.o: /sprite/lib/include/sun4.md/kernel/devAddrs.h
sun4.md/wishMain.o: /sprite/lib/include/sun4.md/kernel/machConst.h
sun4.md/wishMain.o: /sprite/lib/include/sun4.md/kernel/vmSunConst.h
sun4.md/wishMain.o: /sprite/lib/include/kernel/sysSysCall.h
sun4.md/wishMain.o: /sprite/lib/include/kernel/sys.h
sun4.md/wishMain.o: /sprite/lib/include/kernel/user/sys.h
sun4.md/wishMain.o: /sprite/lib/include/status.h
sun4.md/wishMain.o: /sprite/lib/include/fmt.h
sun4.md/wishMain.o: /sprite/lib/include/sun4.md/kernel/machSig.h
sun4.md/wishMain.o: /sprite/lib/include/kernel/sig.h
sun4.md/wishMain.o: /sprite/lib/include/vm.h
sun4.md/wishMain.o: /sprite/lib/include/sun4.md/vmMach.h
sun4.md/wishMain.o: /sprite/lib/include/vmStat.h
sun4.md/wishMain.o: /sprite/lib/include/sun4.md/kernel/vmMachStat.h
sun4.md/wishMain.o: /sprite/lib/include/sx.h
sun4.md/wishMain.o: /sprite/lib/include/util.h monitorClient.h
sun4.md/wishMain.o: wishInt.h /sprite/lib/include/sys/param.h
sun4.md/wishMain.o: /sprite/lib/include/sys/signal.h
sun4.md/wishMain.o: /sprite/lib/include/sun4.md/machparam.h
sun4.md/wishMain.o: /sprite/lib/include/sun4.md/limits.h
sun4.md/wishMain.o: /sprite/lib/include/cmd.h
sun4.md/wishMain.o: /sprite/lib/include/stdio.h
sun4.md/wishMain.o: /sprite/lib/include/mx.h
sun4.md/wishMain.o: /sprite/lib/include/tcl.h
sun4.md/wishMain.o: /sprite/lib/include/signal.h
sun4.md/wishScroll.o: wishScroll.c
sun4.md/wishScroll.o: /sprite/lib/include/string.h
sun4.md/wishScroll.o: /sprite/lib/include/sx.h
sun4.md/wishScroll.o: /sprite/lib/include/X11/Xlib.h
sun4.md/wishScroll.o: /sprite/lib/include/sys/types.h
sun4.md/wishScroll.o: /sprite/lib/include/X11/X.h wishInt.h
sun4.md/wishScroll.o: /sprite/lib/include/sys/param.h
sun4.md/wishScroll.o: /sprite/lib/include/sys/signal.h
sun4.md/wishScroll.o: /sprite/lib/include/sun4.md/machparam.h
sun4.md/wishScroll.o: /sprite/lib/include/sun4.md/limits.h
sun4.md/wishScroll.o: /sprite/lib/include/X11/Xutil.h
sun4.md/wishScroll.o: /sprite/lib/include/cmd.h
sun4.md/wishScroll.o: /sprite/lib/include/stdio.h
sun4.md/wishScroll.o: /sprite/lib/include/mx.h
sun4.md/wishScroll.o: /sprite/lib/include/tcl.h
sun4.md/wishSelect.o: wishSelect.c
sun4.md/wishSelect.o: /sprite/lib/include/sx.h
sun4.md/wishSelect.o: /sprite/lib/include/X11/Xlib.h
sun4.md/wishSelect.o: /sprite/lib/include/sys/types.h
sun4.md/wishSelect.o: /sprite/lib/include/X11/X.h
sun4.md/wishSelect.o: /sprite/lib/include/string.h wishInt.h
sun4.md/wishSelect.o: /sprite/lib/include/sys/param.h
sun4.md/wishSelect.o: /sprite/lib/include/sys/signal.h
sun4.md/wishSelect.o: /sprite/lib/include/sun4.md/machparam.h
sun4.md/wishSelect.o: /sprite/lib/include/sun4.md/limits.h
sun4.md/wishSelect.o: /sprite/lib/include/X11/Xutil.h
sun4.md/wishSelect.o: /sprite/lib/include/cmd.h
sun4.md/wishSelect.o: /sprite/lib/include/stdio.h
sun4.md/wishSelect.o: /sprite/lib/include/mx.h
sun4.md/wishSelect.o: /sprite/lib/include/tcl.h
sun4.md/wishUtils.o: wishUtils.c
sun4.md/wishUtils.o: /sprite/lib/include/string.h
sun4.md/wishUtils.o: /sprite/lib/include/sx.h
sun4.md/wishUtils.o: /sprite/lib/include/X11/Xlib.h
sun4.md/wishUtils.o: /sprite/lib/include/sys/types.h
sun4.md/wishUtils.o: /sprite/lib/include/X11/X.h
sun4.md/wishUtils.o: /sprite/lib/include/util.h wishInt.h
sun4.md/wishUtils.o: /sprite/lib/include/sys/param.h
sun4.md/wishUtils.o: /sprite/lib/include/sys/signal.h
sun4.md/wishUtils.o: /sprite/lib/include/sun4.md/machparam.h
sun4.md/wishUtils.o: /sprite/lib/include/sun4.md/limits.h
sun4.md/wishUtils.o: /sprite/lib/include/X11/Xutil.h
sun4.md/wishUtils.o: /sprite/lib/include/cmd.h
sun4.md/wishUtils.o: /sprite/lib/include/stdio.h
sun4.md/wishUtils.o: /sprite/lib/include/mx.h
sun4.md/wishUtils.o: /sprite/lib/include/tcl.h
