# DO NOT DELETE THIS LINE -- make depend depends on it.

ds3100.md/adduser.o: adduser.c
ds3100.md/adduser.o: common.h /sprite/lib/include/cfuncproto.h
ds3100.md/adduser.o: /sprite/lib/include/pwd.h
ds3100.md/adduser.o: /sprite/lib/include/sprite.h
ds3100.md/adduser.o: /sprite/lib/include/assert.h
ds3100.md/adduser.o: /sprite/lib/include/bstring.h
ds3100.md/adduser.o: /sprite/lib/include/ctype.h
ds3100.md/adduser.o: /sprite/lib/include/errno.h
ds3100.md/adduser.o: /sprite/lib/include/fcntl.h
ds3100.md/adduser.o: /sprite/lib/include/grp.h
ds3100.md/adduser.o: /sprite/lib/include/signal.h
ds3100.md/adduser.o: /sprite/lib/include/machSignal.h
ds3100.md/adduser.o: /sprite/lib/include/stdio.h
ds3100.md/adduser.o: /sprite/lib/include/stdlib.h
ds3100.md/adduser.o: /sprite/lib/include/string.h
ds3100.md/adduser.o: /sprite/lib/include/sys/file.h
ds3100.md/adduser.o: /sprite/lib/include/sys/ioctl.h
ds3100.md/adduser.o: /sprite/lib/include/sys/ttychars.h
ds3100.md/adduser.o: /sprite/lib/include/sys/ttydev.h
ds3100.md/adduser.o: /sprite/lib/include/sys/fb.h
ds3100.md/adduser.o: /sprite/lib/include/sys/param.h
ds3100.md/adduser.o: /sprite/lib/include/sys/types.h
ds3100.md/adduser.o: /sprite/lib/include/ds3100.md/machparam.h
ds3100.md/adduser.o: /sprite/lib/include/machine/limits.h
ds3100.md/adduser.o: /sprite/lib/include/sys/stat.h
ds3100.md/adduser.o: /sprite/lib/include/sys/wait.h
ds3100.md/adduser.o: /sprite/lib/include/machine/machparam.h
ds3100.md/adduser.o: /sprite/lib/include/unistd.h
ds3100.md/common.o: common.c
ds3100.md/common.o: common.h /sprite/lib/include/cfuncproto.h
ds3100.md/common.o: /sprite/lib/include/pwd.h
ds3100.md/common.o: /sprite/lib/include/sprite.h
ds3100.md/common.o: /sprite/lib/include/ctype.h
ds3100.md/common.o: /sprite/lib/include/errno.h
ds3100.md/common.o: /sprite/lib/include/fcntl.h
ds3100.md/common.o: /sprite/lib/include/stdio.h
ds3100.md/common.o: /sprite/lib/include/stdlib.h
ds3100.md/common.o: /sprite/lib/include/string.h
ds3100.md/common.o: /sprite/lib/include/sys/ioctl.h
ds3100.md/common.o: /sprite/lib/include/sys/ttychars.h
ds3100.md/common.o: /sprite/lib/include/sys/ttydev.h
ds3100.md/common.o: /sprite/lib/include/sys/fb.h
ds3100.md/common.o: /sprite/lib/include/sys/param.h
ds3100.md/common.o: /sprite/lib/include/sys/types.h
ds3100.md/common.o: /sprite/lib/include/signal.h
ds3100.md/common.o: /sprite/lib/include/machSignal.h
ds3100.md/common.o: /sprite/lib/include/ds3100.md/machparam.h
ds3100.md/common.o: /sprite/lib/include/machine/limits.h
ds3100.md/common.o: /sprite/lib/include/sys/wait.h
ds3100.md/common.o: /sprite/lib/include/machine/machparam.h
ds3100.md/common.o: /sprite/lib/include/time.h
ds3100.md/common.o: /sprite/lib/include/unistd.h
