# DO NOT DELETE THIS LINE -- make depend depends on it.

symm.md/loadavg.o: loadavg.c
symm.md/loadavg.o: /sprite/lib/include/sprite.h
symm.md/loadavg.o: /sprite/lib/include/cfuncproto.h
symm.md/loadavg.o: /sprite/lib/include/stdio.h
symm.md/loadavg.o: /sprite/lib/include/stdlib.h
symm.md/loadavg.o: /sprite/lib/include/mig.h
symm.md/loadavg.o: /sprite/lib/include/fs.h
symm.md/loadavg.o: /sprite/lib/include/spriteTime.h
symm.md/loadavg.o: /sprite/lib/include/kernel/procTypes.h
symm.md/loadavg.o: /sprite/lib/include/kernel/proc.h
symm.md/loadavg.o: /sprite/lib/include/kernel/sync.h
symm.md/loadavg.o: /sprite/lib/include/list.h
symm.md/loadavg.o: /sprite/lib/include/kernel/syncTypes.h
symm.md/loadavg.o: /sprite/lib/include/kernel/syncLock.h
symm.md/loadavg.o: /sprite/lib/include/kernel/user/sync.h
symm.md/loadavg.o: kernel/machTypes.h
symm.md/loadavg.o: /sprite/lib/include/symm.md/kernel/mach.h
symm.md/loadavg.o: /sprite/lib/include/symm.md/kernel/machConst.h
symm.md/loadavg.o: /sprite/lib/include/symm.md/kernel/vmSymConst.h
symm.md/loadavg.o: /sprite/lib/include/symm.md/kernel/vmSymPTE.h
symm.md/loadavg.o: /sprite/lib/include/symm.md/kernel/machTrap.h
symm.md/loadavg.o: /sprite/lib/include/symm.md/kernel/machFpu.h
symm.md/loadavg.o: /sprite/lib/include/sys/types.h
symm.md/loadavg.o: /sprite/lib/include/fmt.h
symm.md/loadavg.o: /sprite/lib/include/kernel/timer.h
symm.md/loadavg.o: /sprite/lib/include/symm.md/kernel/timerTick.h
symm.md/loadavg.o: /sprite/lib/include/symm.md/kernel/timerMach.h
symm.md/loadavg.o: /sprite/lib/include/kernel/sig.h
symm.md/loadavg.o: /sprite/lib/include/kernel/sigTypes.h
symm.md/loadavg.o: /sprite/lib/include/kernel/rpc.h
symm.md/loadavg.o: /sprite/lib/include/kernel/net.h
symm.md/loadavg.o: /sprite/lib/include/kernel/user/net.h
symm.md/loadavg.o: /sprite/lib/include/symm.md/machparam.h
symm.md/loadavg.o: /sprite/lib/include/symm.md/limits.h
symm.md/loadavg.o: /sprite/lib/include/kernel/user/netEther.h
symm.md/loadavg.o: /sprite/lib/include/kernel/user/netInet.h
symm.md/loadavg.o: /sprite/lib/include/kernel/user/netUltra.h
symm.md/loadavg.o: /sprite/lib/include/kernel/user/sprite.h
symm.md/loadavg.o: /sprite/lib/include/kernel/netTypes.h
symm.md/loadavg.o: /sprite/lib/include/netEther.h
symm.md/loadavg.o: /sprite/lib/include/kernel/netRoute.h
symm.md/loadavg.o: /sprite/lib/include/netInet.h
symm.md/loadavg.o: /sprite/lib/include/kernel/sys.h
symm.md/loadavg.o: /sprite/lib/include/kernel/user/sys.h
symm.md/loadavg.o: /sprite/lib/include/status.h
symm.md/loadavg.o: /sprite/lib/include/kernel/rpcCall.h
symm.md/loadavg.o: /sprite/lib/include/kernel/procMigrate.h
symm.md/loadavg.o: /sprite/lib/include/kernel/trace.h
symm.md/loadavg.o: /sprite/lib/include/option.h
symm.md/loadavg.o: /sprite/lib/include/host.h
symm.md/loadavg.o: /sprite/lib/include/netinet/in.h
symm.md/loadavg.o: /sprite/lib/include/syslog.h
symm.md/loadavg.o: /sprite/lib/include/sys/time.h
symm.md/loadavg.o: /sprite/lib/include/sysStats.h
