# DO NOT DELETE THIS LINE -- make depend depends on it.

sun3.md/mklfs.o: mklfs.c
sun3.md/mklfs.o: /sprite/lib/include/sprite.h
sun3.md/mklfs.o: /sprite/lib/include/cfuncproto.h
sun3.md/mklfs.o: /sprite/lib/include/sun3.md/varargs.h
sun3.md/mklfs.o: /sprite/lib/include/stdio.h
sun3.md/mklfs.o: /sprite/lib/include/option.h
sun3.md/mklfs.o: /sprite/lib/include/stddef.h
sun3.md/mklfs.o: /sprite/lib/include/stdlib.h
sun3.md/mklfs.o: /sprite/lib/include/time.h
sun3.md/mklfs.o: /sprite/lib/include/unistd.h
sun3.md/mklfs.o: /sprite/lib/include/sys/types.h
sun3.md/mklfs.o: /sprite/lib/include/string.h
sun3.md/mklfs.o: /sprite/lib/include/sys/file.h
sun3.md/mklfs.o: /sprite/lib/include/sys/stat.h
sun3.md/mklfs.o: /sprite/lib/include/sys/time.h
sun3.md/mklfs.o: /sprite/lib/include/bstring.h
sun3.md/mklfs.o: /sprite/lib/include/fs.h
sun3.md/mklfs.o: /sprite/lib/include/spriteTime.h
sun3.md/mklfs.o: /sprite/lib/include/kernel/procTypes.h
sun3.md/mklfs.o: /sprite/lib/include/kernel/fs.h
sun3.md/mklfs.o: /sprite/lib/include/kernel/sys.h
sun3.md/mklfs.o: /sprite/lib/include/sys.h
sun3.md/mklfs.o: /sprite/lib/include/status.h
sun3.md/mklfs.o: /sprite/lib/include/kernel/syncTypes.h
sun3.md/mklfs.o: /sprite/lib/include/sync.h
sun3.md/mklfs.o: /sprite/lib/include/kernel/syncLock.h
sun3.md/mklfs.o: /sprite/lib/include/list.h
sun3.md/mklfs.o: /sprite/lib/include/sun3.md/kernel/machTypes.h
sun3.md/mklfs.o: /sprite/lib/include/sun3.md/kernel/devAddrs.h
sun3.md/mklfs.o: /sprite/lib/include/sun3.md/kernel/machConst.h
sun3.md/mklfs.o: /sprite/lib/include/sun3.md/kernel/vmSunConst.h
sun3.md/mklfs.o: /sprite/lib/include/fmt.h
sun3.md/mklfs.o: /sprite/lib/include/proc.h
sun3.md/mklfs.o: /sprite/lib/include/kernel/sigTypes.h
sun3.md/mklfs.o: /sprite/lib/include/sig.h
sun3.md/mklfs.o: /sprite/lib/include/vmTypes.h
sun3.md/mklfs.o: /sprite/lib/include/kernel/dev.h
sun3.md/mklfs.o: /sprite/lib/include/kernel/devSyslog.h
sun3.md/mklfs.o: /sprite/lib/include/user/fs.h
sun3.md/mklfs.o: /sprite/lib/include/sysStats.h
sun3.md/mklfs.o: /sprite/lib/include/kernel/fsdm.h
sun3.md/mklfs.o: /sprite/lib/include/kernel/fslcl.h
sun3.md/mklfs.o: /sprite/lib/include/kernel/devDiskLabel.h
sun3.md/mklfs.o: /sprite/lib/include/kernel/lfsDesc.h
sun3.md/mklfs.o: /sprite/lib/include/kernel/lfsDescMap.h
sun3.md/mklfs.o: /sprite/lib/include/kernel/lfsStableMem.h
sun3.md/mklfs.o: /sprite/lib/include/kernel/lfsFileLayout.h
sun3.md/mklfs.o: /sprite/lib/include/kernel/lfsSegLayout.h
sun3.md/mklfs.o: /sprite/lib/include/kernel/lfsSuperBlock.h
sun3.md/mklfs.o: /sprite/lib/include/kernel/lfsUsageArray.h
sun3.md/mklfs.o: /sprite/lib/include/kernel/lfsStats.h
sun3.md/mklfs.o: getMachineInfo.h /sprite/lib/include/disk.h
sun3.md/mklfs.o: /sprite/lib/include/kernel/ofs.h
sun3.md/mklfs.o: /sprite/lib/include/kernel/devBlockDevice.h
sun3.md/getMachineInfo.o: getMachineInfo.c
sun3.md/getMachineInfo.o: /sprite/lib/include/sprite.h
sun3.md/getMachineInfo.o: /sprite/lib/include/cfuncproto.h
sun3.md/getMachineInfo.o: /sprite/lib/include/sun3.md/varargs.h
sun3.md/getMachineInfo.o: /sprite/lib/include/stdio.h
sun3.md/getMachineInfo.o: /sprite/lib/include/stdlib.h
sun3.md/getMachineInfo.o: getMachineInfo.h
sun3.md/getMachineInfo.o: /sprite/lib/include/kernel/fs.h
sun3.md/getMachineInfo.o: /sprite/lib/include/kernel/sys.h
sun3.md/getMachineInfo.o: /sprite/lib/include/sys.h
sun3.md/getMachineInfo.o: /sprite/lib/include/status.h
sun3.md/getMachineInfo.o: /sprite/lib/include/spriteTime.h
sun3.md/getMachineInfo.o: /sprite/lib/include/kernel/syncTypes.h
sun3.md/getMachineInfo.o: /sprite/lib/include/sync.h
sun3.md/getMachineInfo.o: /sprite/lib/include/kernel/procTypes.h
sun3.md/getMachineInfo.o: /sprite/lib/include/kernel/syncLock.h
sun3.md/getMachineInfo.o: /sprite/lib/include/list.h
sun3.md/getMachineInfo.o: /sprite/lib/include/sun3.md/kernel/machTypes.h
sun3.md/getMachineInfo.o: /sprite/lib/include/sun3.md/kernel/devAddrs.h
sun3.md/getMachineInfo.o: /sprite/lib/include/sun3.md/kernel/machConst.h
sun3.md/getMachineInfo.o: /sprite/lib/include/sun3.md/kernel/vmSunConst.h
sun3.md/getMachineInfo.o: /sprite/lib/include/fmt.h
sun3.md/getMachineInfo.o: /sprite/lib/include/proc.h
sun3.md/getMachineInfo.o: /sprite/lib/include/kernel/sigTypes.h
sun3.md/getMachineInfo.o: /sprite/lib/include/sig.h
sun3.md/getMachineInfo.o: /sprite/lib/include/vmTypes.h
sun3.md/getMachineInfo.o: /sprite/lib/include/fs.h
sun3.md/getMachineInfo.o: /sprite/lib/include/kernel/fsStat.h
sun3.md/getMachineInfo.o: /sprite/lib/include/fsCmd.h
