# DO NOT DELETE THIS LINE -- make depend depends on it.

ds3100.md/checkdir.o: checkdir.c
ds3100.md/checkdir.o: /sprite/lib/include/option.h
ds3100.md/checkdir.o: /sprite/lib/include/cfuncproto.h fscheck.h
ds3100.md/checkdir.o: /sprite/lib/include/disk.h
ds3100.md/checkdir.o: /sprite/lib/include/sys/types.h
ds3100.md/checkdir.o: /sprite/lib/include/ds3100.md/varargs.h
ds3100.md/checkdir.o: /sprite/lib/include/stdio.h
ds3100.md/checkdir.o: /sprite/lib/include/errno.h
ds3100.md/checkdir.o: /sprite/lib/include/stdlib.h
ds3100.md/checkdir.o: /sprite/lib/include/time.h
ds3100.md/checkdir.o: /sprite/lib/include/sys/time.h
ds3100.md/checkdir.o: /sprite/lib/include/list.h
ds3100.md/checkdir.o: /sprite/lib/include/sprite.h
ds3100.md/checkdir.o: /sprite/lib/include/string.h
ds3100.md/checkdir.o: /sprite/lib/include/ctype.h
ds3100.md/fscheck.o: fscheck.c
ds3100.md/fscheck.o: /sprite/lib/include/option.h
ds3100.md/fscheck.o: /sprite/lib/include/cfuncproto.h
ds3100.md/fscheck.o: /sprite/lib/include/list.h
ds3100.md/fscheck.o: /sprite/lib/include/sprite.h fscheck.h
ds3100.md/fscheck.o: /sprite/lib/include/disk.h
ds3100.md/fscheck.o: /sprite/lib/include/sys/types.h
ds3100.md/fscheck.o: /sprite/lib/include/ds3100.md/varargs.h
ds3100.md/fscheck.o: /sprite/lib/include/stdio.h
ds3100.md/fscheck.o: /sprite/lib/include/errno.h
ds3100.md/fscheck.o: /sprite/lib/include/stdlib.h
ds3100.md/fscheck.o: /sprite/lib/include/time.h
ds3100.md/fscheck.o: /sprite/lib/include/sys/time.h
ds3100.md/fscheck.o: /sprite/lib/include/string.h
ds3100.md/fscheck.o: /sprite/lib/include/host.h
ds3100.md/fscheck.o: /sprite/lib/include/netinet/in.h
ds3100.md/fscheck.o: /sprite/lib/include/ds3100.md/machparam.h
ds3100.md/fscheck.o: /sprite/lib/include/machine/limits.h
ds3100.md/fscheck.o: /sprite/lib/include/sys/stat.h
ds3100.md/fscheck.o: /sprite/lib/include/net.h
ds3100.md/fscheck.o: /sprite/lib/include/machparam.h
ds3100.md/fscheck.o: /sprite/lib/include/netEther.h
ds3100.md/fscheck.o: /sprite/lib/include/netInet.h
ds3100.md/fscheck.o: /sprite/lib/include/netUltra.h
ds3100.md/fscheck.o: /sprite/lib/include/netFDDI.h
ds3100.md/fscheck.o: /sprite/lib/include/sys/file.h
ds3100.md/fsUtils.o: fsUtils.c
ds3100.md/fsUtils.o: /sprite/lib/include/option.h
ds3100.md/fsUtils.o: /sprite/lib/include/cfuncproto.h
ds3100.md/fsUtils.o: /sprite/lib/include/list.h
ds3100.md/fsUtils.o: /sprite/lib/include/sprite.h fscheck.h
ds3100.md/fsUtils.o: /sprite/lib/include/disk.h
ds3100.md/fsUtils.o: /sprite/lib/include/sys/types.h
ds3100.md/fsUtils.o: /sprite/lib/include/ds3100.md/varargs.h
ds3100.md/fsUtils.o: /sprite/lib/include/stdio.h
ds3100.md/fsUtils.o: /sprite/lib/include/errno.h
ds3100.md/fsUtils.o: /sprite/lib/include/stdlib.h
ds3100.md/fsUtils.o: /sprite/lib/include/time.h
ds3100.md/fsUtils.o: /sprite/lib/include/sys/time.h
ds3100.md/fsUtils.o: /sprite/lib/include/string.h
ds3100.md/fsUtils.o: /sprite/lib/include/host.h
ds3100.md/fsUtils.o: /sprite/lib/include/netinet/in.h
ds3100.md/fsUtils.o: /sprite/lib/include/ds3100.md/machparam.h
ds3100.md/fsUtils.o: /sprite/lib/include/machine/limits.h
ds3100.md/fsUtils.o: /sprite/lib/include/sys/stat.h
ds3100.md/fsUtils.o: /sprite/lib/include/net.h
ds3100.md/fsUtils.o: /sprite/lib/include/machparam.h
ds3100.md/fsUtils.o: /sprite/lib/include/netEther.h
ds3100.md/fsUtils.o: /sprite/lib/include/netInet.h
ds3100.md/fsUtils.o: /sprite/lib/include/netUltra.h
ds3100.md/fsUtils.o: /sprite/lib/include/netFDDI.h
ds3100.md/fsUtils.o: /sprite/lib/include/sys/file.h
ds3100.md/fsUtils.o: /sprite/lib/include/sysStats.h
ds3100.md/fsUtils.o: /sprite/lib/include/sys/param.h
ds3100.md/fsUtils.o: /sprite/lib/include/signal.h
