
/*
The hidden information for an asymbol is:
*/

 typedef struct coff_ptr_struct
 {

/*
Remembers the offset from the first symbol in the file for this
symbol. Generated by @code{coff_renumber_symbols}.
*/

   unsigned int offset;

/*
Should the tag field of this symbol be renumbered.
Created by @code{coff_pointerize_aux}.
*/

   char fix_tag;

/*
Should the endidx field of this symbol be renumbered.
Created by @code{coff_pointerize_aux}.
*/

   char fix_end;

/*
The container for the symbol structure as read and translated from the file.
*/

   union {
     union internal_auxent auxent;
     struct internal_syment syment;
   } u;
 } combined_entry_type;

/*

Each canonical asymbol really looks like this:
*/

 typedef struct coff_symbol_struct
 {

/*
The actual symbol which the rest of BFD works with
*/

   asymbol symbol;

/*
A pointer to the hidden information for this symbol
*/

   combined_entry_type *native;

/*
A pointer to the linenumber information for this symbol
*/

   struct lineno_cache_entry *lineno;
 } coff_symbol_type;

/*
*/

