/* bfd_core_file_failing_command
Returns a read-only string explaining what program was running when
it failed and produced the core file being read
*/

 PROTO(CONST char *, bfd_core_file_failing_command, (bfd *));

/*

 bfd_core_file_failing_signal
Returns the signal number which caused the core dump which generated
the file the BFD is attached to.
*/

 PROTO(int, bfd_core_file_failing_signal, (bfd *));

/*

 core_file_matches_executable_p
Returns @code{true} if the core file attached to @var{core_bfd} was
generated by a run of the executable file attached to @var{exec_bfd},
or else @code{false}.
*/
 PROTO(boolean, core_file_matches_executable_p,
    (bfd *core_bfd, bfd *exec_bfd));

/*
*/
