#!/bin/csh -f  
if ($#argv != 1) then
    echo "Usage: $0 versionNumber"
    exit
endif
set insDir = '/sprite/src/kernel/Installed'
set version = $1
if (-e $insDir/$version) then
    echo "$insDir/$version already exists. Skipping snapshot of sources."
    exit
endif

mkdir $insDir/$version
foreach i (`cat /sprite/src/kernel/Modules` raid.null)
    mkdir $insDir/$version/$i
    switch ($i)
        #
	# The following modules should have the target of a symbolic link
	# copied, not the link itself
	#
	case 'libc'
	    set updateOptions = $updateOptions '-l'
	    breaksw
	default
	    set updateOptions = ""
	    breaksw
    endsw
    update $updateOptions $insDir/$i $insDir/$version/$i
end

#
# Snapshot the kernel and user include files.  We have to change the
# 'kernel' and 'user' links, since they are absolute in the 
# uninstalled sources.
#

mkdir $insDir/$version/include
update /sprite/lib/include $insDir/$version/include
pushd $insDir/$version/include
rm user
rm kernel
ln -s ../Include kernel
foreach i (*.md)
    pushd $i
    rm kernel
    ln -s ../../Include/$i kernel
    popd
end
popd

mkdir $insDir/$version/Include
update /sprite/src/kernel/Include $insDir/$version/Include
pushd $insDir/$version/Include
rm user
ln -s ../include user
foreach i (*.md)
    pushd $i
    rm user
    ln -s ../../include/$i user
    popd
end
popd


