# DO NOT DELETE THIS LINE -- make depend depends on it.

sun4.md/arpd.o: arpd.c
sun4.md/arpd.o: /sprite/lib/include/stdio.h
sun4.md/arpd.o: /sprite/lib/include/cfuncproto.h
sun4.md/arpd.o: /sprite/lib/include/stdlib.h
sun4.md/arpd.o: /sprite/lib/include/string.h
sun4.md/arpd.o: /sprite/lib/include/errno.h
sun4.md/arpd.o: /sprite/lib/include/host.h
sun4.md/arpd.o: /sprite/lib/include/sys/types.h
sun4.md/arpd.o: /sprite/lib/include/netinet/in.h
sun4.md/arpd.o: /sprite/lib/include/sun4.md/machparam.h
sun4.md/arpd.o: /sprite/lib/include/sun4.md/limits.h
sun4.md/arpd.o: /sprite/lib/include/sys/stat.h
sun4.md/arpd.o: /sprite/lib/include/net.h
sun4.md/arpd.o: /sprite/lib/include/machparam.h
sun4.md/arpd.o: /sprite/lib/include/netEther.h
sun4.md/arpd.o: /sprite/lib/include/netInet.h
sun4.md/arpd.o: /sprite/lib/include/netUltra.h
sun4.md/arpd.o: /sprite/lib/include/netFDDI.h
sun4.md/arpd.o: /sprite/lib/include/sprite.h
sun4.md/arpd.o: /sprite/lib/include/option.h
sun4.md/arpd.o: /sprite/lib/include/sys/socket.h
sun4.md/arpd.o: /sprite/lib/include/net/if_arp.h
sun4.md/arpd.o: /sprite/lib/include/netinet/if_ether.h
sun4.md/arpd.o: /sprite/lib/include/sys/file.h
sun4.md/arpd.o: /sprite/lib/include/sys/param.h
sun4.md/arpd.o: /sprite/lib/include/signal.h
sun4.md/arpd.o: /sprite/lib/include/machSignal.h
sun4.md/arpd.o: /sprite/lib/include/sys/time.h
sun4.md/arpd.o: /sprite/lib/include/time.h
