# DO NOT DELETE THIS LINE -- make depend depends on it.

sun3.md/ctypeBits.po sun3.md/ctypeBits.go sun3.md/ctypeBits.o: ctypeBits.c
sun3.md/ctypeBits.po sun3.md/ctypeBits.go sun3.md/ctypeBits.o: /sprite/lib/include/ctype.h
sun3.md/isalnum.po sun3.md/isalnum.go sun3.md/isalnum.o: isalnum.c
sun3.md/isalnum.po sun3.md/isalnum.go sun3.md/isalnum.o: /sprite/lib/include/ctype.h
sun3.md/isalpha.po sun3.md/isalpha.go sun3.md/isalpha.o: isalpha.c
sun3.md/isalpha.po sun3.md/isalpha.go sun3.md/isalpha.o: /sprite/lib/include/ctype.h
sun3.md/isascii.po sun3.md/isascii.go sun3.md/isascii.o: isascii.c
sun3.md/isascii.po sun3.md/isascii.go sun3.md/isascii.o: /sprite/lib/include/ctype.h
sun3.md/iscntrl.po sun3.md/iscntrl.go sun3.md/iscntrl.o: iscntrl.c
sun3.md/iscntrl.po sun3.md/iscntrl.go sun3.md/iscntrl.o: /sprite/lib/include/ctype.h
sun3.md/isdigit.po sun3.md/isdigit.go sun3.md/isdigit.o: isdigit.c
sun3.md/isdigit.po sun3.md/isdigit.go sun3.md/isdigit.o: /sprite/lib/include/ctype.h
sun3.md/isgraph.po sun3.md/isgraph.go sun3.md/isgraph.o: isgraph.c
sun3.md/isgraph.po sun3.md/isgraph.go sun3.md/isgraph.o: /sprite/lib/include/ctype.h
sun3.md/islower.po sun3.md/islower.go sun3.md/islower.o: islower.c
sun3.md/islower.po sun3.md/islower.go sun3.md/islower.o: /sprite/lib/include/ctype.h
sun3.md/isprint.po sun3.md/isprint.go sun3.md/isprint.o: isprint.c
sun3.md/isprint.po sun3.md/isprint.go sun3.md/isprint.o: /sprite/lib/include/ctype.h
sun3.md/ispunct.po sun3.md/ispunct.go sun3.md/ispunct.o: ispunct.c
sun3.md/ispunct.po sun3.md/ispunct.go sun3.md/ispunct.o: /sprite/lib/include/ctype.h
sun3.md/isspace.po sun3.md/isspace.go sun3.md/isspace.o: isspace.c
sun3.md/isspace.po sun3.md/isspace.go sun3.md/isspace.o: /sprite/lib/include/ctype.h
sun3.md/isupper.po sun3.md/isupper.go sun3.md/isupper.o: isupper.c
sun3.md/isupper.po sun3.md/isupper.go sun3.md/isupper.o: /sprite/lib/include/ctype.h
sun3.md/isxdigit.po sun3.md/isxdigit.go sun3.md/isxdigit.o: isxdigit.c
sun3.md/isxdigit.po sun3.md/isxdigit.go sun3.md/isxdigit.o: /sprite/lib/include/ctype.h
sun3.md/toascii.po sun3.md/toascii.go sun3.md/toascii.o: toascii.c
sun3.md/toascii.po sun3.md/toascii.go sun3.md/toascii.o: /sprite/lib/include/ctype.h
sun3.md/tolower.po sun3.md/tolower.go sun3.md/tolower.o: tolower.c
sun3.md/tolower.po sun3.md/tolower.go sun3.md/tolower.o: /sprite/lib/include/ctype.h
sun3.md/toupper.po sun3.md/toupper.go sun3.md/toupper.o: toupper.c
sun3.md/toupper.po sun3.md/toupper.go sun3.md/toupper.o: /sprite/lib/include/ctype.h
