#
# This file is automatically included by Pmake while it is processing
# Makefile.  Makefile is automatically generated by mkmf, and this file
# provides additional local personalization
#

NAME = vm

#if empty(TM:Mds3100) && empty(TM:Mcleands3100) && empty(TM:Mds5000)
XCFLAGS += -Wall
#endif


#include	<$(SYSMAKEFILE)>
