' $Header: /sprite/src/cmds/kgcore/RCS/kgcore.man,v 1.3 91/05/27 15:01:24 mendel Exp $ SPRITE (Berkeley)
.so \*(]ltmac.sprite
.HS KGCORE cmds
.BS
.SH NAME
kgcore \-  Generate a core dump of a remote Sprite kernel
.SH SYNOPSIS
\fBkgcore\fR \fIoption machine\fR
.SH OPTIONS
.IP "\fB\-o\fI filename\fR" 15
Write the core image to filename rather than the file vmcore.
.IP "\fB\-c\fR" 15
Include the file system block cache in the core dump.
.IP "\fB\-v\fR" 15
Output progress info.
.BE

.SH DESCRIPTION
.PP
The \fBkgcore\fR command is used to make a copy of the kernel memory image of
a Sprite machine. The memory image may be used with \fBkgdb\fR 
to examine the machine's state. 
\fIMachine\fR is the name of a machine
running Sprite. The machine must be in the kernel debugger 
for \fBkgcore\fR to work (see the -d option
of the \fBkmsg\fR command.)
\fBKgcore\fR writes the kernel memory image to the file vmcore unless 
another file name is specified with the \fB\-o\fR option. This file may be
specified as a core image to \fBkgdb\fR.

.SH KEYWORDS
debug, kernel, core, kgdb
