/* Generated automatically by the program `gencodes'
from the machine description file `md'.  */

#ifndef MAX_INSN_CODE

enum insn_code {
  CODE_FOR_cmpsi = 0,
  CODE_FOR_cmpdf = 1,
  CODE_FOR_cmpsf = 3,
  CODE_FOR_tstsi = 5,
  CODE_FOR_tstdf = 24,
  CODE_FOR_tstsf = 26,
  CODE_FOR_seq = 28,
  CODE_FOR_sne = 29,
  CODE_FOR_beq = 36,
  CODE_FOR_bne = 37,
  CODE_FOR_bgt = 38,
  CODE_FOR_bgtu = 39,
  CODE_FOR_blt = 40,
  CODE_FOR_bltu = 41,
  CODE_FOR_bge = 42,
  CODE_FOR_bgeu = 43,
  CODE_FOR_ble = 44,
  CODE_FOR_bleu = 45,
  CODE_FOR_swapsi = 47,
  CODE_FOR_movsi = 48,
  CODE_FOR_movhi = 49,
  CODE_FOR_movqi = 50,
  CODE_FOR_movstrsi = 51,
  CODE_FOR_movdf = 54,
  CODE_FOR_movdi = 55,
  CODE_FOR_movsf = 56,
  CODE_FOR_truncsiqi2 = 57,
  CODE_FOR_trunchiqi2 = 58,
  CODE_FOR_truncsihi2 = 59,
  CODE_FOR_zero_extendhisi2 = 60,
  CODE_FOR_zero_extendqihi2 = 61,
  CODE_FOR_zero_extendqisi2 = 62,
  CODE_FOR_extendhisi2 = 63,
  CODE_FOR_extendqihi2 = 64,
  CODE_FOR_extendqisi2 = 65,
  CODE_FOR_extendsfdf2 = 72,
  CODE_FOR_truncdfsf2 = 73,
  CODE_FOR_floatsisf2 = 75,
  CODE_FOR_floatsidf2 = 77,
  CODE_FOR_fix_truncsfsi2 = 78,
  CODE_FOR_fix_truncdfsi2 = 79,
  CODE_FOR_addsi3 = 80,
  CODE_FOR_subsi3 = 81,
  CODE_FOR_mulsi3 = 82,
  CODE_FOR_umulsi3 = 83,
  CODE_FOR_andsi3 = 90,
  CODE_FOR_andcbsi3 = 91,
  CODE_FOR_iorsi3 = 92,
  CODE_FOR_iorcbsi3 = 93,
  CODE_FOR_xorsi3 = 94,
  CODE_FOR_xorcbsi3 = 95,
  CODE_FOR_negsi2 = 96,
  CODE_FOR_one_cmplsi2 = 97,
  CODE_FOR_adddf3 = 98,
  CODE_FOR_addsf3 = 99,
  CODE_FOR_subdf3 = 100,
  CODE_FOR_subsf3 = 101,
  CODE_FOR_muldf3 = 102,
  CODE_FOR_mulsf3 = 103,
  CODE_FOR_divdf3 = 104,
  CODE_FOR_divsf3 = 105,
  CODE_FOR_negdf2 = 106,
  CODE_FOR_negsf2 = 107,
  CODE_FOR_absdf2 = 108,
  CODE_FOR_abssf2 = 109,
  CODE_FOR_ashlsi3 = 112,
  CODE_FOR_ashrsi3 = 113,
  CODE_FOR_lshrsi3 = 114,
  CODE_FOR_jump = 115,
  CODE_FOR_tablejump = 120,
  CODE_FOR_call = 123,
  CODE_FOR_call_value = 127,
  CODE_FOR_return = 131,
  CODE_FOR_nop = 135,
  CODE_FOR_nothing };

#define MAX_INSN_CODE ((int) CODE_FOR_nothing)
#endif /* MAX_INSN_CODE */
