# DO NOT DELETE THIS LINE -- make depend depends on it.

ds3100.md/loadavg.o: loadavg.c
ds3100.md/loadavg.o: /sprite/lib/include/sprite.h
ds3100.md/loadavg.o: /sprite/lib/include/cfuncproto.h
ds3100.md/loadavg.o: /sprite/lib/include/stdio.h
ds3100.md/loadavg.o: /sprite/lib/include/stdlib.h
ds3100.md/loadavg.o: /sprite/lib/include/mig.h
ds3100.md/loadavg.o: /sprite/lib/include/fs.h
ds3100.md/loadavg.o: /sprite/lib/include/spriteTime.h
ds3100.md/loadavg.o: /sprite/lib/include/kernel/procTypes.h
ds3100.md/loadavg.o: /sprite/lib/include/proc.h
ds3100.md/loadavg.o: /sprite/lib/include/kernel/sigTypes.h
ds3100.md/loadavg.o: /sprite/lib/include/ds3100.md/kernel/machTypes.h
ds3100.md/loadavg.o: /sprite/lib/include/ds3100.md/kernel/machConst.h
ds3100.md/loadavg.o: /sprite/lib/include/ds3100.md/kernel/vmPmaxConst.h
ds3100.md/loadavg.o: /sprite/lib/include/fmt.h
ds3100.md/loadavg.o: /sprite/lib/include/sig.h
ds3100.md/loadavg.o: /sprite/lib/include/vmTypes.h
ds3100.md/loadavg.o: /sprite/lib/include/sync.h
ds3100.md/loadavg.o: /sprite/lib/include/kernel/syncLock.h
ds3100.md/loadavg.o: /sprite/lib/include/list.h
ds3100.md/loadavg.o: /sprite/lib/include/kernel/timer.h
ds3100.md/loadavg.o: /sprite/lib/include/ds3100.md/kernel/timerTick.h
ds3100.md/loadavg.o: /sprite/lib/include/ds3100.md/kernel/timerMach.h
ds3100.md/loadavg.o: /sprite/lib/include/kernel/net.h
ds3100.md/loadavg.o: /sprite/lib/include/net.h
ds3100.md/loadavg.o: /sprite/lib/include/machparam.h
ds3100.md/loadavg.o: /sprite/lib/include/machine/limits.h
ds3100.md/loadavg.o: /sprite/lib/include/netEther.h
ds3100.md/loadavg.o: /sprite/lib/include/netInet.h
ds3100.md/loadavg.o: /sprite/lib/include/netUltra.h
ds3100.md/loadavg.o: /sprite/lib/include/netFDDI.h
ds3100.md/loadavg.o: /sprite/lib/include/kernel/syncTypes.h
ds3100.md/loadavg.o: /sprite/lib/include/kernel/netTypes.h
ds3100.md/loadavg.o: /sprite/lib/include/kernel/fs.h
ds3100.md/loadavg.o: /sprite/lib/include/kernel/sys.h
ds3100.md/loadavg.o: /sprite/lib/include/sys.h
ds3100.md/loadavg.o: /sprite/lib/include/status.h
ds3100.md/loadavg.o: /sprite/lib/include/kernel/netRoute.h
ds3100.md/loadavg.o: /sprite/lib/include/option.h
ds3100.md/loadavg.o: /sprite/lib/include/host.h
ds3100.md/loadavg.o: /sprite/lib/include/sys/types.h
ds3100.md/loadavg.o: /sprite/lib/include/netinet/in.h
ds3100.md/loadavg.o: /sprite/lib/include/sys/stat.h
ds3100.md/loadavg.o: /sprite/lib/include/syslog.h
ds3100.md/loadavg.o: /sprite/lib/include/sys/time.h
ds3100.md/loadavg.o: /sprite/lib/include/time.h
ds3100.md/loadavg.o: /sprite/lib/include/sysStats.h
