# DO NOT DELETE THIS LINE -- make depend depends on it.

sun4.md/Host_ByID.o: Host_ByID.c
sun4.md/Host_ByID.o: /sprite/lib/include/stdio.h
sun4.md/Host_ByID.o: /sprite/lib/include/cfuncproto.h
sun4.md/Host_ByID.o: /sprite/lib/include/host.h
sun4.md/Host_ByID.o: /sprite/lib/include/sys/types.h
sun4.md/Host_ByID.o: /sprite/lib/include/netinet/in.h
sun4.md/Host_ByID.o: /sprite/lib/include/sun4.md/machparam.h
sun4.md/Host_ByID.o: /sprite/lib/include/sun4.md/limits.h
sun4.md/Host_ByID.o: /sprite/lib/include/sys/stat.h
sun4.md/Host_ByID.o: /sprite/lib/include/net.h
sun4.md/Host_ByID.o: /sprite/lib/include/machparam.h
sun4.md/Host_ByID.o: /sprite/lib/include/netEther.h
sun4.md/Host_ByID.o: /sprite/lib/include/netInet.h
sun4.md/Host_ByID.o: /sprite/lib/include/netUltra.h
sun4.md/Host_ByID.o: /sprite/lib/include/netFDDI.h
sun4.md/Host_ByID.o: /sprite/lib/include/sprite.h hostInt.h
sun4.md/Host_ByName.o: Host_ByName.c
sun4.md/Host_ByName.o: /sprite/lib/include/stdio.h
sun4.md/Host_ByName.o: /sprite/lib/include/cfuncproto.h
sun4.md/Host_ByName.o: /sprite/lib/include/host.h
sun4.md/Host_ByName.o: /sprite/lib/include/sys/types.h
sun4.md/Host_ByName.o: /sprite/lib/include/netinet/in.h
sun4.md/Host_ByName.o: /sprite/lib/include/sun4.md/machparam.h
sun4.md/Host_ByName.o: /sprite/lib/include/sun4.md/limits.h
sun4.md/Host_ByName.o: /sprite/lib/include/sys/stat.h
sun4.md/Host_ByName.o: /sprite/lib/include/net.h
sun4.md/Host_ByName.o: /sprite/lib/include/machparam.h
sun4.md/Host_ByName.o: /sprite/lib/include/netEther.h
sun4.md/Host_ByName.o: /sprite/lib/include/netInet.h
sun4.md/Host_ByName.o: /sprite/lib/include/netUltra.h
sun4.md/Host_ByName.o: /sprite/lib/include/netFDDI.h
sun4.md/Host_ByName.o: /sprite/lib/include/sprite.h hostInt.h
sun4.md/Host_ByName.o: /sprite/lib/include/string.h
sun4.md/Host_End.o: Host_End.c
sun4.md/Host_End.o: /sprite/lib/include/stdio.h
sun4.md/Host_End.o: /sprite/lib/include/cfuncproto.h
sun4.md/Host_End.o: /sprite/lib/include/host.h
sun4.md/Host_End.o: /sprite/lib/include/sys/types.h
sun4.md/Host_End.o: /sprite/lib/include/netinet/in.h
sun4.md/Host_End.o: /sprite/lib/include/sun4.md/machparam.h
sun4.md/Host_End.o: /sprite/lib/include/sun4.md/limits.h
sun4.md/Host_End.o: /sprite/lib/include/sys/stat.h
sun4.md/Host_End.o: /sprite/lib/include/net.h
sun4.md/Host_End.o: /sprite/lib/include/machparam.h
sun4.md/Host_End.o: /sprite/lib/include/netEther.h
sun4.md/Host_End.o: /sprite/lib/include/netInet.h
sun4.md/Host_End.o: /sprite/lib/include/netUltra.h
sun4.md/Host_End.o: /sprite/lib/include/netFDDI.h
sun4.md/Host_End.o: /sprite/lib/include/sprite.h hostInt.h
sun4.md/disklabel.o: disklabel.c
sun4.md/disklabel.o: fsmake.h /sprite/lib/include/sprite.h
sun4.md/disklabel.o: /sprite/lib/include/stdio.h
sun4.md/disklabel.o: /sprite/lib/include/cfuncproto.h
sun4.md/disklabel.o: /sprite/lib/include/stdlib.h
sun4.md/disklabel.o: /sprite/lib/include/unistd.h
sun4.md/disklabel.o: /sprite/lib/include/string.h
sun4.md/disklabel.o: /sprite/lib/include/bstring.h
sun4.md/disklabel.o: /sprite/lib/include/sys/types.h
sun4.md/disklabel.o: /sprite/lib/include/sys/file.h
sun4.md/disklabel.o: /sprite/lib/include/sys/dir.h
sun4.md/disklabel.o: /sprite/lib/include/option.h
sun4.md/disklabel.o: /sprite/lib/include/disk.h
sun4.md/disklabel.o: /sprite/lib/include/host.h
sun4.md/disklabel.o: /sprite/lib/include/netinet/in.h
sun4.md/disklabel.o: /sprite/lib/include/sun4.md/machparam.h
sun4.md/disklabel.o: /sprite/lib/include/sun4.md/limits.h
sun4.md/disklabel.o: /sprite/lib/include/sys/stat.h
sun4.md/disklabel.o: /sprite/lib/include/net.h
sun4.md/disklabel.o: /sprite/lib/include/machparam.h
sun4.md/disklabel.o: /sprite/lib/include/netEther.h
sun4.md/disklabel.o: /sprite/lib/include/netInet.h
sun4.md/disklabel.o: /sprite/lib/include/netUltra.h
sun4.md/disklabel.o: /sprite/lib/include/netFDDI.h
sun4.md/disklabel.o: /sprite/lib/include/dev/scsi.h
sun4.md/disklabel.o: /sprite/lib/include/sys/time.h
sun4.md/Host_Next.o: Host_Next.c
sun4.md/Host_Next.o: /sprite/lib/include/stdio.h
sun4.md/Host_Next.o: /sprite/lib/include/cfuncproto.h
sun4.md/Host_Next.o: /sprite/lib/include/sprite.h
sun4.md/Host_Next.o: /sprite/lib/include/ctype.h
sun4.md/Host_Next.o: /sprite/lib/include/host.h
sun4.md/Host_Next.o: /sprite/lib/include/sys/types.h
sun4.md/Host_Next.o: /sprite/lib/include/netinet/in.h
sun4.md/Host_Next.o: /sprite/lib/include/sun4.md/machparam.h
sun4.md/Host_Next.o: /sprite/lib/include/sun4.md/limits.h
sun4.md/Host_Next.o: /sprite/lib/include/sys/stat.h
sun4.md/Host_Next.o: /sprite/lib/include/net.h
sun4.md/Host_Next.o: /sprite/lib/include/machparam.h
sun4.md/Host_Next.o: /sprite/lib/include/netEther.h
sun4.md/Host_Next.o: /sprite/lib/include/netInet.h
sun4.md/Host_Next.o: /sprite/lib/include/netUltra.h
sun4.md/Host_Next.o: /sprite/lib/include/netFDDI.h hostInt.h
sun4.md/Host_Next.o: /sprite/lib/include/stdlib.h
sun4.md/Host_Next.o: /sprite/lib/include/string.h
sun4.md/Host_Next.o: /sprite/lib/include/arpa/inet.h
sun4.md/Host_Start.o: Host_Start.c
sun4.md/Host_Start.o: /sprite/lib/include/stdio.h
sun4.md/Host_Start.o: /sprite/lib/include/cfuncproto.h
sun4.md/Host_Start.o: /sprite/lib/include/host.h
sun4.md/Host_Start.o: /sprite/lib/include/sys/types.h
sun4.md/Host_Start.o: /sprite/lib/include/netinet/in.h
sun4.md/Host_Start.o: /sprite/lib/include/sun4.md/machparam.h
sun4.md/Host_Start.o: /sprite/lib/include/sun4.md/limits.h
sun4.md/Host_Start.o: /sprite/lib/include/sys/stat.h
sun4.md/Host_Start.o: /sprite/lib/include/net.h
sun4.md/Host_Start.o: /sprite/lib/include/machparam.h
sun4.md/Host_Start.o: /sprite/lib/include/netEther.h
sun4.md/Host_Start.o: /sprite/lib/include/netInet.h
sun4.md/Host_Start.o: /sprite/lib/include/netUltra.h
sun4.md/Host_Start.o: /sprite/lib/include/netFDDI.h
sun4.md/Host_Start.o: /sprite/lib/include/sprite.h
sun4.md/diskHeader.o: diskHeader.c
sun4.md/diskHeader.o: /sprite/lib/include/disk.h
sun4.md/diskHeader.o: /sprite/lib/include/string.h
sun4.md/diskHeader.o: /sprite/lib/include/cfuncproto.h
sun4.md/diskHeader.o: /sprite/lib/include/stdio.h
sun4.md/diskHeader.o: /sprite/lib/include/stdlib.h
sun4.md/diskIO.o: diskIO.c
sun4.md/diskIO.o: /sprite/lib/include/disk.h
sun4.md/diskIO.o: /sprite/lib/include/stdio.h
sun4.md/diskIO.o: /sprite/lib/include/cfuncproto.h
sun4.md/diskIO.o: /sprite/lib/include/errno.h
sun4.md/diskIO.o: /sprite/lib/include/sys/file.h
sun4.md/diskPrint.o: diskPrint.c
sun4.md/diskPrint.o: /sprite/lib/include/stdio.h
sun4.md/diskPrint.o: /sprite/lib/include/cfuncproto.h
sun4.md/diskPrint.o: /sprite/lib/include/disk.h
sun4.md/option.o: option.c
sun4.md/option.o: /sprite/lib/include/option.h
sun4.md/option.o: /sprite/lib/include/cfuncproto.h
sun4.md/option.o: /sprite/lib/include/stdio.h
sun4.md/option.o: /sprite/lib/include/stdlib.h
sun4.md/option.o: /sprite/lib/include/strings.h
sun4.md/option.o: /sprite/lib/include/time.h
sun4.md/fsmake.o: fsmake.c
sun4.md/fsmake.o: fsmake.h /sprite/lib/include/sprite.h
sun4.md/fsmake.o: /sprite/lib/include/stdio.h
sun4.md/fsmake.o: /sprite/lib/include/cfuncproto.h
sun4.md/fsmake.o: /sprite/lib/include/stdlib.h
sun4.md/fsmake.o: /sprite/lib/include/unistd.h
sun4.md/fsmake.o: /sprite/lib/include/string.h
sun4.md/fsmake.o: /sprite/lib/include/bstring.h
sun4.md/fsmake.o: /sprite/lib/include/sys/types.h
sun4.md/fsmake.o: /sprite/lib/include/sys/file.h
sun4.md/fsmake.o: /sprite/lib/include/sys/dir.h
sun4.md/fsmake.o: /sprite/lib/include/option.h
sun4.md/fsmake.o: /sprite/lib/include/disk.h
sun4.md/fsmake.o: /sprite/lib/include/host.h
sun4.md/fsmake.o: /sprite/lib/include/netinet/in.h
sun4.md/fsmake.o: /sprite/lib/include/sun4.md/machparam.h
sun4.md/fsmake.o: /sprite/lib/include/sun4.md/limits.h
sun4.md/fsmake.o: /sprite/lib/include/sys/stat.h
sun4.md/fsmake.o: /sprite/lib/include/net.h
sun4.md/fsmake.o: /sprite/lib/include/machparam.h
sun4.md/fsmake.o: /sprite/lib/include/netEther.h
sun4.md/fsmake.o: /sprite/lib/include/netInet.h
sun4.md/fsmake.o: /sprite/lib/include/netUltra.h
sun4.md/fsmake.o: /sprite/lib/include/netFDDI.h
sun4.md/fsmake.o: /sprite/lib/include/dev/scsi.h
sun4.md/fsmake.o: /sprite/lib/include/sys/time.h
sun4.md/fsmake.o: /sprite/lib/include/assert.h
